### ISSUE TITLE
//move is not functioning as expected

### ISSUE THREAD

**Issue by RoboMWM** [boy0001/FastAsyncWorldedit#1]
If I recall correctly, performing a //move simply deletes the selected region, as if running a //set 0 (In other words, it simply deletes the blocks in the region, setting them to air.)

**Comment by Postremus** [comment]
a //move just moves the selected region one block in a direction.
it does not do a //set 0

**Comment by RoboMWM** [comment]
@Postremus I don't think you understand what I'm reporting. When using FAWE, doing a //move does not do what is expected. Yes, I expect it to move the selected region in x amount of blocks, but it is not doing that, and instead giving a result that would be equivalent to running //set 0

**Comment by RoboMWM** [comment]
Weird, I'm unable to reproduce. Will reopen if I'm able to...

**Comment by RoboMWM** [comment]
https://www.spigotmc.org/threads/free-fast-async-worldedit-%CE%B2.100104/page-3#post-1311588

Will retest with larger selection, I closed this issue when doing a 3x1 selection and moving that.

**Comment by UltraX3** [comment]
I am now experiencing this issue too. I think it has to do with FAWE being async and overwriting parts that it has already moved.

**Comment by lasercar** [comment]
I'm also experiencing this issue.

**Comment by boy0001** [comment]
Ugh

**Comment by nopresnik** [comment]
I am getting this issue with build 88 on 1.9.4

**Comment by UltraX3** [comment]
I am having this issue again on 3.5.0 on 1.8.8. This issue only appears when //move is executed into regions which share bounds
