### ISSUE TITLE
%prefix% system

### ISSUE THREAD

**Issue by DoubleThePsycho** [boy0001/FastAsyncWorldedit#1002]
I'm looking into adding prefixes to most but not all messages, such as the no permissions message.
Having to add the prefix everywhere is a pain and a half, so I'd like to see the %prefix% system introduced, to make life easier ^^

**Comment by SirYwell** [comment]
I don't get how it will simplify your plans. With a text editor like Notepad++, VS Code or Sublime Text you can easily add a prefix to all messages.

**Comment by SirYwell** [comment]
But where's the difference between adding `%prefix%` to all the Messages you want to have the prefix for and adding your custom prefix instead directly? Or how should the function work?

**Comment by DoubleThePsycho** [comment]
Difference is I'm lazy and I often forget a '

**Comment by DoubleThePsycho** [comment]
How is find/replace gonna help at all?

**Comment by boy0001** [comment]
As @SirYwell pointed out, there shouldn't be any difference between adding `%prefix%` to all the messages compared to any other string. If you already have `%prefix%` added, then simply find/replace it with the prefix you want. 

I don't mean for this to sound condescending, but in case you don't even know how to use `find/replace` to add `%prefix%`, here's how to do that:
 - In the top menu bar, click Search and select Replace.
 - In the `Search Mode` setting, check the `Regular expression` button
 - In the box for `Find what` put `\n +[a-zA-Z0-9_]+: '?`
 - In the box for `Replace with` put `$0%prefix%`
 - Click `Replace All`

**Comment by DoubleThePsycho** [comment]
I know very well how to use find/replace, it's the most used tool in N++ for me...
