### ISSUE TITLE
Method to save schematics globally when per player is enabled

### ISSUE THREAD

**Issue by aikar** [boy0001/FastAsyncWorldedit#1004]
We need the ability to be able to save schematics globally when per-player-schematics is enabled.

I see in the schem load command it looks for ../ and checks a permission, but //schem save ../foo does not work.

Please make //schem save ../foo work so we can save globally if you have the permission.

**Comment by aikar** [comment]
hmm im confused:

![](https://i.gyazo.com/5fb29ce5a88f69280904c66bfb7378fb.png)

**Comment by aikar** [comment]
I see there is code for ../ in save too, but this is happening.

**Comment by boy0001** [comment]
`../` should now work correctly.  Alternatively use: `//schem save <filename> -g`
