### ISSUE TITLE
Web - //download error

### ISSUE THREAD

**Issue by TrollC** [boy0001/FastAsyncWorldedit#1005]
https://hastebin.com/onucatosux

Description: whenever I do //download it will generate me a link but when I click it it says the file was deleted. Also when I upload a schematic it doesn't work and says that the files didn't finish uploading. I chmoded my uploads/ folder to 777 but it still doesn't work.

Setup the web interface + assets
Do //download
It will give you the link
When you click it it says that the file was deleted

**Comment by boy0001** [comment]
- file uploading is enabled in your php.ini
 - The schematic doesn't exceed the max file size in the configuration (or your php.ini)

**Comment by HighBridRed** [comment]
php.ini doesn't exist and the configuration setting for "max file size" doesn't exist either.
