### ISSUE TITLE
//image error

### ISSUE THREAD

**Issue by Noiknez** [boy0001/FastAsyncWorldedit#1008]
# Bug report
**Debug paste link**:
//image https://i.imgur.com/jpNRUFv.png

**Description of the problem:**
https://pastebin.com/2FEfi4Kv
the //image command generate an error

**How to replicate**:
Do the command //image https://i.imgur.com/jpNRUFv.png

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Noiknez** [comment]
Up

**Comment by N0tMyFaultOG** [comment]
If the issue persists still, reply to the ticket
