### ISSUE TITLE
WorldEdit action was cancelled error

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#101]
"Your WorldEdit actions was cancelled: Outside allowed region" randomly starts occurring after any period of being online, but is fixed by relogging (user is fully within a region). No messages (error or otherwise) appear in the console when the user attempts the command.

**Comment by dordsor21** [comment]
Possibly because of AFK, however occasionally occurs straight after joining server

**Comment by dordsor21** [comment]
**FAWE v3.5.0 on spigot 1.8.9

occurs after first join sometimes AND/OR after being online for a little while.

**Comment by dordsor21** [comment]
Still occurs on FAWE v3.5.0-dev

**Comment by dordsor21** [comment]
Seems to occur much more often when using WorldEditRegions

**Comment by dordsor21** [comment]
Continues on spigot 1.9.4 FAWE v3.5.0-dev

**Comment by Paintsplatters** [comment]
I seem to be experiencing the same thing.

**Comment by dordsor21** [comment]
Also occurs occasionally on switching worlds. Again you have to relog to fix

**Comment by dordsor21** [comment]
When this occurs attempting to execute any FAWE command does nothing, again with no console error

**Comment by dordsor21** [comment]
Error message changed to "Your WorldEdit action was cancelled: No allowed region." as of FAWE build #107

**Comment by dordsor21** [comment]
FAWE effectively shuts down for the user. No commands etc work. Changing worlds and/or relogging fixes most of the time else a server restart is required. No errors shown in console during this period. Debug mode on. Occurs in all FAWE version across 1.8 and 1.9

**Comment by doozzik** [comment]
1. I saved schematic with big size > 6 million blocks with FAWE. I dont remember exactly version of game. 1.8.8 or 1.8.9
2. I start new spigot server 1.8.8
3. //schematic load grib.schematic - ok
4. //paste - "No allowed region"
Here is my schematic: http://rgho.st/68CpRGcbv

**Comment by mohe2015** [comment]
For me it worked to give the player the '*' permission using `pex user Test add *` or  a similar command.

**Comment by dordsor21** [comment]
mohe2015 I believe your issue was that you didn't give the fawe.plotsquared permission or something similar. This is FAWE effectively on occasion "shutting down" for the player.

**Comment by mohe2015** [comment]
@dordsor21 But after that it worked. So that could solve the problem for others too.

**Comment by dordsor21** [comment]
@mohe2015 are you sure it was randomly occuring? Or occuring all the time. Also adding all permissions is really not something that's viable for most servers....at all.

**Comment by mohe2015** [comment]
If I give a player the permissions worldedit.* and fawe.* it works.
But if I give a player op using /op <name> it says: Your WorldEdit action was cancelled: No allowed region.

So possibly op doesn't give the player enough permissions to use FastAsyncWorldedit-

**Comment by mohe2015** [comment]
Some images
![settings](https://cloud.githubusercontent.com/assets/13287984/15861104/e35a2936-2ccb-11e6-86c2-a2c36ca7fed7.png)
![op](https://cloud.githubusercontent.com/assets/13287984/15861120/ebed3476-2ccb-11e6-8687-4474776efcbc.png)
![permissions](https://cloud.githubusercontent.com/assets/13287984/15861124/ede05f6a-2ccb-11e6-9fe1-4bf67c1e9396.png)

**Comment by dordsor21** [comment]
@mohe2015 what you're describing is not being in a region/having permissions. What the problem here is, is not what you're experiencing. You're not setting up permissions properly. This bug is that, even with permissions to WE in an area, the plugin occassionally "shuts down" for the player, meaning they can't do anything until they relog.

**Comment by mohe2015** [comment]
@dordsor21 Ok thank you very much.

**Comment by dordsor21** [comment]
@mohe2015 if you install worldguard then use /rg addowner __global)__ <minecraft name> then you only need to give the fawe.worldguard permission to allow yourself to use it.

**Comment by dordsor21** [comment]
Definitely continues in 1.9.4 spigot and build #.124

**Comment by boy0001** [comment]
Still a problem?

**Comment by zenandreas** [comment]
Yes, still a problem

**Comment by dordsor21** [comment]
seems to be gone

**Comment by boy0001** [comment]
Assumed fixed, will reopen if necessary

**Comment by dordsor21** [comment]
does still happen, but much more rare

**Comment by boy0001** [comment]
Still an issue?

**Comment by dordsor21** [comment]
Don't think so, haven't seen or heard of it in ages.

**Comment by dordsor21** [comment]
Getting reports of "No allowed region (bypass with /wea)" being sent to a player after a while. Only fixed by relog.

**Comment by dordsor21** [comment]
@boy0001 possibly same bug, but where people cannot do any WorldEdits apart from "/u" with no error messages etc.

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
