### ISSUE TITLE
Dynamic Chunk Rendering makes other players invisible

### ISSUE THREAD

**Issue by Miclebrick** [boy0001/FastAsyncWorldedit#1011]
Having dynamic chunk rendering on and server render distance to 1 makes all players invisible

**Comment by boy0001** [comment]
Either client side issue, or paper. Try raising the server render distance to 3 or 4.

**Comment by Miclebrick** [comment]
That makes it so I can see people a few chunks away. I am indeed using paper. Is there a way to make it work on paper?

**Comment by IronApollo** [comment]
Just curious, what is your "dynamic-chunk-rendering" configuration setting set to?

**Comment by Miclebrick** [comment]
at the time of making the issue, the only option was true or false. Afterwards, I tried setting it to 16, but it still didn't work.

**Comment by HauserGrim** [comment]
+1
same problem

**Comment by boy0001** [comment]
Increase the server render distance to 3.
