### ISSUE TITLE
Console error with latest FAWE

### ISSUE THREAD

**Issue by Aerodog** [boy0001/FastAsyncWorldedit#1013]
This is probably all the information you'll need...

https://pastebin.com/raw/wnRmxVhY

Dropped in new update, error during loading.

Edit: Only happens first time.

**Comment by boy0001** [comment]
Yep, I'm aware. It doesn't affect you, just ignore the error, it'll only occur once. 

I changed one of the experimental features in a way which wasn't backwards compatible. Given that it's an experimental option, I didn't elect to write code to convert from older configs, hence the error.
