### ISSUE TITLE
Update Download Link for Paper

### ISSUE THREAD

**Issue by aikar** [boy0001/FastAsyncWorldedit#1014]
Please update the link for Paper downloads to be directly from our CI server and not Yives: https://destroystokyo.com/ci/job/Paper/

Also update the text to be `Paper Server (Improved Bukkit/Spigot)`

**Comment by boy0001** [comment]
Where? I don't see Yives mentioned?
https://github.com/boy0001/FastAsyncWorldedit/blob/master/bukkit/src/main/java/com/boydti/fawe/bukkit/FaweBukkit.java#L116

Anywho, if you submit the PR, I'll accept it.

**Comment by aikar** [comment]
@boy0001  this page: https://github.com/boy0001/FastAsyncWorldedit/releases

**Comment by boy0001** [comment]
Ah, forgot about that. Thanks.
