### ISSUE TITLE
EXPERIMENTAL.DYNAMIC_CHUNK_RENDERING error on server start

### ISSUE THREAD

**Issue by Noiknez** [boy0001/FastAsyncWorldedit#1015]
# Bug report

**Debug paste link**:

https://hastebin.com/ejipaniqot

**Description of the problem:**

https://pastebin.com/vVANvyZB

**How to replicate**:

Turn on the server

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by IronApollo** [comment]
Hello! Writing this in here for documentation's sake. The "experimental.dynamic-chunk-rendering" configuration setting is an integer value, not a boolean value. Therefor, changing "dynamic-chunk-rendering: false" to "dynamic-chunk-rendering: -1" should result in no error while yielding the same "disabled" result. Hope this helps!

**Comment by boy0001** [comment]
#1013
