### ISSUE TITLE
//flip command don't flip builds

### ISSUE THREAD

**Issue by xion87** [boy0001/FastAsyncWorldedit#1016]
# Bug report

**Debug paste link**:
https://hastebin.com/axuzoxizix

**Description of the problem:**
The //flip command don't flip your copied build, i tried with different materials but it do nothing

**How to replicate**:
- select the build
- copy it
- run //flip
- paste ( i attached the photo, only the "position" seem flipped)
![image](https://user-images.githubusercontent.com/3611852/40540653-2c803484-6019-11e8-8dee-eb12ec52d6a6.png)

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Looks flipped to me. Which direction did you flip it in?

**Comment by xion87** [comment]
man I forgot that work by face the direction.... I forgot it because I stopped to use that command... sorry 😅
