### ISSUE TITLE
plotsqaured bypass road issue - worldedit

### ISSUE THREAD

**Issue by Cobwebster** [boy0001/FastAsyncWorldedit#1017]
their plot is in an L shape and it sets/replaces blocks
they merged the plots of 3 in a square, when they worldedit from one corner to the opposite corner that 4th plot inside the square gets changed as well.
https://i.imgur.com/WqWLU41.png

**How to replicate**:
Claim a L shape, use FAWE from 1 plot to the other overlapping a unclaimed plot and it'll still worldedit in that plot.

https://hastebin.com/vakaquyazo

Beyond this everything works fine, if you attempt to worldedit outside of your 1 plot it works perfectly, its only when you trick it into overlapping a unclaimed or someone elses claimed plot it bypasses it and works.

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/1972

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
