### ISSUE TITLE
//fixlighting does not work properly in the end

### ISSUE THREAD

**Issue by MicleBrick** [boy0001/FastAsyncWorldedit#1020]
Fixing block lighting in the end does not seem to work correctly.

Steps: //removelight and //fixlighting

Before: https://i.imgur.com/dayHNv8.png
//removelight
After: https://i.imgur.com/lfV0CLR.png
//fixlighting
After: https://i.imgur.com/zdfGoRE.png
Relog
https://i.imgur.com/6oIH0uu.png (still broken)

No errors in console or anything like that.

https://pastebin.com/mWCiWG6M <-- lighting section of config

(tried it with delay packet sending on)

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
