### ISSUE TITLE
Lighting is not updated in all required chunks

### ISSUE THREAD

**Issue by 56738** [boy0001/FastAsyncWorldedit#1022]
# Bug report

**Debug paste link**: https://hastebin.com/enizoxikew

**Description of the problem:**

Lighting is correctly updated in the chunks which have been changed but not in the chunks below them.
This seems to cause incorrect sky lighting.

**How to replicate**:

Create a large room (multiple chunks tall) without a roof. Then add a roof with FAWE.

Without roof:
![Without roof](https://i.imgur.com/c1wn0VT.jpg)

With roof:
![With roof](https://i.imgur.com/fpXnyWt.jpg)

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
