### ISSUE TITLE
Wrong //schem list result with no params

### ISSUE THREAD

**Issue by NxDs** [boy0001/FastAsyncWorldedit#1023]
**Debug paste link**:

 https://hastebin.com/uxunecawig
**Description of the problem:**

//schem list with no arguments doesn't seem to be working properly, it shows "FAWE: Usage:" message instead of displaying the first page of schematics available or the actual usage of the command.
//schem list \<number\> on the other hand works just fine
Screenshot of the issue: https://imgur.com/WWripSO
**How to replicate**:

Execute //schem list
**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Try updating fawe
If the issue persists still, reply to the ticket
