### ISSUE TITLE
No one can WorldEdit in a plot with `Everyone` added as helpers

### ISSUE THREAD

**Issue by Nickster258** [boy0001/FastAsyncWorldedit#1024]
# Bug report

**Debug paste link**:
https://hastebin.com/ohefedizix

**Description of the problem:**
Plots that have `Everyone` added with `/p add *` and `/p trust *` give a region error when anyone tries to use worldedit in the plot despite having `fawe.plotsquared.member`. Only the owner and those with `fawe.plotsquared.admin` can edit.

**How to replicate**:
Create a new plot then add everyone with `/p add *`.

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by PNWMan** [comment]
This issue prevents the use of FAWE on a large public redstone server due to security policy. All the members are looking forward to using FAWE for its lag reduction and added functionality!
