### ISSUE TITLE
/regen error

### ISSUE THREAD

**Issue by Bedah95** [boy0001/FastAsyncWorldedit#1025]
Hey,
if you select a huge region and regenerate it, the surface doesn´t reset correctly.

![2018-06-03_19 11 45](https://user-images.githubusercontent.com/8694407/40889264-ee265dc4-6763-11e8-95d8-2e6a7dd1a66a.png)
![2018-06-03_19 08 56](https://user-images.githubusercontent.com/8694407/40889274-138ea3fa-6764-11e8-8167-235c0e8a1ee1.png)

newest Paper 1.12.2
newest WE and FAWE

Best Regards
Bedah

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
