### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Wanfengqingl** [boy0001/FastAsyncWorldedit#1026]
Hi, I am using the FAWE anvil to leveldb converter, it's a great program, and it was working when I first downloaded it but suddenly started to crash when I after few days when I tries to open it. I'm completely a newbie on the computer, please help me, thank you so much, your program helped me a lot and I really need it! 
This is the text that generated after the crash:
[hs_err_pid4600.log](https://github.com/boy0001/FastAsyncWorldedit/files/2066655/hs_err_pid4600.log)

**Comment by N0tMyFaultOG** [comment]
If the error persists still, reopen the ticket.
