### ISSUE TITLE
ConcurrentModificationException when modifying block

### ISSUE THREAD

**Issue by BrainStone** [boy0001/FastAsyncWorldedit#1027]
# Bug report

**Debug paste link**:
https://hastebin.com/giferaluba

**Description of the problem:**
Whenever I do any worldedit action, I get this exception and nothing happens.

Weirdly enough it works flawlessly on one server but not the other. The only major difference I can see between them is that one uses PlotSquared and the other GriefPrevention.

https://gist.github.com/BrainStone/be8fb4a803b1e889f563740a00fceed8

**How to replicate**:
Happens every time I try to modify blocks. Like `//set 1` or `//paste`

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by JohnCorby** [comment]
do you have forge on the server it doesn't work on?
by the error, it looks like fawe is trying to handle something with forge

**Comment by BrainStone** [comment]
Yes. It’s a Sponge Forge server. Weirdly enough, it’s only happening in a single spot, that seems to be bugged in the first place. So I’m not entirely sure what going on.

**Comment by JohnCorby** [comment]
If its only happening in one chunk,  it might be a corrupted chunk that's causing the issue

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
