### ISSUE TITLE
Clipboard //paste isn't async

### ISSUE THREAD

**Issue by JohnCorby** [boy0001/FastAsyncWorldedit#1030]
# Bug report

**Debug paste link**:
https://hastebin.com/oyarozoyoh

**Description of the problem:**
I think this should also be async. Doing //set on the same sized region that //paste has is async.
If history and file IO is the reason, disreguard this.
This also applies for schematics (obviously)

**How to replicate**:
Load a big clipboard and do //paste. It should take a second or two because it's on the main thread.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Miclebrick** [comment]
Just because it's async doesn't mean it's instant. Unless other things on the server are frozen as well, it's probably working fine.

**Comment by JohnCorby** [comment]
The thing is, others things on the server ARE lagging,  so something isn't async

**Comment by SirYwell** [comment]
You need to specify what happens if you think you found a bug.

**Comment by JohnCorby** [comment]
I just did specify what happens! I'll say it again, but try to be more specific:
I use a clipboard command like //paste on a large region, and the whole server freezes for a second or two probably because something is ran on the main thread.
This does NOT happen for other commands such as //set on equally big/even bigger region.
NOTE: with something like //set, the fawe thread/threads lag, but the whole entire server (e.g. running non-fawe commands work fine).
Therefore, I'm assuming that the whole server is lagging not because my computer/server is being slow, but because block editing with //set is async while block editing with //paste is not.
I would really appreciate it if this could be re-opened, because I believe it would be beneficial to fix this and would further support that this is a fully async plugin.

**Comment by SirYwell** [comment]
I've pasted >11 million blocks right now. It was a Little bit laggy (tps went down to 19) but in fact, the action was completed asynchronously and wasn't excecuted on the main thread.

**Comment by JohnCorby** [comment]
oh.
It seems I was wrong then.
They _are_ async. Sorry.
What I should've asked was how do you use the Schematic class in the API to save/load schematics.
(e.g. `new Schematic(region).save(file, ClipboardFormat.SCHEMATIC);` and `ClipboardFormat.SCHEMATIC.load(file).paste(world, pos1, false, true, null);`)
How do I make _those_ async because they're not.

**Comment by boy0001** [comment]
you put it in an async task. 
https://github.com/boy0001/FastAsyncWorldedit/wiki/Fawe-TaskManager
https://bukkit.gamepedia.com/Scheduler_Programming

**Comment by JohnCorby** [comment]
i thought that would break stuff cuz async tasks and bukkit api but i guess you accounted for that
alright then.
thanks for the help and sorry for being stupid
