### ISSUE TITLE
FAWE kick/crash player

### ISSUE THREAD

**Issue by ph1823** [boy0001/FastAsyncWorldedit#1032]
# Bug report
Kick error: NativeIoException : syscall:read(..) failed: Connection reset by peer @ io.netty.channel.unix.FileDescriptor:-1
**Debug paste link**: https://hastebin.com/animomilih

**Description of the problem:** I get to replace a loot of block (over 2Million) and the server kick with error: NativeIoException : syscall:read(..) failed: Connection reset by peer @ io.netty.channel.unix.FileDescriptor:-1
**How to replicate**:
Select a big area and replace block, wait a moment and server kick
**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

I think but FAWE dont unload the other chunck, but idk how to enable unable chucnk after replace

**Comment by N0tMyFaultOG** [comment]
If the error persists still, update your fawe and get a new debugpaste
