### ISSUE TITLE
FAWE error when the server is stopped [Sponge]

### ISSUE THREAD

**Issue by galoti** [boy0001/FastAsyncWorldedit#1035]
# Bug report

**Debug paste link**:

   https://hastebin.com/pikurobeba

**Description of the problem:**

   Error: https://gist.github.com/galoti/6053117aa05a224596a050198acc5d6e

**How to replicate**:

   Stop the Sponge server with the latest FAWE build.
**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
