### ISSUE TITLE
On /reload tells me to "Nag author : 'Empire92'"

### ISSUE THREAD

**Issue by ManyPandas** [boy0001/FastAsyncWorldedit#1036]
# Bug report

**Debug paste link**:
https://hastebin.com/wevuquludi

**Description of the problem:**
On /reload (which I use a lot because I am testing my own plugins), the plugin gives me this error message:

`[10:37:26 ERROR]: Nag author: 'Empire92' of 'FastAsyncWorldEdit' about the following: This plugin is not properly shutting down its async tasks when it is being reloaded.  This may cause conflicts with the newly loaded version of the plugin`

It also takes longer for the entire reloading process to complete because of this.
This isn't necessarily an issue for me, I just wanted to report it as it may be some problem under the hood.

This has been mentioned before, however I am not getting an IllegalPluginAccessException in any way.
(https://github.com/boy0001/FastAsyncWorldedit/issues/860)

**How to replicate**:
Run /reload

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin (removed all other installed plugins)

**Comment by N0tMyFaultOG** [comment]
Ew reload, either do what Micle said, use plugman or use /fawe reload as it has his own reloading command.
