### ISSUE TITLE
Not an issue, just need some help!

### ISSUE THREAD

**Issue by UnlimitedNinjas** [boy0001/FastAsyncWorldedit#1038]
I just want to know how to use the web interface stuff? i see pictures of https://www.spigotmc.org/resources/fast-async-worldedit-voxelsniper.13932/
anonymous upload and stuff, how do i do this?

**Comment by boy0001** [comment]
It should work out of the box unless you've messed with the settings. So to download your clipboard use `//download`. To upload a schematic to the server, go to https://empcraft.com/fawe/ and click the upload button.
