### ISSUE TITLE
World won't convert.

### ISSUE THREAD

**Issue by kquade** [boy0001/FastAsyncWorldedit#1039]
# Bug report
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 [ERROR] Conversion failed, you will have to do it manually (Nukkit server + anvil2leveldb command)

**Description of the problem:**
It won't convert.

**How to replicate**:
Tried to convert a world. Source is in creative w/o anything special other than redstone blocks (no actual redstone), an end portal and a nether portal.

**Debug**
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: AWT-EventQueue-0 | Id: 14 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Thread.dumpThreads(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Thread.getAllStackTraces(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 com.boydti.fawe.nukkit.core.converter.ConverterFrame$6.actionPerformed(ConverterFrame.java:272)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 javax.swing.DefaultButtonModel.setPressed(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.Component.processMouseEvent(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 javax.swing.JComponent.processMouseEvent(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.Component.processEvent(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.Container.processEvent(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.Component.dispatchEventImpl(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.Container.dispatchEventImpl(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.Component.dispatchEvent(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.Container.dispatchEventImpl(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.Window.dispatchEventImpl(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.Component.dispatchEvent(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventQueue.dispatchEventImpl(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventQueue.access$500(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventQueue$3.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventQueue$3.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.security.AccessController.doPrivileged(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventQueue$4.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventQueue$4.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.security.AccessController.doPrivileged(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventQueue.dispatchEvent(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventDispatchThread.pumpEvents(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventDispatchThread.pumpEvents(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventDispatchThread.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: D3D Screen Updater | Id: 17 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Object.wait(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 sun.java2d.d3d.D3DScreenUpdateManager.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Thread.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: Attach Listener | Id: 5 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: Timer-0 | Id: 35 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Object.wait(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Object.wait(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.TimerThread.mainLoop(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.TimerThread.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: Thread-8 | Id: 32 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: Finalizer | Id: 3 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Object.wait(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.ref.ReferenceQueue.remove(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.ref.ReferenceQueue.remove(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: AWT-Windows | Id: 12 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 sun.awt.windows.WToolkit.eventLoop(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 sun.awt.windows.WToolkit.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Thread.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: AWT-Shutdown | Id: 11 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Object.wait(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Object.wait(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 sun.awt.AWTAutoShutdown.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Thread.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: DestroyJavaVM | Id: 20 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: TimerQueue | Id: 38 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 sun.misc.Unsafe.park(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.DelayQueue.take(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 javax.swing.TimerQueue.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Thread.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: Java2D Disposer | Id: 10 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Object.wait(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.ref.ReferenceQueue.remove(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.ref.ReferenceQueue.remove(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 sun.java2d.Disposer.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Thread.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: Thread-7 | Id: 30 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 sun.misc.Unsafe.park(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.locks.LockSupport.park(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.LinkedBlockingDeque.takeFirst(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 com.sun.glass.ui.InvokeLaterDispatcher.run(InvokeLaterDispatcher.java:108)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: Reference Handler | Id: 2 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Object.wait(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Object.wait(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.ref.Reference.tryHandlePending(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: Signal Dispatcher | Id: 4 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: pool-3-thread-1 | Id: 36 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 sun.misc.Unsafe.park(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.locks.LockSupport.park(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Thread.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: JavaFX Application Thread | Id: 31 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 com.sun.glass.ui.win.WinApplication$$Lambda$65/1018543077.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Thread.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: QuantumRenderer-0 | Id: 28 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 sun.misc.Unsafe.park(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.locks.LockSupport.park(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Thread.run(Unknown Source)

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
