### ISSUE TITLE
Unable to set a chest

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#104]
I marked a 1x1 spot and tried `set chest`. Instead it created air. `set 1` created cleanstone properly.

FAWE3.4.3

**Comment by boy0001** [comment]
The data values on a chest represent the rotation, so `chest:0` is the down direction which isn't valid for chests. `chest:2` is the first valid direction.

**Comment by boy0001** [comment]
Fixed
