### ISSUE TITLE
Ability to exlude containers or items from containers when using //copy and //cut

### ISSUE THREAD

**Issue by Gasha666** [boy0001/FastAsyncWorldedit#1040]
Please add ability to exlude containers when using //copy and //cut to not copy items from containers at least, cause now there is duplication bug they can abuse easy..

I'm begging last 3 months for this one single feature, i joined your discord..Jesse you promised me that you will add it until 14th 
i waited for so long, please add it..its ultra important feature i can't believe how FAWE don't have it already..

Please add it i already rated five stars and i will rate again, i don't want to give bad reviews so please listen to what i'm saying i don't ask for any upgrade or new feature, i just want to prevent ABUSE, staff with ability to copy/cut are able to duplicate items....please add ability to prevent it it as you said you will!

**Comment by SirYwell** [comment]
I collected some ideas and problems to realize your suggestion:

- Having a server-wide configuration option to toggle item content copying would be the simplest solution but would restrict everyone from copying the content of containers
- Using a switch like for skipping entities would help to choose for each operation but won't help to prevent abuse as long as it isn't default.
- Permissions to copy content of containers would be the easiest way for normal users
- Entities with containers probably need to be checked too

**Comment by Gasha666** [comment]
You promised me that oyu will add it long time ago, please will you add it??
or at least answer

**Comment by Gasha666** [comment]
still after 7 months of promising that you will add that FIX....still nothing..

**Comment by boy0001** [comment]
https://github.com/boy0001/FastAsyncWorldedit/issues/1063
