### ISSUE TITLE
[!] Low memory [!]

### ISSUE THREAD

**Issue by chromocat** [boy0001/FastAsyncWorldedit#1047]
DEBUG PASTE: https://hastebin.com/enuzirevum

We allocate 4gb of RAM, after some time any attempt to set (except for //fast) makes the server freeze for about 5s and then "Low memory" message appears, though /gc shows that we have 2 out of 4gb free. We were trying to allocate more memory to the server (8gb) but, however, this led to the same exception happening just later.
Also an attempt to disable max-memory-percent led to nothing.
Thanks in advance

**Comment by Matthysse** [comment]
Yes me too the server crash for low memory, but after installing FAWE it say low momory

**Comment by chromocat** [comment]
UP!

**Comment by N0tMyFaultOG** [comment]
Try updating fawe
If the error persists still, reopen the ticket and get a new `/fawe debugpaste`
