### ISSUE TITLE
Correct place to report bugs for Anvil to LevelDB Converter?

### ISSUE THREAD

**Issue by Maytalspade** [boy0001/FastAsyncWorldedit#1048]
Why is the "Report Issue" for Anvil to LevelDB Converter linked to here? Is Anvil to LevelDB Converter and FastAsyncWorldedit related? Sorry for my ignorance, I'm new to this Minecraft modding stuff so please be gentle with me. I obviously have an issue with Anvil to LevelDB Converter that I would like to post about if this is the right place. Here is a link to the site that redirects here. https://www.planetminecraft.com/mod/anvil-to-leveldb-converter-java-to-pocket-edition/

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
