### ISSUE TITLE
Little Problem

### ISSUE THREAD

**Issue by Matthysse** [boy0001/FastAsyncWorldedit#1049]
I use this plugin (Schematic Brush that requieres WorldEdit) https://dev.bukkit.org/projects/schematicbrush.
But because it's a old plugin //undo don't affect those schematics place and it don't undo my trees
I said that you modify in some points WorldEdit, it could be nice to fix that!

**Comment by Wqrld** [comment]
its up to them to implement that sadly.

**Comment by Wqrld** [comment]
and fawe has a schematic brush
