### ISSUE TITLE
Error with Forge 1.8.9

### ISSUE THREAD

**Issue by Small-Ku** [boy0001/FastAsyncWorldedit#105]
It didn't change anything
> [10:53:02] [Client thread/INFO]: [CHAT] §8(§5§lFAWE§8)§7 First position set to (-99.0, 55.0, 155.0) .
> [10:53:02] [Client thread/INFO]: [CHAT] §8(§5§lFAWE§8)§7 Second position set to (-99.0, 55.0, 155.0) (1).
> May 10, 2016 10:53:06 AM com.sk89q.worldedit.extension.platform.CommandManager$1 run
> SEVERE: [WorldEdit] An unexpected error while handling a WorldEdit command
> java.lang.ClassCastException: net.minecraft.world.chunk.Chunk cannot be cast to [C
> 	at com.boydti.fawe.forge.v0.ForgeQueue_All.getCombinedId4Data(ForgeQueue_All.java:31)
> 	at com.boydti.fawe.example.MappedFaweQueue.getCombinedId4Data(MappedFaweQueue.java:281)
> 	at com.boydti.fawe.util.FaweQueue.getCombinedId4DataDebug(FaweQueue.java:105)
> 	at com.boydti.fawe.object.HistoryExtent.setBlock(HistoryExtent.java:56)
> 	at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:779)
> 	at com.sk89q.worldedit.function.block.BlockReplace.apply(BlockReplace.java:53)
> 	at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:58)
> 	at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:69)
> 	at com.sk89q.worldedit.command.composition.SelectionCommand.call(SelectionCommand.java:167)
> 	at com.sk89q.worldedit.command.composition.SelectionCommand.call(SelectionCommand.java:64)
> 	at com.sk89q.worldedit.util.command.composition.LegacyCommandAdapter.call(LegacyCommandAdapter.java:52)
> 	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
> 	at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:253)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> 
> [10:53:06] [Client thread/INFO]: [CHAT] Please report this error: [See console]
> [10:53:06] [Client thread/INFO]: [CHAT] java.lang.ClassCastException: net.minecraft.world.chunk.Chunk cannot be cast to [C
> [10:53:06] [Client thread/INFO]: [CHAT] §8(§5§lFAWE§8)§7 Action completed in 0.208 seconds

**Comment by boy0001** [comment]
Fixed
ci.athion.net/job/FastAsyncWorldEdit/
