### ISSUE TITLE
//wand pos2 won't work

### ISSUE THREAD

**Issue by AshiroKun** [boy0001/FastAsyncWorldedit#1051]
# Bug report
**Debug paste link**:
https://hastebin.com/yotafakuca

**Description of the problem:**
I keep having this issue and i have reinstalled, and tried many different ways to fix the solution but nothing worse. The issue focuses on the fact that the //wand pos2 stops working after a period of time. For example, i would reload the server and it would work for like 30 minutes but then stop working and it wont detect. This results the builders on my server to use the command instead of the //wand which is frankly annoying. Is there a fix for this issue?

I am running on 1.12.2 server.

**How to replicate**:
Simply use the wand and try to set a region.
Afterwards, try to set another region and the pos1 will work with the wand but the pos2 will stop working.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
>i would reload

Don't do that, it breaks fawe. If the error persists still, update fawe [here](https://empcraft.com/fawe/download/?bukkit) and get a new debugpaste.
