### ISSUE TITLE
A way to be op on all server

### ISSUE THREAD

**Issue by stembauer2** [boy0001/FastAsyncWorldedit#1056]
# Bug report

**Debug paste link**:
https://hastebin.com/zitoninumi

**Description of the problem:**
I found a huge problem that binds WorldEdit and FAWE. this problem allow me to OP myself on a very large number of server with FAWE.

**How to replicate**:
It's realy easy to make. First you need a personal server. Then on this server make a schematic with WorldEdit from a command_block with any command in it. this schematic need to be made with worldedit because it keep NBT data. now you need to take the schematic file into the server ftp. and upload it on FAWE then you just have to paste it on the server you want to be op.

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Noiknez** [comment]
I have tested this and I agree that this is a big problem

**Comment by okx-code** [comment]
> the schematic file into the server ftp

I don't think this is a problem as if you have access to the server FTP you probably also have OP.

**Comment by boy0001** [comment]
Forgot to mention this, but I've since added a `strip-nbt` section to the fawe `config.yml`. So just add `Command` to the list there.
