### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by FrankHeijden** [boy0001/FastAsyncWorldedit#1057]
Error @ console on startup
Plugin is trying to set a Boolean value in a setInteger method; https://hastebin.com/zezucagazi.sql
- [ ] I included a `/fawe debugpaste` link -> not relevant
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Hastebin is empty, attach the log below if this is an issue still.
