### ISSUE TITLE
Old jar

### ISSUE THREAD

**Issue by TheIntelloBox** [boy0001/FastAsyncWorldedit#1058]
# Bug report

**Description of the problem:**
A .jar of WorldEdit is included at every restart. But this jar is old and I want to remove it.

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by TheIntelloBox** [comment]
Yes but in 1.13, the old WorldEdit doesn't work.

**Comment by Wqrld** [comment]
You will have to wait for fawe to update to 1.13

**Comment by boy0001** [comment]
Delete your current WorldEdit, and install the dev build of FAWE for 1.13:
https://1drv.ms/u/s!ApPBBqB8ixL9qsVVKb294mH3WQxBVQ
