### ISSUE TITLE
No support for 1.13

### ISSUE THREAD

**Issue by LeoDog896** [boy0001/FastAsyncWorldedit#1061]
# Bug report

**Debug paste link**:
This is not from the command, as the command also doesn't work.
[](https://pastebin.com/d0t8WcEu)

**Description of the problem:**
FastAsyncWorldEdit fails to work on 1.13. Even doing //help doesn't work, and all commands do not work at all. I have also looked up the other problems listed in the Pastebin. FastAsyncVoxelSniper does work perfectly, though.

**How to replicate**:
Run FAWE on the latest version, on Minecraft 1.13

**Checklist**:

- [] I included a `/fawe debugpaste` link (I sadly cannot as the plugin just halts the command.)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by TheIntelloBox** [comment]
I confirm. ;)

**Comment by CloudeLecaw** [comment]
i confirm it will be there in a few weens now since we have WorldEdit for 1.13 :3

**Comment by SirYwell** [comment]
@boy0001 is working on it, so don't complain about issues as long as there is no version for 1.13

**Comment by CloudeLecaw** [comment]
dont worry SirWell currently the Plugin would spamthe console endless, and it seems Nothing to work, so i dont think we will report issues before there is a 1.13 Version ;)

**Comment by Miclebrick** [comment]
*sees 1.13 issue before 1.13 version*

**Comment by boy0001** [comment]
unstable build:
https://1drv.ms/u/s!ApPBBqB8ixL9qsVVKb294mH3WQxBVQ

**Comment by CloudeLecaw** [comment]
thx boy0001 even if ist unstable but this Version brang back the woodaxe that still is missing in the normal current WE builds.

**Comment by dudullle** [comment]
This version doesn't work with worldguard 7 (it makes worldguard crash), but i now :) it's unstable

**Comment by me4502** [comment]
@CloudeLecaw Wooden axe has never been missing from WorldEdit builds.

**Comment by CloudeLecaw** [comment]
it does @me4502 try the last WorldEdit_7.0.0-Build3820.jar  from the enginehub of we and try the woodenaxe ;)
