### ISSUE TITLE
Why the data of the block is damage?

### ISSUE THREAD

**Issue by Azim-D3Tm** [boy0001/FastAsyncWorldedit#1065]
https://github.com/boy0001/FastAsyncWorldedit/blob/3ed2e57f3a89f48bd0edac7b930a91e51db57679/nukkit/src/main/java/com/boydti/fawe/nukkit/core/NukkitUtil.java#L137

**Comment by boy0001** [comment]
it just is

**Comment by Azim-D3Tm** [comment]
lol
