### ISSUE TITLE
On occasion updated chunks not sent to player.

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#107]
Chunks are occasionally not updated for the user after a worldedit requiring the user to unload and reload the chunks from the server (move far away and return) - the worldedit is carried out however it does not appear so to the user. This happens throughout the time being logged on and can stop after relog.

**Comment by filoghost** [comment]
I would like to add some details: it happens to me when the changed chunks are far away, see this example: http://imgur.com/a/rQECg

**Comment by boy0001** [comment]
Only affects 1.8 (unless further information shows otherwise)

**Comment by dordsor21** [comment]
will be able to test properly in 1.9 within a few weeks
