### ISSUE TITLE
No protect with PlotMe

### ISSUE THREAD

**Issue by mckite** [boy0001/FastAsyncWorldedit#1072]
# Bug report

**Description of the problem:**
No protect with PlotMe

Just Work with default worldedit, not FAWE , so that have major lag.

(Sync)

**How to replicate**:

**Checklist**:

- [] I included a `/fawe debugpaste` link

# Server Information
server.platform: bukkit
server.plugins: 
 - FastAsyncWorldEdit: 18.08.09-c12f685-1171-20.7.5
 - WorldEdit: 6.1.8-SNAPSHOT;cd4729f
 - AutoSaveWorld: 4.15
 - WorldEditCrashFix: 1.0
 - ProtocolSupportLegacySupport: 1.0
 - PlotMe: 0.16.3
 - EssentialsChat: 2.15.0.1
 - PlotMe-DefaultGenerator: 0.16.1
 - EssentialsProtect: 2.15.0.1
 - EssentialsAntiBuild: 2.15.0.1
 - EssentialsSpawn: 2.15.0.1
 - MultiWorld: 5.2.8
server.version: git-Spigot-642f6d2-6103339 (MC: 1.12.2) / 1.12.2-R0.1-SNAPSHOT

# YAY! Now, let's see what we can find in your JVM
memory.free: 544854984
memory.max: 2097152000
java.specification.version: '1.8'
java.vendor: 'Oracle Corporation'
java.version: '1.8.0_181'
os.arch: 'amd64'
os.name: 'Windows 10'
os.version: '10.0'

# Okay :D Great. You are now ready to create your bug report!
# You can do so at https://github.com/boy0001/FastAsyncWorldedit/issues

**Comment by boy0001** [comment]
What do you get when you try to use it?
Do they have the `fawe.plotme` permission?
Are they standing inside the plot?

**Comment by mckite** [comment]
Yes,I have the Op(*)

WHEN USING "plot clear" and "plotme reset"
-----Original Message-----

**Comment by mckite** [comment]
And I am also on the plot. (If I am not on the plot, the command will not be excuted.)

**Comment by mckite** [comment]
PlotMe. Version : 0.13.2 (Due to offline mode)

THE LASTEST PLOTME ALSO SAME PROBLEM

**Comment by boy0001** [comment]
If you are op, you might be bypassing the region restrictions. 

Do you want to discuss this on discord?
https://discord.gg/ngZCzbU

**Comment by mckite** [comment]
I can't join there.

-----Original Message-----

**Comment by mckite** [comment]
I tried to test without OP, and without  fawe.plotme  permissions.
But the result was same.

**Comment by N0tMyFaultOG** [comment]
PlotMe is an abandoned project. We highly suggest switching to PlotSquared.
