### ISSUE TITLE
The version reported by FAWE throws NPE

### ISSUE THREAD

**Issue by rlf** [boy0001/FastAsyncWorldedit#1077]
# Bug report
**Debug paste link**:
https://hastebin.com/xucihimema

**Description of the problem:**
![image](https://user-images.githubusercontent.com/503044/44217150-188eec00-a177-11e8-8813-6df70e56faed.png)

**How to replicate**:
- Download "latest" https://empcraft.com/fawe/latest.php?bukkit113
- Start up Paper
- Do `version FastAsyncWorldEdit`
- See stack-trace

Plugins that want to integrate with FAWE bleeding edge, really need the version, to be able to correctly detect whether they will work or not.

**Comment by boy0001** [comment]
Fixed.
