### ISSUE TITLE
FAWE 1.13.2 bugs

### ISSUE THREAD

**Issue by N0tMyFaultOG** [boy0001/FastAsyncWorldedit#1079]
**Debug paste link**:
Always testing on latest build
**Description of the problem:**

1.13.2 TODO:
- The queue is not optimized for 1.13
- Auto updating is broken
- `//fawe changelog` results in a stacktrace: https://gist.github.com/N0tMyFaultOG/9802dbbedcad11c120ddd70a0136e61a
- Merge latest changes from WE
- `//set sand` (or gravel and redsand) is always falling and //undo doesn't remove it (same for voxel)
- `//set lava` lets these material float, //undo them will remove only the lava in the area you selected, same for voxel
- `//fixwater` and `//fixlava` does no longer work
- Pasting a copied region while standing in it doesn't let you chat after it. (see bottom for more information)
- `//snow <radius>` no longer creates snow, just prints the message
- `//schematic list <anything behind>` spams you ingame with null pointers and on console with a stacktrace https://gist.github.com/N0tMyFaultOG/32c4093099de616db723717cbb1297dd

Low priority:
- Differential logging of anvil

Wont fix: (Jesse)
- Cannot bind brushes (`//brush sphere`) to hand

Fixed:
- Fixing block rotations on copy/paste
- `//removenear <item> 0` or any other value lower then 0 -> https://gist.github.com/N0tMyFaultOG/b761ccbbf6f89bccab09fe5e40cce18c
- copy/pasting objects while standing in the copied region results in pasting `Invalid entity minecraft:player` on console, doesn't seem very necessary
- `//mask ?` after equipping a brush results in a stacktrace https://gist.github.com/N0tMyFaultOG/795648734c0a9360e3d0c9af02b4ab96
- `//replacenear 5 grass #simplex[3][18,0]` (or any other input) won't work on simplex 
- `//gmask >[block]` doesn't accept values
- `//mask <stone` (or any other material) doesn't seem to work with the < value
- `//br paint` with any subvalue uses the default WorldEdit mesage
- `disallowed-blocks` from WorldEdit config isn't working 
- `//brush primary <brush> <material> <radius>` equipped with a name instead of block ID gives this stacktrace https://gist.github.com/N0tMyFaultOG/bc2def14bc23eb66b029eaf1f90e5eb5
- `//undo <amount> & //redo <amount>` spams the player with the actual amount of undid and redid actions
- `/searchitem bedrock` or any other block triggers the default WorldEdit message still
- `/b eb` and any subvalue behind is not implemented yet
- Using an invalid block/ID (like in //set) responds with "Unkown block for" instead of using the default Fawe message
- `//setbiome` doesn't work still
- `//br height` creates large stone skyscrappers
- `//br cliff` also creates these large block towers like above 
- `//br flatten` same like above
- `//br smooth` doesn't work properly, creates these structures: (in the background you can see the stone skyscrappers) ![imgur](https://i.imgur.com/1itPzGy.png)
- Odd stacktrace where I cannot locate the source https://hasteb.in/gupenava.yaml
- `//anvil` is not supported
Fixed following brushes
- `/b e melt`
- `/b e fill`
- `/b e smooth`
- `/b e lift`
- `/b e floatclean`
- `//none` doesn't uneqeuip the brush from the tool.
- `//stack <amount>` <amount> (or simply a space) throws a null pointer on the player and prints a stacktrace on console https://hasteb.in/qajivoje.yaml
- `//cancel` is not implemented yet
- Persistent brushes are broken
- `//snow` and `//thaw` prints the message without creating or removing snow.
- `//set hand` or brushing with the hand value accepts items. Holding an apple, a trident or a potion (or something else) triggers the same message as when you hold a block. On 1.12 it tells you that you aren't holding a block
- `//fawe debugpaste` doesn't contain the Fawe version and build number, simply showing 1.0 as version. 
- `//paste` shows the "exact" position up to 14 digits behind the comma (not a real issue but but it would look more neat if you round the coordinates or show just the numbers in front of the comma)
- `//undo <amount>` and `//redo <amount>` prints a stacktrace. (https://hasteb.in/abatewor.yaml)
- If you install Fawe for the first time, only WorldEdit appears on `/plugins` even if all fawe commands are working. It requires a restart to show "both" plugins.
These were also tested on build 37.
- Using `//set` or any brush with a material that doesn't exist like 9999 uses 0 instead of canceling the event.
- `//searchitem <block>`  uses the default WorldEdit message.
- `//setbiome <biome>` triggers the message without changing the biome. 
- `//replace` displays a wrong message. It should show `//replace [from-block] <to-block>` like it does on the previous versions.
- Equipping a brush or //set with the value `-,`  prints this stacktrace https://hasteb.in/ijafahoc.yaml. Maybe try cancelling these events and printing the default message like in the previous versions
- `//frb #import` results in a stacktrace https://hasteb.in/olaroyoc.yaml

**Comment by N0tMyFaultOG** [comment]
- `//setbiome <biome>` triggers the message without changing the biome.

**Comment by ipsk** [comment]
Going to add one that I found too.
- `//replace grass dirt` does not work, but `//replace 2 3`.
Could be because I have CoreProtect installed, because I get a message saying `net.coreprotect.worldedit.CoreProtectLogger@<random number> must be abstract`.

**Comment by N0tMyFaultOG** [comment]
>//replace grass dirt does not work, but //replace 2 3.

Use `//replace grass_block dirt`. Grass targets the actual grass (decoration block) if you put it in.

**Comment by N0tMyFaultOG** [comment]
- `//undo <amount>` and `//redo <amount>` prints a stacktrace. https://hasteb.in/abatewor.yaml
Other commands with integers like //set 0 work fine.
Tested on build 37

**Comment by N0tMyFaultOG** [comment]
- `/transforms` shows a message at the bottom linking to ![this](https://github.com/boy0001/FastAsyncWorldedit/wiki/Transforms) wiki page but it's not clickable like on //help
- `//replace` displays a wrong message. It should show `//replace [from-block] <to-block>` like it does on the previous versions.
- `//paste` shows the "exact" position up to 14 digits behind the comma (not a real issue but but it would look more neat if you round the coordinates or show just the numbers in front of the comma)
- copy/pasting objects while standing in the copied region results in pasting `Invalid entity minecraft:player` on console, doesn't seem very necessary
- Using `//set` or any brush with a material that doesn't exist like 9999 uses 0 instead of canceling the event.
- Equipping a brush or //set with the value `-,`  prints this stacktrace https://hasteb.in/ijafahoc.yaml. Maybe try cancelling these events and printing the default message like in the previous versions
- `//frb #import` results in a stacktrace https://hasteb.in/olaroyoc.yaml
- If you install Fawe for the first time, only WorldEdit appears on `/plugins` even if all fawe commands are working. It requires a restart to show "both" plugins.
These were also tested on build 37. I see that you modified the top issue. I'll put this one in there too.

**Comment by N0tMyFaultOG** [comment]
- `//br height` creates large stone skyscrappers
- `//br cliff` also creates these large block towers like above 
- `//br flatten` same like above
- `//br smooth` doesn't work properly, creates these structures: (in the background you can see the stone skyscrappers) ![imgur](https://i.imgur.com/1itPzGy.png)
- Odd stacktrace where I cannot locate the source https://hasteb.in/gupenava.yaml
- `//none` doesn't uneqeuip the brush from the tool. Getting a new tool fixes it, see below
- I'm unsure if this is a bug or on purpose, anyway it's ugly. If you want to show the equipped brush on the tool, you could try to do it a bit nicer lmao
![imgur](https://i.imgur.com/tSLs9kJ.png)
- `//setbiome` doesn't work still
- `//gmask >[block]` doesn't accept values
- `//mask <stone` (or any other material) doesn't seem to work with the < value
- `//set sand` (or gravel and redsand) is always falling and //undo doesn't remove it (same for voxel)
- `//replacenear 5 grass #simplex[3][18,0]` (or any other input) won't work on simplex 
- `//stack <amount>` <amount> (or simply a space) throws a null pointer on the player and prints a stacktrace on console https://hasteb.in/qajivoje.yaml
- `//set water` (or lava) lets these materials float, //undo them will remove only the water/lava in the area you selected, same for voxel
- `//set kelp` always spawns water around [unsure if this is default minecraft stuff, because you can also w/e in saplings]
- `/searchitem bedrock` or any other block triggers the default WorldEdit message still


These below belong to favs:
- `/b eb fill` not implemented yet
- `/b e fill` prints a stacktrace https://hasteb.in/tapilamo.yaml

Tested on build 54

**Comment by N0tMyFaultOG** [comment]
- `//fixwater` and `//fixlava` always removes the water and lava in a 3x3 radius regardless the radius you put in.

**Comment by N0tMyFaultOG** [comment]
- Using an invalid block/ID (like in //set) responds with "Unkown block for" instead of using the default Fawe message, regardless the typo in there ;)
[Added all previous issues in my first post]

**Comment by N0tMyFaultOG** [comment]
The `disallowed-blocks` blocks section from the config-legacy isn't working at all. I'm unsure if it's supposed to work like that way on 1.13 but there is no other option to block them. 
Also it doesn't understand some item ID's/names and errors them on startup such as 351 (https://hasteb.in/ocomelor.yaml). Using their minecraft names results in the same issue.

**Comment by BiGUNMAN** [comment]
The overlay tool does not work: `/b over (d#)`

**Comment by mercurialmusic** [comment]
Also #1115

**Comment by N0tMyFaultOG** [comment]
- Pasting a copied region while standing in it doesn't let you chat after it.
 Don't chat while you do it or did before, hard to explain but I and several other users had the issue as well.

**Comment by N0tMyFaultOG** [comment]
- `//mask ?` after equipping a brush results in a stacktrace https://gist.github.com/N0tMyFaultOG/795648734c0a9360e3d0c9af02b4ab96
On previous versions it responded with "```Invalid block `<block>`. ```

**Comment by N0tMyFaultOG** [comment]
- `//removenear <item> 0` or any other value lower then 0 -> https://gist.github.com/N0tMyFaultOG/b761ccbbf6f89bccab09fe5e40cce18c
- `//snow <radius>` no longer creates snow, just prints the message

**Comment by dyanakiev** [comment]
- `//fixlightning` prints the message but does nothing.

**Comment by martijnpu** [comment]
`//removelightning` and `//fixlightling` doesn't do anything other than printing a message.
No errors are thrown

**Comment by realkarmakun** [comment]
First of all if you try to use any .js file FAWE (I suppose) will ask you to put js.jar in plugins folder which will create disturbing error message in console but nothing else. And FAWE is looking for .js in WorldEdit/craftsctipts folder

**Comment by Javierko** [comment]
Hi, copying (with //copy) on my server doesnt work, using 1.13.2

**Comment by Tsoccerguy3** [comment]
Bug , //flip stairs when connected at a corner results in the stair backwards 
//rotate stairs does the same thing

Not fixed

**Comment by N0tMyFaultOG** [comment]
Please report fawe bugs and issues for 1.13.2 on the fawe 1.13 repo. The link can be obtained from the readme file.
