### ISSUE TITLE
FAWE 1.13 - //set not writing chunks correctly

### ISSUE THREAD

**Issue by braceyourself07** [boy0001/FastAsyncWorldedit#1080]
# Bug report
**Debug paste link**:  
https://hastebin.com/umizomotem

**Description of the problem:**
While using paperspigot 1.13 build 143 using PlotSquared 18.8.12 with worlds: true, I set pos1 and pos2 to these two blocks:
https://brdv.coffee/storage/uploads/4/ApplicationFrameHost_2018-08-17_10-56-09.png

After typing //set 1, this was the result:
https://brdv.coffee/storage/uploads/4/ApplicationFrameHost_2018-08-17_10-56-16.png

After then restarting the server and logging back in (with no other commands issued) this is what I saw:
https://brdv.coffee/storage/uploads/4/ApplicationFrameHost_2018-08-17_10-56-45.png

**How to replicate**:
Steps above

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Joeywp** [comment]
I'm experiencing the same problem but in 1.12.2 on Java 8. #552 Appears to be related
