### ISSUE TITLE
1.13 LEATHER error

### ISSUE THREAD

**Issue by FrankHeijden** [boy0001/FastAsyncWorldedit#1082]
# Bug report

**Debug paste link**:

https://hastebin.com/afayozired.makefile

**Description of the problem:**

Error with worldguard, was told [here](https://dev.enginehub.org/youtrack/issue/WORLDGUARD-3965) that this was an error caused by FAWE. Error: https://hastebin.com/exilepokup.css

**How to replicate**:
start the server

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Use the WG from the fawe download page.

**Comment by FrankHeijden** [comment]
Why is it not compatible with the default worldguard dev builds?
