### ISSUE TITLE
FAWE clears entity list (1.12)

### ISSUE THREAD

**Issue by aikar** [boy0001/FastAsyncWorldedit#1083]
I've been debugging why people are triggering Chunk Entity issues and traced it back to FAWE

https://github.com/boy0001/FastAsyncWorldedit/blob/master/bukkit/src/main/java/com/boydti/fawe/bukkit/v1_12/BukkitChunk_1_12.java#L245

This code is calling .clear() on the entity list anytime the operation is >= 4096 blocks.
This is resulting in players and probably entities being removed from the chunk slice...

The EXPERIMENTAL.KEEP_ENTITIES_IN_BLOCKS setting doesn't even appear to be checked at all here, so turning that to true (which should be the default!!!) doesn't even solve the problem.

In the example //sphere dirt 25, the player entity is removed from the chunk, and never re-added to the chunk.

FAWE needs to 100% stop touching the entities in a chunk unless that flag is set, and then it should only remove the ones in the region, not all of them.

And finally, please default that setting to true so fawe wont touch it unless people opt into this destructive behavior.

**Comment by boy0001** [comment]
I'll fix, though I didn't think players were stored in the chunk slice.
