### ISSUE TITLE
Out of heap space

### ISSUE THREAD

**Issue by bundabrg** [boy0001/FastAsyncWorldedit#1085]
I'm wanting to create a couple of pull request to fix a couple of issues (for example pasting a large schematic that goes over the 256 height limit throws an exception, and some changes to allow proper worldguard allow/deny flags to be used rather than owners/member in fawe).

However, and this is a terribly noobish question but I'm rusty with Java,  when I try to build this project I run out of Java Heap Space during the decompiles. If I update settings.gradle to only list 'core' and 'bukkit' (the stuff I'm interested in) then I can compile my changes and they work fine.

I've tried setting JAVA_OPTS=-Xmx8192m   which grants that to Gradle itself but probably not what it spawns.

Ta

**Comment by bundabrg** [comment]
Resolved. I set it in gradle.properties instead and it seems to work so I might just keep that as a local change.

**Comment by dooferorg** [comment]
Appreciated.. I missed seeing this when I search, I guess it was filtered by new issues.
