### ISSUE TITLE
1.13.1 support.

### ISSUE THREAD

**Issue by TheIntelloBox** [boy0001/FastAsyncWorldedit#1095]

**Comment by Sikatsu** [comment]
It's giving errors and also has some incompatibility with coreprotect.

https://pastebin.com/GhGb4KnB

**Comment by Tiippex** [comment]
@Sikatsu create a new Issue for that please. This bug is even in 1.12.2 present so thats the wrong place here anyway...

**Comment by Sikatsu** [comment]
@Tiippex Then I really wonder how it's not showing up on 1.13, but is on 1.13.1?

**Comment by GeekzGamingz** [comment]
FAWE not working with my 1.13.1 server:
https://pastebin.com/LQQExWNz

**Comment by danjono** [comment]
@GeekzGamingz That's a WorldEdit not a FAWE error. Get the latest version from the WorldEdit Jenkins server.

**Comment by Sikatsu** [comment]
Using fawe we shouldn't install worldedit from jenkins?

**Comment by N0tMyFaultOG** [comment]
Fawe doesn't work on 1.13.1 yet as I have experienced.

**Comment by boy0001** [comment]
Latest build should work with 1.13.1

**Comment by Sikatsu** [comment]
Still having errors; https://pastebin.com/CJHFsWea

**Comment by boy0001** [comment]
@Sikatsu 
Can you attach your startup log?

**Comment by OllieMartin** [comment]
I’m having this same error! Thought I’d just set it up wrong.

**Comment by GeekzGamingz** [comment]
@danjono I have the latest version from jenkins. I also do not have WorldEdit since it's included in FAWE. It's still not currently working with 1.13.1.

**Comment by GeekzGamingz** [comment]
So I did see there was a new version released today. I installed that on the server and the console is spitting out errors everytime I move.
https://imgur.com/xuPdxa2
