### ISSUE TITLE
Bug report schematics

### ISSUE THREAD

**Issue by Karagounis** [boy0001/FastAsyncWorldedit#1096]
# Bug report

**Debug paste link**:

https://hastebin.com/junijesumo

**Description of the problem:**

Can't load or save schematics.
Console error log: https://hastebin.com/uhulecuzod.apache

**How to replicate**:

logged in, typed in /schem load clipboard.schematic (also did without .schematic and tried to save a schematic.)

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of FAWE
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Update your spigot to 1.13.1
Update Fawe as well
