### ISSUE TITLE
java.lang.NoClassDefFoundError on every time I click in game

### ISSUE THREAD

**Issue by robotnikthingy** [boy0001/FastAsyncWorldedit#1097]
# Bug report

**Debug paste link**:
https://hastebin.com/jiyotuzive

**Description of the problem:**
Whenever I right click with any item, it keeps posting the error "java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldedit.bukkit.CachedBukkitAdapter" in the ingame chat

Here is the error from the console logs
https://hastebin.com/ufefibocic.md

**How to replicate**:
Running a server with spigot 1.13.1, and using the 1.13 download from the FAWE website. Any time I right click it gives the error message in chat and in the server console.

**Comment by chedadmin** [comment]
Also having the same issue.

**Comment by boy0001** [comment]
should be fixed by updating.
