### ISSUE TITLE
Error 1.13.1

### ISSUE THREAD

**Issue by Sikatsu** [boy0001/FastAsyncWorldedit#1098]
I'm receiving this error on 1.13.1: https://pastebin.com/6nZu36Te

**Comment by N0tMyFaultOG** [comment]
Seems like fawe uses a paper event on 1.13+
Try using paper https://destroystokyo.com/ci/job/Paper-1.13/

**Comment by Sikatsu** [comment]
I rather not use paper since not all of my plugins are compatible with it.

**Comment by boy0001** [comment]
you can just ignore it, the plugin will still work.

**Comment by Sikatsu** [comment]
Yeah, I know. Just thought to report it tho.

**Comment by N0tMyFaultOG** [comment]
Has heen fixed in https://github.com/boy0001/WorldEdit/pull/14
