### ISSUE TITLE
Redstone dust not lighting up on paste

### ISSUE THREAD

**Issue by UltraX3** [boy0001/FastAsyncWorldedit#11]
**Description**
When pasting lit redstone dust next to a redstone torch or another source, it will lose its power (lit up stage) unless updated by a block placed by the player. This bug does not affect repeaters, doors, redstone lamps, or any other block that has another data value when powered.

**Example**
Here is an example of this bug. The left is the original and the right is after the paste.
![image](https://cloud.githubusercontent.com/assets/7644264/14022893/e67e5f30-f1af-11e5-96b3-ff02635bc5a2.png)

**Plugin Versions**
FastAsyncWorldEdit: v 3.3.0
WorldEdit: 6.1.1-SNAPSHOT;3392-1dd6faf7

**Comment by UltraX3** [comment]
I am still encountering this bug, it does not appear to be fixed. Note: This also happens when the redstone wire is being powered by a repeater.

**Comment by RoboMWM** [comment]
Was this fixed @UltraX3 ?

**Comment by boy0001** [comment]
@RoboMWM yes
