### ISSUE TITLE
After regen of bigger areas border chunks loaded wrong

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#110]
![2016-05-14_17 46 43](https://cloud.githubusercontent.com/assets/3305006/15269336/ec787a64-19fb-11e6-9797-d382511f4cac.png)
![2016-05-14_17 46 42](https://cloud.githubusercontent.com/assets/3305006/15269335/ec78528c-19fb-11e6-907b-06ac8afdac48.png)
![2016-05-14_17 46 41](https://cloud.githubusercontent.com/assets/3305006/15269337/ec7ba7c0-19fb-11e6-85dd-f792495a8724.png)

Bit hard to explain...
When I move the most far away chunks kind a moving with me. A relog fixes this, so minor issue.

FAWE 3.5.0, but was also present in earlier versions.

**Comment by boy0001** [comment]
Not specific to regen.

**Comment by boy0001** [comment]
Try using `//fixlighting` which will resend the nearby chunks.

**Comment by EvilOlaf** [comment]
It seems like that it resent the new chunks, but did not fix the issue, the repeating chunks just have been changed to another one.

**Comment by RoboMWM** [comment]
From what I remember, if block changes are sent to the client, but outside the client's render distance, things will look very odd/weird at the chunk borders. A similar issue was reported with GriefPrevention. I'd chalk this up to a MC client issue.

**Comment by boy0001** [comment]
Fixed with #107 in 9f86b8f
