### ISSUE TITLE
Sapplings won't grow

### ISSUE THREAD

**Issue by xSamagon** [boy0001/FastAsyncWorldedit#1101]
# Bug report

**Debug paste link**: https://hastebin.com/febokusahe

**Description of the problem:**

If you (replace grown trees and) set saplings in this area with FAWE they won't grow naturally until the chunk is reloaded. With bonemeal they grow fine.

I didn't had this with small regions, but with at least 16x16 regions.

I noticed that bug with the replace steps, but while replicating the bug for the debug paste i noticed that it sometimes simply doesn't grow even without removing something before. 

**How to replicate**:

(1. Select a region (at least 16x16)
2. Set the saplings (ex. 6:1): **//set 6:1**
3. Let the trees grow
4. Select the region with the complete trees
5. Set the region to 0:  **//set 0**)

6. Select the sapling region again (at least 16x16)
7. Set the saplings (ex. 6:1): **//set 6:1**

-> They wont grow naturally
Video: https://www.youtube.com/watch?v=hyruibkA6z8

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin (tryed with normal WE and they growed there)

**Comment by N0tMyFaultOG** [comment]
Fawe doesn't use block updates so saplings won't grow, it's supposed to be like that
