### ISSUE TITLE
Buggy - Crash server

### ISSUE THREAD

**Issue by BenjaminHoegh** [boy0001/FastAsyncWorldedit#1102]
1.13 is so buggy, it time out servers and when using on large scale it forget to do it jobs, so it just leave big area as it was before use any commands

**Comment by LoXR** [comment]
It doesnt even load up on my server, making worldguard and worldedit show red in /pl

**Comment by N0tMyFaultOG** [comment]
Update Fawe and WorldGuard for fawe, use 1.13.1 as well
