### ISSUE TITLE
[Question] Patterns, java.io.FileNotFoundException, and Custom MC Directory

### ISSUE THREAD

**Issue by SextupleTap** [boy0001/FastAsyncWorldedit#1103]
I am having problems with using patterns, such as in the command:
//replace {block} #simplex[20][#existing,#darken[true][50],#lighten[true][50]],#simplex[19.5][#existing,#darken[true][50],#lighten[true][50]]

(Seems to happen with patterns #lighten and #darken)

And it causes the error:
java.io.FileNotFoundException: Please create a `FastAsyncWorldEdit/textures` folder with `.minecraft/versions` jar or mods in it.

My question is if FAWE has some sort of issue with being in a custom directory, as the mod is in 1.12.2 and is in a directory called ".minecraft WorldEdit" and not in the original ".minecraft" directory.

I am also wondering if there is a way to fix this on the mods end and or on my end as well as how the patterns work in relation to the FastAsyncWorldEdit/textures folder, as well as if this is supposed to be "normal?"

(I have created a FastAsyncWorldEdit/textures in every single area I can possibly imagine and nothing works)

[I can remake this as a bug report if needed, but right now I am just asking questions]

**Comment by boy0001** [comment]
Same place as where the configuration and such are located. 
`mods/FastAsyncWorldEdit/textures/1.12.2.jar`

**Comment by buddiboi69** [comment]
I'm having this same problem and I edited the FAWE jar file with WinRAR and added in a textures folder. I pasted the 1.12.2.jar file into the textures folder, copied from .minecraft/versions. I'm still getting the error message.
