### ISSUE TITLE
Wrong rotation when copy/pasting stairs, slabs, fences, glass paints and iron bars and ...

### ISSUE THREAD

**Issue by Skydragonsz** [boy0001/FastAsyncWorldedit#1104]
# Bug report
**Debug paste link**: https://hastebin.com/ilucoqubet

**Description of the problem:** When copy pasting blocks that have a facing direction, it automatically faces north.
![Stairs](https://user-images.githubusercontent.com/1357800/44944979-aa862e00-ade0-11e8-8dda-5babab1b7b87.png)
![Fence](https://user-images.githubusercontent.com/1357800/44945004-f9cc5e80-ade0-11e8-9551-72fc11e04cc3.png)

**How to replicate**: Just copy any block that have a facing value and paste it

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Skydragonsz** [comment]
It seems that spigot 1.13 (git-Spigot-417cfb3-4487c1f) was the problem, when I finally updated to 1.13.1 (git-Spigot-0ede7d0-228a5cd) it was fixed. 
I was running 1.13 because the hosting company that I'm using didn't allow 1.13.1 yet. 

To the developer: I hope you can make a 1.13 version for the ones that are still stuck on version 1.13 and I know that this is possible because WE itself runs fine on 1.13.
I also don't know if I should close this issue as some still experience this!

**Comment by mercurialmusic** [comment]
This still happens in 1.13.1 for me.

**Comment by Vanillezucker** [comment]
Sorry, I did not scroll past 2 whole months for dupes. Please fix this, apparently we're waiting for a long time already.

**Comment by Draycia** [comment]
Theres a search feature.

**Comment by Pelt10** [comment]
I just test with git-Spigot-a1f2566-8cd538e and FastAsyncWorldEdit-bukkit-18.11.21-99fb2b5-2072 and doesn't work.

**Comment by N0tMyFaultOG** [comment]
Fixed in upcoming versions

**Comment by Skydragonsz** [comment]
Thanks for the fix!

**Comment by Sean1472** [comment]
Sorry to repost. What update was this fixed in? I can't seem to find the update logs to say it was fixed.

**Comment by iMontouch** [comment]
any news on this? I'm running 1.14-33.

**Comment by N0tMyFaultOG** [comment]
This is the legacy repo, move to https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13

**Comment by Shewolf1896** [comment]
still getting this issue in 1.15.2??
