### ISSUE TITLE
1.13.1 version breaks plugins which rely on using worldedit to make selections

### ISSUE THREAD

**Issue by robotnikthingy** [boy0001/FastAsyncWorldedit#1106]
# Bug report

**Debug paste link**:
https://hastebin.com/cejatigage

**Description of the problem:**
It seems that plugins which rely on Worldedits selection API are broken. Since you can't seem to install Worldedit alongside FAWE this seems to be a problem

**How to replicate**:
For example, when trying to create a portal using Multiverse Portals (which relies on WorldEdits selection) it gives this error

https://hastebin.com/darihucuje.cs

When trying to do the same thing with AdvancedPortals, it doesnt even recognize selections made with FAWE

**Comment by Artuto** [comment]
Any update on this? This is important.

**Comment by dordsor21** [comment]
I think you'll have the same issue with using normal WorldEdit, unless they've kept depreciated methods. As WE 1.13.1 (i.e. WE 7) has an updated/the same API as FAWE
