### ISSUE TITLE
NullPointerException with LuckPerms while doing /wea [Nukkit]

### ISSUE THREAD

**Issue by funniray** [boy0001/FastAsyncWorldedit#1108]
# Bug report

**Debug paste link**: Can't, Hastebin returned 503 error.

**Description of the problem:**

When LuckPerms is installed along with the latest version of FAWE, it throws a null pointer exception.
This only occurs when LuckPerms is installed.
![image](https://user-images.githubusercontent.com/16416198/44957591-8d656400-aea1-11e8-9017-9453f491e8fc.png)

**How to replicate**:

Install FAWE on Nukkit
Install LuckPerms
Go to a protected area
Do /wea

**Checklist**:

- ~I included a `/fawe debugpaste` link~ Can't right now, Hastebin throws an error
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
It's not a FAWE bug. I've submitted changes to LuckPerms which addresses the issue, see: 
https://github.com/lucko/LuckPerms/pull/1213
