### ISSUE TITLE
FAWE is blocking tab-completion in chat. 

### ISSUE THREAD

**Issue by NolanMC** [boy0001/FastAsyncWorldedit#1112]
# Bug report

**Debug paste link**: https://hastebin.com/cehimopizi

**Description of the problem:**

FAWE is somehow blocking tab completion in chat. Figured this out by using a test environment and eliminating plugins one by one. It seems to not be affecting vanilla minecraft commands, but commands provided by other plugins. If you uninstall FAWE then the tab completion works as intended. 
**How to replicate**:

1. Download FAWE and a plugin that supports tab completion in 1.13.1 
2. Try to tab complete a command 
3. It will tab complete the first part of the command and then stop when hitting an argument. 
4. Uninstall FAWE, and tab completion should work as intended. 

EDIT: 9/4 Latest FAWE commit does not fix this issue. 
**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Fixed in https://github.com/boy0001/WorldEdit/commit/fc949e3efcc1d4458a68e3ec548d43b12ab8dc57
