### ISSUE TITLE
Bug ParserException

### ISSUE THREAD

**Issue by fhebuterne** [boy0001/FastAsyncWorldedit#1121]
# Bug report

Hello, 
We have seen some errors in our logs with the last version of FastAsyncWorldEdit.
Could you fix this please ?

**Description of the problem:**
Some errors in our logs

**How to replicate**:
Use commands like : //replace 0 5%95:395%95:9
The probleme is the characters " : "

Look the error here : https://pastebin.com/HKmTMz5Y

**Checklist**:
- [] I included a `/fawe debugpaste` link ( I have an error 503 with this, i can't get this file )
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
You forgot the comma.

**Comment by fabien91** [comment]
@boy0001 It's not me, it's one of my players but it's not possible to show error message just for the player and not a big exceptions in console/log ?
