### ISSUE TITLE
/b e melt broken

### ISSUE THREAD

**Issue by StealWonders** [boy0001/FastAsyncWorldedit#1122]
# Bug report
**Debug paste link**:
https://pastebin.com/PxhD0nkE

**Description of the problem:**
Nothing works, simple as that

**How to replicate**:
Just use paperspigot v. 232 plus FAVS v. 18.09-04-594d72d-2030

**Comment by N0tMyFaultOG** [comment]
See #1079

**Comment by boy0001** [comment]
Fixed in: https://github.com/boy0001/WorldEdit/commit/c1f9120cee1b2c7c87a9c0abaa5178feb66d212f
