### ISSUE TITLE
The FAVS erode brush is actually extremely broken now that the dependency is there.

### ISSUE THREAD

**Issue by Aerodog** [boy0001/FastAsyncWorldedit#1125]
https://imgur.com/a/pgKDfWp <-- using a variety of erode brushes places odd things...

3 different errors. Melt, erode, and undo:
https://paste.md-5.net/gasiratobe.txt

Another error when sniping over the banners that got placed by erode... https://paste.md-5.net/cahicubomo.txt

**Comment by N0tMyFaultOG** [comment]
Try updating fawe & faws.
When the error persist still, comment below
