### ISSUE TITLE
FaWe can't detect sponge schematic files

### ISSUE THREAD

**Issue by alex9849** [boy0001/FastAsyncWorldedit#1127]
#1086 

I now know why my plugin can't use the sponge schematic format.
If I try to load a schematic file with the API, the method _ClipboardFormats.findByFile(file)_
can't detect sponge schematic files. It returns the _ClipboardFormat.SCHEMATIC_ enum when it should return _ClipboardFormat.SPONGE_SCHEMATIC_.

By the way this is the code I use:

    public void resetBlocks(com.sk89q.worldguard.protection.regions.ProtectedRegion region, String worldname, com.sk89q.worldedit.WorldEdit we) {
        File pluginfolder = Bukkit.getPluginManager().getPlugin("MyFunnyPlugin").getDataFolder();
        File file = new File(pluginfolder + "/schematics/" + worldname + "/" + region.getId() + ".schematic");
        World weWorld = new BukkitWorld(Bukkit.getWorld(worldname));
        try {
            ClipboardFormats.findByFile(file).load(file).paste(weWorld, region.getMinimumPoint());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

**Comment by boy0001** [comment]
`.schem` is the extension for sponge schematics. `.schematic` is the extension for the legacy schematic format. See:
https://github.com/SpongePowered/Schematic-Specification/blob/master/versions/schematic-1.md#format
