### ISSUE TITLE
What is DummyFawe.jar?

### ISSUE THREAD

**Issue by CloudeLecaw** [boy0001/FastAsyncWorldedit#1129]
If i start the latest FAWE for 1.13 
i get a unknown file called DummyFawe.jar in my DummyFolder.
what is this file for? and can it be "fixed" that it will not be created? - Its a scarry 2kb jar.. and i think it may not be needed....

**Comment by dordsor21** [comment]
It's needed as it allows you to support plugins that require either WorldEdit or FAWE to work. It basically acts like an API for plugins that require FAWE.

**Comment by CloudeLecaw** [comment]
Is it possible to implement this into the FAWE file itself? I renember oder FAWE didnt had it, so it may was inside?

**Comment by dordsor21** [comment]
No, as old FAWE wasn't inside WorldEdit. So in order for all dependencies to be met ther emust be two plugins, one called "WorldEdit" and one called "FastAsyncWorldEdit". n this case the DummyFAWE is the plugin called FastAsyncWorldEdit.
