### ISSUE TITLE
block ids messed up after using //rotate

### ISSUE THREAD

**Issue by keough99** [boy0001/FastAsyncWorldedit#113]
![2016-05-15_18 26 05](https://cloud.githubusercontent.com/assets/13394623/15277175/a8e6dcaa-1ad2-11e6-8a27-ada41048259f.png)
the area where the air is was all doors and the rotation of the stairs were messed up

**Comment by boy0001** [comment]
Please attach your FAWE config and startup log (latest.log in logs folder)

**Comment by keough99** [comment]
[latest.txt](https://github.com/boy0001/FastAsyncWorldedit/files/276288/latest.txt)
[config.txt](https://github.com/boy0001/FastAsyncWorldedit/files/276289/config.txt)
theres the config and todays startup log

**Comment by boy0001** [comment]
Please update WorldEdit, you are using an outdated version.

i.e. in your startup log:
```
**********************************************
** This WorldEdit version does not fully support your version of Bukkit.
**
** When working with blocks or undoing, chests will be empty, signs
** will be blank, and so on. There will be no support for entity
** and biome-related functions.
**
** Please see http://wiki.sk89q.com/wiki/WorldEdit/Bukkit_adapters
**********************************************
```
