### ISSUE TITLE
[Bug] [Forge] ConcurrentModificationException when modification commands are used

### ISSUE THREAD

**Issue by xunto** [boy0001/FastAsyncWorldedit#1130]
# Bug report

**Debug paste link**: https://hastebin.com/esiginucun
**Description of the problem:** @boy0001, sometimes when I try to do some modification command (//replace or etc) with fawe, some blocks in region are modified and some are not. It kinda correlates with chunk edge but not completely as you can see in the image.

![2018-09-13_04 38 07](https://user-images.githubusercontent.com/5288053/45462211-7f200f00-b70f-11e8-9915-990290c58f58.png)

Logs are included in debug-paste. Looks pretty similar to #1027 but different as I don't use GriefPrevention and Sponge. Also, different from this issue, I can modify some blocks.

It doesn't fixed with server restart and It doesn't happen with ordinary WE and Sponge version of fawe (I use forge version).

**How to replicate**: Don't know exactly, it just happens when I do //replace (or any other modification) in some places in the world.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report 
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by xunto** [comment]
UPDATE: Looks like it somehow related to chests. When I removed them, everything worked as expected. But if I place chest and then try to replace it, exception doesn't appear.

**Comment by evernife** [comment]
Same here, tested on Sponge server and PureForge client.


SinglePlayer tested versions:

> Minecraft 1.12.2
> FastAsyncWorldEdit-forge112-19.03.02-14f3b91-1254-22.0.11
> worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist
