### ISSUE TITLE
FAWE plugin auto stop my server

### ISSUE THREAD

**Issue by lunarenzox** [boy0001/FastAsyncWorldedit#1133]
the plugin auto stop my server and start it again, please help i have this error on console:
`18.09 02:43:13 [Server] INFO java.lang.IllegalArgumentException: Command /targetoffset cannot be alias for itself
18.09 02:43:13 [Server] INFO at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot100.jar:git-Spigot-d5dfb24-ed8c725]
18.09 02:43:13 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.help.CommandAliasHelpTopic.<init>(CommandAliasHelpTopic.java:18) ~[spigot100.jar:git-Spigot-d5dfb24-ed8c725]
18.09 02:43:13 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.help.SimpleHelpMap.initializeCommands(SimpleHelpMap.java:137) ~[spigot100.jar:git-Spigot-d5dfb24-ed8c725]
18.09 02:43:13 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:341) ~[spigot100.jar:git-Spigot-d5dfb24-ed8c725]
18.09 02:43:13 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) ~[spigot100.jar:git-Spigot-d5dfb24-ed8c725]
18.09 02:43:13 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) ~[spigot100.jar:git-Spigot-d5dfb24-ed8c725]
18.09 02:43:13 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) ~[spigot100.jar:git-Spigot-d5dfb24-ed8c725]
18.09 02:43:13 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) ~[spigot100.jar:git-Spigot-d5dfb24-ed8c725]
18.09 02:43:13 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot100.jar:git-Spigot-d5dfb24-ed8c725]
18.09 02:43:13 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]`

**Comment by boy0001** [comment]
Try updating spigot, and deleting `plugins/FastAsyncWorldEdit/commands.yml`
