### ISSUE TITLE
Server crash with "Exception ticking world" when set biome (//setbiome)

### ISSUE THREAD

**Issue by RichVillage** [boy0001/FastAsyncWorldedit#1134]
# Bug report

Error: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.io.IOException: Server returned HTTP response code: 503 for URL: https://hastebin.com/documents

**Description of the problem:**

When set biome using //setbiome, server crashes with "Exception ticking world"

**How to replicate**:

1. Select a position (//pos1, //pos2)
2. Set a biome (//setbiome ocean)
3. Server crashes

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by IronApollo** [comment]
Duplicate #1116
