### ISSUE TITLE
Pull latest WorldGuard commits into FAWE WorldGuard.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#1138]
Paper dev 284 (Spigot 1.13.1)
FAWE 1.13 dev 77
FAVS 1.13 dev 77
FAWE-WorldGuard 1.13 dev 21

Upstream WorldGuard has a new commit. However official WorldGuard dev builds do not work with FAWE 1.13, so latest commits need to be pulled and rebuilt with FAWE dependencies.

https://github.com/sk89q/WorldGuard/commit/ee4259b88d1becf85ab46a6dc3be87a0ff5fea42

**Comment by boy0001** [comment]
fixed
