### ISSUE TITLE
Brushes not working on 1.13.1

### ISSUE THREAD

**Issue by robotnikthingy** [boy0001/FastAsyncWorldedit#1140]
# Bug report
**Debug paste link**:
https://hastebin.com/imobofohug

**Description of the problem:**
Trying to use any of the brush doesnt seem to work.

**How to replicate**:
heres an example
Use command /brush cyl stone 2
Use on stick
You get message saying that brush is set
But when you click to use the brush, nothing happens
No error message or anything in the console

**Comment by N0tMyFaultOG** [comment]
Try updating fawe and test it on a plain server, I couldn't reproduce it :(
