### ISSUE TITLE
Entities no longer included in pastes

### ISSUE THREAD

**Issue by mercurialmusic** [boy0001/FastAsyncWorldedit#1147]
# Bug report
As of Build#84 (FastAsyncWorldEdit-bukkit-18.10.04-75c111e-2053.jar) entities are no longer being included in pastes. This was working on previous builds.

**Debug paste link**:

**Description of the problem:**

**How to replicate**:

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by iTaeyeonKim** [comment]
Agree. Same issue here

**Comment by N0tMyFaultOG** [comment]
#1115

**Comment by mercurialmusic** [comment]
This had nothing to do with #1115. It was a new issue unique to build#84 where mobs and villager entities were not being included in the paste. I went back to build#83 and the problem was fixed. The comment below my original post, I think, was mistaken, nor did they reference which build they're using.

**Comment by N0tMyFaultOG** [comment]
> This had nothing to do with #1115. It was a new issue unique to build#84 where mobs and villager entities were not being included in the paste. I went back to build#83 and the problem was fixed. The comment below my original post, I think, was mistaken, nor did they reference which build they're using.


I assumed you meant items in chests, my bad :)

**Comment by IronApollo** [comment]
Unable to reproduce on build 84 according to the provided description.
https://gyazo.com/840b688e76e529eb4f740ed60c7268e9
