### ISSUE TITLE
Blockid messed up

### ISSUE THREAD

**Issue by MWFIAE** [boy0001/FastAsyncWorldedit#115]
Blocks "DamageValue" are messed up... 

Reproduce Steps
Place Birk-Wood
![2016-05-16_22 10 23](https://cloud.githubusercontent.com/assets/6072971/15302420/2c8ec80c-1bb3-11e6-86bd-9f4e6ac907ac.png)

//copy
//paste

Result
![2016-05-16_22 10 32](https://cloud.githubusercontent.com/assets/6072971/15302424/32b66140-1bb3-11e6-93b4-d7d5b1d814a2.png)

Using Paper 1.9.2 and latest FAWE

**Comment by boy0001** [comment]
Latest fawe is only for 1.9.4. Use 3.4.3 for 1.9.2
