### ISSUE TITLE
#fullcopy is unable to find schematics created in 1.13

### ISSUE THREAD

**Issue by Chipmunk46** [boy0001/FastAsyncWorldedit#1151]
# Bug report
**Debug paste link**:
https://hastebin.com/ciwixekego

**Description of the problem:**
When using the #fullcopy pattern with schematics created in 1.13, FAWE is unable to find the schematic despite it being able to load it up and paste it with other methods of loading schematics.

**How to replicate**:
- Create a schematic in 1.13
- Use the #fullcopy and use it to load the schematic
- Gives an error saying "Schematic not found: (yourschematic)
- java.lang.reflect.InvocationTargetException

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by IronApollo** [comment]
Add your schematic's file extension to the end of your schematic name.  E.g. "grass.schematic, grass.schem, grass.nbt, grass.png"

**Comment by Chipmunk46** [comment]
> Add your schematic's file extension to the end of your schematic name. E.g. "grass.schematic, grass.schem, grass.nbt, grass.png"

When I did this it gave me the message: "Input is corrupt! 0 blocks affected" This seems to be mostly with schem files and not schematic files
