### ISSUE TITLE
//download and //asset does not work.

### ISSUE THREAD

**Issue by Duqino** [boy0001/FastAsyncWorldedit#1157]
Hello,

I cant get the //download and //asset to work. Changed the settings/config (added both links to the websites) but keeps saying the same thing.

https://pastebin.com/td3P5WGW
https://pastebin.com/zegEYt4G
https://hastebin.com/epudegawec

I can upload a schematic via the website to the server. But not the other way.

Im running 1.13.1 and im 2 updates behind. So kinda up to date.

[![Screenshot from Gyazo](https://gyazo.com/2466f31fc5f85e781cbfe4e8729d72ea/raw)](https://gyazo.com/2466f31fc5f85e781cbfe4e8729d72ea)

**Comment by N0tMyFaultOG** [comment]
Like you can see on the screenshot above, it's currently not supported but might be working in the far future again.

**Comment by Duqino** [comment]
True but im not 100% sure. Thats why im posting it.

**Comment by MrZero1** [comment]
Nekem se jó :(

**Comment by poma123** [comment]
A probléma nálam is jelentkezett elég sokszor.
Nyugtalanító.

**Comment by MrZero1** [comment]
Kéremszépen, tessenek javítani az egészet, mert nem jó. Sőt, egyenesen szar. Tessenek megoldani legyenek kedvesek. Köszi.

**Comment by poma123** [comment]
Jó lenne már mert széklet. Majd a fordítóban válasszátok a magyar nyelvet. Köszi

**Comment by MrZero1** [comment]
Gugli transzlét magyarra. Nem hungry amúgy.

**Comment by poma123** [comment]
Éhes magyar vagyok. Mekkora szójáték, elmegyek a 3,14csába.

**Comment by MrZero1** [comment]
Siracc fawe. [ WARN java.lang.NullPointerException ]

**Comment by poma123** [comment]
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException

**Comment by MrZero1** [comment]
Csak jelzem, hogy ezt egy schem berakás után írja a konzol. : ) )) ) ) ) )) ) ) ) )

**Comment by poma123** [comment]
Elvagyunk amúgy, jó te$ák ezek. Csak hib4't javít4ni nem tudn4k

**Comment by poma123** [comment]
kérek bubis kaktuszt

**Comment by MrZero1** [comment]
pupis cacti

**Comment by poma123** [comment]
Szaturnusz.

**Comment by MrZero1** [comment]
Okos falevél??

**Comment by poma123** [comment]
Ehnaton..!

**Comment by MrZero1** [comment]
thor nem halt meg

**Comment by poma123** [comment]
java.lang.NullPointerException-t kapott, nem?

**Comment by MrZero1** [comment]
![kep](https://user-images.githubusercontent.com/29709854/47260559-3271e580-d4be-11e8-8622-0e438b702048.png)
sose lesz vége

**Comment by MrZero1** [comment]
az

**Comment by poma123** [comment]
ez

**Comment by MrZero1** [comment]
amaz

**Comment by MrZero1** [comment]
ha van amazon akkor van amazoff is?

**Comment by poma123** [comment]
van

**Comment by poma123** [comment]
szeresd a testem bébi

**Comment by MrZero1** [comment]
kutyapopó

**Comment by poma123** [comment]
kutya ánusz

**Comment by MrZero1** [comment]
kUtYaKaKiLyUk

**Comment by poma123** [comment]
☺☺☺☺☺☺

**Comment by poma123** [comment]
Azóta se voltak képesek. :DDDD

**Comment by poma123** [comment]
na mizu azota se javitottatok stilok

**Comment by poma123** [comment]
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException

**Comment by poma123** [comment]
irjal tes

**Comment by poma123** [comment]
gg

**Comment by poma123** [comment]
akk jaitotad

**Comment by N0tMyFaultOG** [comment]
I'd appreciate it if you reduce this spam and keep it in english.

**Comment by poma123** [comment]
It's okay, sorry for that.
