### ISSUE TITLE
Cannot load with Spigot 1.13.1

### ISSUE THREAD

**Issue by mrcoffee1026** [boy0001/FastAsyncWorldedit#1159]
Cannot load with Spigot 1.13.1
Errors here: https://pastebin.com/MVMjUwuu

Tried to report as worldguard problem they said I needed to install WorldEdit installed.  This error goes away if I uninstall FAWE and install WorldEdit.

This server is running CraftBukkit version git-Spigot-f6a273b-cd6252a (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)[m

**Comment by N0tMyFaultOG** [comment]
Use Fawe's WorldGuard
