### ISSUE TITLE
[TabAutocomplete] Method "isCommand()" not found in bukkit API.

### ISSUE THREAD

**Issue by MiMic10110** [boy0001/FastAsyncWorldedit#1161]
Using Newest spigot 1.13 + latest build of FAWE from builds page
https://pastebin.com/7q5ZtFni

**Comment by MiMic10110** [comment]
Please, fix it as fast as it is possible because this plugin breaks tag complete for any command on the server and console is spammed by this stacktrace.

**Comment by eUipKh** [comment]
Use this version https://ci.athion.net/job/FAWE-1.13/97/

**Comment by CloudeLecaw** [comment]
hmm i used Build 98...
FastAsyncWorldEdit-bukkit-18.10.19-0c4adb3-2068

**Comment by eUipKh** [comment]
I think is 98 version with spigot (not paper) servers

**Comment by Bobbbe** [comment]
i have this error 2, and im use spigot not paper.
