### ISSUE TITLE
Multi Bug 1.13.1 : Stack,Hpos1,Undo wis Copy Paste

### ISSUE THREAD

**Issue by xam74er1** [boy0001/FastAsyncWorldedit#1166]
# Bug report

**Debug paste link**:
https://hastebin.com/zewisehemi

**Description of the problem:**

Stack on diagonale (45 °)  dosent work .

Hpos1 and Hpos2 make a error in the consol and the chat.
 
World edit cant run command after a specfique undo 

**How to replicate**:
Place a block and look on SHOUT-WEST for exmple and they wrinte SOUTH-WEST was a unknow direction , he was possible in old vertion to stack in diagonale .

Hpos 1 and Hpos 2 in not visible player zone / non loader zone they put a error in the console and put in the cat has famous "NullPointerException".

For this copy a bed wis trapdoor , paste and undo . After this when you try a other command we are a message "Cannot send a chat Message" in red .
In the consolt i have : (FAWE) Invalid entity minecraft:player

**Comment by N0tMyFaultOG** [comment]
Update your server to 1.13.2 and download the latest Fawe build [here](https://empcraft.com/fawe/download/?bukkit113), I tried to reproduce the hpos thing but without a success. The invalid entity is known.
