### ISSUE TITLE
[1.13.2] FAWE doesn't work, errors

### ISSUE THREAD

**Issue by Sikatsu** [boy0001/FastAsyncWorldedit#1168]
**Debug paste link**:
https://hastebin.com/yorujebowi

**Description of the problem:**
WorldEdit commands do not work. Error output: https://pastebin.com/mmgtDrS5

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Sikatsu** [comment]
Another error: https://pastebin.com/vypv9dkd

**Comment by N0tMyFaultOG** [comment]
1.13.2 isn't written yet.

**Comment by Sikatsu** [comment]
I know, just letting you know.

**Comment by Midnight9746** [comment]
If it's not written yet, why do you expect it to be working?

**Comment by Sikatsu** [comment]
I don't expect it to be working. Just informing with the errors.

**Comment by PlasmaPod** [comment]
> 1.13.2 isn't written yet.

what do you mean by this as in you havent updated it yet or worldedit isnt updated

**Comment by N0tMyFaultOG** [comment]
WorldEdit is for 1.13.1 iirc and fawe has no adapted yet for 1.13.2
