### ISSUE TITLE
Crash on //set 8,12, etc...

### ISSUE THREAD

**Issue by Sitmobedaf** [boy0001/FastAsyncWorldedit#117]
If you try to set >1000 blocks, there is a server crash

http://pastebin.com/fkQAagBL

**Comment by RoboMWM** [comment]
Iirc this isn't for 1.7.

Which means FAWE probably isn't even running.

**Comment by boy0001** [comment]
FAWE should still inject and attempt to run, though only 1.8.8 and 1.9.4 are officially supported right now. When FAWe is no longer in beta I'll add proper support to those versions.

If you want to try your luck, some older releases may work better:
https://github.com/boy0001/FastAsyncWorldedit/releases/
or some development builds
ci.athion.net/job/FastAsyncWorldEdit/

**Comment by Sitmobedaf** [comment]
I do not know, as in other countries, but in Russia there are many servers use kernel 1.7.10. I beg you, add support v1_7_R4. 
My server is: play.sparkgames.ru Plugin use in mode: Creative.

**Comment by boy0001** [comment]
Probably fixed since it now has proper 1.7.10 support
