### ISSUE TITLE
[1.13.2] FAWE wont set any blocks in any region if there's any gap of air between the two points

### ISSUE THREAD

**Issue by ameliaversia** [boy0001/FastAsyncWorldedit#1171]
First I create two points and attempt to select them
![image](https://user-images.githubusercontent.com/44408393/47373216-a513d880-d6eb-11e8-9083-e6d63b729e2e.png)

![image](https://user-images.githubusercontent.com/44408393/47373257-bf4db680-d6eb-11e8-9ea5-c217bce702c8.png)

let's //set with sponge as an example
![image](https://user-images.githubusercontent.com/44408393/47373335-ea380a80-d6eb-11e8-824b-7bf91f155ecf.png)

Only replaces one the first position as theres air in the way to reach the 2nd position,

versions: latest FAWE version on 1.13.2 with these plugins
[https://i.imgur.com/2kMUh8o.png](url)

**Comment by N0tMyFaultOG** [comment]
1.13.2 isn't supported yet.
