### ISSUE TITLE
Stack changes high grass to flower

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#118]
Sounds weird, doesn't it?

On the first screenshot you can see the command blocks and on their left some high grass.
I took one of them and stacked it five times and as visible on the second screenshot the high grass does not get replaced properly. Works with other blocks than 137 too.
FAWE 3.5.0 @ Spigot 1.8.8

![2016-05-20_11 38 59](https://cloud.githubusercontent.com/assets/3305006/15423844/ae18ec8a-1e7f-11e6-936d-abac601a8a3b.png)

![2016-05-20_11 39 11](https://cloud.githubusercontent.com/assets/3305006/15423826/97af4a16-1e7f-11e6-98ab-be9b8eb22ff7.png)

On destroy there is no drop of flower or grass which is kind a expected.

**Comment by boy0001** [comment]
That's just how the texture is registered. FAWE doesn't perform physics so it doesn't pop off.

Just punching the bottom layer you'll see the top be a flower for a fraction of a second.
