### ISSUE TITLE
Tab Complete Errors

### ISSUE THREAD

**Issue by zerafox** [boy0001/FastAsyncWorldedit#1181]
# Bug report

05.11 17:07:13 [Server] ERROR Could not pass event TabCompleteEvent to WorldEdit vunspecified
05.11 17:07:13 [Server] INFO org.bukkit.event.EventException: null
05.11 17:07:13 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
05.11 17:07:13 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
05.11 17:07:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
05.11 17:07:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
05.11 17:07:13 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.tabComplete(CraftServer.java:1668) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
05.11 17:07:13 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:49) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
05.11 17:07:13 [Server] INFO at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:68) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
05.11 17:07:13 [Server] INFO at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:379) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
05.11 17:07:13 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:514) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
05.11 17:07:13 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInTabComplete.a(SourceFile:36) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
05.11 17:07:13 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInTabComplete.a(SourceFile:9) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
05.11 17:07:13 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
05.11 17:07:13 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
05.11 17:07:13 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
05.11 17:07:13 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
05.11 17:07:13 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
05.11 17:07:13 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
05.11 17:07:13 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
05.11 17:07:13 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
05.11 17:07:13 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
05.11 17:07:13 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.event.server.TabCompleteEvent.isCommand()Z
05.11 17:07:13 [Server] INFO at com.boydti.fawe.bukkit.listener.SyncTabCompleteListener.onTabComplete(SyncTabCompleteListener.java:16) ~[?:?]
05.11 17:07:13 [Server] INFO at sun.reflect.GeneratedMethodAccessor92.invoke(Unknown Source) ~[?:?]
05.11 17:07:13 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
05.11 17:07:13 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
05.11 17:07:13 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
05.11 17:07:13 [Server] INFO ... 19 more

**Debug paste link**:
[<FAWE DEBUG](https://hastebin.com/cubafehiqu)

**Description of the problem:**
An Error pops into console when attempting to Tab-Complete.

**How to replicate**:
Not entirely sure? I was performing commands with the attempt to use the Tab-complete feature for such plugins as World Guard, Vanilla and Multiverse while initial world setup of my server.

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Delete WorldEdit, FastAsyncWorldEdit and retry it whit [this build](https://ci.athion.net/job/FAWE-1.13/lastSuccessfulBuild/artifact/target/FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar). iirc this has been fixed in a previous patch.

**Comment by zerafox** [comment]
WorldEdit isn't installed, only FAWE.
Also that was the only version I was able to find, but I'll give this other version a try.

**Comment by DereC4** [comment]
> WorldEdit isn't installed, only FAWE. Also that was the only version I was able to find, but I'll give this other version a try.

Hey I'm getting similar errors years later, could you describe how you fixed it?
