### ISSUE TITLE
Compatibility for ChestShop

### ISSUE THREAD

**Issue by TheoRetisch1** [boy0001/FastAsyncWorldedit#1184]
Hej,
ChestShop is the shop plugin of the past, present and future. Apart from Villager or GUI solutions there is no alternative decent plugin. ChestShop was and still is the most popular shop plugin. Unfortunately it doesn't work with version 1.13.2 anymore. The problem is the custom Wolrdguard version of FAWE. Chestshop deactivates itself when starting after an error. With the official release of Worldguard this doesn't happen and everything except FAWE runs fine. I will be grateful for any help you can provide :)

error: https://pastebin.com/x2v58A5H
Paper 1.13.2 #427
ChestShop 3.9.3-SNAPSHOT (build 104) (https://ci.minebench.de/job/ChestShop-3/)
FAWE Worldguard version: 7.0.0-SNAPSHOT;0dc5781
Official Worldguard release (working): http://builds.enginehub.org/job/worldguard/last-successful?branch=master

**Comment by TheoRetisch1** [comment]
The author of ChestShop, Phoenix616, will not fix this error for understandable reasons:

> "This is an error that needs to be fixed in their custom version as it breaks every plugin that tries to do similar things (hook into WorldGuard on plugin load which is an extremely common thing to do). The fact that it works on the normal WorldGuard version and not their custom one shows that it is due to (probably unnecessary) changes made by them.
> 
> I also kinda fail to see why they even need a custom WorldGuard version to begin with, if their WorldEdit fork breaks existing plugins then they really need to think about fixing that instead of customising every single plugin to work with their hack."
 (source: https://github.com/ChestShop-authors/ChestShop-3/issues/180)

This makes it even more important to find a solution with which FAWE and ChestShop can be operated simultaneously right here.

**Comment by mibby** [comment]
Likewise to above, can we just go back to FAWE being an addon extension that hooks into vanilla WorldEdit rather than an all inclusive fork of it? Being a fork of WorldEdit with breaking changes causes every plugin that relies on WorldEdit in some fashion to break. :( Even FAWE's version of WorldGuard and FAWE's version of CraftBook have issues that aren't present in the official build.
