### ISSUE TITLE
PlotSquared delete, clear, and merge do not work.

### ISSUE THREAD

**Issue by Mobkinz78** [boy0001/FastAsyncWorldedit#1187]
# Bug report
**Debug paste link**: https://hastebin.com/ahilumigaz

**Description of the problem:**
In typing /plot delete, /plot clear, or /plot merge it gives a message as if it worked i.e. "Plot cleared in 120ms!" Unfortunately nothing is printed in console by either plugin. If I uninstall FAWE,  aka just remove the jar from /plugins, then the plot commands work as intended. 
Do note, though, that people still can't WorldEdit on plots that aren't theirs- region protection works as intended. I'm on the most recent and stable versions of PlotSquared and of FAWE (10/26)

**How to replicate**:
Type /plot delete, /plot clear, or /plot merge. Nothing in console shows up which makes me feel very guilty writing this issue report because it's not that helpful without any issue reports.
Here is a report on PlotSquared from earlier this year that could be helpful: [https://github.com/IntellectualSites/PlotSquared/issues/2112] - I was a bit unclear on it myself, but posting here as it could be a FAWE issue. Apologies if it is indeed a PS issue (couldn't find any other threads)

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
-- Anything else mentioning plotsquared didn't seem the same. The only thing that seemed potentially related was goPaint/goBrush, but unsure if that has any relevance (apologies if it does; both plugins relying on another plugin? it was from mar 20th 2017 though)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

Thanks in advance

**Comment by N0tMyFaultOG** [comment]
Fixed in https://github.com/boy0001/WorldEdit/pull/19

**Comment by Mobkinz78** [comment]
Where am I able to download the build with the fix / that successful commit?

**Comment by N0tMyFaultOG** [comment]
>Where am I able to download the build with the fix / that successful commit? I just updated the plugin to double check about 10 minutes ago.

Either compile it yourself or visit us on our [discord](https://discord.gg/ngZCzbU), I've published a version there.

**Comment by Mobkinz78** [comment]
Brilliant, thanks for the fast response. Much appreciated. Apologies for overlooking the other reports.
