### ISSUE TITLE
Error with Forge 1.8.9

### ISSUE THREAD

**Issue by Small-Ku** [boy0001/FastAsyncWorldedit#119]
It will never be completed and it do nothing.
Log:http://pastebin.com/kM4ki7S8
Screenshot in the log:
![2016-05-21_14 00 21](https://cloud.githubusercontent.com/assets/16464896/15446759/ef034b90-1f5c-11e6-920a-4781beed37da.png)

**Comment by boy0001** [comment]
Can you provide your startup log and check if there are any errors when you used the command?

**Comment by Small-Ku** [comment]
Crash Report here:http://paste.ee/p/xHaRC
Log here:http://pastebin.com/kM4ki7S8
I just used //set

**Comment by CleanerOrc** [comment]
Small–Ku, how did you get the WorldEdit selection to display highlighted as in the photo?  Is this WE option or another plugin?


–        co

**Comment by RoboMWM** [comment]
@CleanerOrc this is forge, and is using a forge client. Likely is using WE-CUI, but not entirely sure.

**Comment by boy0001** [comment]
Fixed, see the latest dev build:
ci.athion.net/job/FastAsyncWorldEdit/

The issue was specific to the forge client (does not affect forge server).

**Comment by Small-Ku** [comment]
Yes It is WorldEditCUI for Forge
