### ISSUE TITLE
Pleeees reconsider your Worldguard and Worldedit policy

### ISSUE THREAD

**Issue by TheoRetisch1** [boy0001/FastAsyncWorldedit#1193]
Hej,

Please reconsider your new product policy. In order to use FAWE it is now necessary to download a separate worldguard, and the worldguard and fawe api are no longer the same.
This is a disaster for the server administration for the following reasons:

1) Many plugins that are based on the normal worldguard and worldedit API do not work anymore.
2) Other plugin authors cannot understand the decision and are partly not to be convinced to implement the FAWE stuff in addition to the classics worldedit and worldguard.
3) This behavior shifts the entire dependency behavior. For worldguard and craftbook updates you are now also dependent on FAWE and here updates definitely take longer than at the official sources. Don't get me wrong I have always appreciated the innovation and work that goes into FAWE. There were very active and less active phases. One bug was annoying but not bad. As soon as you bring in Worldguard and the broad dependency of other plugins, essential server functions depend on FAWE. It is uncool to just lose the better support by such a modification.

I and I think many others appreciate FAWE and its innovative possibilities very much and can't do without them anymore. But I would love to do without features that have led to this dependency insanity. The changes are the reason why I'm not able to update to 1.13. Just to make some examples:
AreaShop doesn't work because the API is not the same as worldedit's and the author doesn't get the help he needs: #1167 
Chestshop doesn't work because it needs the official worldguard version and the author won’t change anything: #1184 
Many smaller Plugins like worldguardextraflags that won’t get the support that is needed don’t work with fawe version either but with the official builds.

I would be happy if you would at least reconsider your attitude. That's not meant badly, but it is a rational analysis of the circumstances. The idea may have been good, but you definitely don't have the infinite time to do it at a satisfactory level.

Best regards

**Comment by Fabrimat** [comment]
I agree, if the situation doesen't change i'll have to switch to WE official builds. I can't say no to AreaShop and Skript.

**Comment by TheoRetisch1** [comment]
Since Worldguard introduced his new vecotor feature and some plugins updated to it, the situation has significantly worsened. Because the worldguard version of fawe is simply not updated. This makes it very clear that this concept cannot work if someone is not able to update worldguard and craftbook at least once a week. If it's just fawe, which sometimes doesn't work correctly for 3-4 weeks, it's not that bad, but if it's half the server because of fucking unsupported dependencies, it's seriously bullshit.

**Comment by mrcoffee1026** [comment]
Yeah, I agree.  The latest versions of Worldguard and WorldEdit should be supported by this plugin, or there's not much point to this plugin anymore.  This leaves a lot of other plugins broken or nonfunctional as they've been updated to support those other two plugins.  If you want to make the demand that we use the versions you are on, you need to be up to at least the most current build at all times.  Saying to not install WorldEdit at all is a rather ridiculous demand if you're not going to update to the latest WorldGuard features like vectors.  You might as well of said "FAWE won't support 1.13", that would have at least have been honest.  Seems like the only way a person CAN use FAWE is if that's the only plugin they intend to use.

**Comment by RoboMWM** [comment]
To be fair, the dev of WorldEdit/WorldGuard seems to not care that he intentionally broke the API **twice** (and these were not deprecated methods/classes) with the excuse of "well version 7 was never released." Who knows how many more times he's going to break the API while not touching the version...

**Comment by freak-dk** [comment]
@Fabrimat 
Any news on this issue?
Haven't a hard time dealing without Areashop aswell :-)

**Comment by Fabrimat** [comment]
> @Fabrimat
> Any news on this issue?
> Haven't a hard time dealing without Areashop aswell :-)

Nope, I switched to WE official builds

**Comment by Narimm** [comment]
Maven Versioning is very very clear  - a snapshot is a version in development it isnt final and it isnt in theory production ready.   Both WorldEdit and Worldgaurd are still SNAPSHOTS and thus will have breaking changes as they develop that is normal.  Once it moves to BETA then you would assume the api would be stable.  To complain about it before that just shows a disregard of maven versioning...which unfortunately seems all too common in MC development.

**Comment by RoboMWM** [comment]
In that case, then CB is never production-ready. So yea, maven versioning is mostly disregarded - as evidenced by the comments here, everyone is clamoring for FAWE to be up-to-date with the parent fork's API changes despite it being a snapshot.

For a project as large as WorldEdit that has many dependencies though, it'd be nice at the very least release a beta build in maven; me4502 is releasing builds as beta through bukkitdev yet refuses to have the same in maven...

**Comment by TheoRetisch1** [comment]
Well, Jesse is back and the 1.13 development is progressing very well. You can now use the default worldguard and craftbook version again. So this problem is solved. A big thank you for the comeback and all the invested hours!
