### ISSUE TITLE
Height brush (snow / -l) IndexOutOfBounds

### ISSUE THREAD

**Issue by GuusLieben** [boy0001/FastAsyncWorldedit#1196]
# Bug report
**Debug paste link**:
Does not output a link. 503 response from Hastebin.
Specifications :
- SpongeForge 1.12.2-2705-7.1.0-BETA-3206
- SpongeAPI 7.1.0-SNAPSHOT-d453c3e
- FAWE 18.10.17-e26cdc6-1226 (though issue occured through versions going back several months)

**Description of the problem:**
Height brushes using the -l flag throw the following error in the console : `[pool-3-thread-602/INFO] [STDERR]: [com.boydti.fawe.object.FawePlayer:lambda$new$2:316]: java.lang.ArrayIndexOutOfBoundsException`
It does not output anything in chat for the player, nor does it affect any terrain

**How to replicate**:
Use /br height {any parameters} -l
Try to affect any snow area
See console

**Comment by CorvetteCole** [comment]
same issue here
