### ISSUE TITLE
Block State Problem

### ISSUE THREAD

**Issue by DocCodeSharp** [boy0001/FastAsyncWorldedit#1197]
FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069
(Spigot 1.13)

When using //stack <> it will not keep the state of the block and use the deafult state when stacking the block. This might be a issue everywhere (paste, rotate, etc...)

There also a issue where you can not set the state of the block in example '//set minecraft:piston_head[facing=up]' will not work, but in vanilla I can use '/setblock ~ ~ ~ minecraft:piston_head[facing=up]' and will work fine so it seems the option to set a state is not there.

- Place stair block down
- Selection pos1 and 2 with wooden axe
- '//stack 6' to stack block
- See block state not saved.

**Comment by N0tMyFaultOG** [comment]
Block rotations are broken and being worked on, join our [discord](https://discord.gg/ebreupz) to receive updates about major fixes.
