### ISSUE TITLE
Server lag, timings report suggests FAWE

### ISSUE THREAD

**Issue by DoogiePC** [boy0001/FastAsyncWorldedit#1202]
# Bug report

**Debug paste link**:
https://hastebin.com/zigapudofa

**Description of the problem:**
The server is lagging with TPS drops and lag spikes, this timings report suggests FAWE is a major cause: https://timings.aikar.co/?id=eeb9430dd2fa40359c2c5d6452279d5b

here is my config: https://hastebin.com/niqoyageme.coffeescript

**How to replicate**:

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of FAWE
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by Xayanix** [comment]
@DoogiePC Did you get rid of this issue?

**Comment by DoogiePC** [comment]
no
