### ISSUE TITLE
Floating Blocks Bug

### ISSUE THREAD

**Issue by Mxchyz** [boy0001/FastAsyncWorldedit#1206]
**Debug paste link**:
*No permission as normal player, owner/developers aren't sure how to fix the issue either*

**Description of the problem:**
//cut, //paste, or any brushes creates this kind of monstrosity 
![2018-11-23_12 52 01](https://user-images.githubusercontent.com/34492344/48957589-1af3a580-ef1f-11e8-90b7-6e8163d2a0e1.png)
![2018-11-23_13 00 54](https://user-images.githubusercontent.com/34492344/48957703-e3392d80-ef1f-11e8-96c2-9a30de1c537e.png)

**How to replicate:**
Anything that includes //cut, //paste, //brush or any command that requires to remove or move a chunk. 
*Seems to be a visual glitch but is still interactive and can be fixed by relogging but is an extreme hassle

**Comment by N0tMyFaultOG** [comment]
Leave the server/fly away

**Comment by Mxchyz** [comment]
Yes, we figured that but is there any absolute solution? Thanks!

**Comment by N0tMyFaultOG** [comment]
Unfortunately not right now

**Comment by Mxchyz** [comment]
Okay thank you for letting me know
