### ISSUE TITLE
FAWE: Left Click Block with axe breaks block

### ISSUE THREAD

**Issue by crazynightsH** [boy0001/FastAsyncWorldedit#1208]
# Bug report

**Debug paste link**: https://hastebin.com/edoziqedeq

**Description of the problem:** When I left click (with a wooden axe) a block, will break the block and say pos1 set to (coords). https://cdn.discordapp.com/attachments/442743461775540234/516323561762324500/fawe.mov

**How to replicate**: I dont know how.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
1.8 support has been dropped, upgrade to a newer mc-version.
