### ISSUE TITLE
WorldEdit actions can't be logged by HawkEye

### ISSUE THREAD

**Issue by StarDan90** [boy0001/FastAsyncWorldedit#121]
I'm using the latest version of FAWE, the latest dev build of Hawkeye, and the latest dev build of WorldEdit. This is what happens when I use WorldEdit:

http://pix.toile-libre.org/upload/original/1463955640.png

FAWE config:
http://pix.toile-libre.org/upload/original/1463955809.png

**Comment by RoboMWM** [comment]
Install the Blockshub plugin.

**Comment by StarDan90** [comment]
I forgot to tell you that I've already installed BlocksHub and BlocksHub-HawkEye. Still not working

**Comment by boy0001** [comment]
I'll check it out now. Note: there's also the inbuilt fawe logging/rollback which will outperform blockshub.
