### ISSUE TITLE
Downloads aren't working on GithHub or PMC for "Anvil to LevelDB Converter"

### ISSUE THREAD

**Issue by Ethroe** [boy0001/FastAsyncWorldedit#1216]
# Bug report
--- Downloads aren't working on GithHub or PMC for "Anvil to LevelDB Converter"
**Debug paste link**:
--- Downloads aren't working on GithHub or PMC for "Anvil to LevelDB Converter"

**Description of the problem:**
--- Downloads aren't working on GithHub or PMC for "Anvil to LevelDB Converter"

**How to replicate**:
--- I don't know how to fix that?

**Comment by N0tMyFaultOG** [comment]
The servers should be fine now again
