### ISSUE TITLE
Error on creative

### ISSUE THREAD

**Issue by MisterPengu** [boy0001/FastAsyncWorldedit#1217]
Nice plugin but on my server it wont work. I start up and in the console the plugin sais this. but I cant find the file or cant make it. and I made the map but still errors. 
In Minecraft it wont work. error is down below

[ERROR] [FastAsyncWorldEdit] Plugin FastAsyncWorldEdit vunknown has failed to register events for class com.boydti.fawe.bukkit.FaweBukkit because com/sk89q/worldedit/world/World does not exist.

**Comment by N0tMyFaultOG** [comment]
Please head over to your `/logs/latest.log` and upload it to pastebin or a similiar service and drop the link below please

**Comment by MisterPengu** [comment]
Here is the link: https://pastebin.com/qTtumLCc

**Comment by N0tMyFaultOG** [comment]
Delete your FastAsyncWorldEdit.jar and VoxelSniper.jar and install it from the links below
[Fawe](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/FastAsyncWorldEdit-bukkit-18.11.21-1c17b10-1231-21.5.18.jar) and [VoxelSniper](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/FastAsyncVoxelSniper-favs-18.11.21-1c17b10-1231-21.5.18.jar)

**Comment by MisterPengu** [comment]
I have my server on server.pro, how can I install it then to it

**Comment by N0tMyFaultOG** [comment]
Open the Control Panel of your server -> files -> plugins -> upload files
Upload the files you just downloaded from above

**Comment by MisterPengu** [comment]
yeah, if I upload them and restart, its not working. here the logs
https://pastebin.com/r3LC3yEc

**Comment by N0tMyFaultOG** [comment]
You forgot to delete your old FastAsyncWorldEdit.jar, you have them both installed

**Comment by MisterPengu** [comment]
iam so stupid. thx for your time
 it works!

I never had that much help in that short time! realy thx. if I can do anything back for you? say

**Comment by N0tMyFaultOG** [comment]
Don't worry, it's fine :p
