### ISSUE TITLE
Problem with //image in NukkitX 1.8

### ISSUE THREAD

**Issue by CiviledCode** [boy0001/FastAsyncWorldedit#1225]
# Bug report

This bug has happened before to others but not at this level.
**Debug paste link**:
https://hastebin.com/zuqinacipu
**Description of the problem:**
When trying to use the Image function in NukkitX, you get this error

17.12 05:17:27 [Server] INFO java.io.FileNotFoundException: Please create a `FastAsyncWorldEdit/textures` folder with `.minecraft/versions` jar or mods in it.If the file exists, please make sure the server has read access to the directory
17.12 05:17:27 [Server] INFO at com.boydti.fawe.util.TextureUtil.loadModTextures(TextureUtil.java:540)
17.12 05:17:27 [Server] INFO at com.boydti.fawe.Fawe.getTextureUtil(Fawe.java:378)
17.12 05:17:27 [Server] INFO at com.boydti.fawe.Fawe.getCachedTextureUtil(Fawe.java:360)
17.12 05:17:27 [Server] INFO at com.sk89q.worldedit.LocalSession.getTextureUtil(LocalSession.java:1448)
17.12 05:17:27 [Server] INFO at com.boydti.fawe.object.brush.ImageBrush.build(ImageBrush.java:72)
17.12 05:17:27 [Server] INFO at com.sk89q.worldedit.command.tool.BrushTool.act(BrushTool.java:488)
17.12 05:17:27 [Server] INFO at com.sk89q.worldedit.command.tool.BrushTool.actPrimary(BrushTool.java:505)
17.12 05:17:27 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformManager$7.run(PlatformManager.java:545)
17.12 05:17:27 [Server] INFO at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:335)
17.12 05:17:27 [Server] INFO at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25)
17.12 05:17:27 [Server] INFO at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15)
17.12 05:17:27 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
17.12 05:17:27 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
17.12 05:17:27 [Server] INFO at java.lang.Thread.run(Thread.java:748)

**How to replicate**:
Do //image command
**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
>17.12 05:17:27 [Server] INFO java.io.FileNotFoundException: Please create a FastAsyncWorldEdit/textures folder with .minecraft/versions jar or mods in it.If the file exists, please make sure the server has read access to the directory

Did you even set it up? If not, then do that :]

**Comment by alok1207** [comment]
Set what up?
