### ISSUE TITLE
Warn message in console (spam)

### ISSUE THREAD

**Issue by Getblock** [boy0001/FastAsyncWorldedit#1227]
# Bug report
https://pastebin.com/QGQKrThX

**Debug paste link**:
https://hastebin.com/ibupoyigag

**Description of the problem:**
it's spamming the console with error when i updated my paperspigot to the latest version.

paperclip-486

**Checklist**:

- [yes] I included a `/fawe debugpaste` link
- [yes] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [yes] I made sure I am using an up-to-date version of FAWE
- [yes] I Made sure the bug/error is not caused by any other plugin

**Comment by PenguinOwl** [comment]
+1 getting same error

**Comment by N0tMyFaultOG** [comment]
https://github.com/boy0001/FastAsyncWorldedit/issues/1213

**Comment by N0tMyFaultOG** [comment]
Duplicate of https://github.com/boy0001/FastAsyncWorldedit/issues/1213
