### ISSUE TITLE
Pull WE Changes made to Vector System

### ISSUE THREAD

**Issue by veteranmina** [boy0001/FastAsyncWorldedit#1234]
# Bug report

FAWE has not updated to use the new vector system implemented in WE. In result logblock does not support FAWE as it is attempting to call for BlockVector3 which does not exist in FAWE. It is likely that other plugins can loose functionality with FAWE for this reason.

Link to commit in WE for Vector system refresh: https://github.com/sk89q/WorldEdit/commit/399e0ad5fa7637d5d3ccce7ead1ad409e85c7dd2

**Debug paste link**:
https://pastebin.com/9qC2MC4a

**Description of the problem:**
Attempt to use logblocks selection argument results in error as FAWE does not use the new vector system that WE uses noted in above commit change.

**How to replicate**:
Load build 384 build from logblock and FAWE build 18.10.26-94d5028-2069
https://ci.md-5.net/job/LogBlock/384/
Attempt to select region with //wand and then run command /lb lookup selection since 1d
error will occur due to nosuchmethed

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by veteranmina** [comment]
I have found that likely CraftBook's gate function is not working with FAWE as well due to CraftBooks commit on Nov 4th to use the new Vector System implemented in the main WE plugin.
https://github.com/EngineHub/CraftBook/commit/682c8355fcbfaa1dbc36b222379ad2ac7fa070fd#diff-71bff6ddddc2d47fb7c7d97eaf1a30c9

**Comment by N0tMyFaultOG** [comment]
IronApollo is currently updating fawe to the new Vector3 system, you can view his work here https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/tree/new-vector-system
Join our discord to keep updated about the changes made to FAWE, we announce proper releases there https://discord.gg/ngZCzbU
