### ISSUE TITLE
FAWE COPY+ROTATE Issue

### ISSUE THREAD

**Issue by arturek1666** [boy0001/FastAsyncWorldedit#1235]
# Bug report

https://hastebin.com/iqosokazek
**Description of the problem:**

The problem is when you have to copy a building with stairs and rotate as when you do the stairs don't rotate the write way and looks really bad. By title I did not find any issues with stairs so that's why i am reporting it. 
FAWE version: 2080
Minecraft Engine: paperspigot(486)

**How to replicate**:
To replicate this issue you copy a building with stairs than before doing //paste you do //rotate 90 and you now do //paste

**Comment by Draycia** [comment]
https://github.com/boy0001/FastAsyncWorldedit/issues/1079
https://github.com/boy0001/FastAsyncWorldedit/issues/1104
https://github.com/boy0001/FastAsyncWorldedit/issues/1203

**Comment by arturek1666** [comment]
Closing for dublication reasons.
