### ISSUE TITLE
MC Jukebox Error PlayerMoveEvent

### ISSUE THREAD

**Issue by TheCalypso** [boy0001/FastAsyncWorldedit#1236]
Hello, 
My server is on 1.13.2 I use version FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085
I open this issue because there is a problem with the plugin MC Jukebox, here are the tests I made. Mc Kujebox lets you put music according to where you are on the server, so it works with WordGuard. I tested the plugin with WorldEdit latest build and WorldGFuard latest build on this site: http://builds.enginehub.org/job/worldedit?branch=master. I then tried with FastAsyncWorldEdit last build and WorldGuard (downloadable on your site and it does not work) There may be some changes to make in your version of WorldGuard. Here is the error that this displays: https://pastebin.com/9RhAD9cq 

Tell me what you think, thank you very much and congratulations for your plugin is great and can avoid server lags!

**Comment by TheCalypso** [comment]
Please ?

**Comment by Draycia** [comment]
The error is due to FAWE not being updated to comply with the WE7 update. This is currently being worked on.

**Comment by N0tMyFaultOG** [comment]
Join our [discord](https://discord.gg/ngZCzbU) to see when we release a proper update. It's currently being worked on.
