### ISSUE TITLE
[Bugs] Console Errors Spigot 1.13.2

### ISSUE THREAD

**Issue by pinkpig3777** [boy0001/FastAsyncWorldedit#1241]
# Bug report
**Debug paste link**: https://pastebin.com/00B5kfb1

**Description of the problem:**
When server starts I get errors regarding WorldGuard, specifically the WorldGuard provided on the FAWE website that is supposed to work with FAWE. Then when I login to the server, it spams my chat with an [error](https://gyazo.com/1c8b477f6d33947a1936b731b43c1753). Then when I did //schem list global it spammed errors in console.

**latest.log:** https://pastebin.com/1HJ3RVWU
**Plugins:** https://pastebin.com/DDULP6h4
**/version:** CraftBukkit version git-Spigot-82e117e-2b2d084 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**How to replicate**:
1. Use Spigot Version:
  * CraftBukkit version git-Spigot-82e117e-2b2d084 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
2. Plugin Versions Used:
  * FAWE: FastAsyncWorldEdit-bukkit-19.01.01-21a7eb8-2088.jar
  * WorldGuard: worldguard-legacy-7.0.0-beta-02.jar
  * Both of these jar files were downloaded on the official website, [here](https://empcraft.com/fawe/download/).
3. Login to server. After a second it will spam [these](https://gyazo.com/1c8b477f6d33947a1936b731b43c1753) errors in your chat.
4. Do //schem list global. Check console. It will show [these](https://pastebin.com/iBurAtzT) errors.
5. Also, when you do /fawe debugpaste it will spam [errors](https://pastebin.com/00B5kfb1) in console.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I made sure the bug/error is not caused by any other plugin
  * There are multiple errors from FAWE and 1 error from WorldGuard (which is using the version provided on the FAWE website that is supposed to work).

**Comment by pinkpig3777** [comment]
I've moved to AsyncWorldEdit so if you respond chances are I won't see it, sorry. Just letting you know in advance.

**Comment by N0tMyFaultOG** [comment]
Fixed in https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/d4971a4e2f2f75cca89952e0e04fb0f61ae53bd0, update Fawe
