### ISSUE TITLE
Question about WorldEdit 7 API

### ISSUE THREAD

**Issue by Leomixer17** [boy0001/FastAsyncWorldedit#1242]
Hi, I want to make a plugin that uses WorldEdit API.
Where will be available the documentation about the FAWE version of WorldEdit 7 API?

**Comment by Tiippex** [comment]
similar to #1239

**Comment by N0tMyFaultOG** [comment]
https://github.com/IntellectualSites/fastasyncworldedit-1.13, the repo is not equal with upstream yet.
