### ISSUE TITLE
Error on startup running with WorldGuard 7.0 latest release.

### ISSUE THREAD

**Issue by FlailoftheLord** [boy0001/FastAsyncWorldedit#1246]
Running Spigot v1.13.2, gives me a huge error and cancels WorldGuard on startup, i sent it to the worldguard devs and they said it was a bug with FAWE, i used regulr world edit and it started up just fine, switched back to FAWE and it gave me those errors.

Please read the full issue here:
[http://forum.enginehub.org/threads/broken-nosuchfielderror-worldguard-beta-2-build-on-startup.26608/#post-45718](http://forum.enginehub.org/threads/broken-nosuchfielderror-worldguard-beta-2-build-on-startup.26608/#post-45718)

**Comment by N0tMyFaultOG** [comment]
Fawe 1.13 depends on its own WorldGuard until it's fully updated, you can find it here incase you aren't using it yet https://ci.athion.net/job/FAWE-WorldGuard-1.13/
Ensure you removed your WorldEdit.jar before installing fawe
