### ISSUE TITLE
Error FAWE with PlotSquared

### ISSUE THREAD

**Issue by TheCalypso** [boy0001/FastAsyncWorldedit#1247]
Hello, I just tested FAWE with the plugin PlotSquared and I just found an error, here it is with the following link: https://pastebin.com/m0wY8DsV.
 My version of FAWE is FastAsyncWorldEdit-bukkit-1.13.132 and my version of PlotSquared is PlotSquared-Bukkit-4.89. For information I just tested with WorldEdit from this site http://builds.enginehub.org/job/worldedet everything works perfectly, so I think it comes from FAWE. I apologize if you already know this mistake I just want to try to help you!

Congratulation for you great job !

TheCalypso

**Comment by N0tMyFaultOG** [comment]
P2 depends on WorldEdit and cannot be used with Fawe _yet_. We will announce it on out discord once it supports both
