### ISSUE TITLE
Gravity and Water Physics do not work

### ISSUE THREAD

**Issue by Sonic8608** [boy0001/FastAsyncWorldedit#1249]
# Bug report

**Debug paste link**: 
https://hastebin.com/mirapevapi

# Welcome to this paste
# It is meant to provide us at IntellectualSites with better information about your problem

# We will start with some informational files
links.config_yml: https://hastebin.com/oqixeyowuf
links.messages_yml: https://hastebin.com/puxebidori
links.commands_yml: https://hastebin.com/bizelipuji
links.latest_log: https://hastebin.com/ebicakuqis

# Server Information
server.platform: bukkit
server.plugins: 
 - xbottler: 1.1
 - KeepItems: 1.3.2
 - AntiCreeper: 4.19
 - MinePacks: 1.18.1
 - GroupManager: GMBuildVer (Phoenix)
 - Lift: 56
 - ChatControl: 5.7.1
 - FarmProtect: 1.8.4
 - TNT: 4.0
 - ProtocolLib: 4.4.0
 - TreeGravity: 3.9.1
 - AutoSave: 1.1
 - mcMMO: 1.6.0-SNAPSHOT
 - Hugs: 2.0.2
 - ServerListPlus: 3.4.8
 - Vault: 1.7.1-b91
 - ProtocolSupport: 4.29-dev
 - SalvageSmelter: 0.1.8
 - SignRanksPlus: 0.7.1
 - Essentials: 2.15.0.45
 - LWC: 2.1.1-46e9fa0
 - EssentialsChat: 2.15.0.45
 - EssentialsSpawn: 2.15.0.45
 - FastAsyncWorldEdit: 1.0
 - WorldEdit: unspecified
 - LogBlock: 1.13.1-SNAPSHOT (build #36)
 - WorldGuard: 7.0.0-SNAPSHOT;0dc5781
 - ChestShop: 3.8.13-SNAPSHOT (build #37)
 - Jobs: 4.7.4
 - SilkSpawners: 6.0.0-SNAPSHOT-b491
server.version: git-Spigot-f56e2e7-98b862a (MC: 1.13.2) / 1.13.2-R0.1-SNAPSHOT

# YAY! Now, let's see what we can find in your JVM
memory.free: 5657570832
memory.max: 6591873024
java.specification.version: '1.8'
java.vendor: 'Oracle Corporation'
java.version: '1.8.0_181'
os.arch: 'amd64'
os.name: 'Windows 7'
os.version: '6.1'

# Okay :D Great. You are now ready to create your bug report!
# You can do so at https://github.com/boy0001/FastAsyncWorldedit/issues
**Description of the problem:**

<img src="https://i.ibb.co/LdzSrjK/2019-01-11-16-43-06.png" alt="2019-01-11-16-43-06" border="0">
<b>Dropped Gravel or Sand results in the block breaking instead of becoming a full block<b>
<img src="https://i.ibb.co/gyQz1Dx/2019-01-11-16-43-40.png" alt="2019-01-11-16-43-40" border="0">
<b>Selecting a region and cutting near a pool of water does not follow the rule of Physics. Rather the region itself is dry until you make a block update.<b>

**How to replicate**:

1st problem - build a piller 4 or 5 blocks off the ground or at any height and drop a peice of Gravel or Sand from that height.

2nd Problem - use the wooden axe and select a region near a body of water and cut the select to let the flow of water fill the crevice 
**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
The issue is known and being worked on.
