### ISSUE TITLE
replace command not working with block states

### ISSUE THREAD

**Issue by navett52** [boy0001/FastAsyncWorldedit#1250]
# Bug report for FastAsyncWorldEdit

**Debug paste link**:
https://hastebin.com/yebojoyubo

**Description of the problem:**
//replace not working with block states

i.e.
//replace stone_brick_slab[type=double] polished_andesite results in 0 blocks being changed. I guess I might be trying to do this wrong, but this is the block state syntax used in other commands like //fill so I'm at a loss.

Block State syntax that works: //fill stone_brick_slab[type=top]

**How to replicate**:
Place a stone brick slab on top of another one to make a double stone brick slab. Attempt to change the double stone brick slab into something else by using the replace command typed above.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE <1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
The issue is known and will be resolved soon.
