### ISSUE TITLE
I can't find the answer to using schematics in fawe for 1.12.2

### ISSUE THREAD

**Issue by TheMynxieOne** [boy0001/FastAsyncWorldedit#1253]
I have looked everywhere for an answer to this. I have tried to load schematics using /load schem filename
nothing happens. I have no idea how to load the schematics using FAWE. It didn't work in WorldEdit either. I kept getting parameter issues on usage //load. Can you please help me? I found this, but I don't understand what it means..
https://github.com/boy0001/FastAsyncWorldedit/wiki/Commands#schematic-commands-edittop

What does it mean by format,before the filename?

**Comment by IronApollo** [comment]
You're using the wrong command. To load a schematic, you use
//schematic load <format> <filename>

You should be able to safely omit the format parameter and allow FAWE to attempt to find the format on its own. 

For instance, if you are trying to load your schematic named "tree" , you would type
//schematic load tree
