### ISSUE TITLE
Schematics are strange... pls help me

### ISSUE THREAD

**Issue by Skyfighter1** [boy0001/FastAsyncWorldedit#1255]
# Bug report for FastAsyncWorldEdit 1.13.2

**Debug paste link**:
< # https://hastebin.com/jenewosabe
# It is meant to provide us at IntellectualSites with better information about your problem

# We will start with some informational files
links.config_yml: https://hastebin.com/pejiqexuna
links.messages_yml: https://hastebin.com/obedociqed
links.commands_yml: https://hastebin.com/uvucoxagok
links.latest_log: https://hastebin.com/ibitacamin

# Server Information
server.platform: bukkit
server.plugins: 
 - LagAssist: 2.10.1
 - DangerousNether: 1.0
 - DangerousCaves: 1.0
 - PlaceholderAPI: 2.9.2
 - ReasonGM: 1.1
 - Boss: 1.8.17
 - EpicWorldGenerator: 8.0.2
 - EffectLib: 6.1
 - IllegalStack: 1.4.0
 - WorldBorder: 1.8.7
 - Vault: 1.6.10
 - EasyBackup: 2.8.1
 - UltraPermissions: 4.0.2
 - ProtocolSupport: 4.29-dev
 - Multiverse-Core: 2.5.0-b727
 - ProtocolLib: 4.4.0-SNAPSHOT-b415
 - LibsDisguises: 9.7.1
 - TitleManager: 2.0.9
 - DiscordSRV: 1.16.4
 - Hydra: 1.5.5 S
 - CMIEInjector: 1.0.2.1
 - CMI: 8.3.7.3
 - Feudal: 1.13.4
 - FastAsyncWorldEdit: 1.0
 - WorldEdit: unspecified
server.version: git-Spigot-573cdf2-dff66df (MC: 1.13.2) / 1.13.2-R0.1-SNAPSHOT

# YAY! Now, let's see what we can find in your JVM
memory.free: 1911401144
memory.max: 7635730432
java.specification.version: '1.8'
java.vendor: 'Oracle Corporation'
java.version: '1.8.0_191'
os.arch: 'amd64'
os.name: 'Windows Server 2016'
os.version: '10.0'

# Okay :D Great. You are now ready to create your bug report!
# You can do so at https://github.com/boy0001/FastAsyncWorldedit/issues 

**Description of the problem:**
I have createt schematics in 1.12.2 tehn I have upgrade the world to 1.13.2 and then I have pastet the schematics but they are buggy......

**How to replicate**:
Copy a thing and then make a schematic and paste this schematic (the oroblem is only by a structure from 1.12.2 wich is now in my 1.13.2 world

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE <1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Use the 1.13 repo for 1.13 issues
