### ISSUE TITLE
Help with permissions

### ISSUE THREAD

**Issue by RedDiamondREC** [boy0001/FastAsyncWorldedit#1257]
How can i set a user to be able to add people to the "region restrictions"? and if so can i make it so only select users can access X world?

**Comment by N0tMyFaultOG** [comment]
You might are looking for something like [this](https://github.com/boy0001/FastAsyncWorldedit/wiki/Permissions#region-permissions).
If you want to do do it per-world, you need a per-world permission plugin then.
