### ISSUE TITLE
It only loads 1/3 of the map and generates the rest. please fix this 

### ISSUE THREAD

**Issue by hugoneale2004** [boy0001/FastAsyncWorldedit#1258]
# Bug report for FastAsyncWorldEdit <1.12.2

**Debug paste link**:

**Description of the problem:**

**How to replicate**:

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FAWE <1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Please fill out the format given.
