### ISSUE TITLE
//download Causes error

### ISSUE THREAD

**Issue by XXdaugonXX** [boy0001/FastAsyncWorldedit#1259]
# Bug report for FastAsyncWorldEdit <1.12.2

**Debug paste link**: https://hastebin.com/nisucenivo

**Description of the problem:**

When trying to use //download it just creates an error in chat
**How to replicate**: use the command //download or /download after using //copy to copy some blocks

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE <1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
//download is currently unsupported on 1.13

**Comment by HighBridRed** [comment]
> //download is currently unsupported on 1.13

He wasn't talking about 1.13, he was having an issue with version 1.12.2.
