### ISSUE TITLE
VoxelSniper snipes across road into owned plot

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#126]
If using VoxelSniper at the edge of your plot it will continue the snipe onto an adjacent plot if you are able to voxelsnipe on it.

![image](https://cloud.githubusercontent.com/assets/10080017/15589210/c5bd0182-2389-11e6-8a32-33407f702a48.png)

**Comment by dordsor21** [comment]
Update: Also occasionally occurs on plots which are not owned by the player

**Comment by boy0001** [comment]
> If using VoxelSniper at the edge of your plot it will continue the snipe onto an adjacent plot if you are able to voxelsnipe on it.

Is normal behavior.

**Comment by dordsor21** [comment]
is it possible to stop this?

**Comment by dordsor21** [comment]
The occasional VS'ing into other plots is also still an issue^

**Comment by boy0001** [comment]
Still an issue?

**Comment by dordsor21** [comment]
fixed
