### ISSUE TITLE
FastAsyncVoxelSniper-favs-1.13.134.jar causing crashes when i try to paint grass onto stone

### ISSUE THREAD

**Issue by PigguJones** [boy0001/FastAsyncWorldedit#1260]
# Bug report for FastAsyncVoxelSniper 1.13.134

**Debug paste link**:
https://hastebin.com/upogiwohit

**Crash Report**
https://pastebin.com/ubYbfuNX

**Description of the problem:**
I'm honestly not sure what i'm doing wrong. its a bare bones server with only Essentials, Pex, ShopGUIPlus, CommandSigns, Vault, and FAWE/FAVE. all im doing is creating a mountain like i have done plenty of times. i'm at the stage where im using (/b c mm)(/v 1)(/vr 2)(/b 4) and slowly painting grass onto the mountain not even quickly or with a large brush and on peaceful mode during the day with randomtickspeed at 20. At random points the server will just stop.

**How to replicate**:
Peaceful mode
Day time
cylinder brush size 5 painting grass onto stone
blockheight 50-130
paint onto stone at varying heights
disable all other plugins
connect to server ****************

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)]
- [x] I made sure I am using an up-to-date version of [FAWE <1.12.2]
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by PigguJones** [comment]
the crashes usually happen between 15 and 20 uses of a mat-mat ball size 10 replacing stone with grass

**Comment by N0tMyFaultOG** [comment]
> i posted that. reloaded the server. and used it twice and then it crashed

Do not reload your server, we ain't helping you issues regarding a reloaded server.

**Comment by PigguJones** [comment]
> > i posted that. reloaded the server. and used it twice and then it crashed
> 
> Do not reload your server, we ain't helping you issues regarding a reloaded server.

I don't understand what you mean by this. my problem is that the server crashes when i used the ball. i reload the server to test different ways. i really need to get these mountains built. once they're done i dont need vs anymore
