### ISSUE TITLE
problem with worldguard

### ISSUE THREAD

**Issue by mcannie97** [boy0001/FastAsyncWorldedit#1263]
# Bug report for FastAsyncWorldEdit <1.12.2
**Debug paste link**:
https://pastebin.com/HVNgrDe0 

**Description of the problem:**
getting this issue when I'm running latest worldguard + latest fawe on latest 1.13.2 spigot, the worldguard dev told me it was a fawe issue and that I should report it here ;)

**How to replicate**:
latest worldguard + latest fawe + latest 1.13.2 spigot

**Comment by N0tMyFaultOG** [comment]
Do you use Fawe's worldguard ?

**Comment by mcannie97** [comment]
there's a seperate worldguard for fawe? O.O

**Comment by N0tMyFaultOG** [comment]
Yes, due Fawe being updated right now, use Fawe's WorldGuard in the meantime, get it from [here](https://ci.athion.net/job/FAWE-WorldGuard-1.13/lastSuccessfulBuild/artifact/worldguard-legacy/build/libs/worldguard-legacy-7.0.0-SNAPSHOT-dist.jar).
It might won't work with other plugins, but it's just a temporary solution.

**Comment by mcannie97** [comment]
aight, thanks :)
