### ISSUE TITLE
FAWE Ships with Out-Dated WorldEdit

### ISSUE THREAD

**Issue by kangarko** [boy0001/FastAsyncWorldedit#1265]
Hi there!

My plugin CoreArena checks for the latest version of WorldEdit. This causes it to break with the most recent version FAWE for Minecraft 1.13.2 (tested with FAWE 1.13 build 134)

![a](https://i.imgur.com/NzdlJHh.png)

Is there anything that can be done?

Thank you.

**Comment by SirYwell** [comment]
FAWE for 1.13 based on WE for 1.13 is currently under development since the changes in WE aren't compatible with FAWE right now.

**Comment by InfinityAspire** [comment]
> FAWE for 1.13 based on WE for 1.13 is currently under development since the changes in WE aren't compatible with FAWE right now.

This may be but many/most 1.13 plugins that use W/E require W/E 7 now, breaking its compatibility with FAWE entirely.

**Comment by IronApollo** [comment]
The new-vector-system branch of the IntellectualSites' FAWE repo has been updated to be compatible with the latest WorldEdit commits (as of last night), but will require essential bug fixes and testing before it is released for general use.

We are aware that FAWE has essentially been left behind by the updates WorldEdit has been through, but rest assured it's being worked on. Development has been delayed by many factors.

Closed.

**Comment by kangarko** [comment]
Thanks!
