### ISSUE TITLE
lightning cmds not working

### ISSUE THREAD

**Issue by martijnpu** [boy0001/FastAsyncWorldedit#1271]
# Bug report for FastAsyncWorldEdit 1.13.2
`//removelightning` and `//fixlightling` doesn't do anything other than printing a message.

**Debug paste link**:
[https://hastebin.com/wadaducifa](https://hastebin.com/wadaducifa)

**Description of the problem:**
Nothing specials

**How to replicate**:
Select a region and execute the commands.

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE <1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by martijnpu** [comment]
Do nobody know?

**Comment by N0tMyFaultOG** [comment]
Use an external plugin such as LightCleaner, I cannot remember fix light ever working so it might wont be fixed that soon.
