### ISSUE TITLE
About PlotSquared 

### ISSUE THREAD

**Issue by FormulaXS** [boy0001/FastAsyncWorldedit#1273]
# Bug report for FastAsyncWorldEdit <1.13.2

**Debug paste link**:

https://hastebin.com/voyutedabe

**Description of the problem:**

When I use original worldedit, it works well.. but in FAWE.. it doesnt work with crashes..
![gg](https://user-images.githubusercontent.com/42911654/53063659-33686180-3508-11e9-9522-3838d4a687b6.PNG)
![656](https://user-images.githubusercontent.com/42911654/53063660-33686180-3508-11e9-86dd-b93f779e6efd.PNG)

**How to replicate**:

Update..?(IDK)

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FAWE <1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Fawe is not compatible with plotsquared yet, use regular worldedit.
