### ISSUE TITLE
Sponge 1.12 FAWE issue: no long tool and one click registers as two

### ISSUE THREAD

**Issue by Jaded-Avaritia** [boy0001/FastAsyncWorldedit#1277]
**Debug paste link**:
https://incendo.org/paste/view/3a345e686fd84e02b5afd1d802940fc5
and
https://incendo.org/paste/view/fcd9a2cd31914066a058a028e2bcdbe7

**Description of the problem:**
I'm still having an issue with my worldedit.

> Can't do World Edit at a distance. Have to be sitting right on top of the block
> Farwand only works as if it's pos1 and pos2
> Right clicking with a brush once makes the command go twice.
> Left clicking with a brush makes the command go once.

I hope it's readable without stack traces. I see my vote plugin pushing out errors- but I can't update that yet and I already reported that issue.

**Comment by Jaded-Avaritia** [comment]
Okay so, on the main server that above is happening but on my test server it's not doing two clicks- but you can far click with left clicking.

But on my test server you can't right click far away with farwand.

But they have the same server files???

**Comment by KhaozFrost** [comment]
Trying to use the Forge version on spongeforge servers also has broken side effects such as //undo breaking on large edits among several other functions soo this is a pretty big issue. Sponge works apart from being able to manipulate the terrain without actually having to click the block specifically.

I'm using the latest version of sponge with this also.

**Comment by N0tMyFaultOG** [comment]
The sponge module is currently not being worked on so issues are on hold.
