### ISSUE TITLE
 [Sponge] Not Able to use brush from distance

### ISSUE THREAD

**Issue by KhaozFrost** [boy0001/FastAsyncWorldedit#1278]
# Bug report for FastAsyncWorldEdit <1.12.2

**Debug paste link**:

**Description of the problem:**

I'm unable to use basic brushes like "brush sphere air 5" from a distance; i have to actually click on the block that i want to effect which is tedious.. this only happens with the sponge version of the plugin and is not effected in the other versions. 
**How to replicate**:

Use latest sponge with the plugin
**Checklist**:

- [] I included a `/fawe debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE <1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by Jaded-Avaritia** [comment]
I'm getting this same issue and I reported mine here
https://github.com/boy0001/FastAsyncWorldedit/issues/1277
So if anyone can help us both it'd be much appreciated.

**Comment by N0tMyFaultOG** [comment]
The sponge module is currently not being worked on so issues are on hold.

**Comment by Shmeeb** [comment]
Could this one issue possibly be fixed? It breaks a huge part of the mod's functionality that is otherwise pretty much perfect

**Comment by Shiunin** [comment]
@Shmeeb @Jaded-Avaritia 

Try setting the /br range and /br target - this resolved the issue for me

**Comment by Shmeeb** [comment]
Didn't seem to help for me. What FAWE/SF versions are you running?

**Comment by Sirzuki** [comment]
This is still broken and needs to be fixed. A major part of the mod is broken.

**Comment by Sirzuki** [comment]
Actually found a sort of fix. Left clicking works from a distance. Not sure why this is occurring.
