### ISSUE TITLE
CFI Command Not Found

### ISSUE THREAD

**Issue by Vexmate** [boy0001/FastAsyncWorldedit#1279]
# Bug report for FastAsyncWorldEdit < 1.12.2

**Debug paste link**:
https://hastebin.com/alugobulas

**Description of the problem:**
When I try to use command //cfi it says unknown command.

**How to replicate**:
//cfi

**Checklist**:

- [] I made sure that I'm using FAWE on 1.12.2 or lower - We are using 1.13 but read someone else had it running on 1.13 just fine.
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE < 1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Report 1.13 issues on the [1.13 repo](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/new )
