### ISSUE TITLE
Issue using //image

### ISSUE THREAD

**Issue by alok1207** [boy0001/FastAsyncWorldedit#1281]
Whenever i do //image (imgur), this comes up:

https://gyazo.com/0b9dba814765e4e1d1f8e3253f2d1fff

(I'm on a 1.7-1.12 spigot version of FAWE because my server is 1.8.8)
I also think i'm supposed to include this:
https://incendo.org/paste/view/ab72dd742cfc45b8ad7a5f821e7dd5d3

**Comment by N0tMyFaultOG** [comment]
Do whatir says and it will work

**Comment by alok1207** [comment]
> Do what it says and it will work

I don't know what to do, sorry, i'm new to this, but do i make a folder called FastAsyncWorldEdit/textures? and where do i put it?

**Comment by N0tMyFaultOG** [comment]
You create a folder called `textures` inside your Fawe folder and drag a minecraft version in you can find on your computer inside `.minecraft\versions\`

**Comment by alok1207** [comment]
I did it, now it just says:
There was an error handling a FAWE command: [See console]
java.lang.NullPointerException: null

**Comment by N0tMyFaultOG** [comment]
Pastebin it

**Comment by alok1207** [comment]
https://pastebin.com/wPcbzatF

**Comment by N0tMyFaultOG** [comment]
Which version did you drag in?

**Comment by alok1207** [comment]
FastAsyncVoxelSniper-favs-19.03.21-a1ffd3d-1256-22.0.13

**Comment by alok1207** [comment]
FastAsyncWorldEdit-bukkit-19.03.21-a1ffd3d-1256-22.0.13

**Comment by N0tMyFaultOG** [comment]
Well, you cannot drag the plugin in itself.
Drag the minecraft version in

**Comment by alok1207** [comment]
Oh i dragged in 1.8
