### ISSUE TITLE
Cannot copy and paste animals

### ISSUE THREAD

**Issue by mctool** [boy0001/FastAsyncWorldedit#1287]
# Bug report for FastAsyncWorldEdit  1.13.135

First of all, my English is not good. the English content comes from Google Translation.

### Description of the problem:
With paper 1.13.2 (614), there will be an error using the latest version. The current version is the FastAsyncWorldEdit-bukkit-1.13.135, error, which is that animals can't be copied and pasted, and this error has been going on for a long time, and many versions can't copy and paste animals. The last version that can copy and paste animals is FastAsyncWorldEdit-bukkit-18.12.19-f37bd40-2077.

![image](https://user-images.githubusercontent.com/39617185/55861291-a0af7f00-5ba8-11e9-8df5-9350738e17e4.png)

**Comment by N0tMyFaultOG** [comment]
Update fawe, get the latest dev build here ([breaking](https://incendo.org/download)), I tested and copy/pasting animals seems working.
Also, report 1.13 issues on the 1.13 repo like the issue template told you to do so 
`<!--- REPORT ISSUES REGARDING FAWE ON 1.13.x HERE: `

**Comment by mctool** [comment]
> Update fawe, get the latest dev build here ([breaking](https://incendo.org/download)), I tested and copy/pasting animals seems working.
> Also, report 1.13 issues on the 1.13 repo like the issue template told you to do so
> `<!--- REPORT ISSUES REGARDING FAWE ON 1.13.x HERE: `


This page is inaccessible

**Comment by N0tMyFaultOG** [comment]
The page works fine for me, looks like the issue is on your end

**Comment by mctool** [comment]
> The page works fine for me, looks like the issue is on your end

I can access googel.com, but I can't access incendo.org.

**Comment by mctool** [comment]
> The page works fine for me, looks like the issue is on your end

Can you provide fawe in Dropbox?

**Comment by N0tMyFaultOG** [comment]
No? Get it from our CI if you cannot solve the problem to reach incendo

**Comment by mctool** [comment]
Update FastAsyncWorldEdit-bukkit-1.13.26 ,copy/pasting animals seems working.

But the command completion doesn't seem normal.
![image](https://user-images.githubusercontent.com/39617185/55888075-55659280-5be1-11e9-9b7a-a5fbfb75992c.png)


> No? Get it from our CI if you cannot solve the problem to reach incendo

**Comment by N0tMyFaultOG** [comment]
Tab completion has been suppressed some months ago, it's intended to not work rn

**Comment by mctool** [comment]
> Tab completion has been suppressed some months ago, it's intended to not work rn

 Thanks

**Comment by mctool** [comment]
> Tab completion has been suppressed some months ago, it's intended to not work rn

FastAsyncWorldEdit-bukkit-1.13.28.jar

`[23:44:35 INFO]: Angel issued server command: /gm 1
[23:44:51 INFO]: Angel issued server command: //wand
[23:45:01 INFO]: Angel issued server command: //copy
[23:45:01 WARN]: com.sk89q.worldedit.regions.CuboidRegion$2$1: End of iterator
[23:45:10 INFO]: Angel issued server command: //paste
[23:45:10 INFO]: (FAWE) Having `parallel-threads` > 1 interferes with the timings.
[23:45:17 INFO]: Angel issued server command: //undo`
