### ISSUE TITLE
website upload schem dont work

### ISSUE THREAD

**Issue by elmaslarry** [boy0001/FastAsyncWorldedit#1289]
# Bug report for FastAsyncWorldEdit < 1.12.2

**Debug paste link**:

**Description of the problem:**

**How to replicate**:

**Checklist**:

- [] I made sure that I'm using FAWE on 1.12.2 or lower
- [] I included a `/fawe debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FAWE < 1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by elmaslarry** [comment]
it is not working upload option for Fawe

**Comment by N0tMyFaultOG** [comment]
Can you use and fill out the format given please?

**Comment by Pangamma** [comment]
@N0tMyFaultOG  The code that is available only handles .schematic format. The new .schem format is still unsupported. We need an update for schematics that can be used with 1.13.2 and onward.

**Comment by Pangamma** [comment]
I spent some time making the PHP code support .schem, but then FAWE still errors out because it has no option to import as schem. Only as .schematic.

**Comment by N0tMyFaultOG** [comment]
Uploading schems work fine, either from ingame or the website. I just tested it

**Comment by Pangamma** [comment]
Maybe there is an FAWE update.

**Comment by N0tMyFaultOG** [comment]
Tested, worked, assume fixed
