### ISSUE TITLE
/biomelist not work on nukki

### ISSUE THREAD

**Issue by NycuRO** [boy0001/FastAsyncWorldedit#1290]
# Bug report for FastAsyncWorldEdit < 1.12.2

**Debug paste link**:

**Description of the problem:**

Just use //biomelist and you get nothing.
If you use //biomeset PLAINS or //biomeset 1, nothing
**How to replicate**:

**Checklist**:

- [] I made sure that I'm using FAWE on 1.12.2 or lower
- [] I included a `/fawe debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FAWE < 1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by NycuRO** [comment]
Why closed? @N0tMyFaultOG

**Comment by N0tMyFaultOG** [comment]
You have to follow the template and fill it out properly to receive support.

**Comment by NycuRO** [comment]
Ok, you don't care about bugs and this plugin and is more important a issue template when title is obvious.

**Comment by N0tMyFaultOG** [comment]
If you don't care to answer some simple questions to give us important information about the problem, I  don't care to look into issues as well, have a good day.
