### ISSUE TITLE
Transparent hollow

### ISSUE THREAD

**Issue by PixelNotFound** [boy0001/FastAsyncWorldedit#1298]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report for FastAsyncWorldEdit < 1.12.2

**Debug paste link**:

**Description of the problem:**
//hollow doesnt ignore transparent blocks. Example
https://gyazo.com/8cea4bda0965f90bf2a8adc8acd294a4
https://gyazo.com/049a3598cead701ea11c7e73d6fc7f3a
**How to replicate**:

Hollow something with transparent blocks
**Checklist**:

- [] I made sure that I'm using FAWE on 1.12.2 or lower
- [] I included a `/fawe debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FAWE < 1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by PixelNotFound** [comment]
@N0tMyFaultOG How is this invalid, i just cant add a debug link because the command doesnt work

**Comment by N0tMyFaultOG** [comment]
You didn't fill out the checklist, therefore we don't know if you even went thru the points, furthermore if the debugpaste isn't working it's a problem caused by outdated fawe which would be resolved if you took the time and worked thru the checklist and actually did what it's saying, it's there for a reason.

**Comment by PixelNotFound** [comment]
Thanks!
