### ISSUE TITLE
Crash on Java 12

### ISSUE THREAD

**Issue by EsGibtKeineMitte** [boy0001/FastAsyncWorldedit#1308]
Well while using Java 12 the FAWE injection does not work.

I've commented out the bukkit.getServer().shutdown() to get the full stacktrace:

https://pastebin.com/A98jjEyZ

MfG
Leonhard|EsGibtKeineMitte

**Comment by EsGibtKeineMitte** [comment]
Support on flieeeeg

**Comment by ham1255** [comment]
then use java 8

**Comment by EsGibtKeineMitte** [comment]
Outdated until 2020?
I ve just told them their systems are not supporting a new java version.

**Comment by N0tMyFaultOG** [comment]
As long as Mojang sticks with java 8 there is no need for anyone to support higher versions.
Once they decide to update, we will update too.
