### ISSUE TITLE
IslandWorld - new islands are not created properly from schematic

### ISSUE THREAD

**Issue by dentych** [boy0001/FastAsyncWorldedit#131]
When executing the /is create command, IslandWorld will return "Schematic doesn't have a spawn point". When manually going to the island, the island plot is completely empty.

I tried removing FastAsyncWorldEdit, and the island created just fine. I also tried adding "IslandWorld" to the allow plugins list in the config.yml, but that didn't seem to cut it either.

Other than all this, no error messages nor stacktraces are thrown.

IslandWorld version: 6.7
WorldEdit version: 6.1.2
FastAsyncWorldEdit version: 3.5.0-a05ae2e

**Comment by boy0001** [comment]
Please let me know if this is still an issue and I'll reopen.
