### ISSUE TITLE
Error converting, "you will have to do it manually"

### ISSUE THREAD

**Issue by TheShibaLover** [boy0001/FastAsyncWorldedit#1310]
[ERROR] Conversion failed, you will have to do it manually (Nukkit server + anvil2leveldb command)
I believe lots of people have had this issue before. I'm trying to convert a world made by MCedit to education edition, which is built off bedrock edition.
Debug:
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: Attach Listener | Id: 5 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: pool-3-thread-1 | Id: 33 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 sun.misc.Unsafe.park(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.locks.LockSupport.park(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Thread.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: AWT-Shutdown | Id: 9 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Object.wait(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Object.wait(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 sun.awt.AWTAutoShutdown.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Thread.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: AWT-Windows | Id: 10 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 sun.awt.windows.WToolkit.eventLoop(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 sun.awt.windows.WToolkit.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Thread.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: Signal Dispatcher | Id: 4 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: Reference Handler | Id: 2 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Object.wait(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Object.wait(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.ref.Reference.tryHandlePending(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: Finalizer | Id: 3 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Object.wait(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.ref.ReferenceQueue.remove(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.ref.ReferenceQueue.remove(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: JavaFX Application Thread | Id: 26 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 com.sun.glass.ui.win.WinApplication$$Lambda$64/25671951.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Thread.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: QuantumRenderer-0 | Id: 23 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 sun.misc.Unsafe.park(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.locks.LockSupport.park(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Thread.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: TimerQueue | Id: 35 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 sun.misc.Unsafe.park(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.DelayQueue.take(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 javax.swing.TimerQueue.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Thread.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: Timer-0 | Id: 32 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Object.wait(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Object.wait(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.TimerThread.mainLoop(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.TimerThread.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: Thread-7 | Id: 25 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 sun.misc.Unsafe.park(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.locks.LockSupport.park(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.util.concurrent.LinkedBlockingDeque.takeFirst(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 com.sun.glass.ui.InvokeLaterDispatcher.run(InvokeLaterDispatcher.java:108)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: DestroyJavaVM | Id: 17 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: Thread-8 | Id: 27 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: AWT-EventQueue-0 | Id: 12 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Thread.dumpThreads(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Thread.getAllStackTraces(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 com.boydti.fawe.nukkit.core.converter.ConverterFrame$6.actionPerformed(ConverterFrame.java:272)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 javax.swing.DefaultButtonModel.setPressed(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.Component.processMouseEvent(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 javax.swing.JComponent.processMouseEvent(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.Component.processEvent(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.Container.processEvent(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.Component.dispatchEventImpl(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.Container.dispatchEventImpl(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.Component.dispatchEvent(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.Container.dispatchEventImpl(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.Window.dispatchEventImpl(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.Component.dispatchEvent(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventQueue.dispatchEventImpl(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventQueue.access$500(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventQueue$3.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventQueue$3.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.security.AccessController.doPrivileged(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventQueue$4.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventQueue$4.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.security.AccessController.doPrivileged(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventQueue.dispatchEvent(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventDispatchThread.pumpEvents(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventDispatchThread.pumpEvents(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.awt.EventDispatchThread.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 --------------------------------------------------------------------------------------------
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 Thread: Java2D Disposer | Id: 8 | Alive: true
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Object.wait(Native Method)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.ref.ReferenceQueue.remove(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.ref.ReferenceQueue.remove(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 sun.java2d.Disposer.run(Unknown Source)
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 java.lang.Thread.run(Unknown Source)

Any help would be appreciated.
Thanks

**Comment by IronApollo** [comment]
Please join the IntellectualSites Discord, travel to the #anvil-leveldb-converter channel and read the pinned messages.

**Comment by TheShibaLover** [comment]
I'll do that now

**Comment by TheShibaLover** [comment]
It doesn't say much about having to convert manually, and there is nothing in my superflat world.
