### ISSUE TITLE
X-Ray Error

### ISSUE THREAD

**Issue by TheAberto** [boy0001/FastAsyncWorldedit#1327]
[Debug Paste Link](https://athion.net/ISPaster/paste/view/44e58f63217f4267b20ddc89c054a9b5)

**Checklist**:
- [X] I made sure that I'm using FAWE on 1.12.2 or lower
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE < 1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/) (/fawe update is returning no pending)
- [X] I made sure the bug/error is not caused by any other plugin

[Full Console Log Link](https://pastebin.ubuntu.com/p/TMTzbgcW2Z/)
[Error Link (Thats Spamming)](https://pastebin.ubuntu.com/p/qHkn5tpkkg/)

**Comment by N0tMyFaultOG** [comment]
Set async: false inn the config.yml
