### ISSUE TITLE
PlotSquared restriction direction bug

### ISSUE THREAD

**Issue by Hdadaw** [boy0001/FastAsyncWorldedit#1331]
**Bug demonstration:**
https://youtu.be/iematG2mBvk

**/fawe debugpaste:**
https://athion.net/ISPaster/paste/view/1851055e534e40fe918f0027388b6f95

**Comment by Hdadaw** [comment]
@N0tMyFaultOG why did you close this?

**Comment by N0tMyFaultOG** [comment]
Because you ignored the mandatory template.
