### ISSUE TITLE
Problem with FastAsyncWorldEdit-bukkit-1.14-37

### ISSUE THREAD

**Issue by Manu5656** [boy0001/FastAsyncWorldedit#1333]
Hi I'm using FastAsyncWorldEdit-bukkit-1.14-37 with the server in version 1.14.4

Inside the server I have to have both FastAsyncWorldEdit and WorldEdit otherwise the WorldGuard plugin will not work without it.

When I start the server I get this error:
`[07:56:55 ERROR]: Ambiguous plugin name `WorldEdit 'for files` plugins worldedit-bukkit-7.0.1.jar' and `plugins FastAsyncWorldEdit-bukkit-1.14-37.jar 'in` plugins'`

Then FAWE doesn't work, only WorldEdit works. How can I solve it?

**Comment by Owningle** [comment]
Where can you download the 1.14 version? i cant find it anywhere

**Comment by Manu5656** [comment]
@Owningle  it's here https://ci.athion.net/job/FastAsyncWorldEdit-1.14/

**Comment by N0tMyFaultOG** [comment]
Wait for a release to have fawe be compatible with other plugins.
