### ISSUE TITLE
1.14.4 FAWE crashing the server and created error chunks

### ISSUE THREAD

**Issue by DeathsValentine** [boy0001/FastAsyncWorldedit#1338]
I'm using FAWE for 1.14 on a 1.14.4 server and tried to //cyl grass_block 150 1, but it crashes the server and now if I go into that area the server crashes. These are showing up in console (shown in picture). I have switched to normal world edit for now.
![unknown](https://user-images.githubusercontent.com/39684769/69909845-29885e80-13b6-11ea-9b83-d22862a80857.png)

**Comment by N0tMyFaultOG** [comment]
Wrong repo
