### ISSUE TITLE
Cannot bypass WorldEdit restrictions

### ISSUE THREAD

**Issue by LunaLens** [boy0001/FastAsyncWorldedit#134]
typing '/wea' Only outputs '(FAWE) Your WorldEdit is now restricted.'
It does not appear to toggle bypassing restrictions.
If I add fawe.bypass It appears to be bypassed when a player logs on, but once they use /wea they can no longer bypass.

Current config is

>
clipboard:
  use-disk: false
  delete-after-days: 1
command-processor: false
crash-mitigation: true
extent:
  allowed-plugins:
  - CoreProtect
  debug: true
history:
  buffer-size: 531441
  chunk-wait-ms: 100
  combine-stages: false
  compress: false
  delete-after-days: 7
  delete-on-logout: true
  use-disk: true
lighting:
  async: true
  fix-all: true
limits:
  default:
    max-blockstates: 1337
    max-changes: 50000000
    max-checks: 50000000
    max-entities: 1337
    max-fails: 50000000
    max-iterations: 1000
max-memory-percent: 70
metrics: false
queue:
  discard-after-ms: 60000
  extra-time-ms: 0
  max-wait-ms: 1000
  parallel-threads: 8
  progress:
    display: false
    interval: 1
  target-size: 64
region-restrictions: true
require-selection-in-mask: true
tick-limiter:
  items: 50000
  physics: 500000

**Comment by dordsor21** [comment]
The player is bypassing automatically when they have the permission. If you use it again they'll be bypassing.

**Comment by boy0001** [comment]
It's a toggle

**Comment by LunaLens** [comment]
No it isn't.

I've tried running /wea with and without fawe.bypass and it changes nothing.
