### ISSUE TITLE
[1.14.4] Server sometimes crashes when using //replace 

### ISSUE THREAD

**Issue by derMiepz** [boy0001/FastAsyncWorldedit#1340]
**Debug paste link**:
https://www.athion.net/ISPaster/paste/view/f282792c4a94442180b6941ee7b88a8b

**Description of the problem:**
Server crashes on occasion when using //replace. The same thing happened with the plugin AsyncWorldEdit, so I guess it's a general problem with WorldEdit. Here's the [console log](https://hastebin.com/hifaweqevi.sql)

**How to replicate**:
Not 100% reproducible. You have to use //replace over and over again, preferably with a larger area. What you replace doesn't really matter.

**Checklist**:

- [] I made sure that I'm using FAWE on 1.12.2 or lower
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE < 1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Wrong repo
