### ISSUE TITLE
All Users Can Run /we update

### ISSUE THREAD

**Issue by jakkuh** [boy0001/FastAsyncWorldedit#1344]
There doesn't seem to be any permission check for the /we update command as all users can run it with the response "No update is pending". I'm not sure if they can actually update it with it (and restart the server in the process), but it's kind of janky to have that command exposed.

MC Ver: 1.12.2 (paper 1618)
FAWE Ver: Latest for 1.12.2 (https://i.imgur.com/fdGe7h6.png)

**Comment by N0tMyFaultOG** [comment]
They shouldn't be able to restart the server. Also, respect the template and don't delete it.
