### ISSUE TITLE
/superpickaxe doesn't work

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#135]
_Possible a WorldEdit issue, possible FAWE issue. When using "/superpickaxe recur <#>" the server times out straight away and then crashes.

http://hastebin.com/mefiyuviqe.avrasm this is followed by the usual error of this kind, but reveals our plugins._

**Comment by dordsor21** [comment]
SuperPickaxe doesn't do anything with FAWE installed. Works fine without FAWE.

**Comment by Platinteufel** [comment]
Push. It also doesn't work for me.

**Comment by Platinteufel** [comment]
Please try to fix it since I can't use FAWE without this feature :/
I've recorded a video how it should work: https://youtu.be/KxGyh9wHbek
