### ISSUE TITLE
Request to use FAWE without restrictions of GPL

### ISSUE THREAD

**Issue by Rubydesic** [boy0001/FastAsyncWorldedit#1352]
Hello, I'm a developer of Valkyrien Skies, an Apache-2.0 open source licensed mod and we're interested in using the FAWE API for Forge 1.12, could we be granted permission to dynamically link it's API without the constraints of the GPL license, such as under LGPL which the current FAWE is? Under the current GPL license I believe we'd have to change our license from Apache to GPL.

Thanks, this is a really incredible mod that you've made and we'd love to use it to improve ours!

**Comment by boy0001** [comment]
Yeah, I can't change the license without consent of all contributors, which
isn't likely to happen.

Anyway, the API isn't licensed, just the FAWE code so you should be fine.
If you are distributing FAWE code, I think you can have multiple licenses
as long as you are clear what license pertains to what code (and that
anyone contributing is contributing under the Apache-2.0 license, not GPL).

**Comment by Rubydesic** [comment]
We'll use the API then. Thanks for the incredible mod again!
