### ISSUE TITLE
FAWE not working with Thermos 1.7.10 (Build 57)

### ISSUE THREAD

**Issue by CappyT** [boy0001/FastAsyncWorldedit#137]
I have a working setup of WorldEdit 6.1.1 (mod + plugin) everything works fine with those.
As soon as I put FAWE in the mod folder, server loads fine, but worldedit just does nothing.
Also, I can see FAWE is loading good and fine, but still, makes WE throw NullPointerExceptions.

Here is my full log:
http://pastebin.com/g1C3b7jL

If you need more informations, I'm here to provide those...

**Comment by RoboMWM** [comment]
1) Not compatible with 1.7.10
2) Thermos may be missing some NMS classes(?), at least from what I recall from another user reporting an issue with Thermos and another NMS-dependent plugin.

**Comment by CappyT** [comment]
1) Wut? But there's support for 1.7.10, I see there is a 1.7.10 version of the latest release...
2) Can this be workarounded in some way?

Thanks

**Comment by CappyT** [comment]
I update this, as I asked in discord chat of Thermos. They confirm it's a FAWE problem.

http://i.imgur.com/KpRudp7.png (we were talking about AsyncWE and FAWE, which was the best)

**Comment by boy0001** [comment]
Testing now

**Comment by boy0001** [comment]
was fixed, forgot to mention.
