### ISSUE TITLE
/wea dos not toggle restriction

### ISSUE THREAD

**Issue by ghost** [boy0001/FastAsyncWorldedit#138]
I've tried running /wea with and without fawe.bypass. It does not toggle WorldEdit restrictions.
Each time it only outputs [Client thread/INFO]: [CHAT](FAWE) Your WorldEdit is now restricted.

current config

clipboard:
  use-disk: false
  delete-after-days: 1
command-processor: false
crash-mitigation: true
extent:
  allowed-plugins: []
  debug: false
history:
  buffer-size: 531441
  chunk-wait-ms: 100
  combine-stages: false
  compress: false
  delete-after-days: 7
  delete-on-logout: true
  use-disk: true
lighting:
  async: true
  fix-all: true
limits:
  default:
    max-blockstates: 1337
    max-changes: 50000000
    max-checks: 50000000
    max-entities: 1337
    max-fails: 50000000
    max-iterations: 1000
max-memory-percent: 70
metrics: false
queue:
  discard-after-ms: 60000
  extra-time-ms: 0
  max-wait-ms: 1000
  parallel-threads: 8
  progress:
    display: false
    interval: 1
  target-size: 64
region-restrictions: false
require-selection-in-mask: false
tick-limiter:
  items: 50000
  physics: 500000

**Comment by Janmm14** [comment]
Did you tried to change things or did you list looked at the output of the /wea command?

**Comment by LunaLens** [comment]
Apparently denying fawe.bypass makes /wea work properly.

Did I read the wiki wrong or...?

**Comment by RoboMWM** [comment]
> Apparently denying fawe.bypass makes /wea work properly.

> Did I read the wiki wrong or...?

You probably are using wildcard permissions with PEX or have an interesting permission inheritance structure.

**Comment by dordsor21** [comment]
@boy0001 this is still a problem. It outputs "Your WorldEdit is now restricted." twice, then outputs "You are not bypassing blahblah" constantly, but does not toggle wea

**Comment by boy0001** [comment]
Have vault installed?

**Comment by dordsor21** [comment]
yes

**Comment by dordsor21** [comment]
Still a problem, /wea twice outputs restricted twice, and any subsequent /wea outputs byassing message. WE only toggles off during this.

I have fawe.admin and fawe.bypass

**Comment by dordsor21** [comment]
This is kinda annoying. Been a few times where it'd have been useful to have WE region-restricted.

**Comment by Blamo27** [comment]
@boy0001 This is really annoying :/

**Comment by santafejay** [comment]
I'm OP on my server and it's still saying i'm restricted :/
