### ISSUE TITLE
Data gets deleted after paste

### ISSUE THREAD

**Issue by UltraX3** [boy0001/FastAsyncWorldedit#14]
Data of copied blocks (ex: items in chests, or letters on signs) gets deleted after pastes. This is happens on:

Items:
- Chests
- Furnaces
- Droppers
- Dispensers

Characters:
- Signs

**Comment by Vilican** [comment]
I had that problem too and I fixed it by updating to the latest WorldEdit.

Beta WorldEdits:
WorldEdit - http://builds.enginehub.org/job/worldedit?branch=master
WorldEdit for 1.9 - http://builds.enginehub.org/job/worldedit?branch=feature%2Fforge-1.9

**Comment by RoboMWM** [comment]
> WorldEdit for 1.9 - http://builds.enginehub.org/job/worldedit?branch=feature%2Fforge-1.9

That's for forge, not bukkit

**Comment by Vilican** [comment]
Forge or not, for me, it fully works.

**Comment by boy0001** [comment]
Can confirm this has been fixed.

**Comment by UltraX3** [comment]
I am experiencing this again in version 3.5.0 in 1.8.8
