### ISSUE TITLE
Light levels broken

### ISSUE THREAD

**Issue by PIE-yt** [boy0001/FastAsyncWorldedit#140]
Edits made with FAWE installed don't seem to update light levels.

For instance create a cube outside (//faces) at day time, then spawn zombies inside and they will burn as if under the sun. Likewise remove (//set 0) all the blocks above a dungeon and any mobs there won't burn in daylight.

Using WE without FAWE doesn't have these issues.

Using:
FastAsyncWorldEdit version 3.5.0-a05ae2e
WorldEdit version 6.1.3-SNAPSHOT;3552-edb4c0b
Latest Spigot 1.9.4 (git-Spigot-798f32d-0cd0397)

Thanks for your time.

**Comment by dordsor21** [comment]
FAWE doesn't do lighting updates when world-editing. Use //fixlighting in the area to fix the lighting afterwards. This helps reduce the lag of world-editing greatly.

**Comment by PIE-yt** [comment]
I should have mentioned //fixlighting doesn't fix it.

**Comment by dordsor21** [comment]
Have you enabled it in your config?

`lighting:
  async: true
  fix-all: true`

**Comment by PIE-yt** [comment]
Thanks for your reply.
The config is the default which has these set to true.

I'm testing with no other plugins except FAWE, WE and Vault.

**Comment by dordsor21** [comment]
Any console errors when executing //fixlighting?

**Comment by PIE-yt** [comment]
I've just checked again, nothing in the console.

**Comment by PIE-yt** [comment]
Same issue with 3.5.0-c1b22fb

**Comment by dordsor21** [comment]
I can confirm that this is an issue with 1.9(.4) versions of FAWE. 1.8 works fine with fixlighting
