### ISSUE TITLE
Feature Request: split //undo and /u

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#141]
if possible split up WE and Vs undo's so //undo undoes worldedit and /u undoes voxelsniper. At the moment both undo each other.

**Comment by RoboMWM** [comment]
Would probably be better to ask in WE/VoxelSniper devs themselves, but you could also use commands.yml to map the commands as you wish.

**Comment by dordsor21** [comment]
with the integration of VS into FAWE the two commands were merged via FAWE.

**Comment by RoboMWM** [comment]
oh interesting

**Comment by boy0001** [comment]
There would be a loss of functionality if the commands were separate again. i.e. History on disk is centralized so it can be searched with `/frb` (for rolling back specific edits). Then since VoxelSniper doesn't have `//redo`, you'd also lose that.

**Comment by dordsor21** [comment]
Would it be possible to add the option to split the two and disable the two features? I've received more complaints than praise. If it's too much effort don't worry, players can live.

**Comment by mibby** [comment]
#2 I'd also like to see an option to split it since it is normally separated without FAWE. I have different use cases for voxel and worldedit and I'd like to undo each separately as new operations / changes are made. Heard a few complaints from some of my staff with it being connected together. :(
