### ISSUE TITLE
Large area fixlighting issues

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#142]
When doing progressively larger //fixlighting's (in terms of area) small lighting errors are created randomly. These can be fixed by placing a few blocks near them, and stay fixed, as well as doing small fixlightings (around 1-6 chunks)

![2016-06-05_09 32 12](https://cloud.githubusercontent.com/assets/10080017/15804454/96bc5544-2b00-11e6-9c41-474728f89b8d.png)

**Comment by boy0001** [comment]
Possibly from doing it async. Want to try disabling async relighting?

Also, are you still using paper?

**Comment by dordsor21** [comment]
Will try disabling async, and yes

**Comment by dordsor21** [comment]
This makes even bigger broken lighting areas, and has "unfixed" a lot of areas.

![2016-06-06_09 44 03](https://cloud.githubusercontent.com/assets/10080017/15816583/4d361092-2bcb-11e6-9866-957d79dcaa5e.png)

**Comment by dordsor21** [comment]
Still occurs as of build #115 (#114 being "fixes lighting")

**Comment by EvilOlaf** [comment]
Got similar lighting issues. Will catch up later and add some screenshots.

**Comment by RoboMWM** [comment]
Fyi, async lighting has been broken and disabled in 1.9 paper.

**Comment by EvilOlaf** [comment]
![2016-06-06_21 21 55](https://cloud.githubusercontent.com/assets/3305006/15834677/dcf709b4-2c2c-11e6-9199-4e316902a8dd.png)
Spigot 1.8.8
FAWE 3.5.0-ba2f915

**Comment by dordsor21** [comment]
@RoboMWM using 1.8.8 paper and FAWE

**Comment by dordsor21** [comment]
can async lighting be fixed in 1.9, it's really quite useful.

**Comment by dordsor21** [comment]
600 chunk //fixlighting on 1.9.4, FAWE #.124 crashes server, spamming the following error in console:

http://hastebin.com/maceyisebe.avrasm

**Comment by boy0001** [comment]
FIxed (probably)
