### ISSUE TITLE
Feature Request: Add maven artifacts (repository) for easier integration

### ISSUE THREAD

**Issue by rlf** [boy0001/FastAsyncWorldedit#145]
Hi.

I'm going to include FAWE support in our uSkyBlock plugin, but since we ship our building to a public Travis-CI, we need to be able to compile our project relying on artifacts available through public repositories.

Do you have some repo available we can point to?
Or would you mind if I uploaded one of your releases to the uSkyBlock repo? (branch on GitHub).

**Comment by boy0001** [comment]
I uploaded this just now. If you want to stick to the latter, that's fine.
http://empcraft.com/maven2/com/boydti/fawe/

**Comment by rlf** [comment]
Great thanks!
