### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mat41997** [boy0001/FastAsyncWorldedit#149]
logs
http://hastebin.com/useheveper.avrasm

timings
https://timings.aikar.co/v2/?id=75aa9584638b465e91671a45601fdb6e

**Comment by boy0001** [comment]
Hmm, that shouldn't be happening.

Temporary fix would be to set parallel-threads to 1 in the config. (things will be slower)

**Comment by boy0001** [comment]
Can't replicate. Can you send me the server jar you are using?

**Comment by mat41997** [comment]
https://ci.techcable.net/job/TacoSpigot/66/

**Comment by boy0001** [comment]
It's an issue with TacoSpigot specifically. Using paper works fine:
https://ci.destroystokyo.com/job/PaperSpigot/
