### ISSUE TITLE
Pasting = nada

### ISSUE THREAD

**Issue by TWSSYesterday** [boy0001/FastAsyncWorldedit#15]
Cannot paste a simple schematic, log: http://hastebin.com/okisigejag.avrasm
Config: http://hastebin.com/ajuhorezez.sm
When it pastes or at least attempts to, it spews out the log above.

**Comment by boy0001** [comment]
Fixed in: https://github.com/boy0001/FastAsyncWorldedit/commit/24f0cb9bcf5898eda66d724b15c2ce1857ec3d21
