### ISSUE TITLE
//download not in plugin.yml

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#152]
//download is not registered as a command for downloading clipboards

**Comment by boy0001** [comment]
It doesn't need to be in the plugin.yml

**Comment by dordsor21** [comment]
doesn't do anything when used after copying a region

**Comment by dordsor21** [comment]
To clarify "Unknown Command did you type it correctly" is what's sent when using //download

**Comment by boy0001** [comment]
https://github.com/boy0001/FastAsyncWorldedit/blob/master/core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java#L211-L229

Works for me.

**Comment by dordsor21** [comment]
Latest FAWE wasn't properly installed on network. Works
