### ISSUE TITLE
Larger heightmap brush

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#155]
Would it be possible to disconnect the HeightMap brush from the maximim WorldEdit brush size, as it can be much more effective at larger sizes, but allowing normal WE brushes of sizes in excess of 100 can be dangerous.

**Comment by boy0001** [comment]
The worldedit radius option should mostly be obsolete with FAWE limiting being based on block changes/checks etc. 

Is there some reason why you consider the heightmap brush less dangerous than the other brushes?

**Comment by dordsor21** [comment]
this is true
