### ISSUE TITLE
IMPORTANT -- as of build 131

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#158]
IMPORTANT: Cannot undo VoxelSniper

IMPORTANT: Some worlds (now including PlotSquared worlds) cannot be VS'ed in at all. Not main world as defined in server.properties. Occasionally works after restart but breaks again some time afterwards #153 

IMPORTANT: VoxelSniper breaks in random chunks on a plot. It also randomly goes onto road. #132

**Comment by boy0001** [comment]
`using /wea over and over produces:`
Issue with your permissions plugin not being able to keep up. It should start working again after a minute.

**Comment by RoboMWM** [comment]
What Empire92 said, or if you're impatient, use /pex reload or similar.

**Comment by dordsor21** [comment]
The important stuff to do with VS is the main issue^^

**Comment by RoboMWM** [comment]
Best to then leave as-is (as separate issues)?

**Comment by boy0001** [comment]
probably fixed.

**Comment by dordsor21** [comment]
chunk issues not fixed
