### ISSUE TITLE
Feature Request: Max //undo (history?) limit per player

### ISSUE THREAD

**Issue by acidbyt3** [boy0001/FastAsyncWorldedit#160]
Title says all :)

**Comment by RoboMWM** [comment]
Is this not a Worldedit config option?

**Comment by acidbyt3** [comment]
FAWE overrides it. My WE had a //undo limit (either 5 or 10, cant recall) but after installing FAWE it became unlimited. Whether I have it set to save history to disk or not, there doesn't seem to be any limit as to how far back the history goes (other than the "delete after days"/"delete on logout" settings)

**Comment by boy0001** [comment]
Using `/fawe reload` currently doesn't reduce the limit, you need to restart the server. History on disk will always be unlimited (and cleared every startup).

**Comment by boy0001** [comment]
Implemented in a way. The limit in the worldedit config will still apply (raise it if you want). In the FAWE config set `max-history-mb` for the limit group. This will limit history size based on how much memory it uses.

Note: Old history on disk is cleared only when the server starts. As for the `delete-on-logout`, that only applies to what's in memory (it should be documented in the config).
