### ISSUE TITLE
[//wand] doesnt work

### ISSUE THREAD

**Issue by Bodyash** [boy0001/FastAsyncWorldedit#161]
I have WE and FAWE, players have WE.wand permission to create region and make it own by WorldGuard. But with latest FAWE:
https://pp.vk.me/c636518/v636518918/11820/GV7xTzRBk9A.jpg

**Comment by boy0001** [comment]
Not a bug.

**Comment by Bodyash** [comment]
How to give permissions to use //wand, when FAWE is Installed?
