### ISSUE TITLE
Trees

### ISSUE THREAD

**Issue by Vanillezucker** [boy0001/FastAsyncWorldedit#162]
Hi,

I had a bug with trees.
It's not possible to create big trees or trees which aren't small oaks.
Error when /tree bigtree:
```
[INFO]: ====== NO NMS BLOCK PLACER FOUND ======
[INFO]: FAWE couldn't find a fast block placer
[INFO]: Bukkit version: git-Spigot-d20369f-7fc5cd8 (MC: 1.9)
[INFO]: Supported NMS versions: 1.8.8, 1.9.4
[INFO]: Fallback placer: class com.boydti.fawe.bukkit.v0.BukkitQueue_All
[INFO]: =======================================
```
Error when /tree spruce:
none
MC: 1.9 / 1.9.4
FAWE: 1.9.4 3.5.0-00c685c

**Comment by boy0001** [comment]
You need to update to 1.9.4 for FAWE to work. Also that bug was fixed, update FAWE as well.

**Comment by Vanillezucker** [comment]
As I said, I tried it with 1.9 and 1.9.4 server version.

**Comment by Janmm14** [comment]
Did you updated FAWE as requested?
