### ISSUE TITLE
WorldEdit changes are bugged for other players

### ISSUE THREAD

**Issue by UltraX3** [boy0001/FastAsyncWorldedit#163]
### Issue:
_Player A: Player WorldEditing
Player B: Player looking at Player A WorldEdit_
This includes:
- Player B needing to relog when another Player A changes blocks
- Occasionally some chunks (not entire chunk, as the gap does not cover the entire y but entire x and z of a chunk) are not visible for Player B and relogging will not help him see them. They are still there though, and he cannot fly through the blocks as the server knows there are blocks there (note Player A can see the blocks fine). Player B must place a block where the updated blocks should be and then relog to see the rest of the missing chunk. 

### Version:
I am still experiencing this issue on version 3.5.0-00c685c with WorldEdit version 6.1.3-SNAPSHOT;3563-f689d53 on 1.8.8 PaperSpigot. I did not want to use the latest version as it is in development.

### Configuration:
```
max-volume: 50000000
max-memory-percent: 95
command-blacklist:
- cs
- .s
- restore
- snapshot
- delchunks
- listchunks
command-processor: false
max-entities: 1337
max-iterations: 1000
fix-all-lighting: true
require-selection-in-mask: false
max-blockstates: 1337
crash-mitigation: true
limits:
  default:
    max-changes: 50000000
    max-checks: 50000000
    max-iterations: 1000
    max-entities: 1337
    max-fails: 50000000
    max-blockstates: 1337
region-restrictions: true
clipboard:
  delete-after-days: 1
  use-disk: false
lighting:
  async: true
  fix-all: true
history:
  use-disk: false
  chunk-wait-ms: 100
  compress: false
  delete-after-days: 7
  combine-stages: false
  delete-on-logout: true
tick-limiter:
  items: 1337
  physics: 500000
queue:
  max-wait-ms: 1000
  target-size: 64
  parallel-threads: 1
  extra-time-ms: 0
  progress:
    display: false
    interval: 1
extent:
  allowed-plugins:
  - BlockLimit
  - SchematicShop
  debug: true
metrics: true
DOCUMENTATION: https://github.com/boy0001/FastAsyncWorldedit/wiki/Configuration
```

**Comment by dordsor21** [comment]
Always use the latest version. As the spigot post for the plugin states, 

> About: This plugin is still in development, there is no "stable" release, just development builds.

https://www.spigotmc.org/resources/free-fast-async-worldedit-voxelsniper-%CE%B2eta.13932/update?update=98057
