### ISSUE TITLE
Feature Request: operation commands from console

### ISSUE THREAD

**Issue by DragonbornCommunity** [boy0001/FastAsyncWorldedit#165]
I would suggest to add the possibility to paste/create schematics from the console, within a certain location written in the command or with a chunk location.

**Comment by boy0001** [comment]
temporary solution:
http://dev.bukkit.org/bukkit-plugins/virtualplayers2/

/pos1 0,0,0
/pos2 5,5,5
/set stone

**Comment by DragonbornCommunity** [comment]
Does it mean that you're going to provide a proper solution?

Thanks by the way

**Comment by boy0001** [comment]
Changes were already made in FAWE so that WorldEdit would work with VirtualPlayers2. 

Latest commit now supports worldedit from console. To change your position use: `/jumpto world,0,0,0`

**Comment by EvilOlaf** [comment]
For some reason this does not work for me well.
What I've entered:

`jumpto farm,102,63,12`

what I got:
```
[13:20:26] [Craft Scheduler Thread - 397/INFO]: [FAWE] Too many parameters! Unused parameters: farm,102,63,12
[13:20:26] [Craft Scheduler Thread - 397/INFO]: [FAWE] Usage: /jumpto jumpto [world,x,y,z]
```

As a minor bug: there is one `jumpto` to much in the usage explanation
