### ISSUE TITLE
Red Sandstone Half Slabs not Copying and Mirroring Correctly

### ISSUE THREAD

**Issue by mheller3000** [boy0001/FastAsyncWorldedit#166]
I have observed the Redstone Half Slab ID 182 not pasting correctly after all the main operation commands (Copy, Cut, Flip, Paste, etc.)  It always pastes in the lower block state not the upper block state.  So It's shifted from the upper position to the lower position as it relates to manual placement to other blocks around them.  

I have not observed this issue with any other block in general or half slab as of this moment.  
I have included an example screenshot in the zip file included in this bug submission.  The far left is the original room, middle is the room only copied over and the far right is the same room mirrored.  These illustrate the issue at hand.

I have also not observed any console errors at all during these operations.

I have already removed and tried these same operations with and without fawe and without the plugin it works fine and with it the behavior explained above is apparent.  This leads me to believe its a bug in the fawe plugin of come sort.

I am running the latest version of Worldedit 6.1.3.  Latest dev of fawe 3.5.0-dev and running Spigot 1.9.4.

I run a mega-build production server and we use these operations significantly on an almost daily basis.  If this could be fixed the entire staff and community would be grateful.  Assuming the plugin is ultimately to blame of course. :D

Any help to possibly resolve this issue would be so very much appreciated. :D

[Bug Submission Details.zip](https://github.com/boy0001/FastAsyncWorldedit/files/331128/Bug.Submission.Details.zip)

**Comment by xBreaksx** [comment]
I can't use 181:8 after I installed FAWE. Minor concern but still need a fix/way to fix.

**Comment by mheller3000** [comment]
As it relates to the Issue described above and the additional comment above.  I'm not having any issues using or manipulating block id 181:8 using manual placement, Worldedit or fawe with my particular server setup.

**Comment by xBreaksx** [comment]
@mheller3000 Weird. What's your version of WorldEdit and FAWE?

**Comment by mheller3000** [comment]
I am running the latest version of Worldedit-bukkit 6.1.3. Latest dev of fawe 3.5.0-dev and running Spigot 1.9.4.

**Comment by boy0001** [comment]
@xBreaksx
181 is a full block, it doesn't have variants.

**Comment by mheller3000** [comment]
Thank you so much for fixing this issue.  I have verified that it works and I am so grateful for your hard work and quick response.  Your fawe plugin is just simply amazing and literally getting even better than amazing every day :D
Sincerely,
       -mheller3000

**Comment by xBreaksx** [comment]
@boy0001 But there is... 43 is a full block and it has variants. It's the same thing, and there's supposed to be a smooth red sandstone block.

**Comment by boy0001** [comment]
@xBreaksx Ah, my bad. Should be fixed from this last commit.
