### ISSUE TITLE
Feature Request: Max //Set block per group.

### ISSUE THREAD

**Issue by Reeferx7** [boy0001/FastAsyncWorldedit#169]
Hello, is possible to add on group option max number //set blocks ?
Like:

#Max number of block changes (e.g. by //copy).
    max-changes: 5000000
#Max number of block set (e.g. by //set).
    set-changes: 1000

**Comment by boy0001** [comment]
`max-changes` is already what you want. The documentation on the wiki was misleading (has been fixed now)
