### ISSUE TITLE
//undo broken

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#174]
//undo is broken some of the time causing very most to very few to none of the chunks to be undone. For example:

![2016-06-30_20 01 49](https://cloud.githubusercontent.com/assets/10080017/16500721/b9e35ef8-3efd-11e6-82fa-d1be00bf12f2.png)

Using Spigot 1.10 with latest FAWE build (build 159)

**Comment by Janmm14** [comment]
Tried a relog?

**Comment by chamunks** [comment]
@Janmm14 sounds like its not a relog fixable problem.

**Comment by dordsor21** [comment]
also relogs are temporary fixes anyway...

**Comment by Janmm14** [comment]
Checking whether a reload fixes it or not shows whether the blocks are actually not edited or that the edit is just not sent to the client.

**Comment by dordsor21** [comment]
the blocks are not actually edited.

**Comment by dordsor21** [comment]
seems to be fixed as of latest build.
