### ISSUE TITLE
[Suggestion] Add option to disable certain messages

### ISSUE THREAD

**Issue by Masonrf** [boy0001/FastAsyncWorldedit#177]
It would be nice if an option was added to completely disable specific messages entirely instead of just removing permissions.
This stemmed from a server owner (OPed) getting annoyed over these messages: 
![2016-07-01_17 57 50-2](https://cloud.githubusercontent.com/assets/16567072/16546406/eb277b62-410e-11e6-92aa-b81e70ee1d92.png)

**Comment by boy0001** [comment]
Set the message to empty quotes. (Also there was a bug with the translations in older versions, so also  update FAWE)

```YML
history:
  indexing_history: ""
```
