### ISSUE TITLE
End portals in 1.10.2 are not rendering correctly when set with FAWE

### ISSUE THREAD

**Issue by Sejsel** [boy0001/FastAsyncWorldedit#178]
Setting end portals (//set end_portal) creates end portals with no texture, only particles.

This happens in the Client version 1.10.2. There is no difference in rendering in 1.10.0 when you connect to the same server, though.

The portals still work and there is no special data shown in the F3 screen for either of the portals.

Reproducible with WE 3583, FAWE f202a56 (and older versions), Minecraft Client 1.10.2, the server version does not matter as long as it is protocol compatible.

Left in the dirt hole - with FAWE; Right - without FAWE.
![screenshot from 2016-07-04 17 12 26](https://cloud.githubusercontent.com/assets/998408/16565086/4ecfd5cc-420b-11e6-8160-340a52438a07.png)

**Comment by boy0001** [comment]
Merging with #320
