### ISSUE TITLE
Async world loading?

### ISSUE THREAD

**Issue by Sataniel98** [boy0001/FastAsyncWorldedit#180]
Hi,
I've got a question: Is it possible to use the FAWE API to load worlds asynchronously? The API tutorial is great, but I can't find an equivalent to Bukkit.createWorld() for AsyncWorld.

**Comment by Janmm14** [comment]
Basically I'd say you put that createWorld into an asynchronous task

**Comment by Sataniel98** [comment]
It's not thread safe AFAIK

**Comment by boy0001** [comment]
Added for 1.10 (other versions you'll have a lag spike on the main thread when trying async). I haven't tested much so let me know if there are any issues.

The example has been updated:
https://github.com/boy0001/FastAsyncWorldedit/wiki/API#wrappers-for-bukkit-api
