### ISSUE TITLE
Wood planks replaced by Oak wood planks

### ISSUE THREAD

**Issue by Rossmall** [boy0001/FastAsyncWorldedit#182]
Hi !
I'm running on spigot 1.10 with FastAsyncWorldEdit-bukkit19-3.5.1-f202a56, and when i copy Wood planks of different types, they are always replaced by Oak wood planks.
By the way, thanks for this amazing plugin :D
![2016-07-06_21 38 12](https://cloud.githubusercontent.com/assets/16778159/16631980/35cd2490-43c2-11e6-88dd-ed4e99cf18cc.png)

**Comment by dordsor21** [comment]
You're not using 1.10 FAWE

**Comment by Rossmall** [comment]
Oooops, you're right, sorry, i didn't realize that there is a new version for 1.10 !
Thanks for the help !
