### ISSUE TITLE
//set 0 lags like crazy

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#184]
//set 0 lags the hell out of the server. The action "completes" in normal time but the chunks take ages to send and causes high CPU usage and lags the server greatly.

If a //fixlighting is run beforehand (or during) the WorldEdit speeds up and completes in normal time.

This proceeds to occasionally corrupt chunks involved with the WE and renders the world unusable - lagging the server on every join.

It's fixed if you can manage to run a fixlighting on the area of the //set 0

FAWE appears to be attempting to badly fix lighting

**Comment by boy0001** [comment]
Can't replicate. Are you using the correct version of FAWE for the platform? i.e. 1.10 fawe with 1.10

**Comment by dordsor21** [comment]
yep, it's on P2 worlds, and large (over 50k) numbers of blocks.

**Comment by dordsor21** [comment]
The problem was that FAWE was attempting to fix lighting. Problem resolved upon putting lighting.fix-all to false in config

**Comment by dordsor21** [comment]
latest FAWE doesn't have fix-all option, but lighting.mode: 4 seems to work fine
