### ISSUE TITLE
FAWE actions are not recorded by CoreProtect

### ISSUE THREAD

**Issue by Small-Ku** [boy0001/FastAsyncWorldedit#188]
Log:http://pastebin.com/mLbwQFW8
Vid:https://youtu.be/6u59ivTN-98
Config:http://pastebin.com/ui0hGtxL

**Comment by Janmm14** [comment]
See #167 and use BlocksHub.

**Comment by Small-Ku** [comment]
I am using the newest BlocksHub already

**Comment by boy0001** [comment]
BlocksHub failed to load. See here, in the startup log:
http://hastebin.com/gaviyojozi.css

Make sure you also update BlocksHubCoreProtect, otherwise talk to @SBPrime
