### ISSUE TITLE
FixLighting doesn't check skylight

### ISSUE THREAD

**Issue by boy0001** [boy0001/FastAsyncWorldedit#19]
Also, relighting doesn't take sky lighting into account, so this happens:

![Bug](http://i.imgur.com/HqnDF2L.jpg)

Even though we are standing under a giant dome of coal blocks.

**Comment by Quicksteve** [comment]
Also fixlighting imposes limits on how many chunks can be fixed; it would be nice if you could configure (and disable) them.

**Comment by Blue-Guy** [comment]
This is causing "fullbright", even without using the /fixlighting command

**Comment by RoboMWM** [comment]
@Blue-Guy: Yea, since it's not accounting for skylight, yes, we know.

**Comment by boy0001** [comment]
Fixed fixlighting
