### ISSUE TITLE
Redstone is very glitchy

### ISSUE THREAD

**Issue by Blue-Guy** [boy0001/FastAsyncWorldedit#191]
Seems to be the same glitch in [this video](https://www.youtube.com/watch?v=VmhpXyC1t8E)

![image](https://cloud.githubusercontent.com/assets/16492168/16891486/4caa0b12-4ac8-11e6-9ab7-d1827d5c887a.png)

Glitch disappears when I remove FAWE

**Comment by boy0001** [comment]
Raise the physics limit in the config.yml e.g. 50000, also make sure you are on the latest version

**Comment by Blue-Guy** [comment]
Thanks! that fixed it!
