### ISSUE TITLE
Schematics saving incorrectly

### ISSUE THREAD

**Issue by HippyBomb** [boy0001/FastAsyncWorldedit#193]
This might be a result of my personal configuration, but schematics don't transfer.
"Schematic could not read or it does not exist: Schematic file is missing a 'Blocks' tag"
Sorry if this is answered elsewhere, I haven't used GitHub all too much yet.
My configuration: http://pastebin.com/R4e6pji0
*Note: I added schematics to the blacklist tab after it stopped working, to see if that was the issue, but the switch had no effect, and either way produced the same error.

**Comment by dordsor21** [comment]
schematics made on the server with `//schem save` error when trying to paste

http://hastebin.com/orahawapux.avrasm

**Comment by boy0001** [comment]
Try now

**Comment by SirNickParks** [comment]
It appears that chests don't get their items transferred from the schematic. Sometimes even turning invisible when loaded.

Using latest dev build.

**Comment by boy0001** [comment]
@SirNickParks 
Please create a new ticket with your configuration / schematic.
