### ISSUE TITLE
Error on editing new command blocks

### ISSUE THREAD

**Issue by Small-Ku** [boy0001/FastAsyncWorldedit#196]
The Impulse Command Block works normally with the command inside but it direct to a wrong direction.
The other two works normally with the direction but missing the command inside.

[VIDEO](https://youtu.be/0E61kigrjUI)  [LOG](http://pastebin.com/AGKPxmDv)  [CONFIG](http://pastebin.com/RBMVpRhS)

**Comment by boy0001** [comment]
Possibly fixed

**Comment by Small-Ku** [comment]
The problem of impulse command block is fixed,but the others still missing the command.
Thank you :D

**Comment by boy0001** [comment]
If you relog do the commands show up?

**Comment by Relaking** [comment]
Yes, the command blocks are still empty after a relog

**Comment by TheRealB** [comment]
Same issue here

**Comment by TheRealB** [comment]
Adding the two lines:
case 210:
case 211:
to the function hasNBT() in FAWECache Should fix this problem.
Unfortunately you are using a closed server for your Maven repos so it is not easy to build myself and check.

**Comment by boy0001** [comment]
Added those lines.

> Unfortunately you are using a closed server for your Maven repos so it is not easy to build myself and check.

You should be using gradle to build the project. The pom might be broken, I haven't used it.

**Comment by Relaking** [comment]
Nope, sadly still not working

**Comment by boy0001** [comment]
using gradle, or the command blocks?

**Comment by Relaking** [comment]
Sorry, I meant the command blocks

**Comment by Relaking** [comment]
Seems to be fixed in version 16.11.17-e16bcae-372-9.11.4
