### ISSUE TITLE
Enhancement: dynmap integration for WE events

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#197]
Sounds weird, right? Let me explain.

I frequently use `//regen` to recycle orphaned landscapes and offer them to new players. The problem here is that these regenerations are not triggering dynmap to re-render the affected chunks.

So my idea was to somehow trigger a render event for dynmap to automatically. For now I have to use `dynmap radiusrender` which I do quite rarely due to laziness or do a fullrender which takes up to 20 hours to complete and blocking hardware resources.

It seems like dynmap does provide an API to receive render inquiries from other plugins.

As always thanks for reading.

**Comment by RoboMWM** [comment]
Perhaps you could do a localized (i.e. radius-specified) fullrender when you also run the //regen command?

**Comment by EvilOlaf** [comment]
A radius-specific fullrender would be the same as a `radiusrender`. This command only working with a given radius in blocks and optional x and z coordiantes for adjusting the center of starting the render.
The next issue is that in most times you do not have perfect squares to regenerate and re-render, so lot of unneeded tiles would be rendered.
To go further lots of times you do not exactly know how many blocks in length you marked. You just fly straight across the field, mark using the wooden axe or the //pos commands and do the regen. 
Also dynmap seems not to support rendering a given areal using coordiantes given from user inverface. The API does.
