### ISSUE TITLE
Blocks with gravity bug out

### ISSUE THREAD

**Issue by UltraX3** [boy0001/FastAsyncWorldedit#2]
When doing //move or many other commands blocks with gravity (ex: sand, gravel, dragon eggs, anvils) don't get set correctly. This is probably due to FAWE trying to do things async but the blocks are falling at the same time. Maybe try stopping physics for all falling blocks.

**Comment by boy0001** [comment]
Still an issue?

**Comment by UltraX3** [comment]
Nope :)

**Comment by EvilOlaf** [comment]
Seems like it is still an issue. Common brushes with gravity blocks do not work properly.

**Comment by boy0001** [comment]
@EvilOlaf 
Possibly a different issue which may be intended behavior (depends on how it doesn't work properly). 

Physics is disabled as it's slow and a potential cause of a server crash. If you are just expecting it to fall and it doesn't, that's normal. Use the heightmap brush instead for terrain.

**Comment by EvilOlaf** [comment]
Ah, I see.
Than this can be closed again, thanks.
