### ISSUE TITLE
FAWE API - Feedback wanted

### ISSUE THREAD

**Issue by boy0001** [boy0001/FastAsyncWorldedit#20]
Anyone interested. What kind of functions would be useful?

Note: Fawe doesn't prevent you from using the normal WorldEdit API

**Comment by nicosiimon** [comment]
Hey boy0001,
I very interested in a config option or ingame command to enable item phyics. This would be quite usefull while building mountains with sand spheres.

~Nico

**Comment by RoboMWM** [comment]
@nicosiimon this ticket is regarding the API. I think there's a ticket for gravity, but if not, create one.

**Comment by boy0001** [comment]
Seems I didn't get any feedback here :/
