### ISSUE TITLE
Schematic loading/pasting (maybe saving also) bug

### ISSUE THREAD

**Issue by fatboy2380** [boy0001/FastAsyncWorldedit#200]
When loading a large schematic containing a lot of blocks with data such as wool, and some flowers. The paste is broken and some of these blocks are reverted to white wool, and all the plants seem to have reset to dead plants.

This issue is directly relating to schematics as copy/pasting works fine for the same selection, but once the selection is saved/loaded it is pasted broken.

I have also tried creating the same schematic in MCEdit and uploaded it to the server. I get the same results as when saving/loading the schematic.

**Comment by dordsor21** [comment]
#193

**Comment by boy0001** [comment]
Please attach the schematic
