### ISSUE TITLE
Use API to get current queue?

### ISSUE THREAD

**Issue by Gaurav99** [boy0001/FastAsyncWorldedit#205]
Hey,
I was wondering if it was at all possible to use the API to get the current amount of queued blocks for a player.  I was able to use the API to use it to get the max queue per player, but not the current amount of blocks queued.

Thanks!

**Comment by boy0001** [comment]
Probably possible to do, but not something simple through the API since FAWE queues chunks, not individual blocks.

I'll make some changes and let you know.

**Comment by boy0001** [comment]
You can get the EditSessions currently running for a player:
[`FawePlayer#getTrackedSessions`](https://github.com/boy0001/FastAsyncWorldedit/blob/master/core/src/main/java/com/boydti/fawe/object/FawePlayer.java#L443). From each EditSession you can get the changed blocks: [`EditSession#getLimitUsed`](https://github.com/boy0001/FastAsyncWorldedit/blob/master/core/src/main/java/com/sk89q/worldedit/EditSession.java#L327), though this does not necessarily correspond to the current blocks in the queue (as the queue empties as it's dispatching.

Or from the FaweQueue ([`EditSession#getQueue`](https://github.com/boy0001/FastAsyncWorldedit/blob/master/core/src/main/java/com/sk89q/worldedit/EditSession.java#L417)), you can get the active chunks: [`FaweQueue#getFaweChunks`](https://github.com/boy0001/FastAsyncWorldedit/blob/master/core/src/main/java/com/boydti/fawe/object/FaweQueue.java#L137), then each active chunk can be cast to a [`CharFaweChunk`](https://github.com/boy0001/FastAsyncWorldedit/blob/master/core/src/main/java/com/boydti/fawe/example/CharFaweChunk.java) and use [`CharFaweChunk#getTotalCount`](https://github.com/boy0001/FastAsyncWorldedit/blob/master/core/src/main/java/com/boydti/fawe/example/CharFaweChunk.java#L86)
