### ISSUE TITLE
Players Blinking 1.8.8

### ISSUE THREAD

**Issue by Fluxty** [boy0001/FastAsyncWorldedit#206]
Whenever an action is performed in FAWE, the player and all the entities in the chunk (including armorstands, e.g. holograms) blink. By "blink" I mean they dissapear for a split second and re-appear. The problem is that we hook into FAWE for a custom enchant that mines large cuboids of blocks per block break. The end result is the player blinking all over the place while they mine, and all the holograms around them are blinking too. It's very distracting and annoying for the players.

**Comment by mibby** [comment]
@boy0001 Correct me if I am wrong, but I believe this problem is due to FAWE reloading the world chunk with operations directly. As I had problems with entities (armor stands, banners, item frames) flashing / going invisible when doing copy/paste/set to stone/undo operations.

**Comment by Fluxty** [comment]
Yeah maybe, wouldn't happen to know a fix we could rig in?

**Comment by boy0001** [comment]
@mibby 
It used to use the deprecated method `CraftWorld#refreshChunk`, but since that made all entities invisible, and caused issues with tile entities, I am using NMS for it now.

@Fluxty 
Anywho, should be fixed now, try it out.
