### ISSUE TITLE
Possible to disable movement operations such as '/up' from history?

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#208]
FastAsync dev 184
WorldEdit dev 3596
PaperSpigot (MC 1.10) dev 830

WorldEdit does not normally keep movement operations in the undo history. Meaning, I can type `/up` and `/undo` will not remove the block created. But with FAWE, movement operations are affected by the history. Is it at all possible to retain normal WorldEdit behavior with what operations are kept in history and possible to undo?

**Comment by boy0001** [comment]
Nothing to do with moving, it's the block change that's tracked.

I know WorldEdit doesn't have up, superpickaxe, regen and restore go through the EditSession, however I fail to see why you would not want it to be undoable?

More concerning to me would be players using up/regen/superpickaxe to circumvent region restrictions, limits, or block logging to do harm?

**Comment by dordsor21** [comment]
Possibly fixed by the region restriction fixes for them. From what I've experienced, not in history I don't think
