### ISSUE TITLE
FAWE schematic list does not follow worldedit behavior.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#209]
FastAsync dev 184
WorldEdit dev 3596
PaperSpigot (MC 1.10) dev 830

With WorldEdit dev 3596, listing all schematics with ```/schematic list``` properly displays a list with page indentation. But with FAWE, it displays everything in one block. When you have hundreds of schematics, it goes past the window scroll length and makes it impossible to sort through.

Is it at all possible to retain WorldEdit's native schematic list functionality?

**Comment by boy0001** [comment]
FAWE has outdated functionality, didn't realize it was changed in WorldEdit to have pages.
