### ISSUE TITLE
Suggestion - Remove '/i' as an alias to inspect since it is a common command to spawn items in.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#212]
I manually removed 'i' from the alias in the command.yml, but it still registers and takes priority with FAWE rather than being an Essentials command to spawn items in for yourself. :( Normal worldedit with AWE does not have this problem.

Problem cause of here? https://github.com/boy0001/FastAsyncWorldedit/commit/e5ebccd05324b18ef2be9dbce6c269e50fbcb20d#diff-b8dc9d87f5781713133490e81db08052R84

**Comment by boy0001** [comment]
Inspect is a custom command. Strange that the commands.yml didn't work, I'll have to look into that.

Anywho, having it be `/i` was a mistake, it should have been `//i` and has since been changed

**Comment by mibby** [comment]
Ah, alright. Thanks for the change in the meantime. Hopefully removing aliasing from commands.yml can be fixed.
