### ISSUE TITLE
Question - What is the difference between FastAsyncVoxelSniper-favs and FastAsyncWorldEdit-bukkit?

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#213]
What is the difference between the two versions besides in name? They are both roughly the same size with the WorldEdit version slightly larger. Both have /p and /d commands in the plugin.yml. Is the voxelsniper version just a stripped down FAWE? It doesn't generate any configs by itself and errors when trying to use voxel commands with it installed.

**Comment by boy0001** [comment]
FAVS is meant to be for VoxelSniper only, and requires FAWE also installed. Latest commit should reduce the size of it, since the classes were already in the normal FAWE jar.

**Comment by mibby** [comment]
@boy0001 Is it just for region limiting and undoing? As in there are no functional rewrites / optimizations to it?

**Comment by boy0001** [comment]
Uh, it's all about optimizations and functionality:
 - Makes VoxelSniper fast and async
 - Adds Region restrictions
 - Adds Block logging
 - Adds Redo

Is that a problem?

**Comment by mibby** [comment]
Nope. It just didn't seem to generate a config or new folder when using just the Voxel version. As well as errors when trying to use voxel commands with it installed. I also find it a bit odd that voxel permissions are bundled in the worldedit version if it is suppose to be separated. 

I assume /u (Voxel) and //undo (worldedit) are separated then? Or would it still be tied to one undo command if both are used?

**Comment by boy0001** [comment]
If you want FAVS you need FAWE also installed. They use the same undo, as mentioned in the other ticket.

And no, both take about the same amount of time per block change, voxel just tends to be small brushes, so it may not be as noticeable. Same sort of optimizations that were made to WorldEdit.

**Comment by mibby** [comment]
Ah, I see. Would it be possible to separate the undos or add a setting to do so? As I use voxel individually from worldedit for different use cases. Having it tied together makes making edits between the two tools a bit restricting.
