### ISSUE TITLE
Possible to toggle the disabled physics?

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#216]
Physic calculation is forced disabled on all worldedit operations with FAWE. Would it be possible to add a command to toggle it enabled on a per player basis and/or a setting to force it enabled (not disable physics) for calculations / operations?

**Comment by Janmm14** [comment]
would take too much processing power i'd say

**Comment by mibby** [comment]
To allow physic calculations? It seems to be fine with normal worldedit and WE with AWE Premium (physics enabled). Don't see why the option couldn't be provided instead of enforcing changes that may not be wanted.

**Comment by boy0001** [comment]
It's not "fine" with normal worldedit. Normal WorldEdit is slow and can often crash the server. Having physics contributes to that problem. Also people trying to terraform with sand/gravel brushes is depressing when there are much better alternatives out there. 

Closing this in favor of #55, in the meantime, you can use `/fixwater` for those random pockets.

**Comment by kalleswe** [comment]
Can you please add this now in FAWE. We need it as an option to be able to do what we want when building. You forcing people not to have it does not  help. Stop being noob about it. It's been 3 years and it's still not fixed.

**Comment by IronApollo** [comment]
No. Read the above conversation as to why not. Locking this to prevent anyone from resurrecting this issue in the future.
