### ISSUE TITLE
Fixlighting does not recalculate lighting in chunks that are already lit due to chunk corruption that don't have a light source. 

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#218]
FastAsync dev 185
WorldEdit dev 3596
PaperSpigot (MC 1.10) dev 830

If you had lava (or other light sources) in a chunk and removed it with worldedit, the light sometimes does not fix itself - leaving light patches in the chunk. Selecting the region and typing /fixlighting does not remove the light and recalculate what the actual light level should be. You have to type /removelight, then /fixlighting. 

Shouldn't fixlighting be recursive and detect all light problem types? Checking for both black spots and incorrectly lit spots?

**Comment by boy0001** [comment]
Not implemented yet. The main issue is determining whether it's bad lighting, or just lighting bleeding over from another chunk.

**Comment by dordsor21** [comment]
It's a completely unfix-able issue save putting the whole world into MCEdit and relighting the affected areas there every time, which is not practical by any means.

**Comment by mibby** [comment]
What is completely unfix-able? Chunks that have invalid light sources can be fixed, just the lighting in the chunk needs to be removed and then re-calculated. Hence ```/removelight``` > ```/fixlighting```. I just propose that ```/fixlighting``` becomes recursive and determines the type of lighting problem. i.e. fixing light bleed from no source and black spots, not only the ladder.

**Comment by dordsor21** [comment]
I did not know of the existence of this removelight command. Thanks a lot mibby!

**Comment by boy0001** [comment]
Should be fixed
