### ISSUE TITLE
Block face not rotating with rotation operations in FAWE.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#220]
FastAsync dev 185
WorldEdit dev 3596
PaperSpigot (MC 1.10) dev 830

**Wood blocks facing left to right, bone blocks, and free standing signs do not correctly rotate when rotating and pasting.**

Left is original, right is rotated. Typed //copy, //rotate 90, then //paste. Normal WE and WE with AWE Premium works fine.

![link](http://i.imgur.com/6SYeD9t.jpg)
![link2](http://i.imgur.com/vusTxsS.jpg)
![link3](http://i.imgur.com/2RSFw4o.jpg)
![link4](http://i.imgur.com/JmDUEbC.jpg)

**Comment by boy0001** [comment]
Not a FAWE bug but rather your WorldEdit jar, please test again with and without FAWE installed.

You can register blocks in `plugins/FastAsyncWorldEdit/extrablocks.json`. For more info on the format see: https://github.com/sk89q/WorldEdit/blob/master/worldedit-core/src/main/resources/com/sk89q/worldedit/world/registry/blocks.json
