### ISSUE TITLE
Possible to not hook into WorldGuard when region-restrictions: false is set?

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#225]
Would it be possible to _not_ hook into WG when you aren't trying to restrict FAWE to regions?

**Comment by boy0001** [comment]
It doesn't really cause any issues. One reason to still hook, is that the config can be reloaded / value changed.

**Comment by boy0001** [comment]
Hooking into WG / others has no impact on performance (besides a couple milliseconds during startup), and any failure of the hook does not break the plugin. Closing this.
