### ISSUE TITLE
Question - Keep chunks loaded feature.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#230]
RE: https://github.com/boy0001/FastAsyncWorldedit/commit/5c0ae62b17f277f1e704cacfcadf92e1ce334c22

Is the 'keep chunks loaded' feature only for chunks forced to load when pasting in a schematic or worldedit operation outside of your view distance? As Paper has a native feature to keep chunks loaded for x amount of seconds - might conflict. Especially if you set the chunk unload time higher or completely disable it in Paper.

If it is for all chunk unload activity regardless of WE/Voxel (which I kind of disagree with, stretching outside the main reach of the plugin and its primary purpose if you ask me), you might want to have it configurable.

**Comment by boy0001** [comment]
It's just for chunks loaded by the plugin. There are otherwise performance issues when working with unloaded chunks.
