### ISSUE TITLE
WorldEdit's fail if player is outside allowed region

### ISSUE THREAD

**Issue by RoboMWM** [boy0001/FastAsyncWorldedit#24]
On a server using GriefPrevention claims, if player is outside a GP claim when executing a WorldEdit command, a red message stating "Your WorldEdit may have been extended outside your allowed region"

**Comment by EvilOlaf** [comment]
I had the same message, but when using WG. Though I think this is not a bug, more a feature, because it seems like that when you have access to WE you have to 1. inside a region and 2. have member or owner rights within this region. `__global__` does not count.

**Comment by RoboMWM** [comment]
It may cause issues for things like //undo and //redo, since it thinks the command executed successfully, you can't just run those again...

**Comment by boy0001** [comment]
I can probably have it remember the last region.
