### ISSUE TITLE
Anvil API - Feedback wanted

### ISSUE THREAD

**Issue by boy0001** [boy0001/FastAsyncWorldedit#240]
I'm going to be working on a low level framework for manipulating the world files directly. Here's my thoughts so far:
### MCAChunk(NBTInputStream is)

Extends FaweChunk and implements all methods
delete():
- Marks this MCAChunk for deletion

Raw values:

> ids: byte[16][4096]
> data: byte[16][2048]
> skylight: byte[16][2048]
> blocklight: byte[16][2048]
> entities: `Map<BytePair, CompoundTag>`
> tiles: `List<CompoundTag>`
> biomes: byte[256]
> compressedSize: int
> modified: boolean
> deleted: boolean
### MCAFile(File mca): Represents an MCAFile

getChunks():
- Returns a `List<Integer>` of each chunks offsetId

forEachChunk(`RunnableVal<Integer, Integer, Integer>` onEach):
- Loops over each saved chunk
- onEach: cx, cz, offsetId

readChunk(int cx, int cz):
readChunk(int offsetId):
- Reads from disk and returns the chunk

forEachCachedChunk(`RunnableVal<MCAChunk>` onEach):
- Loops over each cached chunk

getCachedChunks():
- Returns a `List<MCAChunk>`

getCachedChunk(int cx, int cz):
- Returns the cached chunk, or null

getChunk(int cx, int cz):
- Returns either a cached copy, decompresses it from disk, or null

streamChunk(int cx, int cz, `RunnableVal<NBTStreamer>` addReaders):
streamChunk(int offsetId, `RunnableVal<NBTStreamer>` addReaders):
- Read parts of the chunk you want (faster, but readonly)

uncache(int cx, int cz): 
- Removes a chunk from cache

flush():
- Write all modified chunks to disk
- Empties the cache
# MCAQueue(FaweQueue parent)

FaweQueue implementation using a map of MCAFile
- This queue can then be used for an EditSession, or directly

More info:
- http://wiki.vg/Region_Files
- http://minecraft.gamepedia.com/Anvil_file_format

**Comment by cyberpwnn** [comment]
Is this already implemented into fawe api? Ive seen it here https://github.com/boy0001/FastAsyncWorldedit/wiki/Anvil-API, and it is in the maven artifact http://ci.athion.net/job/FastAsyncWorldEdit/ws/mvn/com/boydti/fawe-api/16.08.28-f2d54e6-252/, yet upon loading it up on a test server with the latest copy of FAWE and World edit bukkit, i get class not found exceptions. I have never had this issue with AsyncWorld or anything else within fawe. Am i missing something?

**Comment by boy0001** [comment]
@cyberpwnn 
No, it's been added, and it should be working, I just forgot to close this commit.

Want to attach the error you are getting?

**Comment by cyberpwnn** [comment]
Im getting this exception when using MCAWorld
http://paste.phantomapi.org/zifahoxeto.js

I am then initializing it here

``` java
public static MCAQueue getMCAQueue(World world)
{
	return new MCAWorld(world.getName(), new File(world.getWorldFolder(), "region"), true).getQueue();
}

//Used as
W.getMCAQueue(Bukkit.getWorld("world")
```

**Comment by boy0001** [comment]
Can't replicate.
