### ISSUE TITLE
MCEdit schems are messed up

### ISSUE THREAD

**Issue by L4BORG** [boy0001/FastAsyncWorldedit#245]
Glass/Clay color is not right on //paste, stairs rotation is wrong, etc... FAWE schems are ok tho.

Config: http://pastebin.com/QRTdMWv6

**Comment by boy0001** [comment]
Please attach the schematic

**Comment by boy0001** [comment]
I fixed some issues with schematics in the last commit, please test. Create a new ticket if the problem persists.
