### ISSUE TITLE
fixlighting makes light sources dead when behind light-transparent blocks

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#247]
//removelighting then //fixlighting causes "dead" light sources when they are behind blocks that allow light to pass through

![2016-08-19_14 48 29](https://cloud.githubusercontent.com/assets/10080017/17811737/00eb569e-661c-11e6-8b3e-874972cc4ae4.png)
![2016-08-19_14 46 28](https://cloud.githubusercontent.com/assets/10080017/17811685/bfd98018-661b-11e6-808e-7e960efdba9a.png)
![2016-08-19_14 41 45](https://cloud.githubusercontent.com/assets/10080017/17811686/c00174ce-661b-11e6-9d4e-f73752941968.png)

**Comment by boy0001** [comment]
Fixed

**Comment by dordsor21** [comment]
Not fixed, error still occurs

**Comment by boy0001** [comment]
Now fixed
