### ISSUE TITLE
Can't copy large area

### ISSUE THREAD

**Issue by DerEnderKeks** [boy0001/FastAsyncWorldedit#25]
If I try to copy a large Area (150x150x256) this happens: http://hastebin.com/henadiseki
Without FAWE it works fine.

I'm using Spigot 1.9.2, Worldedit 6.1.1-SNAPSHOT #3463 and FAWE 3.3.8

**Comment by boy0001** [comment]
That's a compile issue with FAWE, try updating the plugin:
ci.athion.net/job/FastAsyncWorldEdit/
