### ISSUE TITLE
Stairs not flipped up/down properly

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#250]
When executing '//copy'  '//flip up|down'  '//paste' the stair does not change orientation

![image](https://cloud.githubusercontent.com/assets/10080017/17830460/7fc22342-66c3-11e6-9e22-6f52073ea87c.png)

using latest WE and FAWE v.216

**Comment by boy0001** [comment]
WorldEdit bug, not FAWE

**Comment by boy0001** [comment]
Fixed in FAWE. I suggest you also report this issue to the worldedit issue tracker.
