### ISSUE TITLE
Schematic pasting issues

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#253]
#245 #200 When pasting schematics following errors are displayed in console (sometimes)

http://hastebin.com/axujuhiyan.avrasm with most blocks' datavalues set to 0 (x:0)

If the schematic is loaded a second time no errors are seen and no blocks are reset to x:0

**Comment by boy0001** [comment]
Please attach the schematic

**Comment by dordsor21** [comment]
http://www.mediafire.com/download/r8xp7zjzryp7bm5/schem263.schematic

**Comment by boy0001** [comment]
Thanks. Seems to be an issue with clipboard on disk. For a temporary fix, disable it on disk and use compression to reduce memory usage.
