### ISSUE TITLE
Anvil API issues

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#254]
Decided to try enabling the anvil API and it seemed to work well (I did a big //set 1). However some errors I got in console were:

http://hastebin.com/giyaqitudi.avrasm
The upper occurred for each ungenerated region file, and given the method of completing the worldedit that was probably to be expected. The middle lot and bottom one all occurred at the end.

Undo does not work.

**Comment by boy0001** [comment]
Disabling combined stages will fix undo.

Middle and bottom are from the same error, might be caused by the chunk being in use. I'll have to test further

Note: When finished, anvil operations will be used from console, and perform on unloaded worlds.
