### ISSUE TITLE
Chunk Errors? Perhaps FAWE?

### ISSUE THREAD

**Issue by Fluxty** [boy0001/FastAsyncWorldedit#255]
I feel like there may be some connection between the latest update using NMS rather than refreshing the chunk and new chunk errors. Chunks become invisible and it's impossible to walk on them at random. I'm not 100% sure this is FAWE at fault, but we are using FAWE to handle our explosive OP Prison enchant in an efficient manner.

It's really only a minor annoyance as exploding a block outside of the chunk error sends an update and fixes the chunk error anyways. Just kind of strange. Definitely prefer this over the old method though! 

Thanks :+1:

**Comment by Fluxty** [comment]
It seems there's also an issue where nearby signs are going blank until someone unloads the chunk and comes back.

**Comment by Fluxty** [comment]
Another update, we are using viaversion on a Paper Spigot 1.8.8 server and it seems the sign issue only happens for 1.10 players using explosive (hooking to FAWE API)

**Comment by N0tMyFaultOG** [comment]
Update Fawe
If the issue occurs still, reopen the ticket
