### ISSUE TITLE
Occasional VS weirdness

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#256]
![2016-08-21_19 29 47](https://cloud.githubusercontent.com/assets/10080017/17839098/be1c4b3c-67d5-11e6-9a3c-9cddfd9675c7.png)

caused when using /b e lift

**Comment by dordsor21** [comment]
happens rarely, similar to the dead chunk issue ( #132 )

**Comment by dordsor21** [comment]
Apparently it still happens, very rarely I think

**Comment by boy0001** [comment]
Even with the latest update which fixes the issue with betterbrushes?

**Comment by dordsor21** [comment]
Not sure. I'm putting that on the network now

**Comment by dordsor21** [comment]
probably fixed. Spammed vs for a while and didn't see it
