### ISSUE TITLE
Schematics make chests invisible and miss items 

### ISSUE THREAD

**Issue by SirNickParks** [boy0001/FastAsyncWorldedit#258]
### Using PaperSpigot fixes the issue: https://ci.destroystokyo.com/job/PaperSpigot/

(edit by @boy0001)

---

**Debug paste link**: https://goo.gl/KHH3kS

**Description of the problem:**
So i'm pasting a schematic of a Minigame map from the location 0, 0, 0. Now while this works fine I've had an issue arise. The very first time the schematic is pasted the chests contain their items and work fine. Now when the game ends and that same code is ran again, the chests sometimes appear invisible or missing items (sometimes both).

I'm going to try some different methods of possibly getting it to work but for now that's the best i got that produces the error. 

**How to replicate**:
The schematic was created using MCEdit.
Paste a schematic, play around in it for a little, re-paste it in the same location.

Code being ran: https://goo.gl/Pf4Bk9

I'm still figuring out the best uses/any uses of using sync/async so excuse the call in there if it's incorrect i'm still learning about it. (Also excuse the NMSRelighter i'm also trying to figure that out as I learn more about the schematic format)

Make sure you've completed the following steps:
- [X] Include `/fawe debugpaste` (This was just added a couple hours ago)
- [X] Made sure there aren't duplicates of this report
- [X] Made sure you're using an updated version of FAWE
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
Do you know if the problem occurs if you paste it using commands ingame and with fastmode enabled `//fast`?
Can you attach the schematic?

Not related to the problem but:
 - Pasting already calls the flushQueue method and the NMSRelighter
 - Run the code async with `TaskManager.IMP.async(...)`

**Comment by SirNickParks** [comment]
Sent you an email with the schematic. I'll try the //fast mode in about an hour.

On a side note I was trying to fix lightning because the blocks well..aren't lit & I was seeing how I can fix that. Just a note :)

**Comment by SirNickParks** [comment]
Taken from IRC:
<SirNickParks> Paste schematic -> items all there -> replace from the same spot (overwritting current blocks) -> items are sometimes there? sometimes chests are only half full, sometimes they're invisible, etc.

Entire chat about it:
https://gist.github.com/SirNickParks/d37d757b2ab3cc291f59162d9ab8446b

**Comment by SirNickParks** [comment]
Appears to be a spigot issue. Using paper actually fixes this.

**Comment by boy0001** [comment]
Lighting issues have been fixed in the latest build.
