### ISSUE TITLE
error - slimefun plugin

### ISSUE THREAD

**Issue by mat41997** [boy0001/FastAsyncWorldedit#260]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://pastebin.com/w9VdCPjw

**Description of the problem:**
error in console

**How to replicate**:
create a 1.10 server, instal latest worldedit plugin, latest fawe plugin, latest slimefun plugin
https://dev.bukkit.org/bukkit-plugins/slimefun/files/121-slimefun-v4-0-13/

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/fawe debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] Made sure you're using an updated version of FAWE
- [] Made sure the bug/error isn't caused by any other plugin

timings
https://timings.aikar.co/v2/?id=25cf5a38a1f545c6b1ef43aed1dcacac

**Comment by boy0001** [comment]
- To allow this plugin add it to the FAWE `allowed-plugins` list:
```YML
extent:
  # Don't bug console when these plugins slow down WorldEdit operations
  allowed-plugins:
  - SlimeFun
  # Disable the messages completely
  debug: true
```
 - To hide this message set `debug` to false in the config.yml
```YML
extent:
  # Don't bug console when these plugins slow down WorldEdit operations
  allowed-plugins: []
  # Disable the messages completely
  debug: false
```

**Comment by mat41997** [comment]
thx ^^
