### ISSUE TITLE
You can copy other people's plotsquared plots

### ISSUE THREAD

**Issue by C1audi0** [boy0001/FastAsyncWorldedit#262]
**Debug paste link**: http://hastebin.com/hozilewebo

**Description of the problem:** Players can //pos1 and //pos2 on other players plots and copy them.

**How to replicate**:  //pos1 and //pos2 and //copy on someone else's plotsquared plugin.

Make sure you've completed the following steps (put an X between of brackets):
- [-] Include `/fawe debugpaste` (It just keeps reloading config)
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of FAWE
- [x] Made sure the bug/error isn't caused by any other plugin (We had the other AsyncWorldEdit before and this wasn't possible)

**Comment by boy0001** [comment]
Fixed.


> (It just keeps reloading config)

Means you are using an old version of FAWE.
