### ISSUE TITLE
Worldedit incompatibility

### ISSUE THREAD

**Issue by TheExceed** [boy0001/FastAsyncWorldedit#264]
# Bug report template (Follow this template unless you are making a feature request.)

**Debug paste link**:
http://hastebin.com/ugiyuvigir - debug
http://hastebin.com/etobaqafid.avrasm
http://hastebin.com/nicageneca.avrasm

**Description of the problem:**
Does not work with newest worldedit

**How to replicate**:
FastAsyncWorldEdit version 16.08.28-de9138b-247
WorldEdit version 6.1.3;7a097ca

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/fawe debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of FAWE
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
You aren't on the newest WorldEdit.
http://builds.enginehub.org/job/worldedit/last-successful?branch=master

**Comment by TheExceed** [comment]
http://hastebin.com/kurayezifo.avrasm
FastAsyncWorldEdit version 16.08.28-de9138b-247
WorldEdit version 6.1.4-SNAPSHOT;3621-2e10fe8

Still same issue after updating and using //set

**Comment by boy0001** [comment]
Can you post a new debugpaste then?

**Comment by TheExceed** [comment]
http://hastebin.com/cokivelita

**Comment by boy0001** [comment]
FAWE definitely works with that version of WorldEdit, so it's probably something else. Can you try temporarily starting your server with just FAWE and WorldEdit to see if the problem persists then?

**Comment by TheExceed** [comment]
So after some extensive testing... it is due to another plugin but I cannot find which. It seems to be multiple plugins causing the issue. Even though it is not a direct issue with your plugin, any guidance would be appreciated. 

Trials:
1) Unloading each plugin 1 by 1.
2) Loading each plugin 1 by 1.
3) Loading plugins by groups by alphabetical order, with this, it occurred one we hit P-R, so we removed all plugins from A-O except worldedit and fawe of course. And we had no issue. So we uploaded A and B and no issue then loaded C plugins and had an issue, so we then removed A and B so we only had C and P-R and fawe and worldedit. Got no problem. Then put the A plugins on, no problem, put the B plugins on no problem. Removed A plugins no problem. So even though A-R was a problem before, at this point it was not a problem.....

I have no idea what the issue is or why its happen.


http://hastebin.com/nuxemijohi.coffee - Plugins w/ versions

**Comment by boy0001** [comment]
You aren't using plugman to load the plugins, is that correct?

**Comment by TheExceed** [comment]
We were in Trial 1 and 2 but in Trial 3 we were adding the groupings and restarting the entire server.

**Comment by N0tMyFaultOG** [comment]
Update Fawe
If the issue occurs still, reopen the ticket
