### ISSUE TITLE
Slow super-pickaxe

### ISSUE THREAD

**Issue by Sitmobedaf** [boy0001/FastAsyncWorldedit#268]
https://youtu.be/9kSyjsUoUWc

**Comment by boy0001** [comment]
Video is private.

**Comment by boy0001** [comment]
Can't replciate. Can you please attach a `/fawe debugpaste`?

**Comment by Sitmobedaf** [comment]
https://youtu.be/OsJY9w34k_s

**Comment by Sitmobedaf** [comment]
Console:
http://pastebin.com/gWpXTUhD

**Comment by boy0001** [comment]
I need a `/fawe debugpaste`

**Comment by Sitmobedaf** [comment]
http://hastebin.com/iqopuyotuc

**Comment by dordsor21** [comment]
Probably no longer an issue after similar superpickaxe issues have been fixed
