### ISSUE TITLE
Feature Request: Mirroring

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#270]
Add block placement mirroring similar to https://dev.bukkit.org/bukkit-plugins/mirrormaster/ however with an option for 3x90 degree rotation so both

![2016-08-29_22 50 49](https://cloud.githubusercontent.com/assets/10080017/18068823/3b4053b8-6e3b-11e6-9a15-803a22ea6cf6.png)

and

![2016-08-29_22 50 56](https://cloud.githubusercontent.com/assets/10080017/18068827/407201ec-6e3b-11e6-96c5-379b8f7479c5.png)

are possible

**Comment by boy0001** [comment]
Using both `//flip` and `//deform` with a polygonal region (//sel poly) should work?

**Comment by dordsor21** [comment]
the point of it is to be able to do it in real time. We've currently got the plugin linked installed but it's not perfect, and I'm sure you'd be able to do better, but if it's too much hassle don't worry about it.
