### ISSUE TITLE
ASyncWorld causing chunk saving issues

### ISSUE THREAD

**Issue by SirNickParks** [boy0001/FastAsyncWorldedit#271]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**: http://hastebin.com/icoyofufix

**Description of the problem:** Loading a world using [this code](https://goo.gl/78Igud) causes [this error](https://goo.gl/RCWZnb).

**How to replicate**:
Load a world using ASyncWorld. That error is spammed. <3

- [X] Include `/fawe debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an updated version of FAWE
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
What does `WorldUtil.copyWorld(this.GameID, this.map);` do?

If it copies the uid.dat or the session.lock file, that may be the issue.

**Comment by SirNickParks** [comment]
Removed the uid.dat and session.lock files. However now i'm getting this error:
https://gist.github.com/SirNickParks/e54084cebe22dab2b9ab7094a024d327

Line 116 is:
`AsyncWorld asyncWorld = AsyncWorld.create(new WorldCreator("Invasion-" + GameID));`

**Comment by boy0001** [comment]
Couldn't replicate the error, but I made several changes which may fix it for you.

**Comment by SirNickParks** [comment]
Hm~ seems to have fixed it. Thank you <3
