### ISSUE TITLE
FAWE incompatible with Orebfuscator

### ISSUE THREAD

**Issue by MarkehMe** [boy0001/FastAsyncWorldedit#273]
**Debug paste link**:
* http://hastebin.com/enogeqokev (the latest log in this is irrelevant, see below) 
* http://pastebin.com/nKZ7Vc04

**Description of the problem:**
Using WorldEdit, FAWE and Orebfuscator and the //regen command causes the blocks to become random ores/gravel etc - or huge portions of coal (for eg).

**How to replicate**:

1. Use ```//pos1``` to select your location
2. Move about 2-3 chunks diagonally and use //pos2 to create a square
3. Use ```//expand vert```
4. Use ```//regen```

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/fawe debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of FAWE
- [ ] <s>Made sure the bug/error isn't caused by any other plugin</s> [see this ticket](https://github.com/lishid/Orebfuscator/issues/124)

---

This ticket is also open in [Orebfuscator](https://github.com/lishid/Orebfuscator/issues/124) and has been replicated - this issue does not occur with just WorldEdit.

**Comment by GoadingGoat** [comment]
If you you reload the chunks it's fine.  This happens to me as well. I assume it's Orebfuscator throwing a shitty because the bukkit api wasn't used to edit the map.

**Comment by RoboMWM** [comment]
I thought he said he relogged, but I'm re-reading his orebfuscator ticket and I now realize that he never stated anything like that. So, @MarkehMe , is the issue still present if you reconnect?

**Comment by MarkehMe** [comment]
If you reconnect it reverts back to its normal state.

**Comment by RoboMWM** [comment]
Alright, then this really isn't an issue - it's just an unintended visual effect client-side. FAWE does not use bukkit API methods when modifying the world (iirc, triggering block-break events or the like), and as such, Orebfuscator does not know whether to send you updates near the blocks you've removed.

**Comment by RoboMWM** [comment]
Now, FAWE could tell Orebfuscator to re-send obfuscated chunks if so desired. I personally wouldn't want the server to do more work than necessary, so if it's added, I'd probably also want an option to disable that.

**Comment by MarkehMe** [comment]
I tried this in the nether too, in mid-air.. it causes it all to turn into a huge slab of coal ore.

**Comment by boy0001** [comment]
Fixed according to:
https://github.com/lishid/Orebfuscator/issues/124
[orebfuscator-4.1.6-SNAPSHOT.zip](https://github.com/boy0001/FastAsyncWorldedit/files/451141/orebfuscator-4.1.6-SNAPSHOT.zip)

**Comment by MarkehMe** [comment]
Confirmed, the issue was fixed in Orebfuscator.
