### ISSUE TITLE
Enhance tick limiter

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#274]
Basically I like the feature to limit physics and spawns per tick to prevent crashes related to such reasons.
Though which a rising number of players you also have a rising number of physics that could happen within a tick. In my case a while ago I rarely started getting the same issue that redstone (or in my case furnaces) did not perform as expected anymore and had to increase the number of physics again to `100000`.

Anyway. As said I like the feature and I would not like it to kind a disable it by setting the values very high.

My suggestion is to add some kind a debug information or logging got get an idea about the real current/average number of physics to determ which value would fit for individual servers including a buffer (by multiplying times two or something like that). 

In practical for current physics a simple command that shows the average of the last - dunno - 20 ticks.
And for logging a simple text file that will store these values about once a minute or once every ten minutes (configurable by user?). Depending on your plugins and server concept this way you can determ how much the number of physics per tick increase with the number of players.

As always thanks for reading.

**Comment by boy0001** [comment]
What do you mean by the buffer?

> In practical for current physics a simple command that shows the average of the last - dunno - 20 ticks.

Doing a timings would probably show this.

**Comment by EvilOlaf** [comment]
For example your server has a peak of about 40000 physics per tick you do not want to set the max to exact this value. You want to set it to 60000 or 80000 to have a reserve in case it is needed.  
If you run into trouble and get complains about faulty redstone you know there must be something wrong when at a moment's notice the last known high peak increased by 50 or 100%.

**Comment by boy0001** [comment]
Note: Tick limiter has since been improved to better detect abuse and ignore valid use of redstone etc.
