### ISSUE TITLE
Lighting Problems

### ISSUE THREAD

**Issue by Stevecurious** [boy0001/FastAsyncWorldedit#275]
This might be a duplicate for #233 which was closed, but I'm currently experiencing merely the same. 

Whenever I build, either with "hand" or with WorldEdit and somehow build ceilings or enclosed rooms, there is no darkness, it remains light as day in those/beneath those. Also, when a light source is removed, the light remains nonetheless. 
When I then move my buildings (especially floating frames for planning), there remain shadows were the actual thing was. 
So it seems that somehow the way of normal lighting is completely turned off and I'm supposed to fix everything with the command?

The config is set to
`async: true`
`mode: 1`
We use Build 257, Commit 523f627.

**Comment by boy0001** [comment]
Try setting lighting mode to 2

**Comment by Stevecurious** [comment]
Well ... so first it worked and seemed to be fine, the light computing was okay, but when I reconnected (and thus forced the packets to be sent again) it was light as day again :/
![2016-09-07_22 15 30](https://cloud.githubusercontent.com/assets/21973456/18327045/db355350-7548-11e6-8a3d-1db089595778.png)

**Comment by Stevecurious** [comment]
So, we found out what the current problem seems to be: (and now I'm referring to the default config)
  When you work with FAWE and delete structures, it doesn't really relight them and causes "invisible" lighting bugs at the place of the former structures. 
  When you then build something new at these spots, the corrupted light will cause "real" lighting bugs and creates dark shadows. 
  We found that out with MCEdit, as we loaded the world into there and anywhere we used FAWE, the map rendered completely black, indicating lighting errors. Especially a former draft for a new townhall was visible in its exact former shape, just in black, and when we started to build a new facade there, it touched the "old" shadow at one point, and there you then had the lighting bug. 
  The one and only way we were able to fix this problem was to relight all chunks with MCEdit.
  Our idea then was to "deactivate" the FAWE relighting by setting `async: false` and `mode: 0`, which then caused WorldEdit and Minecraft to just stop computing light completely.
  Our consequence then was to stop using FAWE, as we simply can't stand with those lighting issues, as we use WorldEdit for rather big buildings.

**Comment by boy0001** [comment]
There's `//removelighting`

**Comment by Stevecurious** [comment]
For sure, I'm aware of that ... but it is not comfortable to have to fix lighting bugs "by hand" whenever you build something.

**Comment by TrademarkTM** [comment]
> There's //removelighting and //fixlighting

No problem to use //fixlighting, but it takes longer to fix an entire build than to make a 3000x3000 sphere. Not only lighting bugs, sometimes the chunks doesn't load (invisible blocks), causing many problems...

My friends build professionally, so they can't have these bugs.
Here's another example: http://prntscr.com/cj1drm

**Comment by essem2** [comment]
same problem

**Comment by Noiknez** [comment]
Same problem also

**Comment by boy0001** [comment]
Should be fixed
