### ISSUE TITLE
WorldEdit incompatibility

### ISSUE THREAD

**Issue by Galaxias** [boy0001/FastAsyncWorldedit#276]
http://hastebin.com/ayitejobeq
http://hastebin.com/fezaqadiwo.avrasm

WorldEdit 6.1.3
tested with FastAsyncWorldEdit v16.09.03-dba271b-266 
and FastAsyncWorldEdit v3.5.0-00c685c

Can't do //copy with WorldEdit by now for example.

Minecraft Spigot 1.8.8

**Comment by boy0001** [comment]
That error is thrown by `me.tade.tntrun`
