### ISSUE TITLE
One layer of the world is replaced with sand

### ISSUE THREAD

**Issue by iamceph** [boy0001/FastAsyncWorldedit#277]
**Debug paste link**: http://hastebin.com/natosaloci

**Description of the problem:**
One layer in the world is replaced with sand. Every block in one layer is just replaced with sand, see screenshots.
![2016-09-04_11 52 18](https://cloud.githubusercontent.com/assets/4377405/18230290/b7cdfb2e-7296-11e6-8f37-ab8dea6f2d0b.png)
![2016-09-04_11 52 21](https://cloud.githubusercontent.com/assets/4377405/18230288/b7ca09ba-7296-11e6-9cc0-20f7e8d8bece.png)
![2016-09-04_11 52 57](https://cloud.githubusercontent.com/assets/4377405/18230289/b7cc41bc-7296-11e6-8ecf-53626c75bbcb.png)
This is how it looks before that sand problem happened
![14248099_1669901200004658_1254228149_o](https://cloud.githubusercontent.com/assets/4377405/18230295/c4f07c82-7296-11e6-887e-4828738df493.jpg)
And this is after
![2016-09-04_11 52 26](https://cloud.githubusercontent.com/assets/4377405/18230380/2c2481ee-7299-11e6-80a3-0aa7faa345f4.png)

**How to replicate**:
Words from my builders:
We've just worked on the map as always, then my friend created some //cyl sand circles. Then he thought that those circles are too big, so he deleted it and created new ones (smaller). After this, he just saw that there's some sand lines. He ignored that, but after while, those sand lines started growing. After a while, it's just replaced one layer of map.

(I can't reproduce it by myself, but this must be caused by FAWE, because we never had this problem. I setuped FAWE in last days and it's happened today so..)

**Comment by boy0001** [comment]
I can't fix unless it can be reproduced. Are you sure you didn't have `pos1` or `pos2` accidentally on the other side of the map when doing a replace?

**Comment by iamceph** [comment]
I tried to reproduce it, but without any chance. And I'm 100% sure that my builders didn't replace it. I checked logs too and there is no replace with sand anyway.

**Comment by iamceph** [comment]
Can't really reproduce it, will re-open this issue if it will appear again. (updated fawe to latest version too)
