### ISSUE TITLE
Question about queue actions

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#287]
I am actually unsure but is it possible to queue multiple WorldEdit commands and let them finish one by each other? At the moment I get the `WORLDEDIT_COMMAND_LIMIT` notice when an action has not completed yet.

**Comment by boy0001** [comment]
There's currently a limit of 1 per player. Multiple players can queue multiple WorldEdits, they are performed in the order they are added. 

It's currently not possible to have a single player queue multiple edits, would adding this functionality be desirable?

**Comment by EvilOlaf** [comment]
At least for me it would, yes.

**Comment by EvilOlaf** [comment]
Awesome! I'll give it a try as soon as possible. Thank you
