### ISSUE TITLE
PlotSquared not recognised

### ISSUE THREAD

**Issue by Jabelpeeps** [boy0001/FastAsyncWorldedit#29]
Hi,

I just install this plugin, and on first boot I have noticed the following message on the console:-

[FastAsyncWorldEdit] Plugin 'PlotMe' not found. PlotMe features disabled.

As PlotMe is no-longer updated, our server (along with many others) has moved to alternatives such as   [PlotSquared](https://www.spigotmc.org/resources/plotsquared.1177/)

It would be great if you could support this plot plugin as well.

Many thanks

Jabel

**Comment by RoboMWM** [comment]
Um it does support PlotSquared. It's just indicating that PlotMe integration is disabled. Just like it tells me that PreciousStones, Towny, Factions, etc. is disabled for me.

**Comment by boy0001** [comment]
I'm also the developer of PlotSquared and can confirm it works with it. You will need to give users the permission nodes: `fawe.plotsquared` and `fawe.plotsquared.member` (if you want members to also use WorldEdit)

**Comment by Jabelpeeps** [comment]
ok, thanks, good to hear it is supported already.

Maybe a change to the 'error' message is needed?  (or an additional message to say that PS has been found?)

I'm not sure on the difference with the two permission nodes you have listed.  By 'members' do you mean players other than the owner who have been added to plots with /plot and /plot trust ?

**Comment by boy0001** [comment]
The member group. Trusted/Owners have access to WorldEdit with just `fawe.plotsquared`
Members are added with `/plot add <player>`
Trusted with `/plot trust <player>`
