### ISSUE TITLE
dividing by 0

### ISSUE THREAD

**Issue by PhanaticD** [boy0001/FastAsyncWorldedit#290]
with build 282 for bukkit 1.10 noticed this in console quite a bit: http://pastebin.com/raw/H4LAhprN

**Comment by boy0001** [comment]
*Should be fixed now with build 285+

**Comment by dordsor21** [comment]
Happens randomly and causes server to stop responding.

This is as of latest build (286) [http://hastebin.com/igodikajij.md](http://hastebin.com/igodikajij.md) I timed out between the error and the //set 1 (30s no response)

**Comment by boy0001** [comment]
@dordsor21 
Do you have the thread dump for when the server stops responding?

**Comment by dordsor21** [comment]
The server spits out this http://hastebin.com/xerayosizu for a long time. There may be a thread dump somewhere, I'll have a search, though chances are the servers were killed before one was output.

**Comment by dordsor21** [comment]
@boy0001 http://hastebin.com/eloquqawiy.md it was then followed by more of the "java.lang.ArithmeticException: / by zero" errors

**Comment by boy0001** [comment]
@dordsor21 
Couldn't replicate the error, but I made some changes which may help.

**Comment by dordsor21** [comment]
@boy0001 still occurs. Config: http://hastebin.com/igivuhewiy.coffeescript

Need to complete a few WEs, sometimes happens on first WE, sometimes happens after a number of WEs

**Comment by boy0001** [comment]
@dordsor21 
Can you replicate?

**Comment by dordsor21** [comment]
@boy0001 possibly fixed in those changes you made. Chance that the new version was not propagated fully. Will leave newest version running and see.
