### ISSUE TITLE
AsyncWorld Block state: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Joi3432** [boy0001/FastAsyncWorldedit#291]
When I'm get the BlockState of an Block from an AsyncWorld I'm im get this errror:
http://hastebin.com/evidoraduk.md

Code:
http://hastebin.com/hamugabajo.php

Thanks in adavance!

**Comment by boy0001** [comment]
Check the y value.

**Comment by Joi3432** [comment]
Why? Worked fine with the normal World.

**Comment by boy0001** [comment]
Okay, don't check your inputs, and feel free to wait until I have some free time to look into it.

**Comment by Joi3432** [comment]
Sorry, but what could be wrong with the inputs?

**Comment by boy0001** [comment]
The y value could be negative, or above 255.

**Comment by boy0001** [comment]
Has been fixed ages ago.
