### ISSUE TITLE
Pasting Schematics With the API causes server crash:

### ISSUE THREAD

**Issue by Rexcantor** [boy0001/FastAsyncWorldedit#292]
[Here](http://pastebin.com/V1ZkkQHg) is the crash report.

When this happens:
`public class GameMap {
		private final String name;
		private final Schematic map;

		private GameMap(String name, Schematic map) {
			this.name = name;
			this.map = map;
		}

		public Schematic getMap() {
			return map;
		}

		public String getName() {
			return name;
		}

		public EditSession paste(Location loc) {
			return map.paste(new BukkitWorld(loc.getWorld()),
					new Vector(loc.getBlockX(), loc.getBlockY(), loc.getBlockZ()), false, true, (Transform) null);
		}

	}`
This happens when I execute the method "paste";

Code source: https://github.com/boy0001/FastAsyncWorldedit/wiki/Pasting-a-schematic

Any ideas why this happens?

**Comment by boy0001** [comment]
Try doing it async instead of on the main thread.

Use the bukkit scheduler or something to run code async.
