### ISSUE TITLE
Undo and Redo don't log changes with BlocksHub

### ISSUE THREAD

**Issue by Maxetto** [boy0001/FastAsyncWorldedit#296]
**Description of the problem:**
Undo and Redo don't log any changes done by WorldEdit, other actions does (Such as set, paste, sphere, ecc)

**How to replicate**:
1- Select an area and fill it with something
2- Check with your Logging plugin (Mine is CoreProtect) if everything was logged correctly
3- Yes, proceed.
4- Do //undo
5- Check again, you should expect "Player removed Block" but instead you don't see anything.

**Big list of versions**:
Spigot 1.8.8 (git-Spigot-21fe707-e1ebe52)
FAWE 16.09.05-56384eb-274
WorldEdit 6.1.5-SNAPSHOT;3623-34c31dc
CoreProtect 2.12.0
BlocksHub 2

**Comment by boy0001** [comment]
Technically the data is already logged, it's just been rolled back (if undo has been used).

**Comment by Maxetto** [comment]
Yes, but I want that even undos are logged as removed blocks. Otherwise I can't properly rollback plots with WorldEdit.
