### ISSUE TITLE
Chunks not reloading fully

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#299]
After edit:
![2016-09-19_08 01 58](https://cloud.githubusercontent.com/assets/10080017/18624414/71c494c6-7e3f-11e6-9cca-6a47e1743733.png)

(What it should be) after reloading chunks (going away and coming back):
![2016-09-19_08 02 06](https://cloud.githubusercontent.com/assets/10080017/18624415/7355ac12-7e3f-11e6-91d4-a24db0621b51.png)

**Comment by EvilOlaf** [comment]
I also have this frequently but I do not care as I know the result is straight :P

**Comment by dordsor21** [comment]
This can be quite annoying for me/others on the server

**Comment by dordsor21** [comment]
Yeah, this caused "invisible blocks" trouble, thus glitching when trying to go through a //stack, and means after most WE commands people need to forcefully reload chunks which is pretty annoying.

**Comment by dordsor21** [comment]
Seems to occur frequently when right near (no more than a few blocks away) with voxelsnipes.

Also happens to //stack almost every time.

Is quite annoying having to leave and then re-enter the chunks every other edit...

**Comment by dordsor21** [comment]
still seen with VS when close and when using /b line

**Comment by dordsor21** [comment]
Probably fixed a long time ago
