### ISSUE TITLE
Forge integration?

### ISSUE THREAD

**Issue by HeroicKatora** [boy0001/FastAsyncWorldedit#3]
Would it be possible to port this awesomeness of an addition to Forge, too?
We have been working on a mod that makes use of world edit's schematic files but we need to paste areas from schematics into an empty world "on the fly" if they don't exist already and as you know, on standard world edit, this is only feasable for smaller schematics.

**Comment by RoboMWM** [comment]
It appears there is a forge version that's built for this plugin. Not sure if it actually works but if you compile (from my PR's branch) you'll get a "forge" jar.

**Comment by boy0001** [comment]
Have some classes for SpongeForge, should be easy enough trimming out the sponge stuff and just going with a Forge implementation.

**Comment by JBYoshi** [comment]
@boy0001 Would it be possible to keep both the current Sponge version and a Forge version? Because not all Sponge servers use Forge (e.g. SpongeVanilla).

**Comment by boy0001** [comment]
https://forums.spongepowered.org/t/12126
