### ISSUE TITLE
(FAWE) Error flushing parallel pool

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#307]
FastAsyncWorldEdit dev 294
FastAsyncVoxelSniper dev 294
WorldEdit v6.1.5 dev 3623
VoxelSniper v5.171
Paper (Spigot 1.10.2) dev 876

Config.
http://paste.ubuntu.com/23221330/

Noticed this 'error' in the logs. Nothing else following, just the one line.

```
[02:12:27] [Server thread/INFO]: (FAWE) Error flushing parallel pool
```

The flushing error occurred 16 times today thus far as of the last few hours. One player using voxel, one player using worldedit. Some of them occurred after some command use, some occurred randomly after world saves, presumably someone using a WE or VS brush (no commands).

**Comment by boy0001** [comment]
Can probably be ignored, I'll remove the message.
