### ISSUE TITLE
Add support for additional protection plugins

### ISSUE THREAD

**Issue by boy0001** [boy0001/FastAsyncWorldedit#31]
RedProtect
Some forge mods
etc.

**Comment by interlope7** [comment]
Thanks!

**Comment by interlope7** [comment]
Could you add function to WorldEditReigon & VoxelSniperRegion hook with RedProtect plugin  ???

**Comment by boy0001** [comment]
alright

**Comment by EvilOlaf** [comment]
I think GriefPrevention is also a big one for protecting areas.

**Comment by RoboMWM** [comment]
> I think GriefPrevention is also a big one for protecting areas.

GriefPrevention is already supported.

**Comment by interlope7** [comment]
No .. in my opinion. they are totally different.. Please... support RedProtect..

**Comment by RoboMWM** [comment]
@interlope7 I wasn't responding to you.
