### ISSUE TITLE
Deleting history problem?

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#311]
FastAsyncWorldEdit dev 294
FastAsyncVoxelSniper dev 294
WorldEdit v6.1.5 dev 3623
VoxelSniper v5.171
Paper (Spigot 1.10.2) dev 876

Config.
http://paste.ubuntu.com/23221330/

Is there a problem with history being deleted? This occurred shortly after someone used a worldedit region operation. They claimed it was a 13 million block edit as well, if that is relevant. Their history folder is only 6 MB in size, well below the maximum set in the config.

```
[04:29:39] [Craft Scheduler Thread - 247/INFO]: WorldEdit: player (in "world"): /replace gravel stone - Region: (-13912.0, 0.0, 6625.0) - (-13412.0, 255.0, 7125.0)
```

Deletion log.
http://paste.ubuntu.com/23221373/

**Comment by boy0001** [comment]
Do you know if the files were older than 7 days?

**Comment by mibby** [comment]
Nope. They were created today. I enabled disk history yesterday and wiped everything existing from yesterday today when updated since you changed COMBINE_STAGES to true by default. Figured I'd create new history logs in case it affected anything.

**Comment by boy0001** [comment]
The selected region was 64,000,000 blocks in volume. 13,000,000 blocks were replaced (probably unevenly distributed inside the volume). With 9 bytes per block (upper limit), that's 117,000,000 bytes, or 112MB.

This 112MB edit would be deleted after their next action as it exceeds the 50MB limit, dropping them to the apparent 6MB of stored history.

I suggest you increase the limit or compression level.

**Comment by boy0001** [comment]
> Figured I'd create new history logs in case it affected anything.

Combine stages reduces computations and chunk loading by calculating the history when the blocks are being changed, rather than separately. The files produces use the same format.

**Comment by mibby** [comment]
Alright, thanks for the info. :) I guess that edit was the cause and it just deleted its own history afterwards for exceeding the limit. I have gone back to the temporary cache history for now in any case.
