### ISSUE TITLE
What are the permissions for Nukkit?

### ISSUE THREAD

**Issue by jeremy100** [boy0001/FastAsyncWorldedit#312]
What are the permissions for plugins of permissions without op?. Example: Multipass, Madperms...

**Comment by boy0001** [comment]
http://wiki.sk89q.com/wiki/WorldEdit/Permissions
https://github.com/boy0001/FastAsyncWorldedit/wiki/Commands
https://github.com/boy0001/FastAsyncWorldedit/wiki/Permissions

**Comment by jeremy100** [comment]
Hi boy0001! the permission "worldedit.*" it does not work :/

**Comment by boy0001** [comment]
Your permissions plugin might not support it then. Use the exact perms.
