### ISSUE TITLE
//setskylight and //setblocklight don't do anything

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#314]
As title says, using either command gives expected response (lighting updated in # chunks etc) but nothing seems to happen

**Comment by Rexcantor** [comment]
If you have a selection, it will only affect your selection. If you don't, it should affect the near chunks.

**Comment by dordsor21** [comment]
I made a selection...

**Comment by Rexcantor** [comment]
I could set to 0, as you can see on this screen shot.
https://gyazo.com/b0f85338511197b89249ea9c11182033

But I could only do this one time and it disappeared when I reloged.

This may be a bug and should be fixed. Tried both //setskylight, //setblocklight and //setlight
