### ISSUE TITLE
Unable to disable 'delete-on-logout' setting.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#316]
FastAsyncWorldEdit dev 317
FastAsyncVoxelSniper dev 317
WorldEdit v6.1.5 dev 3623
VoxelSniper v5.171
Paper (Spigot 1.10.2) dev 878

Config.
http://paste.ubuntu.com/23231998/

It seems you are unable to disable the ```delete-on-logout``` config setting. Setting it to false and starting the server up reverts it back to true. I assume it has something to do with it being "broken"? I do not use disk history (at this time) and would very much like for history to persist across player relogs. It may not be the preferred thing to do for history, but vanilla worldedit behavior normally allows for it. :) 

I'm also assuming that FAWE does not break the cached (memory) history limit set in the main worldedit config so it isn't keeping every change made by a player in memory, only the last # of changes - but untested by me at this time.

**Comment by Rexcantor** [comment]
Are you changing it with the server running? If so, stop it before changing the config.

**Comment by boy0001** [comment]
> I'm also assuming that FAWE does not break the cached (memory) history limit

Correct. It's just that setting which is broken.

**Comment by mibby** [comment]
@Rexcantor 
> 
Are you changing it with the server running? If so, stop it before changing the config.

No, of course not. Though I don't see why you wouldn't be able to since you _can_ reload the FAWE config with ```/fawe reload```. Either way, probably has to do with it being currently broken.

> Setting it to false and starting the server up reverts it back to true.

**Comment by Rexcantor** [comment]
@mibby Yeah, I was just asking. I didn't test, but changing the config with the server running is one of the most frequent problems about this type of issue. I'll assume @boy0001 will fix that fast as usual.

**Comment by boy0001** [comment]
Changing the config when the server is running is fine.

**Comment by boy0001** [comment]
@mibby 
I took a slightly different approach if that's okay. It should remember the session so long as there's enough free memory.

**Comment by mibby** [comment]
Will the session still take into account the history storage and size limits?

```
    # Maximum size of the player's history in Megabytes:
    #  - History on disk or memory will be deleted
    max-history-mb: 50
```
```
history:
    size: 10
    expiration: 10
```
