### ISSUE TITLE
Lighting issues.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#318]
FastAsyncWorldEdit dev 317
FastAsyncVoxelSniper dev 317
WorldEdit v6.1.5 dev 3623
VoxelSniper v5.171
Paper (Spigot 1.10.2) dev 878

Config.
http://paste.ubuntu.com/23232047/

There seems to be quite a few problems with lighting in FAWE/FAVS when using any operation at all.

---

WorldEdit & Voxel commands / brush operations fully light chunks when using them underground in caves. Some natural underground caverns, it only occurs every second or third command / brush attempt, But in some cave areas and artificially carved out caves, I'm able to get it to occur every single time. (Might be caused by a certain depth level?) It sets skylight (according to F3) when there shouldn't be any sky above due to being underground and fully closed off.

---

`//fixlighting` does not fix lighting properly / all the way.

Fully lit underground cave caused by above listed issue.
![link](http://i.imgur.com/RlHoVvk.jpg)

Typed `//fixlighting` with nothing in my selection, thus fixing 8 chunk radius by default. Left lighting broken / patchy still.
![link2](http://i.imgur.com/P6jVNDW.jpg)
![link3](http://i.imgur.com/J0I19wa.jpg)

Typed `//fixlighting` again to do another pass. Cleaned up the remaining patchy lighting on the ground.
![link4](http://i.imgur.com/F1DOY0B.jpg)

But it did not clean up lighting in other areas, like the ceiling. 
![link5](http://i.imgur.com/dW2gffI.jpg)
![link6](http://i.imgur.com/MeSdFVE.jpg)

After everything was fixed (//removelighting then //fixlighting), a player used a brush operation in the underground area and caused lighting to break again in the chunk as soon as it was used.
![link7](http://i.imgur.com/MlyKVf9.jpg)

---

Above ground area - lighting normal / untouched. (This issue can also occur below ground.)
![link8](http://i.imgur.com/kThTTI4.jpg)

Set a light source / light block in the area. (Note that the area lighting is not smooth also, have to place or break a block to update / smooth the lighting in the area.)
![link9](http://i.imgur.com/Lydswws.jpg)

Undid the set. Lighting remained.
![link10](http://i.imgur.com/nQ9ensp.jpg)

Typing `//fixlighting` does not fix this light problem. You are forced to type `//removelight` then `//fixlighting` to fix the area. I assume this also occurs when loading in a schematic that has light sources, then trying to undo. It keeps the light in the area. It also occurs when setting a light block and then changing it into something else like stone.

---

_Notes_
- All testing was done with the default config settings -  async enabled and light mode 1.
- Regarding the 2nd issue with fixlighting, when using light mode 2; sometimes you have to type fixlighting a dozen times for it to fully fix all lighting problems underground when there are chunks lit. As it slowly shrinks the lighting area rather than fixes it all at once. Might also occur in light mode 1 since I had to type it twice/thrice per above images, but something I noticed when testing the 2nd mode.
- Regarding the 1st issue with underground being lit with brushes / commands, it seems to be fine in mode 2 as far as my quick testing goes. But is a pretty big problem in mode 1.
- Regarding the 3rd issue with setting a light source and then undoing, it also occurs in mode 2.

**Comment by Noiknez** [comment]
I can confirm that i have the same problem with
FastAsyncWorldEdit-bukkit110-16.11.01-efc0de2-366-9.10.0

**Comment by boy0001** [comment]
Should be fixed with lighting mode 2.

**Comment by mibby** [comment]
@boy0001 Shouldn't the default setting probably be changed to lighting mode 2 since there are bugs with mode 1?
