### ISSUE TITLE
Worldedit / Voxel smooth brushes cause a huge mess when using in caves and under trees / flora (smoothing air blocks).

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#319]
FastAsyncWorldEdit dev 317
FastAsyncVoxelSniper dev 317
WorldEdit v6.1.5 dev 3623
VoxelSniper v5.171
Paper (Spigot 1.10.2) dev 878

Config.
http://paste.ubuntu.com/23232047/

Smoothing with worldedit and voxel causes a bunch of problems when smoothing cave faces and trees / grass.

WorldEdit smooth brush (//br smooth)

Before.
![link](http://i.imgur.com/FxUXdWl.jpg)
After.
![link2](http://i.imgur.com/LL2MhzB.jpg)

Before.
![link5](http://i.imgur.com/2pywCaI.jpg)
After.
![link6](http://i.imgur.com/nSiRcxx.jpg)

Smoothing near grass leaves floating grass.
![link3](http://i.imgur.com/B0gysPB.png)
![link4](http://i.imgur.com/xK6DzNK.png)

![link7](http://i.imgur.com/UEF0mz6.jpg)

Voxel's ```/b e fill``` brush isn't as bad as WorldEdit's smooth brush, but does occasionally come across the same issue since it is placing blocks to smooth. Voxel's ```/b e melt``` brush generally smooths much better since it is removing blocks to smooth, but very rarely runs into the same problems. Is there anything that can be done to improve smooth behavior?

**Comment by boy0001** [comment]
WorldEdit's smooth just sucks.

There's `//br erode` and `//br blendball` which you could try. Or with VS `/b erode` and `/b blendball`
