### ISSUE TITLE
//regen harms chunks surrounding

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#32]
FAWE 3.3.10
WE 6.1.1 b3463

![2016-04-14_17 29 16](https://cloud.githubusercontent.com/assets/3305006/14533709/77f13002-0266-11e6-8a7a-42dfcb456b5b.jpg)

The area within the void was selected for regeneration.

The reason for this might have been that I was not around the regeneration area, so chunks were unloaded.

There was no error messages in game nor any WorldEdit or FAWE related output in the console.

As a side note: When using other commands like `//set` and so on FAWE tells me the time it took to process the command. On `//regen` this does not happen.

**Comment by boy0001** [comment]
I messed up. Temporary fix, set chunk-wait any number > 0

**Comment by boy0001** [comment]
> As a side note: When using other commands like //set and so on FAWE tells me the time it took to process the command. On //regen this does not happen.

regen is handled in a different part of WorldEdit, so that's normal (for now)
