### ISSUE TITLE
Setting ender_portal / end_gateway with FAWE installed makes it invisible.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#320]
FastAsyncWorldEdit dev 324
FastAsyncVoxelSniper dev 324
WorldEdit v6.1.5 dev 3623
VoxelSniper v5.171
Paper (Spigot 1.10.2) dev 881

Config.
http://paste.ubuntu.com/23244770/

Setting ender_portal (ID 119) with FAWE installed places it down invisible. 

With FAWE installed.
![link](http://i.imgur.com/WsCTjoX.png)
//fill endportal 10
![link2](http://i.imgur.com/qbmaoso.png)

---

Without FAWE installed.
![link3](http://i.imgur.com/WsCTjoX.png)
//fill endportal 10
![link4](http://i.imgur.com/bVFGaU4.png)

**Comment by mibby** [comment]
This also occurs with end_gateway (ID 209).

**Comment by mibby** [comment]
@boy0001 Still broken as of FAWE dev 415 (411 on jenkins - http://ci.athion.net/job/FastAsyncWorldEdit/411/)

**Comment by mibby** [comment]
@boy0001 Still broken as of FastAsyncWorldEdit dev 484 (455 on jenkins).

**Comment by mibby** [comment]
@boy0001 This still happens with FAWE dev 520. Setting end_portal in a selection does not make all tiles appear. Left clicking the tile with the worldedit wand forces the tile you hit to appear but when you teleport away and back, they are all invisible again. Even relogging doesn't help. 

Removing FAWE and using stock worldedit, setting end_portal works perfectly fine.

Please reopen the ticket or would you rather I create a new one?

![link15](http://i.imgur.com/LLXFMu1.png)

**Comment by dordsor21** [comment]
Seem to be working fine for me. This still happening @mibby ?

**Comment by mibby** [comment]
@dordsor21 Nope, confirmed fixed.
