### ISSUE TITLE
All operations are pasting without chunk topology data.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#322]
FastAsyncWorldEdit dev 324
FastAsyncVoxelSniper dev 324
WorldEdit v6.1.5 dev 3623
VoxelSniper v5.171
Paper (Spigot 1.10.2) dev 881

Config.
http://paste.ubuntu.com/23244770/

All operations are pasting without chunk topology data. So maps are broken, dynmap renders without shadows, etc.

![link](http://i.imgur.com/R401uhO.png)

All you see is stone / dirt. But it should be grassy and a hill with buildings. Pasting without FAWE installed, the maps render the area properly.

And dynmap renders areas without shadows with FAWE.
![link2](http://i.imgur.com/mJQM0tR.jpg)
This is what it is normally suppose to renders as, with shadow depth (no FAWE pasted builds).
![link3](http://i.imgur.com/fJtbli7.jpg)

You can kind of see in the bottom left side some tiles re-rendered without shadows - the overlap between the two differences (old map render and new map render with FAWE installed/pastes updates).

I've also had issues with heads / signs / banners pasted from schematics being invisible for some players and not others when loading into the area. Generally toggling the VBO graphic setting forces it to reappear. Never use to happen.  Could be related to chunks missing data or the end portals being invisible on placement.

**Comment by mibby** [comment]
For what it's worth, loading into pasted areas (tped to the center of a pasted build for example from elsewhere) takes quite a long time. It loads the chunks very slowly and freezes the client's network connectivity until the area is fully rendered. May be related to operations breaking chunk data.

**Comment by mibby** [comment]
Examples of it pasting signs that are invisible. But oddly are visible to some people and can very oddly reappear to some clients by toggling the vbo graphic setting. Pasting without FAWE, the signs aren't invisible.

![link6](http://i.imgur.com/IrBjIhW.png)
![link7](http://i.imgur.com/bxb5dfM.jpg)
![link8](http://i.imgur.com/6EmKsgS.png)

I've also experienced banners and skulls going invisible. And even skulls losing their skin / attached UUID - reverting back to a generic skeleton skull.
![link9](http://i.imgur.com/e0xpX8m.jpg)

**Comment by dordsor21** [comment]
Can confirm the invisible signs issue

**Comment by mibby** [comment]
@boy0001 Please re-open the issue ticket. This issue is not fixed as of dev build 366 (365 on jenkins).

Config
http://paste.ubuntu.com/23433885/

Tree leaves among various other things are not rendering on maps. 
http://imgur.com/a/qlm2E

**Comment by mibby** [comment]
Dynmap shadows are also still missing with FAWE pastes.

**Comment by boy0001** [comment]
I think it's that I was skipping transparent blocks. Latest commit should count leaves and such.

**Comment by mibby** [comment]
Alright, I'll give it a test tomorrow. Thanks. :)

**Comment by mibby** [comment]
@boy0001 This is still broken as of FAWE dev 379 on 1.11. Tested a few things, couldn't get any build to work. Both in-game map area and dynmap shadows not showing up for worldedited builds with FAWE. No transparent blocks, not even normal buildings (i.e. initial ticket image).

Removing FAWE, this issue isn't present.

**Comment by boy0001** [comment]
Thanks for the info. I'll try to get this fixed soon.

**Comment by mibby** [comment]
@boy0001 Maps seem to be working fine now on FAWE dev 411 (407 on jenkins) http://ci.athion.net/job/FastAsyncWorldEdit/407/.

Though I'm not sure if it is preserving biome type properly? Might want to double check that it is. It doesn't match the other images I posted above. Though that image could have been the broken one and the fix is preserving proper biome type / rendering now. 
![l10](http://i.imgur.com/c5jzBWa.png)

Dynmap unfortunately still seems to be rendering worldedit areas (operations / schematic pastes) without shadows though. :( Removing FAWE and pasting schematics with normal WorldEdit, dynmap renders shadow depth properly. So bug is still partially present?

**Comment by mibby** [comment]
I'm also still noticing invisible signs and heads when pasting a build with FAWE. And some of the heads that didn't go invisible (or get hit when invisible), they reverted to standard skeleton skull heads.

**Comment by mibby** [comment]
Still a problem as of FAWE dev 415 (http://ci.athion.net/job/FastAsyncWorldEdit/411/).

**Comment by mibby** [comment]
@boy0001 Bump. :( Shadows for all worldedit operations still seem to be broken when rendering the chunks with dynmap.

**Comment by mibby** [comment]
@boy0001 Shadow detail when rendering FAWE worldedited builds is still lost on FastAsyncWorldEdit dev 484 (455 on jenkins). :(
