### ISSUE TITLE
No physics for sand or gravel with any WE commands

### ISSUE THREAD

**Issue by iamceph** [boy0001/FastAsyncWorldedit#323]
**Debug paste link**:
http://hastebin.com/bozecukozi.md -- this error ._.
Running this fawe: FastAsyncWorldEdit-bukkit110-16.09.28-bd90df7-326-9.3.0.jar

**Description of the problem:**
![2016-09-29_20 36 32](https://cloud.githubusercontent.com/assets/4377405/18967963/634f6cae-8687-11e6-909d-16c177877e8f.png)
![2016-09-29_20 39 29](https://cloud.githubusercontent.com/assets/4377405/18967964/6353ce2a-8687-11e6-9106-03b600621098.png)

No physics for sand or gravel with any of WE commands

**How to replicate**:
Use //set, //brush or any other command

**Comment by boy0001** [comment]
Not a bug.
Duplicate #55

Use the heightmap brush instead:
#### `//brush height [radius=5] [file|#clipboard=null] [rotation=0] [yscale=1.00]`
Perm: `worldedit.brush.height`
Desc: Raise or lower terrain (omitting an argument will use the default value)
Note: Use a negative yscale to reduce height
Example: `//brush height 10`

More info:
https://github.com/boy0001/FastAsyncWorldedit/wiki/Commands#brushestools

**Comment by iamceph** [comment]
Thank you!

**Comment by iamceph** [comment]
/br height -2 did this o.O

![2016-09-29_21 22 18](https://cloud.githubusercontent.com/assets/4377405/18968834/ec621dc2-868a-11e6-9a1a-b0ae0e887ae8.png)

**Comment by boy0001** [comment]
@iamceph 
-2 is an invalid size for a brush, use a positive number. If you want negative yscale, that's another argument.

**Comment by MTGPROD** [comment]
This is complex
