### ISSUE TITLE
Undo not cleaning up all blocks pasted.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#326]
FastAsyncWorldEdit dev 345
FastAsyncVoxelSniper dev 345
WorldEdit v6.1.5 dev 3623
VoxelSniper v5.171
Paper (Spigot 1.10.2) dev 883

Config.
http://paste.ubuntu.com/23274153/

Schematic used.
http://www.mediafire.com/file/zxq30ymaueczj0z/test.schematic

Was testing out a global transformation. 

Loaded the schematic, typed the command `/gtransformation #scale:1.5:1.5:1.5:#rotate:45:45:45`, pasted, got the output 'Your WorldEdit action was cancelled: Too many blocks changed.', and then tried to undo (`//undo`). It did not clean up all the blocks that were created. Cleaned up most of the created mess, but not all.

![link](http://i.imgur.com/NyLCjzd.png)

**Comment by boy0001** [comment]
Assumed fixed (same as #397)
