### ISSUE TITLE
Permission not checked / outdated wiki

### ISSUE THREAD

**Issue by filoghost** [boy0001/FastAsyncWorldedit#327]
The wiki mentions the `fawe.plotsquared` permission (I suppose it's for using WE on any plot). However, only the `fawe.plotsquared.member` permission [is checked in the code](https://github.com/boy0001/FastAsyncWorldedit/blob/master/core/src/main/java/com/boydti/fawe/regions/general/plot/PlotSquaredFeature.java#L70).

My suggestion is to implement it, because it would be useful to give moderators WE in any plot but not on the roads (/wea bypasses everything as well as `fawe.bypass`). Otherwise just edit the wiki to match the code.

**Comment by boy0001** [comment]
It checks here:
https://github.com/boy0001/FastAsyncWorldedit/blob/d2413daca128b5b2ee8ef3bda6dd2ad3f230335a/core/src/main/java/com/boydti/fawe/util/WEManager.java#L91

**Comment by filoghost** [comment]
Oh, I'm sorry, I must have been doing something wrong.

What permissions am I supposed to set, if I can ask? I tried `fawe.plotsquared` + `plots.worldedit.bypass`, but even after executing `/plot wea` it cancels the edit with the message "Action cancelled: No allowed region".
`fawe.admin` + executing `/wea` works, but it ignores the roads.

Is it currently possible to give moderators the permission to edit any plot BUT excluding the roads?
