### ISSUE TITLE
WorldEdit operation lag / slowdown over time.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#330]
FastAsyncWorldEdit dev 345
FastAsyncVoxelSniper dev 345
WorldEdit v6.1.5 dev 3623
VoxelSniper v5.171
Paper (Spigot 1.10.2) dev 885

Config.
http://paste.ubuntu.com/23294499/

Getting a lot of complaints recently. There seems to be quite a bit of worldedit operation lag / delay when people are using brushes or replace tools. It takes quite a few seconds for the actual operation to work / parse. TPS has been stable at 20 and the operation sizes are not absurd. Could it be caused by parallel-threads being set to 1 (due to the crash bug), async lighting being disabled (due to lighting bugs and issues with automated schematic loading in arenas pasting with black lit areas, not that disabling helps much), or something in a newer recent commit?

**Comment by boy0001** [comment]
Caused by a logic error, has been fixed
