### ISSUE TITLE
FastAsyncRedstone 1.8

### ISSUE THREAD

**Issue by Fluxty** [boy0001/FastAsyncWorldedit#331]
Does not enable on 1.8.8 PaperSpigot. Looks like it is only built for 1.10. Is there a 1.8 version?

**Comment by EvilOlaf** [comment]
http://ci.athion.net/job/FastAsyncWorldEdit/345/artifact/target/
Grab the jar for bukkit18.
If there are errors on enable follow the issue template to create a valid report.

**Comment by Fluxty** [comment]
I don't see any 1.8 jar for Fast Async Redstone. Think even the 1.10 version is only available on dropbox

**Comment by EvilOlaf** [comment]
Sorry, my bad. Thought you were talking about FAWE.

**Comment by cyberpwnn** [comment]
I am also looking into this. Would it be possible to have this on github or some source code at least? Is this not for 1.8 for some reason? I looked at some decompiled sourcecode. It looks like it's only using CraftBukkit 1.10 and FAWE with NMSMapped queues. Is there something in FAWE or craftbukkit that is preventing it to work with 1.8 or i'ts just not finished yet?

**Comment by boy0001** [comment]
It's not finished

**Comment by boy0001** [comment]
https://github.com/boy0001/FastAsyncRedstone/ works for 1.8
