### ISSUE TITLE
Build artifact versioning off from actual jenkins build number.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#334]
The build version is two numbers off from the actual jenkins build number.

FAWE dev 347 on jenkins
http://ci.athion.net/job/FastAsyncWorldEdit/347/

Files compiled state 345.
http://ci.athion.net/job/FastAsyncWorldEdit/347/artifact/target/

**Comment by mibby** [comment]
Still off in the newer builds, except only one number instead of two now.

http://ci.athion.net/job/FastAsyncWorldEdit/354//artifact/target/

**Comment by mibby** [comment]
Ahead by 1 now.

Showing build 366 for jenkins 365.
http://ci.athion.net/job/FastAsyncWorldEdit/365/

**Comment by boy0001** [comment]
The build can't depend on ci.athion.net since anyone needs to be able to build the plugin and get the same jar / version. Best thing is to keep manually offsetting the number, which means this will be a recurring issue.
