### ISSUE TITLE
IslandWorld schematics loading not working

### ISSUE THREAD

**Issue by Borc55** [boy0001/FastAsyncWorldedit#337]
# Bug report template (Follow this template unless you are making a feature request.)

**Debug paste link**:
debug not avalaible
**Description of the problem:**
Creation of islands goes wrong every time, island chest is empty, and end portal appears on it.
I've checked if someone had same problem, and they did, tho it wasn't fixed yet.
https://github.com/boy0001/FastAsyncWorldedit/issues/131
**How to replicate**:
FastAsyncWorldEdit, WorldEdit, IslandWorld, create island.

**Comment by boy0001** [comment]
Try now

**Comment by boy0001** [comment]
Please let me know if this is still an issue and I'll reopen.
