### ISSUE TITLE
Update Permissions documentation

### ISSUE THREAD

**Issue by CleanerOrc** [boy0001/FastAsyncWorldedit#34]
1) What's the difference between the admin permission  fawe.worldeditregion and the region permission fawe.worldguard ?

2) If someone has permission fawe.worldguard and has regular worldedit permissions, are they prohibited from affecting blocks outside of regions they own using WorldGuard?

3) Could you provide answers to these questions in permissions documentation.?

**Comment by EvilOlaf** [comment]
Actually a pretty good question. It is indeed not 100% clear how they work.
As far as I understood:

`fawe.admin` allows you to edit across regions by using `wea` to toggle this behavior
`fawe.bypass` is basically `wea` enabled by default

`fawe.worldguard` allows someone to use WE in a region he does not have member or owner rights.
same for the other 3rd party plugins permissions.

**Comment by boy0001** [comment]
1) `fawe.worldeditregion` is for the `/wrg` command, `fawe.worldguard` is for access to WorldEdit in WorldGuard regions

2) Yes, unless they have the admin bypass permission (`fawe.bypass` or `fawe.admin` and use `/wea`) 

3) Updated the documentation to put the permissions in the correct categories
