### ISSUE TITLE
Rollback?

### ISSUE THREAD

**Issue by NycuRO** [boy0001/FastAsyncWorldedit#344]
You can add rollback to fawe? @boy0001  Nukkit.

**Comment by dordsor21** [comment]
Just use a block logging plugin that supports WE (most work with FAWE) or actually look at the commands list...

https://github.com/boy0001/FastAsyncWorldedit/wiki/Commands#history-commands

**Comment by NycuRO** [comment]
@dordsor21 Not work. Say : Lacking setting: history.use-database

**Comment by dordsor21** [comment]
then set history.use-database true in config
