### ISSUE TITLE
Possible to use default WE behavior with FAWE installed?

### ISSUE THREAD

**Issue by ItsHarry** [boy0001/FastAsyncWorldedit#345]
Is it possible to use default WE behavior while FAWE is installed? I'd like to use FAWE for some operations but use synchronous for certain others

**Comment by boy0001** [comment]
Not currently. What kind of problems are you experiencing?

**Comment by ItsHarry** [comment]
I haven't used FAWE yet, was more of a question type thing.

Some plugins I'm using rely on the map being pasted synchronously, for example they teleport the players right after the map has been pasted. If FAWE was installed it would probably cause problems

**Comment by boy0001** [comment]
@ItsHarry 
They should still work. To maintain compatiblity, when flushed, the calling thread is blocked until the changes are performed.

For commands/brushes, FAWE queues the changes async, so it is flushed async. Plugins using the normal WorldEdit API from the main thread will not be async.

**Comment by ItsHarry** [comment]
So compatibility is fully remained as long as the API is called synchronously? That's pretty smart :+1: 

So if I want to edit the world asynchronously, all I have to do is call the API from another thread?

**Comment by boy0001** [comment]
yes
