### ISSUE TITLE
Mysterious error

### ISSUE THREAD

**Issue by HippyBomb** [boy0001/FastAsyncWorldedit#346]
Debug paste link: http://i.imgur.com/vxrihhy.png

Description of the problem: FAWE loads correctly and is usable, but after a few commands are run only non-command based aspects operate, and the image above is spammed to terminal.

How to replicate: All I do is have WorldEdit (most recent) and FAWE (most recent) and run them

**Comment by boy0001** [comment]
Please include a debugpaste.

**Comment by boy0001** [comment]
In IRC you said that it stopped working after editing the `messages.yml` file. Is that the case here?

**Comment by HippyBomb** [comment]
It stopped working after that, but when the files were restored to normal it still doesn't work

**Comment by HippyBomb** [comment]
And here's the debug paste http://hastebin.com/oticogizon

**Comment by boy0001** [comment]
Was fixed
