### ISSUE TITLE
problems with pistons and redstone lamps

### ISSUE THREAD

**Issue by keough99** [boy0001/FastAsyncWorldedit#35]
plugin wont paste in pistons or redstone lamps

**Comment by RoboMWM** [comment]
Any errors in console?

**Comment by boy0001** [comment]
Cannot replicate. Tested with powered / unpowered variations.

**Comment by boy0001** [comment]
Please respond with a copy of your startup log / fawe configuration if you would like this issue revisited.

**Comment by keough99** [comment]
The issue was resolved when i updated the plugin
