### ISSUE TITLE
FAWE lag spikes (YourKit)

### ISSUE THREAD

**Issue by UltraX3** [boy0001/FastAsyncWorldedit#352]
There is no lag for a few seconds and then a very big lag spike.I think giving you images from YourKit will be enough. If you want, I can send you a full snapshot. Also, I am using 1.8.8 PaperSpigot.

![image](https://cloud.githubusercontent.com/assets/7644264/20460003/1255b8d0-ae9b-11e6-84ea-4c5eb657fee2.png)

![image](https://cloud.githubusercontent.com/assets/7644264/20460014/44fdabc6-ae9b-11e6-8536-23f14c8ebf71.png)

This is what it is like in one of the low plateaus.
![image](https://cloud.githubusercontent.com/assets/7644264/20460032/9de1a21a-ae9b-11e6-9a13-455fb3a0ce22.png)

This is using the latest version of FAWE on Jenkins. Using an old (FastAsyncWorldEdit version 16.09.14-911e7e7-287) version there is essentially no lag.

Here is my config for the old FAWE. The new config is the same but has the default new values. 
http://hastebin.com/ajahisapic

**Comment by UltraX3** [comment]
Or maybe it is the new PlotSquared... I have a feeling it might be due to my generator that I had to update the the latest PlotSquared.

**Comment by boy0001** [comment]
What operation is being used?
What is the expected CPU/Memory usage for said operation?
If another plugin (e.g. PlotSquared) is utilizing FAWE, it's not really a FAWE issue since it's doing what it is requested.
