### ISSUE TITLE
//flip on Nukkit, MCPE

### ISSUE THREAD

**Issue by ghost** [boy0001/FastAsyncWorldedit#354]
//flip not work on MCPE with Nukkit..

**Comment by N0tMyFaultOG** [comment]
If the issue persists still, reply to the ticket

**Comment by NycuRO** [comment]
still

**Comment by N0tMyFaultOG** [comment]
Did you try to update fawe meanwhile?

**Comment by NycuRO** [comment]
no, i forgot about this issue.
