### ISSUE TITLE
Use-Inventory Config/Permissions Not Functioning?

### ISSUE THREAD

**Issue by ElvenChaos** [boy0001/FastAsyncWorldedit#355]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**: http://hastebin.com/buqipegofa

**Description of the problem**: Unable to get fawe's use-inventory settings to function. I've been trying to test it by giving myself minimal permissions and using WE commands/wand, but as soon as I get a function to "work" it completely ignores my survival-mode inventory (while in survival).

**How to replicate**:
WE's Config: http://hastebin.com/qibuzegoru.ini
Permissions related to WE/FAWE: http://hastebin.com/upocebogah.md
SpongeForge 1.10.2 - 5.1.0 - 1914
Used Permissions Plugin: PermissionManager 2.5.1 https://forums.spongepowered.org/t/key-permissionmanager-v2-5-1-api-6-x-5-x-4-2-0-gb-fr-ru-and-more/12310

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/fawe debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an updated version of FAWE
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
So it seems WorldEdit doesn't implement the BlockBag on your platform which FAWE depends on for this feature: https://github.com/sk89q/WorldEdit/blob/master/worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgePlayer.java#L167

I'll see what I can do, but the best solution would be to have it fixed on WorldEdit's end.

**Comment by boy0001** [comment]
@ElvenChaos 
Updating FAWE should fix the issue.

**Comment by ElvenChaos** [comment]
Thanks a ton :D
