### ISSUE TITLE
Can't add extra blocks (custom blocks)

### ISSUE THREAD

**Issue by Termm-O-Code** [boy0001/FastAsyncWorldedit#357]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/higegedaxa
**Description of the problem:**

Hi,
I'm having trouble editing customized blocks using FAWE. While WE has no trouble editing them, FAWE seems to ignore custom blocks and just apply a modulo on the block ID's when pasting.
extrablocks.json: http://hastebin.com/edesecopoj.scala
Am I doing something wrong ?
Thanks

**How to replicate**:
Implement custom blocks on server / clients with blockID > 1024, declare them to FAWE, try copying them. If the problem is correctly replicated, copy should work with classic WE and replace custom blocks when using FAWE.

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/fawe debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an updated version of FAWE
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
@Termm-O-Code 
Should be fixed.
