### ISSUE TITLE
'Using adapter' output when right clicking ground with fist.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#358]
FastAsyncWorldEdit dev 404
http://ci.athion.net/job/FastAsyncWorldEdit/404/
WorldEdit dev 3655
PaperSpigot dev 958

Whenever someone with worldedit permissions right clicks the ground for the first time since start start-up or types //wand, FAWE's 'using adapter' output is outputted in console. This leads me to a few questions.

```
[03:37:25 INFO]: (FAWE) Using adapter: com.boydti.fawe.bukkit.v1_11.FaweAdapter_1_11@2345c512
[03:37:25 INFO]: (FAWE) =========================================
```

1) Is FAWE unnecessarily listening for any and all events? Seems odd that right clicking the ground with just your fist loads the FAWE adapter.

2) Is FAWE's adapter still needed? WorldEdit had an adapter fix commit yesterday.
https://github.com/sk89q/worldedit/commit/82fdab35d1a0dd859045ca28c363547c5ea8c45b

**Comment by boy0001** [comment]
1.) FAWE doesn't register any interaction events, it only loads the adapter when WorldEdit or VoxelSniper creates a new session.
2.) Yes. WorldEdit's adapter still has the issue pf older entities not being compatible with 1.11 and vice versa.
