### ISSUE TITLE
Problem Pasting Large areas - Small area repeats for remaining size

### ISSUE THREAD

**Issue by CleanerOrc** [boy0001/FastAsyncWorldedit#36]
Running FAWE 3.3.12 with WE 6.1.1 #3462, on Spigot 1.8.8

//Copy'd huge area of 257 Million  blocks and saved as Schematic.  After saving, I moved to target area then  did   //paste -a

The paste started, and eventually I got the finished message completed in 51.nnn seconds.

An area of 160 (+x)  x 155 (-Z) blocks pasted OK, but then beyond that area along the +X axit, a 1 chunk long area along the X axis repeated over and over to fill what looks like the size of the original selection (probably  1000 x 256 x 1000)  257 Million blocks.

Compression and history file are enabled in the config file as shown below.  The console log shows the commands being entered but no additional information.  No errors in the Client message log.

Any ideas?

--------------------------------------

**Comment by EvilOlaf** [comment]
Your FAWE is slightly outdated. Check for a new version.

**Comment by boy0001** [comment]
It probably pasted correctly ;)

Anyway, increase the chunk-wait in the config to 100 (milliseconds) so copy can get the blocks in the unloaded chunks. The default value is 0 which is faster but means FAWE cannot copy blocks from unloaded chunks (and subsequently just repeats the last chunk as filler)

**Comment by CleanerOrc** [comment]
That did it.  Thanks.
