### ISSUE TITLE
Butcher broken?

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#361]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/qazidedebu
**Description of the problem:**
//butcher command seems to be broken as 0 mobs being removed. Disabling (to say remove it from plugins) FAWE fixes this issue.
**How to replicate**:
Help yourself for some mobs and use //butcher to remove them.

Paper 958 1.11
WE 6.1.6 3652
WG 6.2.1 1695
FAWE 16.12.03-57d41ae-406-9.12.30

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/fawe debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of FAWE
- [?] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
Can't replicate.

**Comment by EvilOlaf** [comment]
What to say? https://vimeo.com/194693359

**Comment by boy0001** [comment]
`/wea` ?

**Comment by EvilOlaf** [comment]
Works. Though there are no regions set up besides the default `__global__` region.
