### ISSUE TITLE
All world edit commands deleted? Bukkit

### ISSUE THREAD

**Issue by Noblesuntzu** [boy0001/FastAsyncWorldedit#364]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/uwodicabuy
**Description of the problem:**
When I downloaded it, none of the normal world edit commands return anything (when I type them it doesn't update the chat at all.) But none of my other plugins have had an issue like this. I really need it to work, I'm copying a 4 million block castle XD
**How to replicate**:
Can you explain this?
Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/fawe debugpaste` 
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] Made sure you're using an updated version of FAWE
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
The debugpaste log is filled with skript spam. Are you able to upload a new startup log, and also let me know your WorldEdit version?
