### ISSUE TITLE
FAWE disables timings and naughty async stuff when parallel threads > 1

### ISSUE THREAD

**Issue by RoboMWM** [boy0001/FastAsyncWorldedit#365]
No idea why nobody reports or links such things here when they discover it...

Anyways, https://github.com/PaperMC/Paper/issues/444

In short, FAWE does bad async stuff when employing the parallel threads option.

Relevant chat in #aikar: http://i.imgur.com/asslt2k.png

**Comment by boy0001** [comment]
@RoboMWM 
BlackBeltPanda told me and I fixed the issue already. It didn't mean to disable timings, just circumvent the checks. 

@aikar
No, it's not async. That would require the main thread doing its own thing while FAWE is doing another. The main thread is locked the entire time the world is being changed. The only thing FAWE actually does in parallel is swap out/merge the block palette data. The chunks are loaded on the main thread, and entity changes are all synchronized (i.e. not done in parallel, just on another thread).

The checks done by paper assume anything run on another thread is bad, regardless of whether it's actually async/unsafe. 

Also, FYI, AWE does some bad stuff async that FAWE goes out of its way to avoid (by caching chunks on the main thread and passing it off to the async queue):
 - AsyncWorldEdit-Premium/issues/85
 - AsyncWorldEdit-Premium/issues/115

Ironic that AWE calls the async block/entity get "safe operation". 

But Aikar, you can entirely disable the `parallel-thread` (set it to 1) and disable the use of NMS (set `fast-placement` to false, and don't use `/wea` or `//fast`). Then it'll be placing through the Bukkit API like good old AWE, just significantly faster.

**Comment by aikar** [comment]
Can you least only disable timings during the main thread suspend and re-enable it after.

**Comment by boy0001** [comment]
@aikar 
Yes, that's what I'm doing, and had meant to do, I just messed up.
