### ISSUE TITLE
Blocks replaced *randomly ?* when loading schematics with disk-use set to true for clipboard

### ISSUE THREAD

**Issue by lululombard** [boy0001/FastAsyncWorldedit#366]
# Blocks replaced *randomly ?* when loading schematics with disk-use set to true for clipboard
**Debug paste link**:
http://hastebin.com/vorecuhepi

**Description of the problem:**
On the load, blocks are replaced by other, and differents one at each load. The akward thing is that it seems to "loop" between block replaced
**How to replicate**:
Make sure that "use-disk" is set to true for the clipboard
//copy something
//schematic save it
//schematic load it
//paste it
Blocks should be wrong
//schematic load it
//paste it
Blocks should be wrong, but this time another blocks

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/fawe debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an updated version of FAWE
- [X] Made sure the bug/error isn't caused by any other plugin

Problem happens with build 960, 961 and 962 of PaperSpigot, and lastest dev build of WorldEdit (1654).

I'm uploading a video right now to explain my issue, and I'll post it here.
EDIT : Video here : https://youtu.be/ZGNRsDxqeQU

**Comment by boy0001** [comment]
Do you use any sort of anti-xray?

**Comment by lululombard** [comment]
On 2 of my server I'm using Orebfuscator but the issue happens on my creative server too, which is not running it. Topred.fr network has the exact same issue with Spigot instead of Paper without any kind of anti-xray.

**Comment by lululombard** [comment]
UPDATE : 
This issue only happens with "use-disk" clipboard option. 
https://www.youtube.com/watch?v=YzbXImTjACo

I'll try on a server with only FAWE/WE to see if I can reproduce this bug easily.

**Comment by lululombard** [comment]
Last PaperSpigot build, last WorldEdit dev build, last FAWE dev build, all default config, only 3 plugins installed, the issue is here !
![FAWE schematic bug](https://cloud.githubusercontent.com/assets/2182934/21080336/94a8968c-bfac-11e6-8925-69f7b994ef70.png)
Steps to reproduce : download fresh build of all plugins and Spigot/a fork of it, set some blocks (here quartz), //copy it, //schem save it, //schem load it, //paste it

Only happens with ""use-disk" clipboard option as mentioned earlier.
The bug comes from FAWE, I can confirm.

**Comment by lululombard** [comment]
@boy0001 Bump ? ;P

**Comment by boy0001** [comment]
Forgot about the ticket, it was fixed in f0a36ba1fa2d27a36f38a542e10c0123ac733d51
