### ISSUE TITLE
Build Commands

### ISSUE THREAD

**Issue by hexosse** [boy0001/FastAsyncWorldedit#369]
**Debug paste link**:
http://hastebin.com/aberecidag

**Description of the problem:**
Hello, I'm using [build_commands](http://inhaze.net/resources/build_commands/) for quite a long time now, but when I add FastAsyncWorldedit it doesn't work anymore.

**How to replicate**:
Create a selection with WorldEdit.
Select a stick and type : /cs build shape
Click the copy point then try to paste and nothing paste ???

**Checklist**:
- [x] I included a `/fawe debugpaste` link 
- [x] I made sure there aren't duplicates of this report [(Use Search)]
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Fixed. It was pasting, just at the original position

**Comment by hexosse** [comment]
Thanks, it works.
