### ISSUE TITLE
Feature request: Reduce selection to minimal size (constrain to object) 

### ISSUE THREAD

**Issue by ajthemacboy** [boy0001/FastAsyncWorldedit#370]
I'd like a feature to reduce the selection to the smallest size possible, so that no unnecessary air blocks are included in a selection.

Say I had a lot of objects that I wanted to copy quickly, so I just estimate the selection of each one. But I select too much around the edges of the object, meaning the selection copies unnecessary air.

I'd like to be able to run a command like //autoconstraint to fit the selection to the smallest possible size around the object. 

Maybe an option to exclude blocks from the selection would be useful as well, so if I'm making trees in a voidworld with a floating grid of wool, I could select the tree and run //autoconstraint 35 to exclude wool blocks from the constraint.

Thank you!

**Comment by dordsor21** [comment]
//paste -a will past without air

for removing certain blocks you can //paste -s -a (in that order, the -s will move the select to where you pasted) and then //replace <block> air

**Comment by boy0001** [comment]
You can copy with a mask, and exclude the blocks you don't want:
`//copy -m <mask>`    

You can use the fuzzy selection mode to only select connected blocks
`//sel fuzzy` or `//sel fuzzy=<mask>`  e.g. `//sel fuzzy=!air,wool`    

You can set a source mask, and only paste the blocks you want
`//gsmask <mask>` and `//paste`    
Note: `//paste -a` uses `!0` as the source mask.

More information about FAWE's masks can be seen here: 
https://github.com/boy0001/FastAsyncWorldedit/wiki/WorldEdit---FAWE-mask-list
