### ISSUE TITLE
ZSTD Compression Binding

### ISSUE THREAD

**Issue by Fluxty** [boy0001/FastAsyncWorldedit#372]
http://pastebin.com/wa945qp9

PaperSpigot 1.8.8 (Report this if you can't resolve)

/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-0.b15.el6_8.x86_64/jre/bin/jav

**Comment by boy0001** [comment]
Lower compression to 3.

**Comment by boy0001** [comment]
It no longer prints the full stacktrace. The error is from one of the compression libraries FAWE uses (zstd) not finding a library it depends on `GLIBC_2.14`.

Update/Install GLIBC or just ignore the error since the plugin still works.
