### ISSUE TITLE
'Having `parallel-threads` > 1 interferes with the timings.' output.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#374]
Did a paste command and this was outputted in console as a response. Is it necessary to notify when a user uses a worldedit command? 

```
[04:31:19] [Craft Scheduler Thread - 8/INFO]: WorldEdit: player (in "world"): /paste - Position: (-6281.0, 123.0, 2120.0)
[04:31:19] [Server thread/INFO]: (FAWE) Having `parallel-threads` > 1 interferes with the timings.
```

**Comment by boy0001** [comment]
I don't see why not? It only prints it once.

**Comment by mibby** [comment]
Because it seems a bit redundant to output when a worldedit operation is used? Would make a bit more sense if it was outputted when someone ran a timings profile instead.

**Comment by boy0001** [comment]
You can run timings or you can do an edit, the message is only printed when doing both at the same time.

**Comment by mibby** [comment]
Ah, okay. I suppose that makes a bit more sense. Didn't realize I had timings enabled on my test server - thought the message always outputted when using worldedit for the first time. My bad. :)
