### ISSUE TITLE
COMPRESSION BINDING NOT FOUND

### ISSUE THREAD

**Issue by Reeferx7** [boy0001/FastAsyncWorldedit#378]
With /fawe debugpaste i get this error:

http://pastebin.com/T2VB43Ec

About my problem i get this this on server startup:

http://pastebin.com/7UJuik6b

Server version 1.8
Java 8

Config:
http://pastebin.com/0rb6Wk46

**Comment by boy0001** [comment]
Duplicate of https://github.com/boy0001/FastAsyncWorldedit/issues/372
