### ISSUE TITLE
How can I get offset from Schematic?

### ISSUE THREAD

**Issue by haelexuis** [boy0001/FastAsyncWorldedit#379]
If I have object Schematic, is there any way how I can get offset?
Like in WE deprecated CuboidClipboard, function .getOffset() returns Vector object, because I rewritting my old plugin to FaWE and I can't find it.

**Comment by boy0001** [comment]
The Schematic class is just a wrapper for Clipboard. You can use `clipboard = schematic.getClipboardd()` and calculate the offset from `clipboard.getRegion().getMinimumPoint()` and `clipboard.getOrigin()`.

Also, FAWE is API compatible with WorldEdit, so you don't necessarily need to port code to it.
