### ISSUE TITLE
Re-consider the config chunk-wait default value of 0.

### ISSUE THREAD

**Issue by CleanerOrc** [boy0001/FastAsyncWorldedit#38]
Please consider changing the default value of the chunk-wait setting from 0 to a value that should be safe for large paste operations.  For example issue #36 where it had to be upped to 100 to stop paste from causing duplicated chunks.

For example, using a value  that would make FAWE more stable for larger block operations and yet not cause problems other than speed reduction for smaller ones.  This  would decrease support time and increase trust in FAWE.  You could include a comment in the config file that the chunk-wait value can be decreased down to a min of 0 to speed up operations, but if you experience errors like duplicated chunks, then increase it again.

**Comment by boy0001** [comment]
Already changed in a8e335e23cfbc7dd612dd4cdac97e79c5d779c34

Loading chunks from an async thread is actually a recent addition to FAWE. It defaulted to 0 as I wasn't sure about the stability yet.

**Comment by CleanerOrc** [comment]
FWIW, I loaded a 259 Million Block schematic (one of the World of Worlds copies) and it pasted OK with chunk-wait set to 50, using //paste -a.   Estimate air was 60% of the distribution.   But this on a dedicated server with 8MB PC and 6MB Minecraft with no users.

**Comment by RoboMWM** [comment]
> 8MB PC and 6MB Minecraft with no users.

Hope you meant GB

**Comment by CleanerOrc** [comment]
Yeah, 8GB & 6 GB.  My mind was on Million Blocks at the time! :–)
