### ISSUE TITLE
Pasting a Schematic object (PacketPlayOutMapChunk)

### ISSUE THREAD

**Issue by haelexuis** [boy0001/FastAsyncWorldedit#380]
Debugpaste = https://hastebin.com/nuhoziqohu.scala (note works after pasting schematic)

Console log after pasting a schematic https://hastebin.com/efokezekah.pl
Code for pasting a schematic:
schematic.paste(FaweAPI.getWorld(origin.getWorld().getName()), new Vector(origin.getBlockX(), origin.getBlockY(), origin.getBlockZ()), false, true, (Transform) null);

When I paste schematic, I get some packet error. And everywhere in the pasted schematic is bugged light, all is dark.

Plugins (26): CleanroomGenerator, Essentials, PlugMan, Modifyworld, Multiverse-Core, TimingsParser, SkinsRestorer, SpawnUtils, FastAsyncWorldEdit, EssentialsChat, PermissionsEx, CustomJoinItems, Vault, ProtocolSupport, EssentialsSpawn, FakaHedaMinequery, WorldEdit, WorldGuard, WhatIsIt, ViaVersion, ProtocolLib, NoCheatPlus, HolographicDisplays, Basic, SkyWars

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [ ] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Sorry, I accidentally broke stuff in the last version. Try updating.

**Comment by haelexuis** [comment]
Wow, thanks, works perfect.
