### ISSUE TITLE
error with voxelsniper

### ISSUE THREAD

**Issue by PhanaticD** [boy0001/FastAsyncWorldedit#384]
# Bug report template 

**Debug paste link**:

**Description of the problem:**
noticed this in console: http://pastebin.com/raw/fiy9hq6m

**How to replicate**:

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of FAWE
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Should be fixed.
