### ISSUE TITLE
Cant do any work with Fawe : java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by Noiknez** [boy0001/FastAsyncWorldedit#385]
**Debug paste link**:

Logs : http://pastebin.com/mEXvxEb5
Fawe debugpaste : https://hastebin.com/wuwafekowo

**Description of the problem:**

When trying to execute any command with Fawe i got an error (see logs) and the command is not executed.

**How to replicate**:

Do //left & right clic with a wand --> //set 1
Error with every fawe command

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by EvilOlaf** [comment]
Just as a site note: In conclusion to your running kernel I guess your operating system is Ubuntu [Server] 12.04. Keep in mind that the support for this OS will be dropped in April 2017. It is recommended to upgrade at least to the next LTS 14.04 ("trusty").
Your Java installation is also outdated. Try upgrading to `1.8.0_111`.

**Comment by Noiknez** [comment]
"java.lang.reflect.InvocationTargetException: null"
Is something related to the langage ? because of the "lang" in the string ?
