### ISSUE TITLE
Worldguard hooks broken

### ISSUE THREAD

**Issue by popcorn9499** [boy0001/FastAsyncWorldedit#388]
https://hastebin.com/qilamicipe

Im seeming to have broken worldguard hooks in fastasyncworldedit. It just makes it so in worldguard regions i cant do worldedit to work without /wea which is a bit annoying.

**Comment by boy0001** [comment]
The hooks are working fine for me. Make sure you have the permission `fawe.worldguard` and are added to the region.

**Comment by PoisonedPanther** [comment]
I'm having this issue as well, from my testing it seems like owners of the region are allowed to worldedit, but not members. I have flagged in the region that members are allowed to build, but FAWE doesn't seem to listen to that flag, and if I set a member to owner, they can worldedit. I would like members of the region to be able to worldedit as well for my use case.

**Comment by boy0001** [comment]
@PoisonedPanther 
`fawe.worldguard.member`

**Comment by PoisonedPanther** [comment]
That perm doesn't seem to work, still have the same symptoms as before where owners of the region can worldedit but not members.
