### ISSUE TITLE
History broken as of latest commit + build

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#392]
No console errors/etc, simply get given the message "Nothing left to undo. (see also /inspect and /frb)." Nether /frb or /inspect are able to detect a worldedit having taken place.

**Comment by boy0001** [comment]
What command did you use?

**Comment by dordsor21** [comment]
set and move, didn't try others

**Comment by dordsor21** [comment]
Thanks!
