### ISSUE TITLE
bug //move

### ISSUE THREAD

**Issue by hamyuu** [boy0001/FastAsyncWorldedit#398]
Please watch movie.
https://youtu.be/M8V30m77aqw

Spigot 1.11.2
FastAsyncWorldEdit-bukkit-17.01.15-708ac6e-475-10.3.7
worldedit-bukkit-6.1.7-SNAPSHOT-dist

**Comment by dordsor21** [comment]
can confirm. Seems to be when stairs/slabs are moved such that they still overlap with the original selection. Pix:
![2017-01-17_17 28 37](https://cloud.githubusercontent.com/assets/10080017/22031996/8a944560-dcda-11e6-8cd5-4bd0007d70af.png)
![2017-01-17_17 28 41](https://cloud.githubusercontent.com/assets/10080017/22031997/8a95068a-dcda-11e6-9f30-e004ac7e5ea5.png)
![2017-01-17_17 28 47](https://cloud.githubusercontent.com/assets/10080017/22031998/8a95fc0c-dcda-11e6-8b98-19d51498bd4c.png)

**Comment by dukedase** [comment]
Yep.  The last updated I installed a day ago fixed //undo leaving blocks behind, but not //move doesn't work properly.

**Comment by Challenger2** [comment]
//move doesn't work for me either if the move distance is smaller than the size of the thing to move. It works if the movement distance is greater than the thing's size.

//undo does't work to undo a botched move either. Ah oh!

I was using version FastAsyncWorldEdit-bukkit-17.01.15-708ac6e-475-10.3.7

**Comment by belfedia** [comment]
Same here with FastAsyncWorldEdit-bukkit-17.01.15-708ac6e-475-10.3.7.jar

**Comment by UltraX3** [comment]
From what I have seen the issue lies in this commit:
https://github.com/boy0001/FastAsyncWorldedit/commit/5e2d3b25236e5e3126e6695682a12f7942c0cf18

**Comment by MassiveChoons** [comment]
Just want to corroborate OP - same issue here:


[<img src="http://i.imgur.com/da4V4mR.png">](1)

**`//move 1 u`**

[<img src="http://i.imgur.com/pTBvtRh.png">](1)

**`//move 2 u`**

[<img src="http://i.imgur.com/sqHJfxv.png">](1)

**`//move 1 d`**

[<img src="http://i.imgur.com/kq5naZC.png">](1)

Thanks for reading! Hope this can be fixed.

**Comment by wow4201** [comment]
> From what I have seen the issue lies in this commit:
812c12f

The previous build also doesn't work so cannot be that?

**Comment by UltraX3** [comment]
@wow4201 yeah, I think that is true. However, I think it is just more broken in 812c12f

**Comment by wow4201** [comment]
**Appears Fixed with the latest commit**

**Comment by hamyuu** [comment]
Thank you very match!

**Comment by belfedia** [comment]
That's fix :) Thanks !
