### ISSUE TITLE
Commands not loading

### ISSUE THREAD

**Issue by imjack** [boy0001/FastAsyncWorldedit#404]
# Bug report template 

**Debug paste link**:

Command can't be ran
**Description of the problem:**
Using Nukkit (https://github.com/Nukkit/Nukkit/commit/88fe1dcbc54917336a71bfca76a7f42a739bf31b) none of the commands work.
A error is printed once the plugin is attempted to be enabled http://pastebin.com/e8RGNMmz

**How to replicate**:

Using FAWE (FastAsyncWorldEdit v17.01.15-708ac6e-475-10.3.7) the server shows the plugin loaded in /plugin although none of the commands work.
**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Try now.

**Comment by imjack** [comment]
Seems to work great up to now. Thanks!
