### ISSUE TITLE
br 5 voxelsniper console error

### ISSUE THREAD

**Issue by Noiknez** [boy0001/FastAsyncWorldedit#406]
**Debug paste link**:

http://pastebin.com/syQTc3LQ
https://hastebin.com/olicopesuf
**Description of the problem:**
This is just an error in console, the rest work fine

**How to replicate**:
Doing /br 5
**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Should be fixed.
