### ISSUE TITLE
region-restrictions not working

### ISSUE THREAD

**Issue by GlobooX** [boy0001/FastAsyncWorldedit#414]
**Debug paste link**:
https://hastebin.com/lojofotiwu

**Description of the problem:**
region-restrictions not working. When i have FAWE installed players can use WorldEdit anywhere on PlotSquared plots. When i unninstal FAWE they can use WE only on own plot. Sorry for english..

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by GlobooX** [comment]
bump

**Comment by boy0001** [comment]
Make sure players don't have the perm `fawe.bypass`

**Comment by GlobooX** [comment]
They don't have this permission ;/

**Comment by MADS0LADEN** [comment]
Can relate

**Comment by GlobooX** [comment]
bump

**Comment by boy0001** [comment]
Having `fawe.bypass`, `fawe.admin`, being op, or having `region-restrictions: false` in the config.yml could cause the problem.
