### ISSUE TITLE
BukkitQueue18R3#getCombinedId4Data NullPointerException

### ISSUE THREAD

**Issue by andrewgazelka** [boy0001/FastAsyncWorldedit#416]
**Debug paste link**:
https://hastebin.com/epuqivajec.php

**Description of the problem:**
https://hastebin.com/acadicuqiz.vbs

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Still an issue?

**Comment by N0tMyFaultOG** [comment]
If the issue occurs still, reopen the ticket
