### ISSUE TITLE
java.io.IOException: Invalid argument

### ISSUE THREAD

**Issue by andrewgazelka** [boy0001/FastAsyncWorldedit#417]
**Debug paste link**:
https://hastebin.com/epuqivajec.php

**Description of the problem:**
https://hastebin.com/ikiyafirox.md

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Do you know what kind of object you were trying to copy with the copy brush and what radius you used?

**Comment by N0tMyFaultOG** [comment]
If the issue occurs still, reopen the ticket
