### ISSUE TITLE
//stack above 256

### ISSUE THREAD

**Issue by UltraX3** [boy0001/FastAsyncWorldedit#418]
**Debug paste link**:
https://hastebin.com/epuqivajec.php

**Video of the problem:**
[![Bug Video](https://img.youtube.com/vi/NCYfZHWTx40/0.jpg)](https://www.youtube.com/watch?v=NCYfZHWTx40)

**Comment by boy0001** [comment]
Can't replicate.

**Comment by boy0001** [comment]
I think it's just the blocks affected being wrong. `58320 x 8 = 466560` not `2099520`
