### ISSUE TITLE
Non-Cuboidal selections partially supported

### ISSUE THREAD

**Issue by Darlelet** [boy0001/FastAsyncWorldedit#419]
**Debug paste link**:
https://hastebin.com/juhapecogi

**Description of the problem:**
Trying to replace blocks selected using non-cuboidal selection method throws the following error:
```
[WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.ClassCastException: com.sk89q.worldedit.regions.(Polygonal2DRegion | EllipsoidRegion | ...) cannot be cast to com.sk89q.worldedit.regions.CuboidRegion
[...]
```

`//cut` is working fine though

**How to replicate**:
- change the selection method from cuboid to poly: `//sel poly`
- perform a simple selection using poly selection method
- replace blocks within it (eg: `//set x`)

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
[Please update the plugin.](empcraft.com/fawe/latest.php?bukkit)

**Comment by Darlelet** [comment]
isn't the plugin auto-updating when restarting the server?

**Comment by Darlelet** [comment]
My bad, just assumed it was... Sorry for wasting your time, keep up the good work :+1:
