### ISSUE TITLE
EditSessionBuilder changeSet is null

### ISSUE THREAD

**Issue by Autom3** [boy0001/FastAsyncWorldedit#420]
# Bug report template 

**Debug paste link**: https://hastebin.com/yenowejazu

**Description of the problem:** I've found a problem with the EditSessionBuilder:
`EditSessionBuilder.(...).changeSet(false, null, 0).build();` doesn't seem to be actually setting the changeSet. I used `System.out.println(editSession.getChangeSet());`, and this printed `null`.
However I was able to manually set the changeSet by using `editSession.setChangeSet(new MemoryOptimizedHistory(world));` for example.

**How to replicate**:

My full code:
```java
final World world = FaweAPI.getWorld(player.getLocation().getWorld().getName());
        EditSession editSession = new EditSessionBuilder(world)
                .autoQueue(true)
                .checkMemory(false)
                .allowedRegionsEverywhere()
                .limitUnlimited()
                .player(FawePlayer.wrap(player))
                .fastmode(true)
                .changeSet(false, null, 0)
                .build();
        System.out.println(editSession.getChangeSet());
        editSession.setChangeSet(new MemoryOptimizedHistory(world));
        System.out.println(editSession.getChangeSet());
```

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Thanks, it should be fixed in 47999d323ba6e473ae164853459e722b04497552
