### ISSUE TITLE
FAWE won't load in Thermos

### ISSUE THREAD

**Issue by Eufranio** [boy0001/FastAsyncWorldedit#421]
**Debug paste link**:
https://hastebin.com/ohahezaqil

**Description of the problem:**
FastAsyncWorldEdit won't load in a Thermos server.
Error on load: https://hastebin.com/wegacawiwo.md

**How to replicate**:
Just install Thermos, Forge-FAWE, Forge-WE and Bukkit-WE. 

Thermos 1614.58
Forge 1614
Minecraft 1.7.10
worldedit-bukkit-6.1.7-SNAPSHOT-dist
FastAsyncWorldEdit-forge1710-17.02.08-07945af-507-10.8.1
worldedit-forge-mc1.7.10-6.1.1-dist

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
You are using different versions of WorldEdit:
```
[22:07:49] [Server thread/WARN]: [WorldEdit] Multiple ports of WorldEdit are installed but they report different versions (6.1.1 and 6.1.7-SNAPSHOT;3677-000c238). If these two versions are truly different, then you may run into unexpected crashes and errors.
```

**Comment by Eufranio** [comment]
Those versions are Forge & Bukkit, WE always sent this message.
