### ISSUE TITLE
BUG: Setbiome Command Error

### ISSUE THREAD

**Issue by ItsAZZA** [boy0001/FastAsyncWorldedit#423]
**Debug paste link**: https://hastebin.com/notuseyoma

**Description of the problem:**
Every time the command //setbiome is run with a correct biome, the plugin gives this error on console: https://hastebin.com/icevomojan

**How to replicate**:

Select any region, use "//setbiome jungle" for example. The error will occur.

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
What biome is currently there?
