### ISSUE TITLE
selection bug?

### ISSUE THREAD

**Issue by hamyuu** [boy0001/FastAsyncWorldedit#424]
![2017-02-15_10 32 11](https://cloud.githubusercontent.com/assets/13864186/22957768/e5491766-f36d-11e6-80d1-01da3ca41a3c.png)
↓  //set 0
![2017-02-15_10 32 19](https://cloud.githubusercontent.com/assets/13864186/22957783/ff97cbb2-f36d-11e6-9ecf-0750f1cb6b8f.png)

Probably from build#501 or above.

**Comment by boy0001** [comment]
I can't replicate. Can you include a `/fawe debugpaste` and steps to reproduce?

**Comment by hamyuu** [comment]
debugpaste
https://hastebin.com/acadeqalig

config is all default.
no errors in log.

![fawebug01](https://cloud.githubusercontent.com/assets/13864186/22960183/33963bd6-f37f-11e6-8140-4ce2120243cd.jpg)
![fawebug02](https://cloud.githubusercontent.com/assets/13864186/22960190/3a965916-f37f-11e6-83fb-51eb1d6454c1.jpg)

**Comment by hamyuu** [comment]
It seems to be strange if **combine-stages:** is set to **false**.

sorry google translate.

**Comment by boy0001** [comment]
Replicated; CoreProtect seems to be the issue.

**Comment by boy0001** [comment]
Fixed, please update.
