### ISSUE TITLE
Incomplete //undo

### ISSUE THREAD

**Issue by hamyuu** [boy0001/FastAsyncWorldedit#425]
https://hastebin.com/udoduhulew
Config is all default.

Occurs in large edit.

![2017-02-15_21 42 04](https://cloud.githubusercontent.com/assets/13864186/22974986/3f22f892-f3c8-11e6-80e1-92f9fa3f0c1e.png)
↓ //set 0
![2017-02-15_21 42 10](https://cloud.githubusercontent.com/assets/13864186/22974992/427ec408-f3c8-11e6-9a80-df31c32bf479.png)
↓ //undo
![2017-02-15_21 42 18](https://cloud.githubusercontent.com/assets/13864186/22974995/46c2f2f0-f3c8-11e6-806f-72b1cdc685af.png)

**Comment by boy0001** [comment]
Can you attach your startup log please?

**Comment by hamyuu** [comment]
latest.log?
https://hastebin.com/pocasequka

**Comment by boy0001** [comment]
For now try disabling CoreProtect WorldEdit logging in the CoreProtect config.yml AND in BlocksHub, and see if that fixes it.

**Comment by boy0001** [comment]
Replicated; CoreProtect seems to be the issue.

**Comment by boy0001** [comment]
Fixed, please update.

**Comment by hamyuu** [comment]
Thank you for prompt response!
