### ISSUE TITLE
FAWE won't load with Thermos

### ISSUE THREAD

**Issue by Eufranio** [boy0001/FastAsyncWorldedit#426]
**Debug paste link**:
Can't paste the debug because hastebin is off :/

**Description of the problem:**
FastAsyncWorldEditForge won't work with Thermos, with an error on load.

**How to replicate**:
Install FAWE Forge on a Thermos server. Error: https://paste.ee/p/C9Ljf

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

Using:
Thermos 1.7.10-B58
FastAsyncWorldEdit-forge1710-17.02.17-3d81e98-524-10.8.20
worldedit-forge-mc1.7.10-6.1.1-dist
worldedit-bukkit-6.1.5

**Comment by boy0001** [comment]
Is WorldEdit-forge in the mods folder with FAWE? Also, can you attach your full startup log?
