### ISSUE TITLE
Completely Defected

### ISSUE THREAD

**Issue by TooVeryIcey** [boy0001/FastAsyncWorldedit#427]
**Debug paste link**:
https://hastebin.com/pobeyusaxo

**Description of the problem:**
I installed the plugin, but it simply doesn't function,...I never get any FAWE messages in chat, and the commands seems to work, but /select will either give no output, or it will say that I have no region selected. Overall, it is just acting like it isn't able to function...and yet the commands are registered

**How to replicate**:
It simply does not work...no way to replicate

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Plugins**:
`Minecraft
StatusProtocol
 SpongeVanilla
 FoxCore
 IPLog
 ClearMob
 Laborus
 PlayerShopsRPG
 FastAsyncWorldEdit
 CraftBook
 EconomyLite
 LinkMe
 Mod Coder Pack
 Prism
 SpongeAPI
 WorldEdit
 Holograms
 Nucleus
 Mailboxes
 Consensus
 Graveyards
 LuckPerms
 ServerListPlus
 BookSmith
 CommandBooks
 VoxelSniper`

**Comment by boy0001** [comment]
Ah, the injector is failing during startup. I should be able to fix soon.

**Comment by TooVeryIcey** [comment]
Awesome, Thank you!

**Comment by boy0001** [comment]
Sorry, It was fixed in SpongeForge, not SpongeVanilla yet.

**Comment by boy0001** [comment]
@TooVeryIcey 
Temporary fix, use this:
https://www.dropbox.com/s/hl77txacqoxwd27/worldedit-sponge-6.1.7-SNAPSHOT-dist.jar?dl=1
