### ISSUE TITLE
It Is Enabled, but everything except //wand gives an error

### ISSUE THREAD

**Issue by TooVeryIcey** [boy0001/FastAsyncWorldedit#429]
# Bug report template 

**Debug paste link**:
https://hastebin.com/icogokifil

**Description of the problem:**
I just tried to perform a paste, and I get an error...now after a bit of experimenting, I have noticed that basically everything except //wand gives me an error (https://hastebin.com/regapagito.sql), ingame it says "Java.lang.NoClassDefFoundError: could not initalize class com.boydti.fawe.sponge.v1_11.SpongeQueue_1_11"

**How to replicate**:
Run anything but //wand

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
If you update FAWE it should fix it. Also you should remove WorldEdit with the newer sponge version of FAWE.

If you want to deubg/discuss I am available on [IRC](webchat.esper.net/?nick=&channels=IntellectualCrafters&fg_color=000&fg_sec_color=000&bg_color=FFF).

**Comment by TooVeryIcey** [comment]
Sorry it took so long, but I am using the newest one on the release page, I will try removing worldedit now
