### ISSUE TITLE
Minor regen issues

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#43]
Tried to regen an area with fastmode enabled. After completion there were many unedited chunks which was expected due to the fastmode. Relog fixes this.
However it seems like some leafs as well as water and lava are not removed properly, see below. Not sure if this is an issue with FAWE or WorldEdit itself.

No further console output besides `Region regenerated.` available.

FAWE 3.3.22
WE 3463
1.8

![2016-04-23_08 19 16](https://cloud.githubusercontent.com/assets/3305006/14759712/30ede6d8-092c-11e6-81f3-49c8eb06c883.png)

Doing `regen` a second time over the same area fixes this.

**Comment by boy0001** [comment]
For the water / lava, is it possible that it's there because there's time to spread while the regen is taking place?

It could also be related to why the leaves are still there, so I'll look into that and hopefully it will solve both.

**Comment by EvilOlaf** [comment]
Hm good thinking. I saw the flow spread after the regen completed. However the source has not been removed properly ;)

**Comment by boy0001** [comment]
Possibly fixed

**Comment by boy0001** [comment]
Can you test?

**Comment by EvilOlaf** [comment]
Mostly fixed I think.
