### ISSUE TITLE
A lot of NPEs and schematics not pasting correctly with Thermos

### ISSUE THREAD

**Issue by Eufranio** [boy0001/FastAsyncWorldedit#433]
**Debug paste link**:
https://hastebin.com/idoqokafih

**Description of the problem:**
I have a Thermos server, and every time I make any change with FAWE, the console will print a lot of NPEs, but with no stacktrace, like this: https://hastebin.com/gigiqusole.md

Also, when placing schematics, they'll be wrong, won't paste at all, or will paste with missing parts. That's an example of the result of pasting my server spawn:

![a](http://image.prntscr.com/image/6230191b695a493c86dd15dd9773f795.png)

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

Using:
Thermos-1.7.10-B58
worldedit-bukkit-6.1.5
FastAsyncWorldEdit-forge1710-17.02.19-a080735-529-10.8.27
worldedit-forge-mc1.7.10-6.1.1-dist

**Comment by boy0001** [comment]
Looks like you had the `experimental.anvil-queue-mode` enabled. Make sure it's disabled then restart the server.

**Comment by Eufranio** [comment]
Restarted the server, the same happens (so I think this issue shouldn't be closed? or should I open a new one?)

**Comment by Eufranio** [comment]
@boy0001?
