### ISSUE TITLE
Schematics not being placed correctly with Thermos

### ISSUE THREAD

**Issue by Eufranio** [boy0001/FastAsyncWorldedit#437]
**Debug paste link**:
https://hastebin.com/eraluluvel

**Description of the problem:**
I'm pasting a schematic, and after using //paste it will not place the blocks correctly.

Screenshots: 

![1](http://image.prntscr.com/image/c0c470cb88de4ead8953b90583022e8f.png)

![2](http://image.prntscr.com/image/68b26e62a7ec465780adbf69de2e0e8d.png)

![3](http://image.prntscr.com/image/2462003c2cff4723b7c9d164b0aed6be.png)

**What it should look like:**

![1](http://image.prntscr.com/image/dfd39fba49f240b6adc4faf611f7db77.png)

![2](http://image.prntscr.com/image/0bf83040aec54a2abe5470d47a2b6c01.png)

![3](http://image.prntscr.com/image/27bd3d990bfc4450b096d690d318347d.png)

**How to replicate**:
Copy a schematic, and paste it in a Thermos server.

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

Using:
FastAsyncWorldEdit-forge1710-17.02.20-b16276e-530-10.8.30
worldedit-forge-mc1.7.10-6.1.1-dist
worldedit-bukkit-6.1.7-SNAPSHOT-dist
Thermos 1.7.10-B58

**Comment by Eufranio** [comment]
Note: with only WorldEdit, the schematic will paste correctly. Adding FastAsyncWorldEdit the problem will appear.

**Comment by boy0001** [comment]
Should be fixed.
