### ISSUE TITLE
Crash on flushQueue()

### ISSUE THREAD

**Issue by Joannou1** [boy0001/FastAsyncWorldedit#438]
Thread dump: http://pastebin.com/gRsns8FY

Debug paste: Looks like hastebin is having issues, produces an "internal_error" SSLException
at com.boydti.fawe.util.HastebinUtility.upload(HastebinUtility.java:24)
(Basic info)
Server version: Paper version git-TacoSpigot-"2b961b0f" (1.11.2)
FAWE version: 17.02.20-b16276e-530
WorldEdit: 6.1.7-SNAPSHOT;3677-000c238

**Description of the problem:**
Server crashes sometimes when a flushQueue() is executed on an EditSession.
Might be related to patterns? It happens in two separate instances of usage in the code.

**How to replicate**:
Can't reproduce consistently, seems to happen at random.
I'm using a standard EditSession builder, setting blocks to a pattern then flushing the queue.

(Simplified to show editsession interactions)
`EditSession editSession = new EditSessionBuilder(mine.getFrom().getWorld().getName()).fastmode(true).build();`
`RandomFillPattern pattern = new RandomFillPattern(blocks);`
`editSession.setBlocks(region, pattern);`
`editSession.makeCuboidWalls(region, new BaseBlock(7));`
`editSession.setBlocks(regionFloor, new SingleBlockPattern(new BaseBlock(7)));`
`editSession.flushQueue();`

**Checklist**:
- [ ] NA | I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Joannou1** [comment]
Here's another crash, happens almost daily now.
http://pastebin.com/gRsns8FY

Different flushQueue() executor this time.
Any ideas?

**Comment by Joannou1** [comment]
Hm, still seems to be crashing, the dump is a bit different this time however.
Anything I should be doing to aid debugging?

http://pastebin.com/WWk35Wy1

**Comment by boy0001** [comment]
The issue is caused when using FAWE on the main thread from an event call to remove an entity (or set some blocks, which indirectly removes the entities).
