### ISSUE TITLE
//undo on fastmode

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#44]
...is not supported, I know, but that is not the point ;)

What I did was enabling fastmode, using `//copy` and `//paste`. Tried `//undo` and got the reply that `Undo successful.` which should not be the case as there should not be any history that could be undone.  Also not sure if this is more related to WE rather than FAWE.

FAWE 3.3.22

**Comment by boy0001** [comment]
Uh, it's default WorldEdit behavior to remember the action after it's performed. I need to add a check for fastmode to exclude it. Thanks for letting me know.

**Comment by EvilOlaf** [comment]
You're welcome.
