### ISSUE TITLE
//set will not work with modded IDs

### ISSUE THREAD

**Issue by Eufranio** [boy0001/FastAsyncWorldedit#440]
**Debug paste link**:
https://hastebin.com/vajohicojo

**Description of the problem:**
I'm using //set air, and //set stone (or //set 0 and //set 1), and the IDs are not being respected if the selected block (in the area) is a modded one. Look:

**Original**:

![1](http://image.prntscr.com/image/34524d79fcae430bb2439cb588fae6b9.png)

**After //set wool**:

![2](http://image.prntscr.com/image/c4261e4855594f5b9a113d67cb5cb6f2.png)

The part that worked is inside one chunk, as you can see here:

![3](http://image.prntscr.com/image/e28acacf3309424887ded5ddb8939621.png)

The main problem is the IDs being changed. The top blocks should be wool too, but instead they were changed to another random block. Using now **//set gravel**:

![4](http://image.prntscr.com/image/9c30017978d74f15b6e04fe5fab89471.png)

**//set 0**:

![5](http://image.prntscr.com/image/73288bb8a7624e07a1a51178e9858671.png)

I hope you can fix those issues, FAWE is very useful in modded servers, since they're much more heavy.

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

Versions:
FastAsyncWorldEdit-forge1710-17.02.20-b16276e-530-10.8.30
worldedit-forge-mc1.7.10-6.1.1-dist
worldedit-bukkit-6.1.7-SNAPSHOT-dist
Thermos 1.7.10-B58

**Comment by boy0001** [comment]
Can you try the latest version?

**Comment by Eufranio** [comment]
Now, it will set the blocks to Air instead wrong modded blocks (latest).

**Comment by N0tMyFaultOG** [comment]
Update Fawe
If the issue occurs still, reopen the ticket
