### ISSUE TITLE
Smooth or mask console error

### ISSUE THREAD

**Issue by Noiknez** [boy0001/FastAsyncWorldedit#441]
**Debug paste link**:

Fawe debugpaste : https://hastebin.com/piyigiguwi
Console error : http://pastebin.com/Xkct9bks

**Description of the problem:**
I dont know maybe it is the smooth or the mask 159:7

**How to replicate**:
Trying to do smooth or mask
**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
You need to manually update FAVS since it doesn't auto-update itself yet.
