### ISSUE TITLE
ExceptionInitializerError IllegalArgumentException: Replacing commands is currently undefined behavior

### ISSUE THREAD

**Issue by BlackBeltPanda** [boy0001/FastAsyncWorldedit#443]
**Description of the problem:**
On startup, FAWE fails to initialize with the following error: http://pastebin.com/raw/QmNhWGvn

**Checklist**:

- [ ] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
I renamed a command assuming it would work and it ends up breaking the plugin. I'll be more careful in the future. 

Fixed now.
