### ISSUE TITLE
//move is buggy

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#445]
![2017-03-04_21 05 59](https://cloud.githubusercontent.com/assets/10080017/23582257/78a11b7c-011e-11e7-9155-a19015a870c0.png)
![2017-03-04_21 06 13](https://cloud.githubusercontent.com/assets/10080017/23582256/789a3262-011e-11e7-889e-3d197587795e.png)

**Comment by UltraX3** [comment]
I had a similar issue, but it was fixed sometime in the last week I believe. Which version of FAWE are you using? Can you do /fawe debugpaste ?

**Comment by Miclebrick** [comment]
I can't //undo with //move sometimes.

**Comment by dordsor21** [comment]
build 535 I think
