### ISSUE TITLE
BlocksHub won't log changes without "fawe.bypass" permission

### ISSUE THREAD

**Issue by Maxetto** [boy0001/FastAsyncWorldedit#446]
# Bug report template 

**Debug paste link**:

https://hastebin.com/igusabejol

**Description of the problem:**
When making changes with WorldEdit, blocks are logged only if I have the permission "fawe.bypass".

I have:
PaperSpigot 1.8.8
CoreProtect 2.12.0
BlocksHub 2.1.0
WorldGuard 6.1.3-SNAPSHOT (Both with Regions enabled and disabled)
WorldEdit 6.1.5
FAWE 17.03.04-e7e8337-541-10.12.0
PlotSquared 3.5.1-SNAPSHOT-aa7b770

Players have permissions:
- fawe.plotsquared
- fawe.use
- fawe.worldeditregion
- worldedit.*

**How to replicate**:

Make a change with WorldEdit.
Check using your favourite Block Logger.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Can you attach your CoreProtect and BlocksHub configuration?

**Comment by boy0001** [comment]
I can't replicate. Are they using `//fast` by any chance?

**Comment by Maxetto** [comment]
No, fast permission is denied by the group.
"- - worldedit.fast"

**Comment by boy0001** [comment]
Without `fawe.bypass` can you
 - use //undo
 - find the changes using the tool //inspect

Want to also attach your BlocksHub and CoreProtect config.yml?

**Comment by Maxetto** [comment]
As for //undo, no I can't.

For the other things I'll post them later, I'm not home right now

**Comment by boy0001** [comment]
Update, or set `fast-placement: true` in the config (in the limit second)
