### ISSUE TITLE
"cancelled: No allowed region" until entering the region

### ISSUE THREAD

**Issue by Maxetto** [boy0001/FastAsyncWorldedit#447]
# Bug report template 

**Debug paste link**:

https://hastebin.com/igusabejol

**Description of the problem:**
With PlotSquared (but may work the same with other region plugins), you will get "Your WorldEdit action was cancelled: No allowed region" until you get inside the region (the plot in this case).

I have:
PaperSpigot 1.8.8
FAWE 17.03.04-e7e8337-541-10.12.0
PlotSquared 3.5.1-SNAPSHOT-aa7b770

**How to replicate**:

Log out on the road.
Within the road, select the 2 points
Try a //set or anything.

If it doesn't work, stop the server when you're on the road, then retry.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin (Might be an extension of #101 )

**Comment by boy0001** [comment]
Normal behavior.
