### ISSUE TITLE
Question about the crash

### ISSUE THREAD

**Issue by IAlekseyI22** [boy0001/FastAsyncWorldedit#448]
I have had this problem. When using your plugin, for unknown reasons, the server hangs, and CPU load big jumps up to 100%. After replacing your on AsyncWorldEdit plugin the problem disappeared. But I would like to use your plugin, it is more convenient and less prone to crash. Please tell me whether you knew about this problem, and fixed the new versions?

Sorry for my English. I don't know him, have used a translator.

**Comment by boy0001** [comment]
Please attach the crash log.

**Comment by IAlekseyI22** [comment]
Answers forum spigot. Sorry for the duplicate.
