### ISSUE TITLE
Self-hosted web interface returns not schematic error

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#449]
`[18:02:55 INFO]: dordsor21 issued server command: //copy
[18:02:57 INFO]: dordsor21 issued server command: //download
[18:02:57 INFO]: (FAWE) Sorry, only .schematic files are allowed.
`
Console output when using //download and pointing to a self-hosted web interface. Player gets sent link still, but it "File deleted!" on the webpage and outputs (FAWE) Sorry, only .schematic files are allowed. in console

**Comment by boy0001** [comment]
Can you attach the files you are using for the interface?

**Comment by dordsor21** [comment]
[plot-download.zip](https://github.com/boy0001/FastAsyncWorldedit/files/820473/plot-download.zip)

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
