### ISSUE TITLE
Console Spam - " Could not pass event PlayerItemHeldEvent to FastAsyncWorldEdit"

### ISSUE THREAD

**Issue by GoadingGoat** [boy0001/FastAsyncWorldedit#455]
**Debug paste link**:
https://hastebin.com/neloduvege

**Description of the problem:**
Console getting spammed after using /tree, when scrolling between items in the hotbar. bound /tree to a porkchop, and then when scrolling across it, get console spam.

**How to replicate**:
 bound /tree to a porkchop, and then when scrolling across it, get console spam.

**Checklist**:

 - [X] I included a `/fawe debugpaste` link
 - [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
 - [X] I made sure I am using an up-to-date version of FAWE
 - [ ] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
I've seen this occasionally too. I do that this m it's specific to /tree

**Comment by dordsor21** [comment]
I've seen this occasionally too. I don't think that it's specific to /tree
