### ISSUE TITLE
//schematic load issue

### ISSUE THREAD

**Issue by hysteria1228** [boy0001/FastAsyncWorldedit#456]
You are unable to load schematics that are in a subfolder.

The schematic is placed in
/worldedit/schematic/build/house1.schematic

I do //schematic load build/house1.schematic (which normally works on normal world edit)
And it tells me the schematic does not exist

**Comment by dordsor21** [comment]
With the latest FAWE I believe you need to do ../build/house1

**Comment by boy0001** [comment]
You can disable `per-player-schematics`. I'll also fix this soon so that it searches both locations.
