### ISSUE TITLE
empcraft.com/fawe does not work properly

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#458]
Uploaded schematic, got URL; "File could not be read or it does not exist"

tried //download, "Failed to generate download link" and http://pastebin.com/p4j3rvBQ was outputted

**Comment by boy0001** [comment]
Works for me on the default interface.

**Comment by dordsor21** [comment]
This was the default interface. Perhaps there was some lag on the machine for empcraft? I'll give it another test

**Comment by dordsor21** [comment]
yeah, still not working

**Comment by dordsor21** [comment]
http://empcraft.com/fawe doesn't work. http://empcraft.com/fawe/ does
THE "/" IS VERY IMPORTANT!!!

**Comment by boy0001** [comment]
Hmm, didn't know. Glad it's fixed.
