### ISSUE TITLE
FAVS:  /u also undoes worldedits

### ISSUE THREAD

**Issue by braceyourself07** [boy0001/FastAsyncWorldedit#460]
Debugpaste Link:  https://hastebin.com/idetorobec

When typing /u with FAVS and FAWE loaded, the /u command also undoes WorldEdits and Voxelsniper edits.  Not sure if that was by design.

**How to replicate**:
Place blocks in worldedit (e.g. //set), place blocks in voxel, and then use /u... it will not just undo Voxelsniper blocks.

**Comment by boy0001** [comment]
It's by design. You could give players access to `worldedit.history.rollback` and `worldedit.tool.inspect` so they can inspect and undo specific edits.
