### ISSUE TITLE
WorldEdit command alias losing priorty with FAWE installed.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#461]
FAWE dev 554
WorldEdit dev 3681

WorldEdit uses /j as a shortcut alias for /jumpto. Since updating FAWE recently, /j no longer acts as an alias for WorldEdit's /jumpto command. Players are reporting they no longer have permission to use it. Debugging permissions, Essentials is instead now taking priority for its version of /jump. Removing FAWE, /j is prioritized to WorldEdit's command again.

I believe this may be the problem commit since FAWE never use to de-prioritize worldedit's aliases.
https://github.com/boy0001/FastAsyncWorldedit/commit/eb55f5fd7ddcfe64919679a4e53dbb0e2941cad3

Or may be this commit if command registration is happening after Essentials now due to the new delay.
https://github.com/boy0001/FastAsyncWorldedit/commit/b595ec2f2d11cf63e4cec335df8a211aa342cc8c

**Comment by boy0001** [comment]
You might be able to disable `j` in the essentials config: by adding it to the `disabled-commands` second.

**Comment by mibby** [comment]
There's no way to register the worldedit commands earlier like before without having to disable the ```j``` alias in Essentials? Was working as intended prior to those two commits. :(

**Comment by boy0001** [comment]
Fixed
