### ISSUE TITLE
FAWE+WorldGuard = builders cannot build

### ISSUE THREAD

**Issue by herm1ne** [boy0001/FastAsyncWorldedit#463]
# Bug report template 

**Debug paste link**:
https://hastebin.com/izexuhicap

**Description of the problem:**
I installed FAWE, as well as CoreProtect and BlocksHub. All are latest versions.  
The problem I encountered is when I set `region-restriction` to true, the "builders" cannot use FAWE on the region where they suppose to be able to build. (They can still build by hand (w/o FAWE))  
On the other hand, if I set `region-restrictions` to `false`, the "builders" can bypass WorldGuard  by using FAWE (They cannot build w/o using FAWE)  

I tried to give `fawe.worldguard` to builders but the situation does not change. (basically I couldn't understand what this permission allows)  

**How to replicate**:

Set `region-restrictions` to `true`  
Run `/rg addmember TESTRG ME` on console
Go to TESTRG then make sure I can place/remove blocks w/o FAWE
Hold wooden axe and select the area
Run `//set 1`
Got `(FAWE) Your WorldEdit action was cancelled` error (no exceptions are thrown)

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
`fawe.worldguard` and `fawe.worldguard.member` allow them to WorldEdit in WorldEdit regions they own, or are members of respectively.

**Comment by herm1ne** [comment]
so I should  
set `region-restrictions` to `true`
and give `fawe.worldguard` and `fawe.worldguard.members` to builders to let builders build on all regions which they are either owner or member
Am I right?

**Comment by boy0001** [comment]
Set `region-restrictions: true`
Give `fawe.worldguard`
Update FAWE, since I was wrong and `fawe.worldguard.member` wasn't a thing until an hour ago.

**Comment by herm1ne** [comment]
Okay, I updated the latest build and give `fawe.worldguard.member` and `fawe.worldguard` to Builder.  
However, Builders can still build by using FAWE without build privilege.  
https://t.gyazo.com/teams/umcs/e223cfb0c53103deb037ef296df1aa8b.mp4

This is the output for `/fawe paste`
https://hastebin.com/nonavaluno

Thanks in advance.

**Comment by herm1ne** [comment]
Any advice? @boy0001
