### ISSUE TITLE
FAWE tips enabled by default without the permission node.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#466]
FAWE dev 577
WorldEdit dev 3681

FAWE tips seem to be enabled by default despite not having the permission node ```fawe.tips```. I have a player who inherits all worldedit permissions with a wildcard flag ```worldedit.*```, but not the FAWE permission.

I even set it from op to false in the plugin.yml inside the jar but tips are still enabled by default. Note: He is not an OP however.
```
  fawe.admin:
    default: false
```

Would it be possible to have the tips toggleable to be set as off by default in the config, then allow players to opt-in via /tips command?

**Comment by boy0001** [comment]
The permission node disabled them.

**Comment by mibby** [comment]
I am confused. So having ```fawe.tips``` permission node actually disables the tips?

**Comment by boy0001** [comment]
Yes

**Comment by mibby** [comment]
Shouldn't it be the other way around logically? You provide the permission node to receive the tips?

**Comment by boy0001** [comment]
> Would it be possible to have the tips toggleable to be set as off by default in the config, then allow players to opt-in via /tips command?

Give them the permission node, and they can opt-in with `//tips`.

**Comment by mibby** [comment]
But that is the problem. They are already opted-in without the permission node and every time they login post server restart,, it is enabled again. With the permission node, it is still enabled by default but it gives them the option to now toggle it. I'd like to have it disabled by default always.

**Comment by boy0001** [comment]
The permission to toggle should be `fawe.use`.
