### ISSUE TITLE
Naturalize command lag & operation stops when reaching an elevation outside region selection.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#468]
FastAsyncWorldEdit dev 582
FastAsyncVoxelSniper dev 582
WorldEdit dev 3681
VoxelSniper 5.171.0-SNAPSHOT
Paper dev 1064 (Spigot 1.11.2)

FAWE Config
http://paste.ubuntu.com/24189032/

Issue 1: When you try naturalizing a region selection, it stops when it reaches the top of the region selection instead of continuing on with the rest of the terrain that is above ground inside the selection. Part of the mountain is above the region selection but it stops at the row right before the elevation extends outside the selection.

![link](http://i.imgur.com/f2oGFFX.png)
![link2](http://i.imgur.com/EUEbkY9.png)

Issue 2: When you naturalize in a region that is a bit taller so there is no part of the mountain that is outside the top of the selection, naturalizing takes forever and stops for too many checks. I assume it is checking every air block in the selection at every elevation change?

Issue 3: When a player naturalizes within a much smaller selection, it doesn't stop for too many checks but it takes a while to complete and can't be undone ```/undo```. In my specific user's case, it finished the naturalize in about 2 minutes after the command was typed and outputted 1064 blocks affected. But typing //undo did nothing, no message in chat whatsoever. As well as FAWE broke for the player afterwards. (They weren't able to use any worldedit commands). I had to force a FAWE reload and had them relog for it to function again.

Something definitely seems broken within naturalize's checks / operation behavior. This laggy and broken behavior is reproducible 100% of the time.

**Comment by boy0001** [comment]
Naturalize stopping like that happens without FAWE.

**Comment by N0tMyFaultOG** [comment]
Update Fawe
If the issue occurs still, reopen the ticket
