### ISSUE TITLE
Doing //move on a hopper with a sign attached to it makes the sign lose its text and go invisible.

### ISSUE THREAD

**Issue by MicleBrick** [boy0001/FastAsyncWorldedit#470]
**Debug paste link**:
https://hastebin.com/utijolayon

**Description of the problem:**
Something is messed up with the tile entity code and hoppers.

**How to replicate**:
1. Place a hopper
2. Put a sign on it with any text
3. Set position 1 to the hopper
4. Set position 2 to the sign
5. Look in the direction of the sign's attached face
6. Run the command //move 1
7. Enjoy your derped signs

**Comment by Miclebrick** [comment]
Bump

**Comment by Miclebrick** [comment]
This bug is back, happens with furnaces too, not just signs

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
