### ISSUE TITLE
Region restriction vertical checks.

### ISSUE THREAD

**Issue by FlamestoN** [boy0001/FastAsyncWorldedit#472]
Spigot: git-Spigot-96235ab-d345570 (MC: 1.11.2)
WorldGuard: 6.2.1-SNAPSHOT;0ba312d
FAWE: 
(FAWE) Version Date: 18.03.2016 0:00:00
(FAWE) Version Commit: 1fa63d8
(FAWE) Version Build: #587
https://hastebin.com/icamoqupij

Region restriction for //sphere works incorrectly
Video: http://snap.ashampoo.com/a4wuZAm4

**Comment by boy0001** [comment]
It should be more than just sphere.

**Comment by boy0001** [comment]
Duplicate #415
