### ISSUE TITLE
Crash server issue

### ISSUE THREAD

**Issue by Dimatert9** [boy0001/FastAsyncWorldedit#473]
Latest we. Dev build
Latest FAWE. Dev build
Spigot 1.11.2
//set 54:2
//set 54
stop server, start server. Join. Server will crash.

Video: https://youtu.be/stDXk8WXl-8

 log: https://mega.nz/#!ORoVFLYD!a_yiq2k7Ee6s3Kp-OJpdKRiWSAeaWaPWqSEZRsdfoUs

**Comment by boy0001** [comment]
Happens with an invalid configuration of chests. You could block chests in the worldedit config.yml.

**Comment by Dimatert9** [comment]
We do this. But others servers dont know this.

**Comment by Dimatert9** [comment]
I can't reproduce this without FAWE

**Comment by Dimatert9** [comment]
@boy0001 
Not fixed in latest version. 
Without fawe all god.

**Comment by Dimatert9** [comment]
@boy0001 why you dont fix this critical bug? disallowed-blocks can be bypassed with #copy flag
![image](https://cloud.githubusercontent.com/assets/8667294/26026997/ea7fc6cc-380e-11e7-8ae5-6ec0737c1628.png)

**Comment by Dimatert9** [comment]
Fast guide to corrupt world:
1) Join
2) //wand
3)
4) place some chest.  select pos 1 and 2 with chests
5) //set #copy 
6) unload and load chunk
7) make a world wipe)

**Comment by Dimatert9** [comment]
now server dont crash but there is error on startup
https://hastebin.com/vokuzanumo.md
