### ISSUE TITLE
FeatureRequest: per-player-schematics-list & and public schematic file

### ISSUE THREAD

**Issue by RedstoneFuture** [boy0001/FastAsyncWorldedit#475]
-> If I use "per-player-schematics: true": 

1.  I would like be list only my own schematics. Actually if I use /schematics list  I get the list of all schematics on the server.

2. Permission to use only the own and the public schematic.

perms: "worldedit.schematics.list.<file>"
(e.g. File: "WorldEdit/schematics/public" -> Perm: "worldedit.schematics.list.public" -> Command: "/schematic list public")

perms: "worldedit.schematics.load.<file>"
(e.g. File: "WorldEdit/schematics/public" -> Perm: "worldedit.schematics.load.public" -> Command: "/schematic load public/...")

- [X] I made sure I am using an up-to-date version of FAWE

**Comment by boy0001** [comment]
Should be fixed.

**Comment by RedstoneFuture** [comment]
Do you have added the permission-function for a public-schematic file?

**Comment by boy0001** [comment]
`//schem list [mine] [<filters>] [page]
e.g. 
`//schem list mine`
`//schem list tree`

Relevant perms:
 - `worldedit.schematic.load.other`
 - `worldedit.schematic.save.other`

**Comment by RedstoneFuture** [comment]
My Problem:

1. per-player-schematics for the player
2. public-schematic-file for all player

-> If I give the player the "..other" permission he can use all schematics of all players:

- the own per-player-schematic-file --- ok!
- the public-schematic-file --- ok!
- all other per-player-schematic-files --- not good!
