### ISSUE TITLE
Chests invisible when set

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#477]
as title suggests, when using //set or //replace to make chests, they are not visible.

**Comment by dordsor21** [comment]
possible solution: add logic checks to stop WEs of impossible blocks occurring

**Comment by Dimatert9** [comment]
Also //set chest can cause server crash. #473

**Comment by dwaynehulsman** [comment]
+1

**Comment by dordsor21** [comment]
is when setting chests next to each other, which is normal behaviour
