### ISSUE TITLE
Physics-enabled brush

### ISSUE THREAD

**Issue by Pugabyte** [boy0001/FastAsyncWorldedit#482]
[IRC log](http://paste.bn-mc.net/raw/tacij)

tl;dr A brush that will simulate the effects of physics (like //fall), since FAWE disables all WE physics, restoring the functionality of sand sphere brushes.

See: #2 #55 #172 #216 #323 #567 #572

**Comment by jacklollz2** [comment]
Want.

**Comment by Pugabyte** [comment]
Bump @boy0001 ?

**Comment by jacklollz2** [comment]
As this was bumped, I'd like to add some information.
I would love to do this.
For code efficiency, you could make the brush it's own function entirely.
I want to see this for all blocks too, not just on sand or gravel. Making big piles of dirt fall down would be fun.

**Comment by boy0001** [comment]
`//brush sphere <pattern> -f`

**Comment by MClausz** [comment]
Please reopen this issue, I still prefer the old one.

**Comment by Pugabyte** [comment]
![](https://i.imgur.com/DAr4Hhu.png)

Thank you @boy0001. :)

**Comment by boy0001** [comment]
@MClausz 
Why!? The old one is laggy and you need to wait each use for the blocks to fall? Not to mention that it's still a bad tool for creating terrain?

**Comment by Ghostlyr** [comment]
```
            if (fill instanceof BaseBlock) {
                BaseBlock block = (BaseBlock) fill;
                switch (block.getId()) {
                    case BlockID.SAND:
                    case BlockID.GRAVEL:
                        BBC.BRUSH_TRY_OTHER.send(player);
                        falling = true; // Why?
                        break;
             }
```

I can not understand why you made compulsory physics for these blocks.
Anyway, for a normal brush, the `-f` flag does not change anything.

//brush sphere 12  5 -hf:

![2018-04-15_21 06 45](https://user-images.githubusercontent.com/8511068/38779943-568df690-40f1-11e8-9414-77c28a6d78d8.png)
