### ISSUE TITLE
FAWE Undo dosent fully restore blocks

### ISSUE THREAD

**Issue by MinecraftB0ss** [boy0001/FastAsyncWorldedit#485]
# Bug report template 

**Debug paste link**:

https://hastebin.com/upehuridix

**Description of the problem:**
I select a block with both positions, and expand it by 1000 on x/z and completely vertically. I then set the region to stone. I then did "/undo" on it, however a majority of the area that was replaced with stone was essentially the equivalent of setting it to air. It didnt replace the blocks that were there previously.

**How to replicate**:

It does the same thing every time I do the above, however the chunks it voids are random, there seems to not be any pattern to that.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

History file:
[12.zip](https://github.com/boy0001/FastAsyncWorldedit/files/874171/12.zip)

**Comment by dordsor21** [comment]
Possibly related, but seen some odd behaviour where some of the WE "comes back" after an undo. Starts happening after a while, and stops happening at a random point afterwards.

Config: https://hastebin.com/fozulabaga.coffeescript

(it's possible this may have been fixed after setting delay-packet-sending to false?)

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
