### ISSUE TITLE
BlockPhysicsEvent Causes Lags

### ISSUE THREAD

**Issue by GeorgeMelikyan** [boy0001/FastAsyncWorldedit#486]
**Hello, boy0001!**
Thanks you for the amazing plugin!
I was faced with a serious problem.

https://hastebin.com/tazelunilu

I have a survival server with creative elements. Server from Russia.
Recently, when online over from 100 people, I notice strong sagging.

MassiveLag indicates _FAWE_ as a loading plugin:
https://hastebin.com/huzumeneti.css

I see that the problem with the physics of the blocks, but how can I reduce the load?

**Comment by boy0001** [comment]
So the chunk listener is to prevent FAWE abuse (e.g. setting an entire chunk to torches). If you aren't worried about this then you can disable the `tick-limiter` in FAWE's `config.yml`. 

I've also made some optimizations to the event in the case where you want to keep this functionality.
