### ISSUE TITLE
BUG on startup  java.lang.NoClassDefFoundError: 

### ISSUE THREAD

**Issue by GlobooX** [boy0001/FastAsyncWorldedit#488]
# Bug report template 

**Debug paste link**:
https://hastebin.com/iwutanemer

**Description of the problem:**
Bug on server startup: https://pastebin.com/ALYnt2ct

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
It should be fixed in the latest version.
