### ISSUE TITLE
Missing database(?) error on modifications

### ISSUE THREAD

**Issue by Eufranio** [boy0001/FastAsyncWorldedit#489]
**Debug paste link**:
https://hastebin.com/jeqifunixi

**Description of the problem:**
I'm having issues using //set, //replace and all those commands that modifies something. 
Stacktrace: https://hastebin.com/nimahukebe.md

Using FAWE Sponge

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Make sure the server has write access to `FastAsyncWorldEdit/<world>/summary.db`. 

If that doesn't work, you can disable `use-database` in the settings.yml.
