### ISSUE TITLE
FixWater / FixLava is broken / reporting incorrect number of blocks fixed.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#492]
FAWE dev 623
WorldEdit dev 3682
Paper dev 1079 (Spigot 1.11.2)

Stood slightly above the edge of this water. Then typed ```/fixwater 25```. It did not fix the water and outputted that 30,000+ blocks were fixed. Surely that can't be the correct number? Even making a small puddle and typing ```/fixwater 25``` outputs ~20k blocks fixed.
![link](http://i.imgur.com/UXyaMFy.png)

**Comment by boy0001** [comment]
So with combine stages enabled, it sets the block even if it's already water.
