### ISSUE TITLE
Invisible Blocks in the Nether and in the End

### ISSUE THREAD

**Issue by TheoRetisch1** [boy0001/FastAsyncWorldedit#493]
If you use fawe in the Nether or the End added Blocks turn invisible. You have to reload the chunks to see your changes. It doesn’t matter how you add blocks, just use copy, stack or something similar to reproduce. In worlds with the attribute normal everything works fine.

FAWE: 17.04.05-7c4934-624-11.10.1
Worldedit: 6.1.7-SNAPSHOT;3682-41de204
PaperSpigiot: 1.11.2 Version 1079

**Comment by boy0001** [comment]
Can't replicate.
