### ISSUE TITLE
Itemframes doesn’t rotate

### ISSUE THREAD

**Issue by TheoRetisch1** [boy0001/FastAsyncWorldedit#494]
It is not possible to rotate Itemframes, they just stay in their old position and fall down while everything else is rotated.
1.	Copy a structure with Itemframes 
2.	type //rotate [degress]
3.	//paste

FAWE: 17.04.05-7c4934-624-11.10.1
Worldedit: 6.1.7-SNAPSHOT;3682-41de204
PaperSpigiot: 1.11.2 Version 1079

**Comment by dordsor21** [comment]
#210
