### ISSUE TITLE
“//Set 0” or “//cut” doesn’t work for armorstands

### ISSUE THREAD

**Issue by TheoRetisch1** [boy0001/FastAsyncWorldedit#495]
One can’t remove armorstands with //Set 0 or //cut they just stay and/or fall down. If you use //cut you can copy and paste the armorstands but they won’t be deleted and tied up at their old spot.

FAWE: 17.04.05-7c4934-624-11.10.1
Worldedit: 6.1.7-SNAPSHOT;3682-41de204
PaperSpigiot: 1.11.2 Version 1079

**Comment by dordsor21** [comment]
#210
