### ISSUE TITLE
Schematics doesn’t contain armorstands or itemframes

### ISSUE THREAD

**Issue by TheoRetisch1** [boy0001/FastAsyncWorldedit#496]
If you paste a schematic with Armorstands and itemframes those doesn’t show up. If you paste the same schematic without fawe enabled the armorstands and itemframes are included.

FAWE: 17.04.05-7c4934-624-11.10.1
Worldedit: 6.1.7-SNAPSHOT;3682-41de204
PaperSpigiot: 1.11.2 Version 1079

**Comment by dordsor21** [comment]
#210

**Comment by boy0001** [comment]
Can't replicate.
