### ISSUE TITLE
Enhancement: Allow temporary disabling of FAWE

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#50]
Sometimes you run in a situation where you don't want to use FAWE during your WorldEdit edits. Be it because you run into a bug or whatever.

So my suggestion is to add a command to disable the FAWE wrapper for the executing player and let him use WorldEdit the direct (inefficient) way.

**Comment by boy0001** [comment]
FAWE is too invasive i.e. classes are replaced during startup, and adding checks for every method call to revert to original behavior would be too costly (performance wise).

It may be feasible to revert specific behavior, but not much.

**Comment by RoboMWM** [comment]
Fyi AWE free is able to do this.

**Comment by EvilOlaf** [comment]
I know that ;)

**Comment by boy0001** [comment]
No, AWE can't do this. AWE has a toggle for it being async. It still has its injected classes. The main difference being AWE doesn't go out of it's way to rewrite as much of WorldEdit as FAWE does, so most problems, if any, would be from the block placer.

I can also add a toggle for block placement, but it's a much smaller part of the plugin, and it wouldn't fix your `//move` bug.
