### ISSUE TITLE
//thru error

### ISSUE THREAD

**Issue by mikroskeem** [boy0001/FastAsyncWorldedit#500]
**Debug paste link**: https://hastebin.com/idoxobegeh

**Description of the problem:**
`//thru` is broken and throws CCE to console.

**How to replicate**:
1. Install FAWE version shown in debug paste  
2. Do `//thru`  
3. You should see something like [this in console](https://paste.nightsnack.cf/zukugicefo.rb)

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Extra info about lines at start of the log:**
Server uses [Orion](https://github.com/mikroskeem/Orion) core, which modifies server internals little bit, but I am completely sure it doesn't blow up anything related to FAWE or WE itself.

**Comment by Flavourized** [comment]
I can confirm this.  Latest update breaks /thru

stack: https://paste.nightsnack.cf/medexuxawo.apache

Server: Paper1.9.4
Worldedit: 6.1.3
FAWE: Latest

**Comment by boy0001** [comment]
Was fixed
