### ISSUE TITLE
Prefix

### ISSUE THREAD

**Issue by MADS0LADEN** [boy0001/FastAsyncWorldedit#501]
It's not an issue.
it would be nice if the prefix had the space inside instead of in the hard code
![image](https://cloud.githubusercontent.com/assets/4103363/24874344/97503076-1e24-11e7-9bfd-eecb7bfb61d3.png)
![image](https://cloud.githubusercontent.com/assets/4103363/24874373/acb3a600-1e24-11e7-9ad5-8afe05e73fb1.png)
in the config there's no space, but there's a space ingame

**Comment by boy0001** [comment]
If it's empty there won't be a space, just put the color code in the messages.
