### ISSUE TITLE
FAWE destroys sign and skull data on undo.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#502]
FAWE dev 636
WorldEdit dev 3682
Paper dev 1081

When you worldedit something and ```//undo```, it does not restore sign or skull data. Such as if you had a sphere brush of air, accidentally right click to destroy an area with written sign text and player heads, then undo your operation, it does not restore the data. And sometimes, the signs are there but invisible.

**Comment by mibby** [comment]
@boy0001 Apparently FAWE can't handle any type of NBT data anymore. Even chests when they get rolled back, don't preserve the data in the undo cache. Chests, signs, skulls, and other stuff.

**Comment by Flavourized** [comment]
Can confirm this. Happens also with item frames and items inside item frames.

Latest fawe
W.e 6.1.3
Paper 1.9.4 b773

**Comment by EvilOlaf** [comment]
confirmed with `FAWE 17.10.3-4150413-916`
on `WE 6.1.5;4651611`
on `Spigot 1.8.8`

`//undo` does not restore *sign text* after using `//regen` on area. 

Thanks for reading.
