### ISSUE TITLE
Suggestion: Add a command to activate and deactivate fawe

### ISSUE THREAD

**Issue by TheoRetisch1** [boy0001/FastAsyncWorldedit#505]
I would like to suggest a command to activate and deactivate fawe without restarting the server. So that a admin can easily decide if he or she wants to use normal worldedit or fawe for a specific task. 

Let me explain: On a server there is more going on than just building, you need worldedit for a bunch of tasks. Its very hard to finish those task with all the bugs. You have to see what you are doing in the nether and the end, you have to rotate items frames, load schematics with armorstands and dealing with lightbugs and -a undo during an event is a huge problem. On the otherside fawe is absolutly amazing for terraforming, building or performance matters. One just keeps exploring the possibilities of the new feature. I want both: I want all the new possibilities and the option to use a working system for general server stuff without having to restart the server every two hours.

**Comment by boy0001** [comment]
Not going to happen. See: https://github.com/boy0001/FastAsyncWorldedit/issues/50

It would be easier to fix the issues if you provided the debug information it asks of you when reporting issues.
