### ISSUE TITLE
Replace command does not work for mod IDs

### ISSUE THREAD

**Issue by TomberWolf** [boy0001/FastAsyncWorldedit#506]
Sind newer versions of MC WorldEdit has to use block names instead of IDs for mod blocks which doesn't work with FAWE for SpongeForge 1.10.2.

Example:
`//replace 159 conquest:stone_full_11`

**Comment by boy0001** [comment]
The blocks still have an id internally, it's just non-obvious. Use FAWE-forge and WorldEdit-Forge and it should fix the issue.

**Comment by TomberWolf** [comment]
So no chance with the Sponge version?

**Comment by TomberWolf** [comment]
I've tried the Forge version with no success.
Same errors as with the Sponge version.

![fawe_mod_replacement](https://cloud.githubusercontent.com/assets/9993839/25202943/946b6b84-2557-11e7-91d5-104fe1181d26.png)
