### ISSUE TITLE
No platform was found supporting CONFIGURATION

### ISSUE THREAD

**Issue by Eufranio** [boy0001/FastAsyncWorldedit#507]
That error is printed on server stop or player quit:
```
> [20:59:37 ERROR]: Exception stopping the server
com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
    at com.sk89q.worldedit.extension.platform.PlatformManager.queryCapability(PlatformManager.java:186) ~[PlatformManager.class:?]
    at com.sk89q.worldedit.extension.platform.PlatformManager.getConfiguration(PlatformManager.java:314) ~[PlatformManager.class:?]
    at com.sk89q.worldedit.WorldEdit.getConfiguration(WorldEdit.java:801) ~[WorldEdit.class:?]
    at com.sk89q.worldedit.session.SessionManager.get(SessionManager.java:172) ~[SessionManager.class:?]
    at com.sk89q.worldedit.WorldEdit.getSession(WorldEdit.java:210) ~[WorldEdit.class:?]
    at com.boydti.fawe.object.FawePlayer.getSession(FawePlayer.java:376) ~[FawePlayer.class:?]
    at com.boydti.fawe.object.FawePlayer.unregister(FawePlayer.java:447) ~[FawePlayer.class:?]
    at com.boydti.fawe.forge.ForgeMain.handleQuit(ForgeMain.java:59) ~[ForgeMain.class:?]
    at com.boydti.fawe.forge.ForgeMain.onPlayerQuit(ForgeMain.java:46) ~[ForgeMain.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_300_ForgeMain_onPlayerQuit_PlayerLoggedOutEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.58]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.58]
    at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:582) ~[FMLCommonHandler.class:1.7.10-1614.58]
    at net.minecraft.server.management.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:446) ~[oi.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:953) ~[nh.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147360_c(NetHandlerPlayServer.java:289) ~[nh.class:?]
    at net.minecraft.server.management.ServerConfigurationManager.func_72392_r(ServerConfigurationManager.java:1689) ~[oi.class:?]
    at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:586) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:755) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```
Running FAWE Forge 1.7.10 on a Thermos Server and WorldEdit 6.1.

**Comment by boy0001** [comment]
Make sure you have the following
FAWE-Forge (in `mods/` for 1.7.10)
WorldEdit-Forge (in `mods/` for 1.7.10)
WorldEdit-Bukkit (in `plugins/` - latest version)

**Comment by Eufranio** [comment]
I have.

**Comment by boy0001** [comment]
Want to provide your startup log and FAWE `config.yml` then.

**Comment by Eufranio** [comment]
config.yml (altrough it's the default one): https://hastebin.com/igoyifebiq.coffeescript
The startup logs don't contain any errors, still wanting them? That happens with a clean setup too.

**Comment by boy0001** [comment]
Yes

**Comment by Tjaartvb** [comment]
hi guys im a noob pls help me with these errors 
6:47:57 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:47:57 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:47:57 PM CONSOLE: Source) ~[?:?]
6:47:57 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:47:58 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:47:58 PM CONSOLE: Source) ~[?:?]
6:47:58 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:47:58 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:47:58 PM CONSOLE: Source) ~[?:?]
6:47:58 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:47:58 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:47:58 PM CONSOLE: Source) ~[?:?]
6:47:58 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:47:59 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:47:59 PM CONSOLE: Source) ~[?:?]
6:47:59 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:47:59 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:47:59 PM CONSOLE: Source) ~[?:?]
6:47:59 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:47:59 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:47:59 PM CONSOLE: Source) ~[?:?]
6:47:59 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:00 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:00 PM CONSOLE: Source) ~[?:?]
6:48:00 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:00 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:00 PM CONSOLE: Source) ~[?:?]
6:48:00 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:00 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:00 PM CONSOLE: Source) ~[?:?]
6:48:00 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:00 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:01 PM CONSOLE: Source) ~[?:?]
6:48:01 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:01 PM CONSOLE: Source) ~[?:?]
6:48:01 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:01 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:01 PM CONSOLE: Source) ~[?:?]
6:48:01 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:01 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:02 PM CONSOLE: Source) ~[?:?]
6:48:02 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:02 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:02 PM CONSOLE: Source) ~[?:?]
6:48:02 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:02 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:02 PM CONSOLE: Source) ~[?:?]
6:48:02 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:02 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:02 PM CONSOLE: Source) ~[?:?]
6:48:02 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:03 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:03 PM CONSOLE: Source) ~[?:?]
6:48:03 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:03 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:03 PM CONSOLE: Source) ~[?:?]
6:48:03 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:03 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:03 PM CONSOLE: Source) ~[?:?]
6:48:03 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:04 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:04 PM CONSOLE: Source) ~[?:?]
6:48:04 PM CONSOLE: [INFO] LadyJools issued server command: /hologram create pshop &8----------***----------
6:48:04 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:04 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:04 PM CONSOLE: Source) ~[?:?]
6:48:04 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:04 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:04 PM CONSOLE: Source) ~[?:?]
6:48:04 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:05 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:05 PM CONSOLE: Source) ~[?:?]
6:48:05 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:05 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:05 PM CONSOLE: Source) ~[?:?]
6:48:05 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:05 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:05 PM CONSOLE: Source) ~[?:?]
6:48:05 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:05 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:06 PM CONSOLE: Source) ~[?:?]
6:48:06 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:06 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:06 PM CONSOLE: Source) ~[?:?]
6:48:06 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:06 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:06 PM CONSOLE: Source) ~[?:?]
6:48:06 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:06 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:07 PM CONSOLE: Source) ~[?:?]
6:48:07 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:07 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:07 PM CONSOLE: Source) ~[?:?]
6:48:07 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:07 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:07 PM CONSOLE: Source) ~[?:?]
6:48:07 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:07 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:07 PM CONSOLE: Source) ~[?:?]
6:48:08 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:08 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:08 PM CONSOLE: Source) ~[?:?]
6:48:08 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:08 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:08 PM CONSOLE: Source) ~[?:?]
6:48:08 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:08 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:08 PM CONSOLE: Source) ~[?:?]
6:48:08 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:09 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:09 PM CONSOLE: Source) ~[?:?]
6:48:09 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:09 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:09 PM CONSOLE: Source) ~[?:?]
6:48:09 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:09 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:09 PM CONSOLE: Source) ~[?:?]
6:48:09 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:10 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:10 PM CONSOLE: Source) ~[?:?]
6:48:10 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:10 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:10 PM CONSOLE: Source) ~[?:?]
6:48:10 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:10 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:10 PM CONSOLE: Source) ~[?:?]
6:48:10 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:10 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:11 PM CONSOLE: Source) ~[?:?]
6:48:11 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:11 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:11 PM CONSOLE: Source) ~[?:?]
6:48:11 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:11 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:11 PM CONSOLE: Source) ~[?:?]
6:48:11 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:11 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:12 PM CONSOLE: Source) ~[?:?]
6:48:12 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:12 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:12 PM CONSOLE: Source) ~[?:?]
6:48:12 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:12 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:12 PM CONSOLE: Source) ~[?:?]
6:48:12 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:12 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:12 PM CONSOLE: Source) ~[?:?]
6:48:13 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:13 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:13 PM CONSOLE: Source) ~[?:?]
6:48:13 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:13 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:13 PM CONSOLE: Source) ~[?:?]
6:48:13 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:13 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:13 PM CONSOLE: Source) ~[?:?]
6:48:13 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:14 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:14 PM CONSOLE: Source) ~[?:?]
6:48:14 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:14 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:14 PM CONSOLE: Source) ~[?:?]
6:48:14 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:14 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:14 PM CONSOLE: Source) ~[?:?]
6:48:14 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:15 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:15 PM CONSOLE: Source) ~[?:?]
6:48:15 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:15 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:15 PM CONSOLE: Source) ~[?:?]
6:48:15 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:15 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:15 PM CONSOLE: Source) ~[?:?]
6:48:15 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:16 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:16 PM CONSOLE: Source) ~[?:?]
6:48:16 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:16 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:16 PM CONSOLE: Source) ~[?:?]
6:48:16 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:16 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:16 PM CONSOLE: Source) ~[?:?]
6:48:16 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:16 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:17 PM CONSOLE: Source) ~[?:?]
6:48:17 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:17 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:17 PM CONSOLE: Source) ~[?:?]
6:48:17 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:17 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:17 PM CONSOLE: Source) ~[?:?]
6:48:17 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:17 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:17 PM CONSOLE: Source) ~[?:?]
6:48:18 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:18 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:18 PM CONSOLE: Source) ~[?:?]
6:48:18 PM CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v18.04.15-d1231fb-1064-19.4.27
6:48:18 PM CONSOLE: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
6:48:18 PM CONSOLE: Source) ~[?:?]
