### ISSUE TITLE
FAWE [BIG BUG]

### ISSUE THREAD

**Issue by Alex0Klain** [boy0001/FastAsyncWorldedit#510]
Hello.
I have a problem with your plugin.
The problem is that a player has commands of WorldEdit, but he is without permissions for their use anywhere (they can use it only in themselves regions) can use them in bypass of the protection.
Algorithm of player's action:
1. Created region with /rg claim, but player stay inside it
2. Written command //expand with necessary parameters
3. After all used //set (also with necessary params).
So: player used //set (maybe not only them, example: //walls) easy bypassing the protection.

**Comment by boy0001** [comment]
Don't give them `fawe.admin` or disable region restrictions.
