### ISSUE TITLE
Peature-Request: add messages for Right-click with compass on the air

### ISSUE THREAD

**Issue by RedstoneFuture** [boy0001/FastAsyncWorldedit#511]
**Description of the problem:**
Can you add a messages-definition-function for the right-click-messages with a compass, please?

**How to replicate**:
Right-click with a compass on the air -> You get the default worldedit messages "Nothing to pass throught".

- [X] I made sure I am using an up-to-date version of FAWE

**Comment by boy0001** [comment]
NAVIGATION_WAND_ERROR
