### ISSUE TITLE
FAVS VoxelSniper Filldown Brush no longer functions at all

### ISSUE THREAD

**Issue by jmck95** [boy0001/FastAsyncWorldedit#512]
# Bug report template 

**Debug paste link**: https://hastebin.com/ilaholelaf

**Description of the problem:**
Hello, We are currently trying to setup an area using FAWE, FAVS, and WorldGuard for people of a specific rank to use VoxelSniper and WorldEdit within a restricted area. However, when FAVS is installed on the server, the VoxelSniper Filldown brush ceases to function for all ranks. I am unsure as to whether or not this is a limitation of FAVS in which the brush is simply just canceled, or a bug. Even when I attempt to use it, no errors or anything appear in console.

**How to replicate**:

I have been able to reproduce this issue on our main server, as well as my own personal test server. In both instances, the VoxelSniper Filldown brush ceases to function. It does not matter if it is within a restricted region, it ceases to function across the server in its entirety. Upon uninstalling FAVS, the functionality returns to normal.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
still broken?

**Comment by jmck95** [comment]
Apologies for necroposting on this, but yes it is still broken. I have no idea why. I have tried almost everything I can think of to try and get it working. Even with a default spigot 1.12 server with only FAWE, FAVS, VoxelSniper, WorldGuard, WorldEdit, and Vault installed, it ceases to function. Is there anything I can do to provide more information?

**Comment by jmck95** [comment]
It seems to be an issue with liquid detection in VoxelSniper. I was able to get it working with some duct tape code and compiling my own version.

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
