### ISSUE TITLE
Plotsquared region protection 

### ISSUE THREAD

**Issue by Noiknez** [boy0001/FastAsyncWorldedit#513]
In the latest beta of FAWE, the permission fawe.plotsquared does not work at all and everybody with this permission can sadly use worldedit on all non-plot world

Regards

Spigot : git-Spigot-9ba269b-c19c293 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
Fawe version : #660 (22 avr. 2017 12:23:06) 
Debugpaste : https://hastebin.com/dixevuyazu

**Comment by boy0001** [comment]
Can't replicate. 
Make sure you haven't toggled region restrictions by using `/wea` and don't have the `fawe.bypass` perm.

**Comment by boy0001** [comment]
Fixed the issue. However, I suggest if you don't want them to WorldEdit in that world, the best solution is to not give them WorldEdit perms. Most permissions plugins support per world permissions.

**Comment by dordsor21** [comment]
@boy0001 it's much easier to  give all permissions every, then restrict where you can WE than do WE perms many times for many different worlds

**Comment by Noiknez** [comment]
@boy0001 Thank you for the fix

@boy0001 @dordsor21 I can only fully agreed to this, much easier
