### ISSUE TITLE
Suggestion: Multiverse Compatibility

### ISSUE THREAD

**Issue by CeairMC** [boy0001/FastAsyncWorldedit#515]
Hello, 

I wanted to know if you could make permissions to give WorldEdit access to specific world? something like that:
fawe.world.<world_name>

Thanks in advance !

**Comment by dordsor21** [comment]
just use per-world permissions. Pretty much all permissions plugins have this feature. You could also use the group-feature of adding people to WRG regions, and add the default group to the __global__ region in worlds where people should be able to WE.
