### ISSUE TITLE
FAWE interferes with NPC/Worldguard interaction.

### ISSUE THREAD

**Issue by Sparclen** [boy0001/FastAsyncWorldedit#518]
**Description of the problem:**
Installing FAWE makes NPC's from the 'citizens' plugin invulnerable to damage when they are located in a worldguard non-pvp zone. Upon removal of FAWE, these NPC's can once again be damaged by players.

**How to replicate**:
1. Install Citizens + Sentinel addon.
2. Install worldguard.
3. Create a sentinel npc in a non-pvp worlguard zone.
4. The NPC is vulnerable to players, as it should be.
5. Install FAWE.
6. The NPC has suddenly become invulnerable.

**Additional info**:
No console error.
Plugins were removed 1 by 1, 100% fact that FAWE is responsible, this has been tested multiple times with consistent results.

**Comment by boy0001** [comment]
Please attach the `/fawe debugpaste`

**Comment by dordsor21** [comment]
@Sparclen bump

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
