### ISSUE TITLE
nukkit crazy console spam java.lang.NoClassDefFoundError: org/json/simple/parser/ParseException

### ISSUE THREAD

**Issue by PhanaticD** [boy0001/FastAsyncWorldedit#521]
https://pastebin.com/7a5PBvKK

FAWE: https://github.com/boy0001/FastAsyncWorldedit/commit/fb779a8daa08bc770e402ba32a45037aa3a7046d

nukkit latest

**Comment by BrainStone** [comment]
Same in Sponge and Forge
