### ISSUE TITLE
% of collection of blocks as pattern

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#525]
pretty much //br sphere 50%3,50%(121,5:2,12) would be cool, so 50% dirt, and the other 50% 121, 5:2 or 12

**Comment by boy0001** [comment]
One of the following might work:
`//set 4%3,121,5:2,12`
`//set 3,"121,5:2,12"`
`//set 50%3,50%"121,5:2,12"`

**Comment by dordsor21** [comment]
`//br sphere 2,"3,4" 5` doesn't work
`//set 4%3,121,5:2,12` this seems to work? does this means 4:7 of 3 and 1:7 of each of 121 5:2 and 12?
`//set 50%3,50%"121,5:2,12"` also doesn't work

**Comment by boy0001** [comment]
Pattern syntax has changed. Try: `50%3,50%[121,5:2,12]`
