### ISSUE TITLE
FAWE completely broken

### ISSUE THREAD

**Issue by georgster** [boy0001/FastAsyncWorldedit#528]
# Bug report template 

**Debug paste link**:

07.05 09:20:31 [Server] WARN java.lang.NoSuchMethodError: com.sk89q.minecraft.util.commands.CommandContext.split(Ljava/lang/String;)[Ljava/lang/String;
07.05 09:20:31 [Server] WARN at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:113)
07.05 09:20:31 [Server] WARN at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:378)
07.05 09:20:31 [Server] WARN at com.sk89q.worldedit.extension.platform.CommandManager$2$1.run(CommandManager.java:450)
07.05 09:20:31 [Server] WARN at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:140)
07.05 09:20:31 [Server] WARN at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:168)
07.05 09:20:31 [Server] WARN at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:215)
07.05 09:20:31 [Server] WARN at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:447)
07.05 09:20:31 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
07.05 09:20:31 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
07.05 09:20:31 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
07.05 09:20:31 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
07.05 09:20:31 [Server] WARN at java.lang.Thread.run(Thread.java:745)
**Description of the problem:**
Well, as you can see, I can't even do a debug paste...
I can not execute any commands whatsoever, it just all of a sudden broke on my server.
I have tried reinstalling worldedit and FAWE completely, along with clearing their files.

**How to replicate**:

I don't know how to replicate, the whole thing is just broken.

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of FAWE
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Can you attach your startup log please?

**Comment by georgster** [comment]
https://pastebin.com/gC0g7pFz

**Comment by boy0001** [comment]
Using outdated version of WorldEdit, please update:
http://builds.enginehub.org/job/worldedit/
