### ISSUE TITLE
Brushes no longer consider water a surface layer.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#529]
FAWE 7.05.07-1e31827-684-12.7.1
WorldEdit dev 3684
Paper dev 1095 (Spigot 1.11.2)

@boy0001 Brushes don't consider water blocks as a surface anymore. Aiming a brush at water just ignores it and paints the surface underneath it. 

Setting a brush ```/br sphere air 15``` , ```//mask water``` use to act on the surface of the water and clear a 15 wide circle from the top. Now, it still cuts a circle that size, but does it from the bottom of the ocean instead of the top. In other words, if the water is more than 15 blocks from the surface of the ocean, you won't be able to get rid of it all with brushes anymore. Another example is setting the top-most layer of water to ice - does it from the bottom up since the top-most part of the water isn't considered a layer.

**Comment by dordsor21** [comment]
might be better behaviour

**Comment by boy0001** [comment]
It was changed to ignore non solid blocks. Mostly since having grass, flowers or other decorations messed up some brushes.

**Comment by boy0001** [comment]
Okay, I've added `//targetmask <mask>`, to set the brush target mask. 

So to target anything not air, use `//targetmask !0`
