### ISSUE TITLE
FAWE Possibly causing main thread hang?

### ISSUE THREAD

**Issue by Joannou1** [boy0001/FastAsyncWorldedit#531]
It's difficult to tell if FAWE is the cause of this, but a couple people on Paperspigot https://github.com/PaperMC/Paper/issues/681 have suggested at FAWE causing a main thread hang.

Should give that issue a look over and see if FAWE could be responsible, FAWE is used probably a hundred thousand times a day by our players to create rooms from a template editor and there's a good chance that this hang/crash is occurring when players are adding/removing rooms.

I'll try to get some debug info for you to figure out what the last thing occurring before the hang is, is there a debug option to get more details when operations are underway? I saw the extent debug, but I'm not sure that's the right debug option.

Paper version git-Paper-1095
FastAsyncWorldEdit version 17.05.07-1e31827-684-12.7.1
WorldEdit version 6.1.7-SNAPSHOT;3682-41de204

**Comment by boy0001** [comment]
`/fawe debugpaste`

Try setting `lighting.async: false` and `parallel-threads: 1`.

**Comment by boy0001** [comment]
You doing anything with world borders?

**Comment by Joannou1** [comment]
Ah alright, well, debugpaste seems to have some issues:
javax.net.ssl.SSLException: Received fatal alert: internal_error

Here's threads on a healthy server:
https://hastebin.com/besesutuye.md

I'll try those settings soon, got a bit of an event coming up and don't want to change anything till that storm has passed

As for the level.dat's, I could probably try to grab them from all the worlds loaded at the time the next time one crashes.
There are usually 10-30 worlds loaded at once however, just depends (this specific gamemode requires multiple worlds for each player)

**Comment by boy0001** [comment]
> Ah alright, well, debugpaste seems to have some issues:
javax.net.ssl.SSLException: Received fatal alert: internal_error

You might be using an older version of FAWE.

**Comment by Joannou1** [comment]
It's not that old?
17.05.07-1e31827-684-12.7.1

few days ago?

**Comment by boy0001** [comment]
Oh, nvm then. Something else must be causing the debugpaste to fail uploading to hastebin.

**Comment by Joannou1** [comment]
I've got some level.dat's here, these were loaded at the time of crash.
Included is also a debug log of the last 20 seconds or so of player movement / chunk loads / etc

http://gld.bz/uploads/levelDats.rar

**Comment by boy0001** [comment]
Try this:
https://www.dropbox.com/s/1byll9asj3fi7yq/paper-1.11.2.jar?dl=1

**Comment by Joannou1** [comment]
Alright, tried that version, didn't take long before I saw your debug lol
Log file ended being 45GB with this: https://hastebin.com/cuzomuhoma.sql

**Comment by boy0001** [comment]
Any mentions of FAWE, or is it only paper doing bad stuff async?

**Comment by Joannou1** [comment]
I can't really tell because the log file is so huge

**Comment by boy0001** [comment]
Did the server still crash?

**Comment by Joannou1** [comment]
It didn't crash that time, it was just 100% occupied with the infinite Blockposition/blockstate/chunk thing, hence the 45GB log
