### ISSUE TITLE
NBT Data Error

### ISSUE THREAD

**Issue by CruaverVoidDrake** [boy0001/FastAsyncWorldedit#535]
# Bug report template 
**Debug paste link**: https://hastebin.com/yixeyeguqa

**Description of the problem:**
After much experimentation I have figured out why sometimes when I am setting air in places I want to clear, everything "goes to chunk hell" as I've called it. Most of the build or area goes away but isolated chunks remain unaffected.

**How to replicate**:
Simply put NBT data items like chests cause some kind of error in the system making it halt on that area. While I don't mind leaving the chests behind in case I forgot something important like a custom spawn egg, it really shouldn't stop the clearing process.

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
