### ISSUE TITLE
Feature Request: surface option for height brush

### ISSUE THREAD

**Issue by JakBBB** [boy0001/FastAsyncWorldedit#536]
I'd be awesome to be able to add and subtract at the same time when using the height brush.
So grey pixels of the heightmap will leave the surface untouched, while white pixels will raise it and black pixels will lower it.
This would allow to "sculpt the surface" while keeping the shape of the terrain untouched

**Comment by dordsor21** [comment]
This isn't how heightmaps work

**Comment by dordsor21** [comment]
This isn't how heightmaps work

**Comment by bidule995** [comment]
There's no way a HeightMap work... There's only way softwares use it.

**Comment by JakBBB** [comment]
Yes it is, there are a lot of sculpting software that can treat heightmaps this way.

The feature I'm suggesting at the moment could be achieved with 2 heightmaps, one adding to the terrain and the other subtracting, but it would be much handier to have it all in one

**Comment by dordsor21** [comment]
That's hella complex for not a lot of gain. You'd either have to somehow specify the "zero" point, or you'd end up with the wrong output anyway. Just lower the height the heightmap is used from
