### ISSUE TITLE
Option to disable hardcoded aliases.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#537]
@boy0001 Would it be possible to allow for hardcoded aliases to be disabled or manually removed? For example https://github.com/boy0001/FastAsyncWorldedit/commit/b9c056c879d8b9277801d10d30f6a57209c9d6a2#diff-e3f8cd85a66ac6ef2134738e8a4e6aceR57 overrides ```/anvil``` from another plugin I use. That plugin formerly opened up a virtual anvil, but now it only outputs the FAWE information.

I can understand having ```//anvil``` output FAWE information being that worldedit uses two slashes for many commands, but a single `/` breaks some compatibility and behavior from other plugins that use that command.

**Comment by boy0001** [comment]
I may at some point, though it would require restructuring the command system. For now I'll just remove the alias.

**Comment by mibby** [comment]
Appreciated, thanks. :)
