### ISSUE TITLE
//br deform doesn't work on y and z axis

### ISSUE THREAD

**Issue by braceyourself07** [boy0001/FastAsyncWorldedit#540]
# Bug report template 

**Debug paste link**:
https://hastebin.com/yinubosaya

**Description of the problem:**
When using the deform brush, it works in the y-axis but doesn't work in x or z axis (causes FAWE to stop responding).  For example, this the command used:
`//br deform sphere 50 y+=0.2*sin(x*2.5+z*5)+0.2*tan(x*5+z*2.5)+0.2*tan(z*5)`

**How to replicate**:
Use the above command and apply it to an area. 

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
can't replicate
