### ISSUE TITLE
Versioning of maven artifacts

### ISSUE THREAD

**Issue by Postremus** [boy0001/FastAsyncWorldedit#544]
According to the api page<sup>[1]</sup> in the wiki, the official location of the fawe-api maven repository is `http://ci.athion.net/job/FastAsyncWorldEdit/ws/mvn/`. The newest version of this artifact in this repository seems to be `17.05.16-b870081-696-13.0.0`. According to the pom<sup>[2]</sup>, the newest version is `3.5.1`.

Is the version number from the api artifacts generated by jenkins? If so, can this please be changed to use the exact same version as is used in the pom?  
Reasoning is, that it caused me a few minutes of confusion to figure this out at first.  

[1]: https://github.com/boy0001/FastAsyncWorldedit/wiki/API
[2]: https://github.com/boy0001/FastAsyncWorldedit/blob/master/pom.xml#L11

**Comment by boy0001** [comment]
Ignore the pom, gradle is used to build the project, and the version number is generated. You can find the versions on the CI, or use `latest`. 

I'll delete the pom.
