### ISSUE TITLE
Crash: Asynchronous Async Chunk Load! Blocking thread until it returns

### ISSUE THREAD

**Issue by Joannou1** [boy0001/FastAsyncWorldedit#545]
Debug paste still not working for me, sorry.
Stacktrace: https://hastebin.com/zofusetuvo.sql
FastAsyncWorldEdit version 17.05.07-1e31827-684-12.7.1
git-Paper-2103c75 (MC: 1.11.2) 

This is a rather odd issue, according to this stack, my updater task hung as a result of that thread being blocked?
The updater task just calls an update event at certain intervals to make repeating tasks easy to use, line 23 of Updater: module.getServer().getPluginManager().callEvent(new UpdateEvent(update));

However the updater is in a different plugin entirely and doesn't trigger the pathfinder anyways.

That pathfinder method mentioned in the stacktrace is ran async, there's a lot going on so it seemed like a good idea and usually finishes in a second or so without issue.
I've seen this crash happen a few times, it's pretty rare though.

Checklist is kinda a grey area with this:

**Checklist**:
- [ ] I included a `/fawe debugpaste` link -- Not working
- [x] I made sure there aren't duplicates of this report -- Yes, you fixed it last month but it's back.
- [ ] I made sure I am using an up-to-date version of FAWE -- A couple weeks old, didn't look like there was too much changed in regard to this, but I figured it's worth posting. I'll update today.
- [x] I Made sure the bug/error is not caused by any other plugin -- It is, but isn't?

**Comment by boy0001** [comment]
Server hung as your pathfinder is unsafely loading chunks async: `net.championsmc.realms.pathing.AStar.isTileWalkable(AStar.java:251)`

If you are needing to run it async and need some help with that, please attach your code.

**Comment by Joannou1** [comment]
Alright, I figured that was possible, it was just so rare that it seemed worth posting.
Is there a way I could PM/email you the code? I'm not sure some people would be happy with me posting this publicly.
