### ISSUE TITLE
FAWE force disables timings when the adapter enables from breaking a block.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#546]
FAWE dev 694

I was running a timings profile on the server to measure arena lag but noticed I could not type ```/timings paste``` or ```/timings report``` to get the actual generated measurements uploaded / viewable. Looking into why, it seems FAWE force disables timings if parallel-threads > 1. 

https://github.com/boy0001/FastAsyncWorldedit/blob/4a9464c307f13b66416233b759a74fbc56462a60/bukkit/src/main/java/com/boydti/fawe/bukkit/v0/BukkitQueue_0.java#L223

```
[15:51:43] [Server thread/INFO]: (FAWE) Using adapter: com.boydti.fawe.bukkit.v1_11.FaweAdapter_1_11@24fd54cd
[15:51:43] [Server thread/INFO]: (FAWE) =========================================
[15:51:43] [Server thread/INFO]: (FAWE) Having `parallel-threads` > 1 interferes with the timings.
```

* Is there any reason why FAWE disables timings forcefully when parallel-threads is > 1?
* Wouldn't it then only affect worldedit timing data, not all global timings?
* Would it be possible to not force disable timings and allow it to be viewed anyways?

As no players were worldediting or using worldedit / fawe commands. It just forced the timings disabled when presumably someone who has access to worldedit broke a block to initialize the adapter. As there are no worldedit commands used in the log file prior to that.

**Comment by boy0001** [comment]
It should only interfere when FAWE is being used. Maybe indirectly if you have PlotSquared or some other plugin which uses it?

**Comment by N0tMyFaultOG** [comment]
If the issue persists still, reply to the ticket
