### ISSUE TITLE
Jenkin builds failing to compile.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#549]
http://ci.athion.net/job/FastAsyncWorldEdit/695/console

Failing to compile since the removal of the pom in this commit.
https://github.com/boy0001/FastAsyncWorldedit/commit/f89e95de111da61e0728acf103312f116cc5e573

**Comment by boy0001** [comment]
unrelated. the ci is just having issues

**Comment by mibby** [comment]
Any idea on when it will be resolved?

**Comment by boy0001** [comment]
@dordsor21

**Comment by dordsor21** [comment]
fixed @boy0001 @mibby
