### ISSUE TITLE
Instant physics

### ISSUE THREAD

**Issue by boy0001** [boy0001/FastAsyncWorldedit#55]

**Comment by EvilOlaf** [comment]
sub

**Comment by boy0001** [comment]
What operations?

**Comment by mibby** [comment]
Mainly brush operations like smoothing gravel/sand, placing gravel/sand spheres, or even cutting a region selection in the ocean. Being able to toggle physics (even if it is instant physics rather than normal) for everything would be nice instead of having it forced off.

**Comment by boy0001** [comment]
Heightmap brush
Erode brush
Smooth brush
Blend brush
etc.

Are considerably better alternatives to sand spheres.

**Comment by mibby** [comment]
From one of my worldedit users.

> physics is useful to me to help keep things natural when making landscape, by constructing with gravel and allowing it to fall naturally as I sculpt. 
without it the brushes edges leave dents in the landscape that need to be manually removed or smoothed (if possible)

>and when creating the original starting point I use gravel spheres to have a somewhat natural starting point as I stack spheres ontop of eachother and they collapse

**Comment by boy0001** [comment]
Can you at least try suggesting for them to try out the other brushes and masks?

#### `//brush height [radius=5] [file|#clipboard=null] [rotation=0] [yscale=1.00]`
Perm: `worldedit.brush.height`
Desc: Raise or lower terrain (omitting an argument will use the default value)
Note: Use a negative yscale to reduce height
Example: `//brush height 10`

More info:
https://github.com/boy0001/FastAsyncWorldedit/wiki/Commands#brushestools
https://github.com/boy0001/FastAsyncWorldedit/wiki/WorldEdit---FAWE-mask-list

**Comment by mibby** [comment]
Will do. I'll inform them about it and let you know what they think / if it is a suitable replacement for what they were using physics for. Though in some cases, instant physics may be nice to avoid having to manually fix things like this. :) http://i.imgur.com/R7RIYi8.jpg

**Comment by boy0001** [comment]
`//fixwater`
