### ISSUE TITLE
Chunks Unaffected By Commands..?

### ISSUE THREAD

**Issue by Dann001** [boy0001/FastAsyncWorldedit#552]
I ran into an issue and it's never happened before. While using commands such as "//hcyl,//cyl,//set" in the region selected some of the chunks remain untouched. 
![o-o](https://cloud.githubusercontent.com/assets/28934767/26423468/ceba979c-409b-11e7-9169-c8d9be5927e1.png)

**Comment by dordsor21** [comment]
are you using the latest build from http://ci.athion.net/job/FastAsyncWorldEdit/ ?

**Comment by Dann001** [comment]
Yes I always tend to use the latest build. Note that when just using WorldEdit by itself it works perfectly fine but with FAWE as the screenshot shows that happens 90% of the time. (I would just use WE without FAWE but server tends to lag too much.)

**Comment by dordsor21** [comment]
I've tried to replicate. Could you run a /fawe debugpaste and post it here?

**Comment by Dann001** [comment]
links.config_yml: https://hastebin.com/dudulawume
links.messages_yml: https://hastebin.com/watezilelu
links.commands_yml: https://hastebin.com/zikobijowi
links.latest_log: https://hastebin.com/wadepumori.md
# Server Information
version.server: bukkit

# YAY! Now, let's see what we can find in your JVM
memory.free: 327316752
memory.max: 2863661056
java.specification.version: '1.8'
java.vendor: 'Oracle Corporation'
java.version: '1.8.0_131'
os.arch: 'amd64'
os.name: 'Windows 10'
os.version: '10.0'

**Comment by Dpa1991** [comment]
Little late to the party, but I also have this problem. I just updated my plugins so I'd have to do more testing.

**Comment by Dpa1991** [comment]
Still having this issue. I've noticed this occurs in any chunk with chests in them

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
