### ISSUE TITLE
Biome ID is out of bounds

### ISSUE THREAD

**Issue by a810587921** [boy0001/FastAsyncWorldedit#553]
# Welcome to this paste
# It is meant to provide us at IntellectualSites with better information about your problem

# We will start with some informational files
links.config_yml: https://hastebin.com/diqisatuju.coffeescript
links.messages_yml: https://hastebin.com/uzowogeqow
links.commands_yml: https://hastebin.com/mazalagixa
links.latest_log: https://pastebin.com/DLQUTfeF

# Server Information
version.server: Thermos-1.7.10-1614-57-server

# YAY! Now, let's see what we can find in your JVM
memory.free: 571482040
memory.max: 1908932608
java.specification.version: '1.8'
java.vendor: 'Oracle Corporation'
java.version: '1.8.0_121'
os.arch: 'amd64'
os.name: 'Windows 10'
os.version: '10.0'

mods:
FastAsyncWorldEdit-forge1710-17.05.21-31d43b2-697-13.0.4.jar
worldedit-forge-mc1.7.10-6.1.1-dist.jar

bukkit Plugin code:
https://hastebin.com/epimoteduv

**Comment by N0tMyFaultOG** [comment]
If the issue persists still, reply to the ticket
