### ISSUE TITLE
WARN/ Start and error

### ISSUE THREAD

**Issue by foxygameru** [boy0001/FastAsyncWorldedit#554]
core Thermos-1.7.10-1614-57

When you start error and shut off WorldEdit

Can you please fix it, thanks in advance.

> [23:15:05] [Server thread/INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v3.3.19
> [23:15:05] [Server thread/INFO]: [FastAsyncWorldEdit] §6Metrics enabled.
> [23:15:05] [Server thread/INFO]: ====== LZ4 COMPRESSION BINDING NOT FOUND ======
> [23:15:05] [Server thread/WARN]: java.lang.NullPointerException
> [23:15:05] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.setupInjector(Fawe.java:260)
> [23:15:05] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.<init>(Fawe.java:183)
> [23:15:05] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.set(Fawe.java:126)
> [23:15:05] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.onEnable(FaweBukkit.java:65)
> [23:15:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
> [23:15:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
> [23:15:05] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
> [23:15:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
> [23:15:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
> [23:15:05] [Server thread/WARN]: 	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:463)
> [23:15:05] [Server thread/WARN]: 	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138)
> [23:15:05] [Server thread/WARN]: 	at net.minecraft.world.World.<init>(World.java:374)
> [23:15:05] [Server thread/WARN]: 	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162)
> [23:15:05] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375)
> [23:15:05] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
> [23:15:05] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
> [23:15:05] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
> [23:15:05] [Server thread/INFO]: ===============================================
> [23:15:05] [Server thread/INFO]: FAWE will still work, but some things may be slower
> [23:15:05] [Server thread/INFO]:  - Try updating your JVM / OS
> [23:15:05] [Server thread/INFO]:  - Report this issue if you cannot resolve it
> [23:15:05] [Server thread/INFO]: =============================================

**Comment by dordsor21** [comment]
could you do a `/fawe debugpaste` and put the link here?

**Comment by foxygameru** [comment]
If the prescribe command from the console, resets config.

> [10:24:38] [Server thread/INFO]: [FastAsyncWorldEdit] §d§8(§5§lFAWE§8)§7 Reloaded configuration
> [10:24:44] [Server thread/INFO]: [FastAsyncWorldEdit] §d§8(§5§lFAWE§8)§7 Reloaded configuration
> [10:24:48] [Server thread/INFO]: [FastAsyncWorldEdit] §d§8(§5§lFAWE§8)§7 Reloaded configuration

If prescribed this command to the game, deduced the following error

> [10:30:05 INFO]: GrayFox issued server command: /fawe debugpaste
> [10:30:05 ERROR]: null
> org.bukkit.command.CommandException: Unhandled exception executing command 'fawe' in plugin FastAsyncWorl
> dEdit v3.3.19
> >       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1
> 614.58]
> >       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.cla
> ss:1.7.10-1614.58]
> >       at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) ~[CraftServer
> .class:1.7.10-1614.58]
> >       at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.c
> lass:?]
> >       at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.c
> lass:?]
> >       at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java
> :38) [ir.class:?]
> >       at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java
> :53) [ir.class:?]
> >       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
> >       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
> >       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.
> class:?]
> >       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.clas
> s:?]
> >       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.c
> lass:?]
> >       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
> >       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
> Caused by: java.lang.NullPointerException
> >       at com.boydti.fawe.object.FawePlayer.getSession(FawePlayer.java:126) ~[?:?]
> >       at com.boydti.fawe.object.FawePlayer.<init>(FawePlayer.java:42) ~[?:?]
> >       at com.boydti.fawe.bukkit.BukkitPlayer.<init>(BukkitPlayer.java:15) ~[?:?]
> >       at com.boydti.fawe.bukkit.FaweBukkit.wrap(FaweBukkit.java:99) ~[?:?]
> >       at com.boydti.fawe.bukkit.BukkitCommand.onCommand(BukkitCommand.java:21) ~[?:?]
> >       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1
> 614.58]
> >       ... 13 more
> >
> 

When you run the plugin gives some errors:

> [10:24:27] [Server thread/ERROR]: Error occurred while enabling WorldEdit v6.1.5;4651611 (Is it up to date?)
> java.lang.NoSuchMethodError: com.sk89q.worldedit.util.command.parametric.ParametricBuilder.addExceptionConverter(Lcom/sk89q/worldedit/util/command/parametric/ExceptionConverter;)V
> 	at com.sk89q.worldedit.extension.platform.CommandManager.<init>(CommandManager.java:141) ~[?:?]
> 	at com.sk89q.worldedit.extension.platform.PlatformManager.<init>(PlatformManager.java:86) ~[?:?]
> 	at com.sk89q.worldedit.WorldEdit.<init>(WorldEdit.java:95) ~[?:?]
> 	at com.sk89q.worldedit.WorldEdit.<clinit>(WorldEdit.java:91) ~[?:?]
> 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:100) ~[?:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.58]
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.58]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.58]
> 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.58]
> 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.58]
> 	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
> 
> [10:24:29] [Server thread/WARN]: [FastAsyncWorldEdit] Task #5 for FastAsyncWorldEdit v3.3.19 generated an exception
> java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldedit.WorldEdit
> 	at com.boydti.fawe.Fawe$1.run(Fawe.java:173) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:1.7.10-1614.58]
> 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.58]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by dordsor21** [comment]
Does WorldEdit work without FAWE installed? And are you using the correct WE version for your server.

**Comment by foxygameru** [comment]
VERSION 1.7.10
Try these versions:

name: FastAsyncWorldEdit
main: com.boydti.fawe.bukkit.FaweBukkit
version: 3.3.19

name: FastAsyncWorldEdit
main: com.boydti.fawe.bukkit.FaweBukkit
version: 3.3.22

name: WorldEdit
main: com.sk89q.worldedit.bukkit.WorldEditPlugin
version: "6.1.5;4651611"

name: WorldEdit
main: com.sk89q.worldedit.bukkit.WorldEditPlugin
version: "6.1.1-SNAPSHOT;3482-867e59b"

**Comment by dordsor21** [comment]
are you using the latest FAWE version from http://ci.athion.net/job/FastAsyncWorldEdit/ ?

**Comment by dordsor21** [comment]
and the correct FAWE for Thermos^

**Comment by foxygameru** [comment]
NEW Version Errors
FastAsyncWorldEdit v17.05.28-b3ee619-699-13.0.6
Server Goes to restart

Is there FAWE for Thermos?
or version 1.7.10 ? 

> [11:30:43] [Server thread/INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v17.05.28-b3ee619-699-13.0.6
> [11:30:43] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/boydti/fawe/Fawe
> [11:30:43] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.<init>(FaweBukkit.java:73)
> [11:30:43] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:66)
> [11:30:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
> [11:30:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
> [11:30:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
> [11:30:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
> [11:30:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
> [11:30:43] [Server thread/WARN]: 	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:463)
> [11:30:43] [Server thread/WARN]: 	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138)
> [11:30:43] [Server thread/WARN]: 	at net.minecraft.world.World.<init>(World.java:374)
> [11:30:43] [Server thread/WARN]: 	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162)
> [11:30:43] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375)
> [11:30:43] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
> [11:30:43] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
> [11:30:43] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
> [11:30:43] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: Failed to remap class com.boydti.fawe.Fawe
> [11:30:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:534)
> [11:30:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:455)
> [11:30:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211)
> [11:30:43] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> [11:30:43] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> [11:30:43] [Server thread/WARN]: 	... 15 more
> [11:30:43] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
> [11:30:43] [Server thread/WARN]: 	at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source)
> [11:30:43] [Server thread/WARN]: 	at org.objectweb.asm.ClassReader.a(Unknown Source)
> [11:30:43] [Server thread/WARN]: 	at org.objectweb.asm.ClassReader.b(Unknown Source)
> [11:30:43] [Server thread/WARN]: 	at org.objectweb.asm.ClassReader.accept(Unknown Source)
> [11:30:43] [Server thread/WARN]: 	at org.objectweb.asm.ClassReader.accept(Unknown Source)
> [11:30:43] [Server thread/WARN]: 	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:246)
> [11:30:43] [Server thread/WARN]: 	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:232)
> [11:30:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:499)
> [11:30:43] [Server thread/WARN]: 	... 19 more
> [11:30:43] [Server thread/ERROR]: Error occurred while enabling FastAsyncWorldEdit v17.05.28-b3ee619-699-13.0.6 (Is it up to date?)
> java.lang.NullPointerException
> 	at com.boydti.fawe.bukkit.FaweBukkit.<init>(FaweBukkit.java:88) ~[?:?]
> 	at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:66) ~[?:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.58]
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.58]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.58]
> 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.58]
> 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.58]
> 	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:463) [ayq.class:?]
> 	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
> 	at net.minecraft.world.World.<init>(World.java:374) [ahb.class:?]
> 	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by dordsor21** [comment]
you should be using the forge version I believe?

**Comment by foxygameru** [comment]
Forge version is exactly the same error and disconnects.
Also worldedit disabled and not working.

**Comment by dordsor21** [comment]
using the correct WE forge version also?

**Comment by foxygameru** [comment]
I can use any version, the main thing worked!
But not forge not Bukkit FAWE does not work for 1.7.10 Thermos

**Comment by dordsor21** [comment]
probably the point I should ask @boy0001 if thermos is still supported, as thermos isn't in development anymore.

**Comment by foxygameru** [comment]
Well, I will wait for an answer.

**Comment by foxygameru** [comment]
The problem was solved by the fact that it turns out thermos reads renaming mods (.jar1/.jar--) in the mods folder. Removing the mod and putting the version with Bukkit, the problem was solved.

**Comment by foxygameru** [comment]
http://joxi.ru/zANGjvXTp58Xr9.png
example
