### ISSUE TITLE
Where are Schematics Stored?

### ISSUE THREAD

**Issue by Techno3600** [boy0001/FastAsyncWorldedit#569]
Hello,
Where are schematics stored? I can't find it.

Thanks

**Comment by Sollembum78** [comment]
Hello there! schematics are usualy stored in default schematics folder, which is /plugins/WorldEdit/schematics, unless you specified different folder in config of worldedit. However, in latest versions of FAWE, new folder is created for each user, which performs //schem save *name*. Like this:
/plugins/WorldEdit/schematics/c0179ce9-8006-3d0a-9d3e-841218fa6867
subfolder of which corresponds to uuid of user that saved schematic.
