### ISSUE TITLE
Redstone does not update after paste/set

### ISSUE THREAD

**Issue by Rickyboy320** [boy0001/FastAsyncWorldedit#570]
# Bug report 
**Debug paste link**:
https://hastebin.com/zijucitexu

**Description of the problem:**
Redstone does not update after a redstone block or redstone torch (or possibly all redstone emitting blocks) are placed through at least //set and //paste.
Could not find any configuration node that enables this. Tested with a clean install and still occurred. 
Affects more types of block updating (sponges, observers, comparators etc).
Feel like I've done something wrong, as I've not seen the report here before (or is this not supported and am I expecting the wrong things?).

**How to replicate**:
1) Place a door or piston
2) Select the block next to the placed block
3) //set redstone_block

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

I've attached the expected behaviour (which happens when WorldEdit is installed alone), what actually happens, Fawe version, spigot version and current plugins.
![screenshot_1](https://cloud.githubusercontent.com/assets/3754047/26765779/ca6f421e-4983-11e7-9dd0-faeaaded2148.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/3754047/26765784/d45b0f92-4983-11e7-8dab-811b963f9cde.png)

![version](https://cloud.githubusercontent.com/assets/3754047/26765804/e625d0f4-4983-11e7-9ed9-81c392176b86.png)
![version_spigot](https://cloud.githubusercontent.com/assets/3754047/26765806/e7cddac8-4983-11e7-9bc4-c2fe92cd8672.png)
![plugins](https://cloud.githubusercontent.com/assets/3754047/26765807/e8fc4164-4983-11e7-8f0a-09566617755e.png)

**Comment by dordsor21** [comment]
Normal behaviour. The block is places without causing block updates massively reducing lag. You can force a block update by placing a block next to the door/redstone etc
