### ISSUE TITLE
Missing chunks after restart

### ISSUE THREAD

**Issue by wasder** [boy0001/FastAsyncWorldedit#571]
**Debug paste link**: https://hastebin.com/voqolojipe

**Description of the problem:**
I will copy it from there - https://github.com/IntellectualSites/PlotSquared/issues/1569  
Sometimes server is starting to lag, TPS is getting below 18. I try to restart it normally and it hangs during world save.
https://hastebin.com/vilehuqimi
I have no choice but to kill the process. After force restart some shit like this happens:
![](http://i.imgur.com/xTT8M0V.png)
My guess that it is happening because of WordEdit (FAWE). It always loses chunks on regions which were edited with WE. The region on screenshot was pasted from schematic before restart.
P2 debug log: https://hastebin.com/ozaqijavoy

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
how do you know this is FAWE?

**Comment by wasder** [comment]
It happens on regions that were worldedited.

**Comment by dordsor21** [comment]
it's likely when you're saving the world, you're saving far too much world, so the TPS drops, and thus gets stuck on saving world when you try to stop the server. Therefore only part of the worldedit saves as the world has been changed in those locations. What is ticks-per.autosave set as in your bukkit.yml? And have you also disabled saving elsewhere? As the fact the world isn't saved will reduce TPS, and cause the server to spend ages saving when trying to stop.

**Comment by wasder** [comment]
`ticks-per.autosave: 6000 `
I didn't disable saving.

**Comment by dordsor21** [comment]
that saves every 10 minutes, try setting to 3000. Are there any other plugins that affect chunks/chunk saving, and are you using a very bad HDD?

**Comment by wasder** [comment]
EmptyWorldGenerator, OpenInv, MarriageMaster, PlugMan, BetterChairs, ActionBarAPI, BanManager, ProtocolLib, NoCheatPlus, FastAsyncWorldEdit, SignColors, VanishNoPacket, PermissionsEx, AntiPortalTrapping, Hats, LightAPI, WorldEdit, CommandBlockerUltimate, RandomCraft, PlotSquared, Multiverse-Core, DiscordSRV, BiomeGenerator, ProtectionLib, Vanity, RandomCreative, WorldEditSelectionVisualizer, ArmorStandTools, HolographicDisplays, FurnitureLib, DiceFurniture

Nothing here is affecting chunks besides FAWE I guess.
Is it a bad HDD?
```
=== START OF INFORMATION SECTION ===
Device Model:     HGST HUS724020ALA640
Serial Number:    PN2181P5GZMJRX
LU WWN Device Id: 5 000cca 24ecdec7b
Firmware Version: MF6OAA70
User Capacity:    2,000,398,934,016 bytes [2.00 TB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    7200 rpm
Form Factor:      3.5 inches
Device is:        Not in smartctl database [for details use: -P showall]
ATA Version is:   ATA8-ACS T13/1699-D revision 4
SATA Version is:  SATA 3.0, 6.0 Gb/s (current: 3.0 Gb/s)
Local Time is:    Tue Jun  6 17:25:10 2017 CEST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
```

**Comment by dordsor21** [comment]
try setting world save to 3000, and also get a /timings report a few times as well. Make sure you're updated with everything, including bukkit/spigot/whatever you're using

**Comment by wasder** [comment]
Still crashing with world save at 3000. 
https://timings.spigotmc.org/?url=ketonorali
https://timings.spigotmc.org/?url=soyebuquha
```
[16:38:18 INFO]: This server is running CraftBukkit version git-Spigot-c6871e2-0cd0397 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)
[16:38:18 INFO]: Checking version, please wait...
```

**Comment by dordsor21** [comment]
what does randomcraft do? That's using a huge amount of CPU time. It's very likely that this is causing the issue.

**Comment by dordsor21** [comment]
your worldsave is also using a ridiculous % of the tick. How many worlds do you have loaded on the one server, and how many new chunks are created?

**Comment by wasder** [comment]
Randomcraft is our main library for server's network. It works well on all other servers.

There are 8 worlds currently loaded, but only the main one (with plots) is mostly in use. Others are for small separate builds. However the main world is currently at 49.7 GB on disk space. It's so huge because we have 512*512 plots and auto clear task just doesn't work. https://github.com/IntellectualSites/PlotSquared/issues/1607

**Comment by dordsor21** [comment]
run a /ps trim now and again

**Comment by wasder** [comment]
Thanks. Will do it at night, when there are no players.

**Comment by dordsor21** [comment]
that might not solve the issue, as you've already got chunk processor enabled, but the issue is likely RandomCraft and RandomCreative as they're using the majority of your resources, so get those two checked out for memory leaks/bad coding.
