### ISSUE TITLE
Hard to use gravity

### ISSUE THREAD

**Issue by Tiplish** [boy0001/FastAsyncWorldedit#572]
Hello,

I'm new with your plugin and i try to create fill and brush with gravity as with worldedit without FAWE. 

The problem is that with FAWE, there is only //fall or gravity brush to force gravity on blocks. It needs several //fall and brush to get a sand mountain without hole for example. Is there another way to force gravity when we put a sand sphere for example?

Thx

**Comment by dordsor21** [comment]
#482
