### ISSUE TITLE
NBT copy/paste problem.

### ISSUE THREAD

**Issue by Panossa** [boy0001/FastAsyncWorldedit#573]
**Debug paste link**: https://hastebin.com/odadihibib <- is not important here

**Description of the problem:**
If pasting or moving (or similar) a block with NBT data onto another block with NBT data the old one gets not replaced.

**How to replicate**:
You place one sign e.g. on the wall. Write the letter "A". Place another sign right next to it, write "B". Then select the "B" sign with WE and //move it into the "A" sign. The "A" sign stays there.
The same happens if you //copy //paste the signs. And I'm sure the same happens with everything that has NBT. E.g. chests have the same bug.
**EDIT:** I made a short video regarding this problem. Found another interesting thing about the bug:
https://youtu.be/zKG4d4dafkk

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [?] I Made sure the bug/error is not caused by any other plugin <- Maybe WE itself?

**Comment by dordsor21** [comment]
#557 #535 You're not using the latest build.
