### ISSUE TITLE
Errors in the console

### ISSUE THREAD

**Issue by enlyow** [boy0001/FastAsyncWorldedit#574]
When the territory (set) is filled with a forbidden block, a mistake occurs in the console. http://prntscr.com/fh87q3

WorldEdit debug: false

WE version: 6.1.7
FAWE version: latest 17.6.6

Debug link: https://hastebin.com/ivijebogay

**Comment by dordsor21** [comment]
#558 #559 are probably the same bug

**Comment by dordsor21** [comment]
is this still an issue?

**Comment by enly1337** [comment]
yep.

**Comment by dordsor21** [comment]
using latest version?

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
