### ISSUE TITLE
Nukkit Bugs

### ISSUE THREAD

**Issue by imjack** [boy0001/FastAsyncWorldedit#576]
# Bug report template 

**Debug paste link**:

https://hastebin.com/ekanuzedeh
**Description of the problem:**
Placing a block causes this issue: https://hastebin.com/yoruyalaya.vbs and placing blocks too.

This is using the latest version of nukkit on this branch which will latest be pulled to the main branch https://github.com/yescallop/Nukkit

**How to replicate**:

use //wand select two points using the warn
**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Is this specifically when using the wand to select pos1/pos2?

**Comment by imjack** [comment]
When placing blocks or right clicking air. There is quite a few bugs within FAWE for Nukkit. This one is simply to notify when the update is pushed it will break the plugin.

**Comment by EnderKenji** [comment]
@imjack https://github.com/yescallop/Nukkit/tree/1.1.0

**Comment by imjack** [comment]
Yes that's correct @EnderKenji

**Comment by Goodstuff4UonYT** [comment]
@EnderKenji @imjack I made a pull request to fix the problems with nukkit 1.1

**Comment by EnderKenji** [comment]
Some bugs need to be fixed,

- After Flipped or Rotated, wooden slabs will be changed to different slabs, its not necessary for us.
- Fences can't be changed using WE... hmm?
- Still, pos2 on wand doesn't work... help

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
