### ISSUE TITLE
Blocks are logged twice

### ISSUE THREAD

**Issue by Maxetto** [boy0001/FastAsyncWorldedit#58]
Seems like CoreProtect changes gets logged twice.
I've had a similiar problem before and I solved it by setting "worldedit: false" on CoreProtect. However this time it doesn't work.

Config: http://pastebin.com/csXDzszT

![2016-04-27_00 24 12](https://cloud.githubusercontent.com/assets/1360752/14836238/ea5068b4-0c0e-11e6-8d4d-fe42299e3df8.png)

Using:
Spigot 1.8.8
WorldEdit b3482
WorldGuard 6.1
WorldEditSelectionVisualizer 1.4.3
CoreProtect 2.12.0 (worldedit: false)
Factions 2.8.8
BlocksHub 1.2
BlocksHub-CoreProtect 1.2.1
BlocksHub-Factions 1.2
BlocksHub-WorldGuard 1.2

**Comment by RoboMWM** [comment]
Disable CoreProtect's WorldEdit logging in config if you use BlocksHub.

**Comment by Maxetto** [comment]
I'd rather also add to this ticket an issue where teleports (by /thru, for example) are done Asnyc, while they should not be.
http://pastebin.com/C4vNwbxC

**Comment by boy0001** [comment]
download it here:
http://ci.athion.net/job/FastAsyncWorldEdit/68/
