### ISSUE TITLE
NBT copy/paste problem. [Updated!]

### ISSUE THREAD

**Issue by Panossa** [boy0001/FastAsyncWorldedit#581]
**Debug paste link**:
https://hastebin.com/vegilapeya <- is not important here

**Description of the problem**:
If pasting or moving (or similar) a block with NBT data onto another block with NBT data the old one gets not replaced.

**How to replicate**:
You place one sign e.g. on the wall. Write the letter "A". Place another sign right next to it, write "B". Then select the "B" sign with WE and //move it into the "A" sign. The "A" sign stays there.
The same happens if you //copy //paste the signs. And I'm sure the same happens with everything that has NBT. E.g. chests have the same bug. What is kinda interesting: The server seems to remember the NBT data that was on the same block but removes the block itself.
I made a short video regarding this problem:
https://youtu.be/7gsGmZhDLqg

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report
- [x] I made sure I am using an up-to-date version of FAWE
- [?] I Made sure the bug/error is not caused by any other plugin // WE?

**Comment by dordsor21** [comment]
Are you using the latest FAWE?

**Comment by Panossa** [comment]
@dordsor21 I used the latest FAWE version when I tested that. Now I updated to the newest version available and it's still buggy.
Maybe it's cause of MC 1.8 but I'm not sure. At least it doesn't work even in the newest version.

**Comment by dordsor21** [comment]
latest from http://ci.athion.net/job/FastAsyncWorldEdit/ right?

**Comment by Panossa** [comment]
I have currently installed:
FAWE 17.6.19-edd8dcc-720
I just downloaded it from the spigotmc site.

**Comment by dordsor21** [comment]
download the latest from http://ci.athion.net/job/FastAsyncWorldEdit/ <-- is where you should be downloading from

**Comment by Panossa** [comment]
It IS the same version though. Completely same ID 'n' stuff.

**Comment by dordsor21** [comment]
odd. Still works fine for me...

**Comment by Panossa** [comment]
Are you on a spigot 1.8(.8) server?
I have worldedit-bukkit-6.1.3, newest FAWE and FAVS currently. (and more but the other plugins shouldn't affect that bug)

**Comment by dordsor21** [comment]
1.12, latest everything. Try WE from here: http://builds.enginehub.org/job/worldedit

**Comment by Panossa** [comment]
worldedit-bukkit-6.1.8-SNAPSHOT-dist.jar (1685.58 kBytes)
or
 worldedit-core-6.1.8-SNAPSHOT-dist.jar (1308.28 kBytes) ?

**Comment by dordsor21** [comment]
bukkit

**Comment by Panossa** [comment]
Ok I were a few versions of WE behind but it still doesn't work.

**Comment by boy0001** [comment]
Fixed in 5caeed19a1fc7856150322ba1e1801811d047914 or by enabled `combine-stages` in the `config.yml`
