### ISSUE TITLE
Blocks Missing on '//paste' or '//set <block>'

### ISSUE THREAD

**Issue by Namasteh** [boy0001/FastAsyncWorldedit#584]
# Bug report template 

**Debug links:**
https://www.pastiebin.com/593dd8721a297
https://hastebin.com/ozobugovaj

**Description of the problem:**
  When I paste a schematic, or just do '//set stone' (or any block) there are bits that are left out, giant sections of unchanged blocks. I have no idea why it is happening, but above I included two links. One is a paste of the console after I try making a paste, and the other is the debug information you need.

**How to replicate**:

1. Load schematic or choose area for editing.
2. Either '//paste' or '//set <block>'
3. Observe missing sets of blocks

![2017-06-11_19 03 38](https://user-images.githubusercontent.com/5873737/27015643-c1620616-4ed8-11e7-809d-4215a38f528d.png)

![2017-06-11_19 05 55](https://user-images.githubusercontent.com/5873737/27015653-033dabda-4ed9-11e7-9f42-bfea1e0fb86a.png)

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Use spigot
