### ISSUE TITLE
Server Crash Forge 1.7.10 + WorldEdit + FAWE

### ISSUE THREAD

**Issue by Johnny-Ich** [boy0001/FastAsyncWorldedit#586]
Hi there.

I have a Minecraft Server Runing Forge 1.7.10 with
World Edit. I would like to use FAWe, but the server crashes every time i
put this mod into /mods folder and try to start the server.

The Server output says:

https://pastebin.com/72wt2tAc

-  I made sure there aren't duplicates of this report (Use Search)
-  I made sure I am using an up-to-date version of FAWE
-  I Made sure the bug/error is not caused by any other plugin

Could you help here?

Many thanks an greetings from Germany,
Johnny

**Comment by dordsor21** [comment]
you're definitely using the forge version for 1.7.10?

**Comment by Johnny-Ich** [comment]
I am using MinecraftForge v10.13.4.1558 for Minecraft 1.7.10.
http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html
And everything is working fine(inculding the mods TrainCraft and Realisitg Terrain Generator), until i add FAWE into the mods folder.

**Comment by dordsor21** [comment]
the FAWE forge version...

**Comment by Johnny-Ich** [comment]
I think so.
I downloaded "FAWE for forge 1.7.10" on this site:
https://github.com/boy0001/FastAsyncWorldedit/releases
The file i downloaded is named:
"FastAsyncWorldEdit-forge**1710**-17.06.09-0f3138e-713-13.0.17.jar"

**Comment by dordsor21** [comment]
try this: http://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/FastAsyncWorldEdit-forge1710-17.06.09-0f3138e-713-13.0.17.jar (direct download link)

latest version from http://ci.athion.net/job/FastAsyncWorldEdit/

**Comment by Johnny-Ich** [comment]
I already tried to use this Version.
The server crashes every time.

**Comment by Johnny-Ich** [comment]
SOLVED!!!
I used the wrong Version of worldedit.
The right one can be found here: https://minecraft.curseforge.com/projects/worldedit/files/2309699

I used:
"**worldedit-forge-mc1.7.10-6.1.1-SNAPSHOT-dist.jar**"
The right one is:
"worldedit-forge-mc1.7.10-6.1.1-dist.jar"

Thank you for helping me!
