### ISSUE TITLE
Website Upload error on file upload

### ISSUE THREAD

**Issue by YugieDev** [boy0001/FastAsyncWorldedit#587]
# Website seems to not upload
This seems to be because of that there are that many schmatics its getting full. Would it be possible for you to provide soruce code for the website so we can host our own schmatic upload section and have lots more storage and make it fit our theme.

**Comment by dordsor21** [comment]
Already exists https://github.com/boy0001/plotupload

**Comment by YugieDev** [comment]
That's relating to PlotSquared not fawe unless they work in the same way

**Comment by dordsor21** [comment]
works the same

**Comment by YugieDev** [comment]
array(1) { ["schematicFile"]=> array(5) { ["name"]=> string(15) "tree1.schematic" ["type"]=> string(24) "application/octet-stream" ["tmp_name"]=> string(14) "/tmp/phpFh2Ac7" ["error"]=> int(0) ["size"]=> int(146325) } } 0uploads/e4f9a824-57ec-441a-9578-f6fa254cb018.schematic
FAILURE

I get that error when I try and upload a schematic to the site

Web Server Information
- Apache2
- PHP 7
- 2TB HHD
- 16GB Ram

**Comment by dordsor21** [comment]
it;s exactly the same code as empcraft, so it's something being done wrong your end. Try increasing the max file size (in bytes).

**Comment by YugieDev** [comment]
I keep getting the same error after making the byte size 

$config['size']  = 99999999999999999999 ; #Max file size#

All I have done  is edited the ips but it still doesn't let me upload it

**Comment by dordsor21** [comment]
can I see the rest of the config + changed files?

**Comment by YugieDev** [comment]
<?php

class Config {
    private static $info = array();
    public static function set($key, $value) {
        self::$info[$key] = $value;
    }
    public static function get($key) {
        return self::$info[$key];
    }
    public static function getAll() {
        return self::$info;
    }
}

########################################################################################################################
$config = array();                                                                                                     #
                                                                                                                       #
//DO NOT EDIT ABOVE THIS                                                                                               #
                                                                                                                       #
# Edit below this ######################################################################################################
$config['title'] = 'PlotSquared plot download'                            ; # Title of the web page                    #
# ============== # Styles: 8bit, dark, default, shadow, phanaticd, orange, green, clean, grey, frame. # ============== #
$config['style'] = "dark"                                                 ; # The style to use (see styles folder)     #
//If you like a specific style: $config['style'] = 'default'                                                           #
                                                                                                                       #
$config['navtitle'] = 'Plot Upload:'					        		  ; # The text in the navbar				   #
$config['header1'] = 'PlotSquared Plot Downloading'						  ; # The big text on the web page			   #
$config['serverip'] = 'your.ip.here'									  ;	# The server IP to display on the web page #
$config['home']  = 'https://www.spigotmc.org/resources/1177/' ;             # The website for the home link            #
                                                                                                                       #
# e.g. array('192.168.1.10')                                                                                           #
$config['ups']   = array()                                                ; # To authorize all servers use array()     #
                                                                                                                       #
$config['size']  = 99999999999999999999                                               ; # Max file size                            #
                                                                                                                       #
$config['allow-delete']  = true                                           ; # Allow file deletion requests             #
########################################################################################################################

// DO NOT EDIT BELOW THIS
foreach($config as $var => $val) {
    Config::set($var, $val);
}
unset($config);
?>

**Comment by dordsor21** [comment]
?

**Comment by YugieDev** [comment]
I have just reset the files and just edited the size and that's it

**Comment by YugieDev** [comment]
array(1) { ["schematicFile"]=> array(5) { ["name"]=> string(16) "Trees2.schematic" ["type"]=> string(24) "application/octet-stream" ["tmp_name"]=> string(14) "/tmp/phpIY96Pb" ["error"]=> int(0) ["size"]=> int(277923) } } 0uploads/01e29b24-b4b7-4585-af25-e02f00b526ac.schematic
FAILURE

And thats the error

**Comment by dordsor21** [comment]
put the size down to something more normal, like 100000000

**Comment by YugieDev** [comment]
Same issue as before 

array(1) { ["schematicFile"]=> array(5) { ["name"]=> string(15) "tree1.schematic" ["type"]=> string(24) "application/octet-stream" ["tmp_name"]=> string(14) "/tmp/phpGn3jsJ" ["error"]=> int(0) ["size"]=> int(146325) } } 0uploads/76ac6267-b31e-4641-b549-bc936aa1287b.schematic
FAILURE

**Comment by YugieDev** [comment]
Any suggestions?

**Comment by dordsor21** [comment]
@boy0001 will probably know more about the error than I

**Comment by boy0001** [comment]
I've updated [`plotupload`](https://github.com/boy0001/plotupload) to what's currently running on `empcraft.com`, though it should have already been working.

**Comment by YugieDev** [comment]
I still get the same error which is very weird. @boy0001 Is there anything I need to do to make it work straight away or should it just install and work. Here is the site for you to test out - http://www.buildzcreative.com/upload/

**Comment by YugieDev** [comment]
array(1) { ["schematicFile"]=> array(5) { ["name"]=> string(15) "tree1.schematic" ["type"]=> string(24) "application/octet-stream" ["tmp_name"]=> string(14) "/tmp/phptQPcxY" ["error"]=> int(0) ["size"]=> int(146325) } } 0 uploads/bba81eac-a0c1-4f88-ab19-6b8777a3126c.schematic FAILURE2

**Comment by boy0001** [comment]
Check the permissions for the uploads directory. It probably doesn't have write access.

**Comment by YugieDev** [comment]
Thanks @boy0001 That fixed the issue
