### ISSUE TITLE
command can't be remapped with bukkit commands.yml

### ISSUE THREAD

**Issue by Fchen48** [boy0001/FastAsyncWorldedit#588]
# Bug report template 

**Debug paste link**: https://hastebin.com/fuvemicewu

**Description of the problem:** I use FAWE (and WE before) with single slashes, additional with VoxelSniper (and now FAVS, but this doesn't matter with the error) and if I type `/b e melt` the WE brush command `/br` will be triggered. If I disable FAWE, VS will be triggered. 

Now I tried to remap the command `/b` to `/voxelsniper:b` using bukkits commands.yml file, but FAWE is still grabbing the command if I will do this with `/monkey` to `/voxelsniper:b` the command works pretty well. I tested it again with another command, like `/help` also this will be grabbed by FAWE, but also without FAWE, WE will grab this command. 

WE is a penetrating plugin in terms of commands and aliases.

commands.yml work on my server well with around 30-50 other commands.

The Issue #537 shows a similar problem, which have also the same root cause.

**How to replicate**: You can try to map any WE/FAWE command to another plugin, the commands.yml settings still won't work. 

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [ ] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Panossa** [comment]
Confirmed for newest spigot 1.12, newest VS, WE, FAWE and FAVS.
But only if the setting "no-double-slash:true" is active in the WE config.

**Comment by boy0001** [comment]
Was fixed. You may need to reset the `commands.yml`
