### ISSUE TITLE
Entities in Schematics throws InvocationTargetException

### ISSUE THREAD

**Issue by Maxetto** [boy0001/FastAsyncWorldedit#59]
Most notably, Entities are added Asynchronously, causing the paste to stop.
http://pastebin.com/grAH0Auy

"Caused by: java.lang.IllegalStateException: Asynchronous entity world add!"

Using:
Spigot 1.8.8
WorldEdit b3482
WorldGuard 6.1
WorldEditSelectionVisualizer 1.4.3
CoreProtect 2.12.0
Factions 2.8.8
BlocksHub 1.2
BlocksHub-CoreProtect 1.2.1
BlocksHub-Factions 1.2
BlocksHub-WorldGuard 1.2

**Comment by RoboMWM** [comment]
I thought he stopped placing entities asynchronously... *sigh*

**Comment by boy0001** [comment]
> net.licks92.WirelessRedstone.WorldEdit.WorldEditLogger.onBlockChange
Is hooking into WorldEdit and throwing the exception.

**Comment by Maxetto** [comment]
Yeah, confirmed it's a problem with WirelessRedstone's Logger.
I've removed it from extent for now.
