### ISSUE TITLE
Why is this taking so damn long... don't understand it.

### ISSUE THREAD

**Issue by MrKiller01** [boy0001/FastAsyncWorldedit#590]
I have a rather weird issue, i use around 80 plugins on 1.12, and every day i keep it up to date, i also run FastAsyncWorldEdit-bukkit-17.06.09-0f3138e-713-13.0.17 and I am about to switch to FastAsyncWorldEdit-bukkit-17.06.16-7ae2d65-714-13.0.18. (not yet, because an action is in progress)
Sadly enough i had a small piece (one block deep - part of a tunnel (5 blocks high and 3 blocks wide), and stacked that 11000 times in a row. It took almost 5 hours to complete. This morning i had to put some light in the tunnel, so in the center i places not only one PreciousStone (cityplot) but also a candle, i selected the area from one candle to the next minus 1 of course (otherwise there will be 2 candles next to each other) and did stack that 20 times in the long corridor underground. When i started the stack command, i started my stopwatch. In a few minutes, nothing happened, so i started disabling non essential plugins, step by step, and after 15 minutes on the stopwatch it gave a reaction of former tasks i did, and finally i saw the message [FAWE] Action completed in 67.737 seconds, whilst my stopwatch told me 16.50 minutes...
I diminished the plugins temporarily to 39, and i can still disable a few...
So my question is, what is wrong here.... I reported also to the dev of WorldEdit, and i might even told you?
What i really would like to see is that FAWE handles all actions faster, because after giving this command to FAWE, all other actions, like placing, removing, moving around, and all that has nothing to do with FAWE is working perfectly....

I'd be happy to provide more info if you want to, because i am not sure which info is urgent or important for you to have...

**Comment by dordsor21** [comment]
I believe that based on how WorldEdit works, it stacks it 11000 times, rather than doing one action. It's likely far more efficient to stack 20 times then 550 times, for example

**Comment by MrKiller01** [comment]
Thanks for the insight, but now i stacked over the whole length those candles, and i devided the nr. of blocks through 11000 and the result was it finished in 187 seconds.... 
But, what are you telling me now that i should do?

**Comment by dordsor21** [comment]
try //stack 20, select that area, and //stack 550, loads of small WorldEdits are always going to be longer than fewer large ones for the same number of blocks

**Comment by MrKiller01** [comment]
Ok, gonna restart my server with newest, and i'll try this tip, thank you.....

**Comment by boy0001** [comment]
Want to attach a `/fawe debugpaste` ?

**Comment by MrKiller01** [comment]
ehm, and how exactly do i add that? just in the console?
(sorry for late reaction, a migraine kept me away!)

**Comment by dordsor21** [comment]
/fawe debugpaste in chat or in console, paste link here

**Comment by MrKiller01** [comment]
ouch, little late, sorry.

I think that you updated the plugin like a zillion times in the mean time.....
Although I now have two servers with both FAWE installed on it, i'll paste the links from both of them...
https://hastebin.com/labederesa    This is from the new inherited server
https://hastebin.com/eyofemugaz  this is from the original server I/we have

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
