### ISSUE TITLE
'/fawe debugpaste' doesn't work

### ISSUE THREAD

**Issue by AlexMCool** [boy0001/FastAsyncWorldedit#592]
**Debug paste link**:
Can't paste because of this bug

**Description of the problem:**
When typing '/fawe debugpaste' it returns an error.

**How to replicate**:
1. Type '/fawe debugpaste'

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
what error

**Comment by AlexMCool** [comment]
@dordsor21 Sorry for forgetting to add that :S 
Here's the log: https://pastebin.com/QMh42dQG

**Comment by dordsor21** [comment]
cheers

**Comment by AlexMCool** [comment]
@dordsor21 I just tried it a second ago and it still happens :(

**Comment by AlexMCool** [comment]
Now it's working again. I have no clue what caused it not to work.

**Comment by dordsor21** [comment]
Likely an issue with hastebin, though possible the way FAWE connects to hastebin isn't great.

**Comment by boy0001** [comment]
`hastebin.com` was down for maintenance.
