### ISSUE TITLE
Saving .nbt files can't go bigger than 32x32x32 (while you CAN load them in vanilla mc)

### ISSUE THREAD

**Issue by AlexMCool** [boy0001/FastAsyncWorldedit#599]
**Debug paste link**:
https://hastebin.com/jeqopubeko

**Console log**:
https://pastebin.com/0mbcHYwx

**Description of the problem:**
When you have a selection copied to your clipboard which is bigger than 32x32x32 and you try to save it as a .nbt file (//schem save nbt test1), it returns: "Unknown filename: test1" In the console, it gives you an error that the region is too large. However, you are actually able to load structures bigger than 32x32x32 via structure_blocks. So it would be really nice if you would also be able to save structures bigger than 32x32x32.

**How to replicate**:
1. Select an area which is 32x32x32
2. Look in any direction and expand the region by one "//expand 1"
3. Copy to your clipboard (//copy)
4. Save as a .nbt file (//schem save nbt test1)

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Ah, I was unable to save anything that large using structure blocks, so I just assumed the same limitation applied to loading.
