### ISSUE TITLE
Blocks seem to get "leaked"

### ISSUE THREAD

**Issue by Blue-Guy** [boy0001/FastAsyncWorldedit#60]
I typed `/hpyramid diamond,iron,gold,emerald,redstoneblock 42` and it generated a pyramid with "holes" in it. Also, holes remain after quit-rejoin

Side node: using bungeecord and paperspigot, not sure if that matters

My FAWE config: 
https://gist.github.com/Blue-Guy/d874244978b7bd6b9e4966361760771e
(practically untouched, except for disk history)

![image](https://cloud.githubusercontent.com/assets/16492168/14871066/f49395a0-0cac-11e6-870d-2ce4cd0f216e.png)

**Comment by boy0001** [comment]
Fixed.
