### ISSUE TITLE
com.sk89q.minecraft.util.commands.WrappedCommandException: java.lang.reflect.InvocationTargetException on latest SpongeForge

### ISSUE THREAD

**Issue by BrainStone** [boy0001/FastAsyncWorldedit#600]
**Debug paste link**:

https://hastebin.com/todeluwine

**Description of the problem:**

Any command results in this exception the first time: https://hastebin.com/qicehivobu.swift and this exception every time after https://hastebin.com/sapikuzubi.rb

**How to replicate**:

Setup SpongeForge server with Forge `14.21.0.2335`, SpongeForge `1.12-2331-7.0.0-BETA-2400` and FAWE `sponge-17.06.19-edd8dcc-720-13.1.7`. Then make a selection and run `//set air` (or really any other command that modifies blocks)

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
it isn't updated to 1.12 yet for sponge

**Comment by BrainStone** [comment]
Do you have an ETA for the 1.12 update for forge and or sponge?

**Comment by BrainStone** [comment]
@boy0001 @dordsor21 Still nothing? Sponge and Forge are out and stable for 1.12 for several weeks...

**Comment by BrainStone** [comment]
Fixed by #661
