### ISSUE TITLE
Structure_void blocks get replaced by air when you save a selection as a .nbt file

### ISSUE THREAD

**Issue by AlexMCool** [boy0001/FastAsyncWorldedit#601]
**Debug paste link**:
https://hastebin.com/ajipotasew

**Description of the problem:**
When you save a selection which contains structure_void blocks as a .nbt file. And you load that file via structure_blocks, the structure_void blocks get replaced with air instead of being no block at all.

**How to replicate**:
1. Select an area which contains structure_void blocks
2. Copy that area to your clipboard (//copy)
3. Save the selection as a .nbt file (//schem save nbt test)
4. Drag the .nbt file to world/structures
5. Grab a structure block and set it to load
6. Type "test" in the text box.
7. Set blocks in the region the structure block would place the structure (so you can see that all the blocks get replaced)
8. Load the structure and see that the places were structure_void blocks were, got replaced with air.

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Whoops, sorry.

**Comment by AlexMCool** [comment]
@boy0001 I just want to say that I really love this plugin and the fast bugfixes you provide =D
