### ISSUE TITLE
Feature request: Keep data when replacing

### ISSUE THREAD

**Issue by Miclebrick** [boy0001/FastAsyncWorldedit#603]
The idea is that if you did e.g. //rep wool:* concrete:*, it would keep the colors. Something like that would be very useful!

**Comment by boy0001** [comment]
`//replace #id:concrete`

https://github.com/boy0001/FastAsyncWorldedit/wiki/WorldEdit-and-FAWE-patterns
https://github.com/boy0001/FastAsyncWorldedit/wiki/Commands#patterns-id-pattern
