### ISSUE TITLE
Blockstates don't get saved to .nbt files

### ISSUE THREAD

**Issue by AlexMCool** [boy0001/FastAsyncWorldedit#604]
**Debug paste link**:
https://hastebin.com/erecipoyaz

**Description of the problem:**
As the title states, the blockstates (variants, rotation, facing, etc) don't get saved to .nbt files when saving a schematic. 

**How to replicate**:
1. Make a structure with blocks with blockstates (stairs, glazed_terracotta, furnace, end_portal_frame, etc)
2. Select the structure and save it (//schem save nbt test)
3. Load the structure via a structure_block
4. Every block has the default state 

Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by AlexMCool** [comment]
Any news on this bug?

**Comment by boy0001** [comment]
Update WorldEdit:
builds.enginehub.org/job/worldedit?branch=master
