### ISSUE TITLE
//regen does not work properly

### ISSUE THREAD

**Issue by T1MOXA** [boy0001/FastAsyncWorldedit#605]
**Debug paste link**:
https://hastebin.com/ufelomupoy
**Description of the problem:**
During regeneration of the region are skipped chunks or break the current construction at the intersection of chunks when using //sel poly

![image](https://user-images.githubusercontent.com/19938629/27331688-332079e6-55c7-11e7-933e-46b10b824a7f.png)

![image](https://user-images.githubusercontent.com/19938629/27331677-2b522278-55c7-11e7-9076-841a0b8bdbe5.png)

![image](https://user-images.githubusercontent.com/19938629/27331588-db84be68-55c6-11e7-990f-47b1e1415125.png)

Client - 1.11.2
Server - 1.12

**How to replicate**:
Make construction and around it using //sel poly, select the region and then type //regen

**Comment by T1MOXA** [comment]
With //sel cuboid same problem.
![image](https://user-images.githubusercontent.com/19938629/27332175-80c8cf16-55c9-11e7-97f4-b851dfaf8646.png)

**Comment by T1MOXA** [comment]
The same problem with //overlay
Before: 
![image](https://user-images.githubusercontent.com/19938629/27409691-7d5f64f2-56eb-11e7-90a2-d719e9237520.png)

After:
http://ssmaker.ru/781bc307.jpg

**Comment by T1MOXA** [comment]
And problem with trees 
![image](https://user-images.githubusercontent.com/19938629/27510415-9ae54594-5918-11e7-8a07-5ab445a7e425.png)

**Comment by dordsor21** [comment]
trees are randomly places, so even if you re-made a world with the same seed, trees wouldn't be in the same place. It's not possible to regen a world with the same trees afaik.

**Comment by T1MOXA** [comment]
I don't mean it.
I mean the fact that all the trees are deformed

**Comment by dordsor21** [comment]
yes, because they fall inside and outside the regen region, works fine for me otherwise though.
