### ISSUE TITLE
[FEATURE REQUEST] /br spike

### ISSUE THREAD

**Issue by bidule995** [boy0001/FastAsyncWorldedit#610]
~~Just seen that the /cs build spike from BuildCommands doesn't work anymore...~~ 
**Edit: Fixed**

So this would be cool to add a brush like this in FAWE, and maybe with more options, like a curve.

Also can be cool to have a spike with multiple points. Here is an awesome paint thing to explain my ideas:

![spikes](https://user-images.githubusercontent.com/16438002/27509759-2cc73180-5904-11e7-8758-4e17d19bbea9.png)

Would be awesome if that possible to add this brush !
Thanks.

**Comment by dordsor21** [comment]
What doesn't work about it? Any console errors etc? You might be able to get the wanted results with the spline brush anyway.

**Comment by bidule995** [comment]
Just tested recently on two different servers in 1.12, and it doesn't work since they have been updated. It doesn't display any error in chat, just doesn't place the spike. Seems that the same for every BuildCommand commands. I don't have access to the console on them. Anyways it's maybe possible to have it with the spline brush, but it's not very useful when you want to make like a large terrain with a lot of spikes, and also it will be nice to have a dedicated brush.

**Comment by dordsor21** [comment]
can confirm, build commands do not work at all.

**Comment by Panossa** [comment]
I think while /cs build is working you don't have to worry about it not being integrated natively into FAWE. Empire could focus on much more things that some addons can not provide, first. (bug fixes included)

**Comment by dordsor21** [comment]
Cs not working was a bug, that is now fixed. This is now a feature request... Smh
