### ISSUE TITLE
WorldEdit Inventory not working

### ISSUE THREAD

**Issue by kamileks999** [boy0001/FastAsyncWorldedit#612]
Hello,
I have a problem with FastAsyncWorldEdit. On my Freebuild server I gave players permission to WorldEdit, but the items aren't removing from inventory (type 2 in config).

**Comment by boy0001** [comment]
update: https://ci.athion.net/job/FastAsyncWorldEdit/

**Comment by kamileks999** [comment]
Still not working.
Now, the block limit isn't working too.
