### ISSUE TITLE
/checkblock as new command

### ISSUE THREAD

**Issue by realKSMC** [boy0001/FastAsyncWorldedit#614]
Pls add `/checkblock X Y Z` which returns the minecraft id of the block at the position, e.g.
`/checkblock 100 54 132` - answer: `minecraft:stone:2`, which is Polished Granite.
With that u open developers an possibility to create an decaying world.

**Comment by realKSMC** [comment]
In minecraft there is such `testforblock X Y Z air`, to test if there is e.g. air.
As result u get an OK or No, there is stone, but never the id u need.

**Comment by dordsor21** [comment]
I'm confused as to what the point of this is?

**Comment by realKSMC** [comment]
> With that u open developers an possibility to create an decaying world.

**Comment by realKSMC** [comment]
If u can check which block is at X Y Z u can build an database and finally create an decaying world.

**Comment by realKSMC** [comment]
FAWE is perfect for checking coordinates because it works async.

**Comment by dordsor21** [comment]
it's really not that hard to code yourself

**Comment by realKSMC** [comment]
I believe, but I am no sponge developer, just an shell scripting dude ;) Hopefully u can add this ;)

**Comment by realKSMC** [comment]
+ the most efficient way is FAWE to test tons of blocks ;)

**Comment by realKSMC** [comment]
Maybe u add the way to check also an region, like `checkblocks X1 Y1 Z1 X2 Y2 Z2` and as result all coords with their blocks, so FAWE shows its efficient work.
As result e.g.: `100 100 100 minecraft:air, 101 100 100 minecraft:stone, 102 100 100 minecraft:air, ...`

**Comment by dordsor21** [comment]
well //distr already tells you what's in a region, and that output would be very large and very ugly. This is really something that seems specific to you, so it's likely you'd get it much faster. Bukkit has an async scheduler built into it, so there's really no need to rely on FAWE to see what block is what.

**Comment by realKSMC** [comment]
Ya distr// shows how much is in an region and what, but also not the ID and not where which block is ;)

**Comment by boy0001** [comment]
All that _efficiency_ is thrown out as soon as you are doing single block checks through commands, printing everything to console, and parsing it with a scripting language. Your script won't work and I'm not adding the commands. 

Please explain exactly what you want to do with your "decaying world". There may be a way to do it using `//replace [mask] <pattern>`.

**Comment by realKSMC** [comment]
`The best solution is to learn 2 code.` - will do :)
