### ISSUE TITLE
/butcher

### ISSUE THREAD

**Issue by Fargus5** [boy0001/FastAsyncWorldedit#616]
I would like to tell you that the command /butcher doesn't work... I do this command and any mob disapper... I also tried doing /butcher 1000 but anything change.

    Ostile Mobs are still there 

Info: mcversion 1.12
Everything is the latest versions

**Comment by Fargus5** [comment]
Someone have the same problem?

**Comment by boy0001** [comment]
Can't replicate. Use `/wea`
