### ISSUE TITLE
[Bug] //set between the plots PlotSquared

### ISSUE THREAD

**Issue by loveGhb** [boy0001/FastAsyncWorldedit#621]
# Bug report template 

**Debug paste link**:
https://hastebin.com/osoqefadap

**Description of the problem:

If, in each world, the player owns two plots, it can use the command //set 1 between the sections, as will be able to install //pos 1 and //pos 2. Thus it is possible to break both the road and the plots of other players, which lie between the two sections of the player.

**How to replicate**:

Since I bad speak English, I have attached a picture https://prnt.sc/fqkcri

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of FAWE
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by loveGhb** [comment]
Digging deeper, I found out that the second phase is not needed. You can just use //pos both on the road and on someone else's site. This allows you to use the command //set

**Comment by boy0001** [comment]
You have region restrictions disabled in the config (line 20)
