### ISSUE TITLE
I have this error

### ISSUE THREAD

**Issue by Fargus5** [boy0001/FastAsyncWorldedit#622]
I have this error: what is happening?

20:57:38 CONSOLE: [INFO] (FAWE) [FAWE `tick-limiter`] Detected and cancelled physics lag source at Location{world=CraftWorld{name=Nevayln},x=-916.0,y=64.0,z=295.0,pitch=0.0,yaw=0.0}

**Comment by dordsor21** [comment]
This is not an error, it is the tick limiter doing its job.

**Comment by dougkwilson** [comment]
What is it that causes this?  What is the tick-limiter catching and can I fix/change something in my world to prevent it from continuing?
