### ISSUE TITLE
Trying to paste a schematic

### ISSUE THREAD

**Issue by Howman** [boy0001/FastAsyncWorldedit#623]
# Bug report template 

**Debug paste link**:

# Welcome to this paste
# It is meant to provide us at IntellectualSites with better information about your problem

# We will start with some informational files
links.config_yml: https://hastebin.com/sanepohavu
links.messages_yml: https://hastebin.com/zeguxibeya
links.commands_yml: https://hastebin.com/ovuyudozic
links.latest_log: https://hastebin.com/aqugurenok

# Server Information
version.server: forge

# YAY! Now, let's see what we can find in your JVM
memory.free: 416157000
memory.max: 1037959168
java.specification.version: '1.8'
java.vendor: 'Oracle Corporation'
java.version: '1.8.0_131'
os.arch: 'x86'
os.name: 'Windows 10'
os.version: '10.0'

# Okay :D Great. You are now ready to create your bug report!
# You can do so at https://github.com/boy0001/FastAsyncWorldedit/issues

server log: https://hastebin.com/otejehexas.sql

**Description of the problem:**
I was just trying to past a schematic

**How to replicate**:

Size of schematic 24K
I guess it could be that there is not a release
for world edit or fastasyncworldedit for minecraft 1.12 
**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
same error as
WorldEditing Error #615
but i was trying to paste a schematic
- [x] I made sure I am using an up-to-date version of FAWE
- [?] I Made sure the bug/error is not caused by any other plugin

**Comment by Panossa** [comment]
That's not how you're supposed to add the debugpaste xD

**Comment by dordsor21** [comment]
FAWE is not updated for sponge 1.12
