### ISSUE TITLE
Timing out issues - Nukkit

### ISSUE THREAD

**Issue by imjack** [boy0001/FastAsyncWorldedit#625]
# Bug report template 

**Debug paste link**:

(built using a local version since the build is currently failing)
**Description of the problem:**
When the plugin is used on nukkit players constantly timeout when they join.

**How to replicate**:

Have a lot of traffic to the server and everyone will crash.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Not enough info

**Comment by imjack** [comment]
What other information can I provide? I have 80 players attempting to join. When this plugin is enabled they join and instantly timeout. When a single player joins alone connecting is fine.

**Comment by dordsor21** [comment]
well, you didn't include a debugpaste

**Comment by imjack** [comment]
At the time of reporting the build was failing so I compiled it. I will check this bug again and paste the debug.

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
