### ISSUE TITLE
//move quite broken

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#631]
![inked2017-07-08_14 02 07_li](https://user-images.githubusercontent.com/10080017/27985629-83f3a44c-63e6-11e7-9aa7-16be64961b79.jpg)
![2017-07-08_14 02 21](https://user-images.githubusercontent.com/10080017/27985632-908a7cbc-63e6-11e7-9ff5-c4c960f2126f.png)
![2017-07-08_14 02 33](https://user-images.githubusercontent.com/10080017/27985633-91560ac6-63e6-11e7-916a-d4f22d599fc6.png)
![2017-07-08_14 02 44](https://user-images.githubusercontent.com/10080017/27985635-9259098c-63e6-11e7-8be7-4144cb2317a6.png)
![2017-07-08_14 02 59](https://user-images.githubusercontent.com/10080017/27985636-933ca728-63e6-11e7-9432-e136701c72a2.png)

when moving south, things get very broken

**Comment by boy0001** [comment]
should also occur when moving west sometimes.

**Comment by dordsor21** [comment]
I think it does occur west also.
