### ISSUE TITLE
Problem doing //paste

### ISSUE THREAD

**Issue by Fargus5** [boy0001/FastAsyncWorldedit#635]
Please to consider this error:

`22:06:47 CONSOLE: WARN]: java.lang.NullPointerException
22:06:47 CONSOLE: WARN]: at com.boydti.fawe.bukkit.v1_12.BukkitChunk_1_12.storeEntity(BukkitChunk_1_12.java:93)
22:06:47 CONSOLE: WARN]: at com.boydti.fawe.bukkit.v1_12.BukkitChunk_1_12.call(BukkitChunk_1_12.java:287)
22:06:47 CONSOLE: WARN]: at com.boydti.fawe.example.WeakFaweQueueMap.next(WeakFaweQueueMap.java:174)
22:06:47 CONSOLE: WARN]: at com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:199)
22:06:47 CONSOLE: WARN]: at com.boydti.fawe.bukkit.v1_12.BukkitQueue_1_12.next(BukkitQueue_1_12.java:436)
22:06:47 CONSOLE: WARN]: at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:140)
22:06:47 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
22:06:47 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
22:06:47 CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738)
22:06:47 CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
22:06:47 CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
22:06:47 CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
22:06:47 CONSOLE: WARN]: at java.lang.Thread.run(Thread.java:745)

----

# Welcome to this paste
# It is meant to provide us at IntellectualSites with better information about your problem

# We will start with some informational files
links.config_yml: https://hastebin.com/ocufukuhij
links.messages_yml: https://hastebin.com/qumibubimu
links.commands_yml: https://hastebin.com/ikolosinod
links.latest_log: https://hastebin.com/usohevujad

# Server Information
server.platform: bukkit
server.plugins: 
 - EasyCourt - Repuska - Combatant - Lift - Vehicles - PlugMan - RPGDrop - SimpleAntiProxy - DreamFish - HPWizard - MaintenanceMode - SimpleAPI - Itemizer - Timber - Realistic-Swimming - InvRestore2 - Modifyworld - VehiclesFlags - WitcheryX - ActionBarAPI - PremiumTurrets - Multiverse-Core - RealisticFish - MCCore - MVdWPlaceholderAPI - FastAsyncWorldEdit - PermissionsEx - RPGHealthIndicator - PEXPlayersRemover - RPGFood - TimeFold - FastAsyncVoxelSniper - PlaceholderAPI - VarScript - UltimateTs - PorteCoulissante - NametagEdit - GeneralLib - CompaniesManager - RPGMiner - TitleAPI - VoxelSniper - EpicWorldGenerator - Graves - ParticleLIB - PartySystem - MOTD - CoreProtect - WorldEdit - VoxelSniperGUI - OpenInv - Essentials - PlayerMention - TreasureChest - MysteryBoxes - SQLibrary - EffectLib - Vault - ChairStairs - MassiveCore - CreativeGates - StreetlightsAdvanced - EssentialsGeoIP - GrowingOres - AddLight - MyCommand - EpicNetherGenerator - ServerTutorialPlus - MessageAnnouncer - Reporter - Calendar - EssentialsChat - SkillAPI - SignColors - EssentialsProtect - EssentialsAntiBuild - EssentialsSpawn - InfernalMobs - AdvancedAchievements - OpenAudioMc - BKCommonLib - Train_Carts - TrainCartsOA - RPGHorses - HolographicDisplays - Cinematic-Death - RPGMobMoney - RPGPlayerLeveling - MythicMobs - Quests - Statz - Skript - SkAction - LargeSk - WildSkript - NPCDestinations_Animator - SimplePets - Citizens - NPC_Destinations - NPC_Police - CarlTheCreeper - WorldGuard - ResourceGens - Blacksmith - ShopChest - CommandNPC - WorldGuardPushBack - NavyCraft - Kingdoms - Sentinel - NPCDestinations_Farmer - WGRegionEvents - PirateSK - Hotels - ChatActions - Skills - Sentries - ProtocolLib - ChatItem - WorldEditSelectionVisualizer - skRayFall - TransportPipes - ChangeSkin - LiteBans - LibsDisguises - RealVillagerTowns - VanishNoPacket - RPGInventory - FactionMobs - DisguiseAbilities
server.version: git-Spigot-8cbfc85-202da97 (MC: 1.12) / 1.12-R0.1-SNAPSHOT

# YAY! Now, let's see what we can find in your JVM
memory.free: 281301664
memory.max: 7635730432
java.specification.version: '1.8'
java.vendor: 'Oracle Corporation'
java.version: '1.8.0_111'
os.arch: 'amd64'
os.name: 'Linux'
os.version: '3.14.32-xxxx-std-ipv6-64'

# Okay :D Great. You are now ready to create your bug report!
# You can do so at https://github.com/boy0001/FastAsyncWorldedit/issues`

**Comment by boy0001** [comment]
update worldedit: builds.enginehub.org/job/worldedit?branch=master
