### ISSUE TITLE
Problem with VoxelSniper that doesn't load

### ISSUE THREAD

**Issue by Fargus5** [boy0001/FastAsyncWorldedit#638]
# We will start with some informational files
links.config_yml: https://hastebin.com/manoxunanu
links.messages_yml: https://hastebin.com/jivegobine
links.commands_yml: https://hastebin.com/afoqavolew
links.latest_log: https://hastebin.com/dojiticala

# Server Information
server.platform: bukkit
server.plugins: 
 - EasyCourt - Repuska - Combatant - Lift - Vehicles - PlugMan - RPGDrop - SimpleAntiProxy - DreamFish - HPWizard - MaintenanceMode - SimpleAPI - Itemizer - Timber - Realistic-Swimming - InvRestore2 - Modifyworld - VehiclesFlags - WitcheryX - ActionBarAPI - PremiumTurrets - Multiverse-Core - RealisticFish - MCCore - MVdWPlaceholderAPI - FastAsyncWorldEdit - PermissionsEx - RPGHealthIndicator - PEXPlayersRemover - RPGFood - TimeFold - FastAsyncVoxelSniper - PlaceholderAPI - UltimateTs - PorteCoulissante - NametagEdit - GeneralLib - CompaniesManager - RPGMiner - TitleAPI - EpicWorldGenerator - Graves - ParticleLIB - PartySystem - MOTD - CoreProtect - WorldEdit - OpenInv - Essentials - PlayerMention - TreasureChest - MysteryBoxes - SQLibrary - EffectLib - Vault - ChairStairs - MassiveCore - CreativeGates - StreetlightsAdvanced - EssentialsGeoIP - GrowingOres - AddLight - MyCommand - EpicNetherGenerator - ServerTutorialPlus - MessageAnnouncer - Reporter - Calendar - EssentialsChat - SkillAPI - SignColors - EssentialsProtect - EssentialsAntiBuild - EssentialsSpawn - InfernalMobs - AdvancedAchievements - OpenAudioMc - BKCommonLib - Train_Carts - TrainCartsOA - RPGHorses - HolographicDisplays - Cinematic-Death - RPGMobMoney - RPGPlayerLeveling - MythicMobs - Quests - Statz - Skript - SkAction - LargeSk - WildSkript - NPCDestinations_Animator - SimplePets - Citizens - NPC_Destinations - NPC_Police - CarlTheCreeper - WorldGuard - ResourceGens - Blacksmith - ShopChest - CommandNPC - WorldGuardPushBack - NavyCraft - Kingdoms - Sentinel - NPCDestinations_Farmer - WGRegionEvents - PirateSK - Hotels - ChatActions - Skills - Sentries - ProtocolLib - ChatItem - WorldEditSelectionVisualizer - skRayFall - TransportPipes - ChangeSkin - LiteBans - LibsDisguises - RealVillagerTowns - VanishNoPacket - RPGInventory - FactionMobs - DisguiseAbilities - VoxelSniper
server.version: git-Spigot-8cbfc85-202da97 (MC: 1.12) / 1.12-R0.1-SNAPSHOT

# YAY! Now, let's see what we can find in your JVM
memory.free: 587120568
memory.max: 7635730432
java.specification.version: '1.8'
java.vendor: 'Oracle Corporation'
java.version: '1.8.0_111'
os.arch: 'amd64'
os.name: 'Linux'
os.version: '3.14.32-xxxx-std-ipv6-64'

**Comment by boy0001** [comment]
Try updating FastAsyncVoxelSniper

**Comment by Fargus5** [comment]
Dear

Thanks for your answer... but after some try, we individuated the problem.
Problem is the latest version of FAVS...
We removed it and now voxelsniper works correctly as aspected. If we add it, everything will broke.
Instead latest version of FAWE works correctly.

**Comment by boy0001** [comment]
According to part of your startup log, VoxelSniper loaded correctly:
```
[20:19:08] [Server thread/INFO]: [VoxelSniper] Enabling VoxelSniper v5.171.0-SNAPSHOT
[20:19:08] [Server thread/INFO]: [VoxelSniper] Registered 75 Sniper Brushes with 149 handles.
[20:19:08] [Server thread/INFO]: [VoxelSniper] Registered Sniper Listener.
```

What indicated to you that it didn't? Any errors in console?

**Comment by Fargus5** [comment]
I don't know, but any commands works with latest version. If I do /b e fill doesn't work... and plugin result don"t be loaded. If I go in the folder, i find two voxelsniper.jar generated automatically.

It's not normal, this maybe block the plugin loading. Instead, as I told you, if I remove the latest version of FAVS and I put the precedent version, voxelsniper works correclty

**Comment by boy0001** [comment]
What  version of FAVS were you using?

**Comment by Fargus5** [comment]
https://github.com/boy0001/FastAsyncWorldedit/releases/tag/v3.5.0-dev

This version http://empcraft.com/fawe/latest.php?favs

**Comment by boy0001** [comment]
That's just a redirect to the latest version. It should say during startup what version it is. 

This is current version:
http://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/FastAsyncVoxelSniper-favs-17.07.11-65c6702-748-13.7.4.jar

**Comment by Fargus5** [comment]
I updated FAVS yesterday... so. All of yesterday and all of this morning voxel didn't work.
I use to have always latest versions of all... so I don't know what to tell you more than what I already sent to you.


So having latest version of favs. Starting the server it duplicate me the voxelsniper.jar and any commands worked.

Putting just the precedent version, everything was ok.

I will let you come in the server later if you want ....

**Comment by boy0001** [comment]
Can anyone else replicate?
