### ISSUE TITLE
Holes in copy/paste operation.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#64]
FAWE 3.4.2
WorldEdit 6.1.1 dev 3487
ProtocolLib 4.0 dev 273
PaperSpigot 712.

Copied a perfect glass box with some chests and a sign (//copy), then pasted a little bit further away (//paste). Tested numerous times, each time with different holes located in the build. Problem with compression or read from disk maybe?

![link](http://i.imgur.com/ZXjNTll.png)
![link2](http://i.imgur.com/uO9x2HS.png)
![link3](http://i.imgur.com/CeovWsa.png)
```
limits:
  default:
    max-changes: 50000000
    max-checks: 50000000
    max-iterations: 1000
    max-entities: 1337
    max-fails: 50000000
    max-blockstates: 1337
region-restrictions: false
max-memory-percent: 95
lighting:
  async: true
  fix-all: true
command-blacklist:
- cs
- .s
- restore
- snapshot
- delchunks
- listchunks
history:
  use-disk: true
  buffer-size: 531441
  chunk-wait-ms: 100
  compress: true
  delete-after-days: 7
queue:
  discard-after-ms: 60000
  max-wait-ms: 1000
  target-size: 64
  extra-time-ms: 0
  parallel-threads: 1
command-processor: false
extent:
  allowed-plugins: []
  debug: false
crash-mitigation: true
metrics: false
require-selection-in-mask: false
clipboard:
  delete-after-days: 1
  use-disk: true
```

**Comment by mibby** [comment]
Disabling compress for history, I can't seem to reproduce the holes. So the compression would be the problem from my testing.

With compression enabled on history.
![link5](http://i.imgur.com/dF5dLIo.png)

Without compression enabled on history.
![link6](http://i.imgur.com/b2bxiHM.png)

**Comment by mibby** [comment]
Scratch that, as I had a hole occur with compression disabled (use-disk enabled). Compression enabled just makes the holes more common. 

![link9](http://i.imgur.com/T9hJaKn.png)

**Comment by boy0001** [comment]
It could be an issue with the clipboard on disk which is a relatively new feature. If it's related to any history settings (which I doubt since you aren't using undo/redo) it would probably be indirectly e.g. having history compression enabled slows down the execution which increases some condition related to the bug.

Anyway, try disabling clipboard on disk and see if that's your problem.

**Comment by mibby** [comment]
As can be seen from the above screenshot and comment, I tested with all compression and disk settings disabled. The problem still occasionally happens.

**Comment by boy0001** [comment]
You mentioned the compression / disk settings for history. I wasn't sure if you tested with the clipboard.

**Comment by mibby** [comment]
I first tested with compress and all use-disk settings enabled. Then with compression disabled, then with all use-disk settings disabled. Just to cover all bases for testing to make sure none of those settings were the direct cause. More frequent with it enabled, but still happens with it disabled.

So yes, I tested with use-disk disabled for clipboard. :)
