### ISSUE TITLE
Option to disable file deletion verbose at startup.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#640]
http://paste.ubuntu.com/25064492/

**Comment by dordsor21** [comment]
How would you have history deleted otherwise? You could always just up how log history is kept a lot

**Comment by mibby** [comment]
I'm not asking for the deletion to be removed, just hide the verbose from outputting to console or add an option to log it to a separate log file in the FAWE folder if you wanted a history of what it deleted.

**Comment by boy0001** [comment]
Update the plugin and change `file_deleted` to empty quotes in the `message.yml`.
