### ISSUE TITLE
API - Undoing all changes on an EditSession

### ISSUE THREAD

**Issue by XLordalX** [boy0001/FastAsyncWorldedit#643]
I am trying to paste a schematic gradually (1 block every few ticks). This works fine with the following code:

        new BukkitRunnable()
        {
            @Override
            public void run()
            {
                if(!iterator.hasNext())
                {
                    cancel();
                    return;
                }

                Pair<Vector, BaseBlock> block = iterator.next();
                Vector relative = block.getKey();
                Vector clone = new Vector(relative.getX(), relative.getY(), relative.getZ());

                try
                {
                    session.setBlock(clone.add(new Vector(location.getX(), location.getY(), location.getZ())),
                            block.getValue(), true);
                    session.flushQueue();
                }
                catch (MaxChangedBlocksException e)
                {
                    cancel();
                    e.printStackTrace();
                }
            }
        }.runTaskTimer(plugin, 0, 5);

However, after a while I want to remove every block that has been pasted. For this I tried the following:

        session.undo(session);
        session.flushQueue();

The problem with this, though, is that it only removes the last block that was pasted.

How can I undo all blocks which have been pasted gradually?

**Comment by ediTv2** [comment]
Am also curious on this..

Any ideas/suggestions @boy0001?

**Comment by N0tMyFaultOG** [comment]
If you need help still, reply to the ticket.
