### ISSUE TITLE
Possibility to add worldedit option "disallowed-blocks" by rank  ?

### ISSUE THREAD

**Issue by fhebuterne** [boy0001/FastAsyncWorldedit#645]
Hello,

On my server, we have replace AsyncWorldEdit by FAWE and i've see it's not possible to configure disallowed-blocks by rank whereas it possible in AsyncWorldEdit.

Can you add this please ?

Sincerely yours,
Fabien

**Comment by kamileks999** [comment]
You can do it in WorldGuard blacklist

**Comment by fabien91** [comment]
@kamileks999 No, i want this option to configure disallowed-blocks by **rank** on my server, this function doesn't exist with worldguard and blacklist worldguard don't work this commande worldedit like //set etc...

**Comment by boy0001** [comment]
The disallowed blocks can easily be bypassed on WE/AWE using the clipboard pattern, stack and other commands. 

What blocks do you want to disallow and why?

**Comment by fabien91** [comment]
@boy0001 This option disallowed blocks are for all command of FAWE and worldedit like //set and no just for placing with hand.
Example : I want to disabled redstone torch with //set and all command WE for the first and second rank of my creative server because it's possible to generate many entities and maybe a crash server.
This is possible with AsyncWorldEdit but not with FAWE.

**Comment by dordsor21** [comment]
limit.disallowedblocks in WE config.yml

![image](https://user-images.githubusercontent.com/10080017/28268561-9f53d272-6af6-11e7-9267-428f527f88a1.png)

**Comment by fabien91** [comment]
@dordsor21 It don't work by **RANK** in the WE config ...

**Comment by boy0001** [comment]
@fabien91 
FAWE's tick limiter is there to prevent entity spam. What is your configuration? Does it not detect and cancel when people use `//set redstonetorch` ?

**Comment by fabien91** [comment]
@boy0001 It's juste an example but i don't player //set a big block of hooper or other, it's can generate many tiles and the server don't like many tiles.
Example : I've generate an plot with only hooper and an expand vert and i'm disconnect after //set hooper with this error :

![wlilulrn_17-07-17_20-02-15](https://user-images.githubusercontent.com/5675697/28282515-f5f6b160-6b2a-11e7-85eb-52879788c218.png)

That why i want to disable block by rank and i don't want my new player use some blocks like hooper with WorldEdit or FAWE commands.

**Comment by boy0001** [comment]
You can already set a `tile` and `entity` limit per player with FAWE.

**Comment by RedstoneFuture** [comment]
Sorry, but where I must define this?

`[03:09:34 INFO]: (FAWE) Failed to set config option: limits.disallowed-blocks: [137, 210, 211, 255] | null | Settings.yml`

**Comment by RedstoneFuture** [comment]
ah, okay ... I have to define it in the /plugins/WorldEdit/config.yml and it work (with the correct permission). :) Thanks.

**Comment by boy0001** [comment]
@RedstoneFuture It's the same with normal WorldEdit.
