### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Nishh** [boy0001/FastAsyncWorldedit#646]
# Bug report
**Debug paste link**:
https://hastebin.com/emowogizak

**Description of the problem:**
Crash txt created by server: https://hastebin.com/picitafaxe.sm
Log https://hastebin.com/wuqatiqica.vbs (is it because of "tick-limiter"?)

**How to replicate**:
Not sure but i think it happens when chunk generated with a lot of block physics

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
The tick limiter is just cancelling physics, it shouldn't be the cause. Checkout and remove whatever is at the offending chunk. 
`EfsaneCraft_Orman,x=917197.0,y=21.0,z=841862.0`

**Comment by Nishh** [comment]
http://efsanecraft.com/2017-07-25_12.48.05.png
just lava

**Comment by Nishh** [comment]
this happened once and crashed server
