### ISSUE TITLE
error with anvil command

### ISSUE THREAD

**Issue by PhanaticD** [boy0001/FastAsyncWorldedit#650]
https://pastebin.com/raw/qjaYzG72

**Comment by boy0001** [comment]
Seems your 1.11 jar has a different field name to the one I was building against.

**Comment by PhanaticD** [comment]
am using paperspigot, hope it doesnt matter for regular spigot users?

**Comment by dordsor21** [comment]
works fine on paper 1.12 for me

**Comment by boy0001** [comment]
@PhanaticD 
Try the update. I changed how it refreshes the chunk.
