### ISSUE TITLE
NoClassDefFound Error when using #saturate pattern

### ISSUE THREAD

**Issue by braceyourself07** [boy0001/FastAsyncWorldedit#651]
# Bug report

**Debug paste link**:

https://hastebin.com/qunatocige

**Description of the problem:**

When using the #saturate pattern I get the following error:
[![Screenshot from Gyazo](https://gyazo.com/27ae8e567b4783b30b2fb34593c082d1/raw)](https://gyazo.com/27ae8e567b4783b30b2fb34593c082d1)

Error in console:  https://hastebin.com/zohewocoho.swift

I have 1.12.jar in /textures

**How to replicate**:

See command used in screenshot

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Not sure why you're getting this now. That's a java class that's missing.
