### ISSUE TITLE
Crashes when use .flushQueue();

### ISSUE THREAD

**Issue by XjCyan1de** [boy0001/FastAsyncWorldedit#652]
# Bug report
**Debug paste link**:
Crash report: https://hastebin.com/pedoduxusi.md
ru.cyanworld.cyanuniverse.Coding.moveBlocks(Coding.java:688) is  paste.flushQueue();

**Description of the problem:**
Server crashes randomly when use this method: 
`            EditSession copy = new EditSessionBuilder(world).fastmode(true).build();
            EditSession paste = new EditSessionBuilder(world).fastmode(true).build();
            CuboidRegion region = new CuboidRegion(pos1, pos2);
            BlockArrayClipboard lazyCopy = copy.lazyCopy(region);
            Schematic schem = new Schematic(lazyCopy);
            schem.paste(paste, pasteto, true);
            paste.flushQueue();`

**Ho`w to replicate**:
Its crash throwing randomly i cant replicate this

**Comment by boy0001** [comment]
I don't know if that'll fix it. Please try it and let me know.
