### ISSUE TITLE
specific "bug"

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#653]
trying to use `/patterns #relative[=[y>0]]`

which ought to work, however get sent `Couldn't find #relative[=[y>0]]. Maybe try one of #relative ?`

**Comment by boy0001** [comment]
`/material` is for setting your brush pattern, and will accept arguments.     
`/patterns` Is for listing patterns and help. It won't accept arguments.

**Comment by dordsor21** [comment]
Huh. Okay
