### ISSUE TITLE
Throws NPE when new Schematic(region). FAWE b756 

### ISSUE THREAD

**Issue by XjCyan1de** [boy0001/FastAsyncWorldedit#654]
# Bug report
FAWE 17.7.22-b07d728-756

**Description of the problem:**
When making new Schematic(), fawe throws NPE when making new Schematic(region);
Code:
![image](https://user-images.githubusercontent.com/18630111/28491000-63b3ecc2-6ef0-11e7-819c-26619b567825.png)
Logs: https://hastebin.com/vunujaxeba.vbs

**Comment by boy0001** [comment]
A world needs to be provided
```Java
Region region = new CuboidRegion(world, pos1, pos2)`
```

**Comment by XjCyan1de** [comment]
Oh thanks. Why its possible to make Region without world? :D

**Comment by boy0001** [comment]
Because legacy WorldEdit didn't have the Extent class, and changing it now would break plugins that use the API.

I've changed the error message, so it should be more helpful to anyone else using it.
