### ISSUE TITLE
Meta data bug.

### ISSUE THREAD

**Issue by WolfVFX** [boy0001/FastAsyncWorldedit#655]
hello Dev,

today I was using FAWE and I pasted a map with colored blocks and the blocks where changes to another meta tag data I'm using 1.7.10.
![2017-07-23_23 09 36](https://user-images.githubusercontent.com/30395144/28504104-4d43c080-7011-11e7-919e-3befc5b62c88.png)
![2017-07-23_23 09 32](https://user-images.githubusercontent.com/30395144/28504107-57c891f2-7011-11e7-9359-12e14f277861.png)

**Comment by boy0001** [comment]
Could you please attach the schematic you are using, and a `/fawe debugpaste` ?

**Comment by WolfVFX** [comment]
https://hastebin.com/junucapuji

**Comment by WolfVFX** [comment]
[Schematic .zip](https://github.com/boy0001/FastAsyncWorldedit/files/1170575/Schematic.zip)
here the schematic where you asked for
