### ISSUE TITLE
fail net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FastAsyncWorldEdit(com.boydti.fawe)

### ISSUE THREAD

**Issue by SiliconeValley** [boy0001/FastAsyncWorldedit#657]
# Bug report

**Debug paste link**:

**Description of the problem:**
 FAWE crashes constantly, error code is on the title. Here's the full crash report:

> ---- Minecraft Crash Report ----
> // Would you like a cupcake?
> 
> Time: 7/24/17 8:40 PM
> Description: There was a severe problem during mod loading that has caused the game to fail
> 
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FastAsyncWorldEdit (com.boydti.fawe)
> Caused by: java.lang.NoClassDefFoundError: com/boydti/fawe/object/FaweQueue
> 	at com.boydti.fawe.forge.ForgeMain.preInit(ForgeMain.java:33)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:635)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
> 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
> 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:626)
> 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:438)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:350)
> 	at net.minecraft.client.main.Main.main(SourceFile:124)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> Caused by: java.lang.ClassNotFoundException: com.boydti.fawe.object.FaweQueue
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	... 38 more
> Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/extent/Extent
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(Unknown Source)
> 	at java.security.SecureClassLoader.defineClass(Unknown Source)
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
> 	... 40 more
> Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.extent.Extent
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	... 44 more
> Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/extent/InputExtent
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(Unknown Source)
> 	at java.security.SecureClassLoader.defineClass(Unknown Source)
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
> 	... 46 more
> Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.extent.InputExtent
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	... 50 more
> Caused by: java.lang.NullPointerException
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
> 	... 52 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.11
> 	Operating System: Windows 10 (x86) version 10.0
> 	Java Version: 1.8.0_131, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
> 	Memory: 131905968 bytes (125 MB) / 294371328 bytes (280 MB) up to 523501568 bytes (499 MB)
> 	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP 9.35 Powered by Forge 13.19.1.2199 5 mods loaded, 5 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 	UCH	minecraft{1.11} [Minecraft] (minecraft.jar) 
> 	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
> 	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11-13.19.1.2199.jar) 
> 	UCH	forge{13.19.1.2199} [Minecraft Forge] (forge-1.11-13.19.1.2199.jar) 
> 	UCE	com.boydti.fawe{3.5.1} [FastAsyncWorldEdit] (FastAsyncWorldEdit-forge111-17.07.24-9649482-760-13.7.18.jar) 
> 	Loaded coremods (and transformers): 
> 	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.14008 Compatibility Profile Context 21.19.128.4' Renderer: 'Radeon (TM) R5 M420' 

Specs:
Intel Core i7 - 7500U Dual Core
AMD Radeon R5 M420
4GB RAM

**How to replicate**:
Launch FAWE with Forge 1.10.2-12.18.3.2316 or Forge 1.11 13.19.1.2199

**Checklist**:

- [] I included a `/fawe debugpaste` link (There's none)
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by DR4RCON** [comment]
Which worldedit version you are using?

**Comment by SiliconeValley** [comment]
The latest one of course..

**Comment by DR4RCON** [comment]
Cant see its loaded. Dont mix FAWE with worldedit. Fawe can only work on top of worldedit.

**Comment by DR4RCON** [comment]
and 512MB Memory? Thats less then the recommended 1GB for minecraft vanilla. Really want to work with this?

**Comment by SiliconeValley** [comment]
oh shet 
I forgot to turn on jvm arguments
but I don't think that's the problem

**Comment by SiliconeValley** [comment]
xD I don't mix FAWE with WorldEdit

**Comment by SiliconeValley** [comment]
when I add FAWE to WorldEdit mod files
WorldEdit completely takes over

**Comment by DR4RCON** [comment]
You said you are using worldedit 3.5.0-dev, but worldedit is on release 6.1.4
Put this into your modfolder WorldEdit for Forge 1.10.2 http://empcraft.com/fawe/latestwe.php?branch=feature%2Fforge-1.10&platform=forge

**Comment by SiliconeValley** [comment]
FAWE 3.5.0-dev oh gosh

**Comment by SiliconeValley** [comment]
my fault anyway

**Comment by DR4RCON** [comment]
;-) I checked this out, using forge too, see my last posted report. Fawe is fantastic, works like expected in my case, also when it not can cover all blocks of all mods Iam using.
Have a nice day!

**Comment by SiliconeValley** [comment]
Solved, thanks!

**Comment by SiliconeValley** [comment]
WAIT
I used 1GB of RAM
and it still said out of memory

**Comment by DR4RCON** [comment]
sure that is much to less for a modded minecraft try minimum 2GB and dont forget to close that issue please.

**Comment by SiliconeValley** [comment]
like what...

**Comment by SiliconeValley** [comment]
ok

**Comment by SiliconeValley** [comment]
how to close xD

**Comment by DR4RCON** [comment]
*g* The button next to comment, you hit 10 times. "Close Issue" No need for another developer to stick in this. ;-)
