### ISSUE TITLE
/b snow is buggy

### ISSUE THREAD

**Issue by Panossa** [boy0001/FastAsyncWorldedit#658]
**Debug paste link**:
https://hastebin.com/nulucasela (probably not needed)

**Description of the problem:**
Sometimes /b snow is buggy. See attached image:
![snap_2017 07 24_22h34m39s_004_](https://user-images.githubusercontent.com/23323875/28543546-746d32ea-70c0-11e7-8fd1-64382313fde1.png)
![snap_2017 07 24_22h32m47s_003_](https://user-images.githubusercontent.com/23323875/28543550-769486b8-70c0-11e7-98aa-7e978f2fbb95.png)

**How to replicate**:
Use /b snow on some place where many slabs/stairs are used. Here's a schematic that I used for the images.
[panossa1.zip](https://github.com/boy0001/FastAsyncWorldedit/files/1171143/panossa1.zip)

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [?] I Made sure the bug/error is not caused by any other plugin <- VoxelSniper?

**Comment by boy0001** [comment]
Does the same issue occur without FAVS?

**Comment by Panossa** [comment]
The behaviour seems to be pretty different when using FAVS rather than not using FAVS. But the bug I was talking about appears even without FAVS.
Here's 4 screenshots without FAVS:
1. (Equipped brush ![2017-07-28_01 30 52](https://user-images.githubusercontent.com/23323875/28696213-78b4ba6e-7334-11e7-9e6a-3cef51715ce8.png)
2. (First click - same cursor position) 
![2017-07-28_01 30 55](https://user-images.githubusercontent.com/23323875/28696230-8cf1a5a0-7334-11e7-95e8-030e20d52769.png)
3. (Second click - still same cusor pos)
![2017-07-28_01 30 59](https://user-images.githubusercontent.com/23323875/28696233-97d8e6ea-7334-11e7-9148-83307db9e726.png)
4. (Last click - still same pos)
![2017-07-28_01 31 01](https://user-images.githubusercontent.com/23323875/28696254-c2c34c74-7334-11e7-89ff-7a9230c3da13.png)

Now with FAVS:
1. (Equipped brush)
![2017-07-28_01 35 30](https://user-images.githubusercontent.com/23323875/28696329-376f8eca-7335-11e7-964b-4f219cf35e1a.png)
2. (First click - same cursor position) 
![2017-07-28_01 35 34](https://user-images.githubusercontent.com/23323875/28696334-3e7eb772-7335-11e7-8ce6-2e93282bf69a.png)
3. (Second click - still same cusor pos)
![2017-07-28_01 35 37](https://user-images.githubusercontent.com/23323875/28696339-44621120-7335-11e7-98c3-67e0af4ef278.png)
4. (Last click - still same pos)
![2017-07-28_01 35 41](https://user-images.githubusercontent.com/23323875/28696344-4bc56e44-7335-11e7-833d-7837c6404a22.png)

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
