### ISSUE TITLE
/visualize 0 forgets to clear existing (clientside) glass

### ISSUE THREAD

**Issue by Panossa** [boy0001/FastAsyncWorldedit#659]
**Debug paste link**:
https://hastebin.com/nulucasela (probably not needed)

**Description of the problem:**
If you use /visualize 1 or 2 on a brush and then set /visualize to 0 then the glass stays where it was.

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report 
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Fixed in 2712f5fea855e0e42320a7c275dec2c2f3662e7a
