### ISSUE TITLE
Schematics folder?

### ISSUE THREAD

**Issue by GrandNickyNick** [boy0001/FastAsyncWorldedit#660]
Hello, I currently have FastAsyncWorldedit installed on my Sponge server. I have not been able to locate a schematics folder to drop a schematic from another one of my servers. 

Configuration:
Default (Literally have not touched a thing) 

Version:
FastAsyncWorldEdit-sponge-17.07.25-2712f5f-761-13.7.19.jar

Directories:
[](http://prntscr.com/fzwzzk)

**Comment by GrandNickyNick** [comment]
http://prntscr.com/fzwzzk - Directory for FastAsyncWorldedit.

**Comment by N0tMyFaultOG** [comment]
They are stored in your `/plugins/config/worldedit/schematics` folder
