### ISSUE TITLE
Add progress information for lighting as well

### ISSUE THREAD

**Issue by BrainStone** [boy0001/FastAsyncWorldedit#662]
Hi. I recently had the issue that when lighting is async that after the progress finishes, the lighting takes a long time after (about as long as the actual action). This is ok, however there is no indication that something is going on. Having a second status title for the lighting progress would be very useful!

(Talking about round about 500 000 000 blocks. Which takes several minutes)

**Comment by boy0001** [comment]
If you disable `delay-packet-sending`, it'll send the chunks earlier. 

There are several other things occurring after the block changes complete. The change may still be writing to disk, and the server will be unloading/saving chunks.

**Comment by BrainStone** [comment]
or generally having a progress indicator for the whole thing would be really cool.
