### ISSUE TITLE
Primary and secondary brush quite broken.

### ISSUE THREAD

**Issue by Panossa** [boy0001/FastAsyncWorldedit#665]
**Debug paste link**:
https://hastebin.com/aloceyayat

**Description of the problem:**
1. If you set only the primary brush, left click is set to the same as right click resulting in not being able to destroy blocks with your hand cause instead the brush gets activated (even though left click is the secondary brush and therefore should do nothing as nothing is specified).
2. If you only set the secondary brush (without having a primary one) both brushes get set.
3. There is no option to remove only one brush (primary OR secondary).

**How to replicate**:
1. 
```
/br primary sphere 1
<left click>
```
What it should do: (if not sword equipped:) Destroy one block if in reach. (Or even better: The same could happen if you use `/br sphere 1` cause normally you're meaning only the right click while executing /br.)
What it does: Executes a brush iteration.
2. 
```
/br primary sphere 1
<right click>
```
What it should do: (if not sword equipped:) Nothing.
What it does: Executes a brush iteration.
3. `/br primary none` or something similar doesn't work.

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Panossa** [comment]
Update: I just realized `/size` and `/mat` have **no** param to specifiy whether you mean the primary brush or the secondary brush.

**Comment by boy0001** [comment]
@Panossa 
It sets the last used brush. To change the offhand, use `/size <value> -h`
