### ISSUE TITLE
CraftScript is very buggy.

### ISSUE THREAD

**Issue by Panossa** [boy0001/FastAsyncWorldedit#666]
**Debug paste link**:
https://hastebin.com/aloceyayat

**Description of the problem:**
The WorldEdit Craftscript seems to be working pretty random. Sometimes it just breaks without pasting **any debug info** in the console and every command you use afterwards that uses craftscrips seems to be broken.
[NOTE:] I remember one older version of FAWE where I had no problems at all with CraftScripts.

**How to replicate**:
1. Install e.g. the given craftscript: [craftscripts.zip](https://github.com/boy0001/FastAsyncWorldedit/files/1181526/craftscripts.zip)
2. `/cs build` (sometimes even this pastes "error while executing..." in chat and everything's broken.)
3. `/cs build list`
4. `/cs build spike info`
5. Every other /cs execution is broken at this point. (except `/cs` without params.)

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Panossa** [comment]
Update: I tested another script ("Rotate script" by the same guy I suppose) on my 1.8.8 server after /cs build got me a "error while executing" error and it showed me:
![snap_2017 07 28_01h23m08s_005_](https://user-images.githubusercontent.com/23323875/28696076-9fda69dc-7333-11e7-9896-d75676d8879d.png)

**Comment by boy0001** [comment]
Can you try that "rotate script" without FAWE?

**Comment by Panossa** [comment]
Okay the rotate script doesn't work without FAWE.
But to be fair... WorldEdit has problems with scrips in general. It can't even execute one of the build scripts. Plain WE doesn't say "error while executing" though.
![2017-07-28_14 18 17](https://user-images.githubusercontent.com/23323875/28716847-9e3a7ed4-739f-11e7-9f29-c08fb6c3a7dc.png)

Here's the rotate script btw. (Worked on an older version of FAWE as well as the build scrips):
[rotate.zip](https://github.com/boy0001/FastAsyncWorldedit/files/1182988/rotate.zip)

**Comment by Panossa** [comment]
I congrat myself on opening #666 btw. Best number.

**Comment by braceyourself07** [comment]
You try equipping a brush like a wooden stick and then running the cs command?

**Comment by Panossa** [comment]
Sure! Sometimes it works and sometimes it doesn't

**Comment by braceyourself07** [comment]
Could try inhaze's build tools at http://inhaze.net/resources/build_commands/ which includes a rotate script, but it's also buggy especially for large edits.  Will want to increase the script timeout significantly to give it more time to process, otherwise it will only half-do the edit and sometimes can't undo :(

**Comment by Panossa** [comment]
I have a normal (very good) rotate script and the inhaze tools. But both of them work only like every second time when I test them. (the standalone rotate script isnt working for a longer time)

**Comment by boy0001** [comment]
@Panossa
The error above (```cannot call method "setDisplayName" of null```) is caused by you trying to bind to your hand. You need to hold an item. The error occurs without FAWE.

**Comment by Panossa** [comment]
Okay you're right. But the initial bug still remains. :/

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
