### ISSUE TITLE
Fixlighting makes players in certain chunks invisible.

### ISSUE THREAD

**Issue by Panossa** [boy0001/FastAsyncWorldedit#669]
**Debug paste link**:
https://hastebin.com/wamevalade

**Description of the problem:**
If you use //fixlighting in an area bigger than one chunk (the chunk of the execution excluded - I think) you'll have invisible players. (MC 1.12 was tested)
As seen in the video down below (I was between two chunks when the execution started, I believe) I have only two chunks in which I or other players are visible (for me) after //fixlighting was executed. Players seem only to see players which are in the chunks where they were when the command was executed.
https://youtu.be/hEAem5uR4qs

**How to replicate**:
Fix lighting in a huge area and try moving around in F5.
**IMPORTANT:** Doesn't occur every time the command is executed!

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Panossa** [comment]
Possibly relates to #454

**Comment by boy0001** [comment]
Duplicate
