### ISSUE TITLE
Layer brush permission bug

### ISSUE THREAD

**Issue by Panossa** [boy0001/FastAsyncWorldedit#670]
**Debug paste link**:
https://hastebin.com/wamevalade

**Description of the problem:**
Even though I have admin rights and build permissions in my world (i can use normal brushes) this brush shows me that my region is wrong: `/br layer 10 2 2 175:2 175:10`
"Outside allowed region" it says.

**How to replicate**:
Use the command and right click ^^

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Panossa** [comment]
Btw I'm trying to place two block tall tallgrass and it's not working. Is there maybe any other way to do that? There's no bone meal brush.

**Comment by Panossa** [comment]
Update: I tested a bit more. Here's a video:
https://youtu.be/LR20g01zyQw
Look in the video description, there is the console output to that bug.
(Also: Why does the brush NOT place the halfs of the double plants on the surface where it WORKS?)

**Comment by EnderZaMan** [comment]
This is a legit bug, seems to be happening in some areas with the splatter brush as well.

**Comment by boy0001** [comment]
It occurs when it tries to change a block below the world.

**Comment by Panossa** [comment]
Ok can confirm. Maybe change the message to "Region outside of the world"?
But this isn't a bug and can be closed I think. Then I'll open a feature request for /br bonemeal or something that can actually place double tallgrass
