### ISSUE TITLE
Issues on 1.12.1

### ISSUE THREAD

**Issue by FrankHeijden** [boy0001/FastAsyncWorldedit#675]
# Bug report

**Debug paste link**:

https://hastebin.com/radepateme

**Description of the problem:**

issue on //paste and //br
//paste: https://hastebin.com/honahexefa.bash
//br: https://hastebin.com/ehijumaguw.pl

type //paste or //br
**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by mikroskeem** [comment]
Reproduceable on 1.12.1.

**Comment by aikar** [comment]
This is due to Spigot unobfuscating TileEntity#load
