### ISSUE TITLE
Anvil replaceall borking worlds and explosions on said worlds

### ISSUE THREAD

**Issue by Miclebrick** [boy0001/FastAsyncWorldedit#676]
# Bug report

**Description of the problem:**
I've been having issues with explosions freezing the server in certain areas on certain planets, and I just, finally, FINALLY realized some MINORLY relevant piece of information - both of those planets are worlds I did //anvil replaceall on to change ores. Basically, when any explosion happens in some (random?) areas on those two planets, the server freezes to crap. Is there anything I can do??

**How to replicate**:
I don't actually know..? Very weird bug...

**Comment by Miclebrick** [comment]
Oh, and if it helps, I get this error when I don't force restart it: https://pastebin.com/FGakA4i9

**Comment by Miclebrick** [comment]
Do I have any option besides resetting the worlds? People live there...

**Comment by boy0001** [comment]
You can disable explosions with worldguard or something. 
If you can still replicate the crash by going to a specific position in the map, please attach that here. 
If you remember what command you ran when doing the replace, that will also help.

**Comment by dordsor21** [comment]
is this fixed @Miclebrick ? As possible relation to #691 with saving not quite working

**Comment by Miclebrick** [comment]
I ended up resetting the world and no longer know the coords, sorry.

Commands I did:
/mv unload QuodCanis
//anvil replaceall QuodCanis 99:3 1
/mv load QuodCanis

My theory is that it might be because instead of removing the world and changing the world and restarting, I used multiverse commands.
