### ISSUE TITLE
Glitchy Colors

### ISSUE THREAD

**Issue by SpaicyGaming** [boy0001/FastAsyncWorldedit#679]
**Description of the problem:**
I'm setting up a practice server and I've noticed that when I(or the practice plugin) //cut - //paste an arena, the blocks (like wool, clay and glass) change colors themselves.

Here is a proof: http://imgur.com/a/vWexz
Another example: http://imgur.com/a/qyrSU

**How to replicate**:
- //cut something with colored blocks
- //paste it
(Sometime it also happens when pasting a .schematic)

I'm using FAWE 17.8.4-1186ca8-791

**Checklist**:
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Can you include a `/fawe debugpaste` ?

**Comment by SpaicyGaming** [comment]
Sure: https://hastebin.com/icovinabuq

**Comment by SpaicyGaming** [comment]
This guy has the same problem: https://www.spigotmc.org/threads/1-7-1-8-propractice-4-mysql-queueing-scoreboard-builduhc-combo-parties-party.169961/page-114#post-2587166

**Comment by boy0001** [comment]
Can you see if disabling clipboard on disk fixes it?
Line `30`, `use-disk` of the FAWE  `config.yml`
