### ISSUE TITLE
Paste and undo error

### ISSUE THREAD

**Issue by Kirrasio** [boy0001/FastAsyncWorldedit#680]
# Bug report

**Debug paste link**:  The debug will not give me a link, instead it gives off this error: https://pastebin.com/MR1as11X

**Description of the problem: 
*As of 1.12.1
Undo does not undo a paste fully, it gets stuck and leaves behind part of the paste. This error happens when doing paste/undo: https://pastebin.com/jKXUJ1zd      https://pastebin.com/MR1as11X
Here's a few pics:
https://pasteboard.co/GEgWWVF.png
https://pasteboard.co/GEhd3kr.png

**How to replicate**: /undo and /paste on the corrupt area seems to give the error again. We are unsure what exactly causes the paste to get stuck in the first place.

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Please update the plugin. The version you are using does not support `1.12.1`.
