### ISSUE TITLE
FAWE Keep Inventory 

### ISSUE THREAD

**Issue by AccioAce** [boy0001/FastAsyncWorldedit#682]
As you said enabled on FAWE config.yml for keep inventory. I have try number 1 and 2 and it doesn't seem to work with the inventory one. 

As you said - https://gyazo.com/189b3700a0eeccdf86d4546c030da5dd

Thank You! :D

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
