### ISSUE TITLE
//br populateschematic (pschem brush) to have option for paste at center

### ISSUE THREAD

**Issue by braceyourself07** [boy0001/FastAsyncWorldedit#684]
Not a bug report, but a feature request.  When using the populate schematic brush, even when setting a radius of 1 the schematic always pastes a few to several blocks away from where it is clicked.  Is it possible for there be a flag or option to paste the center of the schematic at the location clicked?

[![Screenshot from Gyazo](https://gyazo.com/3b059c5dfc7a49f8a4fbb7e2909871c4/raw)](https://gyazo.com/3b059c5dfc7a49f8a4fbb7e2909871c4)

**Comment by boy0001** [comment]
Use the copypaste brush to place a single schematic.

**Comment by braceyourself07** [comment]
What if they want to use multiple schematics?

**Comment by boy0001** [comment]
`//schematic loadall` to load multiple schematics.
