### ISSUE TITLE
Unable to connect to server when FAWE installed.

### ISSUE THREAD

**Issue by Kainzo** [boy0001/FastAsyncWorldedit#685]
# Bug report
**Description of the problem:**

When I have FastAsyncWorldEdit-bukkit-17.04.30-95faf00-681-12.6.11.jar installed, players are unable to connect to the server. They time out immediately in Bungee with a "Disconnected" message. When logging in - the server keeps them at "logging in" 

**How to replicate**:

Simple have FastAsyncWorldEdit-bukkit-17.04.30-95faf00-681-12.6.11.jar - enabled on your server.
**Checklist**:

- [-] I included a `/fawe debugpaste` link
I was unable to do this due to not being able to connect.
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
I can't replicate. Update the plugin (since you are ~100 versions behind) and send me your server log if it still doesn't work.

> I was unable to do this due to not being able to connect.

Console?
