### ISSUE TITLE
undo not working

### ISSUE THREAD

**Issue by LoopTurn** [boy0001/FastAsyncWorldedit#686]
I have a problem where I can't do //undo. It won't work at all. This started happening when I updated the plugin to the latest. I don't know where to get a previous version. There are no console logs it says the player did the command but it will not undo it. It will say "Undo successful" but doesn't undo it.

https://hastebin.com/hodecitagu

**Comment by boy0001** [comment]
Can you try clearing the files at:
`plugins/FastAsyncWorldEdit/history` ?

**Comment by boy0001** [comment]
Issue has been fixed, please update.

Also, I have some recommendations:
 - Update WorldEdit
 - Update spigot to 1.8.8 (FAWE doesn't properly support 1.8.0)
