### ISSUE TITLE
Bug with //paste and use-database

### ISSUE THREAD

**Issue by Panossa** [boy0001/FastAsyncWorldedit#688]
**Debug paste link**:
Debugpaste: https://hastebin.com/uduwiniriv
Error: https://hastebin.com/databehati.md

**Description of the problem:**
Server started, someone copied a small selection and then the error started to appear (at least the "missing database" past) untill the server could not respond.
Thing is: It's the first time this happened and normally FAWE could write in those files. After a restart it worked, too.

**How to replicate**:
Actually no idea. :/

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
I don't think this is something I can fix.

**Comment by dordsor21** [comment]
tried updating SQLite drivers/etc? *wincy face*

**Comment by Panossa** [comment]
Empire, I found the cause of the bug. The hard drive was full. It would be neat if FAWE would stop logging when the first SQL error occurs. Cause data gets corrupted when the hard drive is full but the log keeps getting bigger. I think even our map got corrupted cause of that. (we have backups of course)

**Comment by boy0001** [comment]
If the disk is full, the map will corrupt regardless of FAWE logging. (the sql database only uses a few kb). 

Additionally, it's probably more likely for an error to be thrown which isn't from the disk being full. Stopping all logging at that point would be detrimental, as if some future edit needs to be rolled back, it can't.
