### ISSUE TITLE
Connectivity issues

### ISSUE THREAD

**Issue by iBradyy** [boy0001/FastAsyncWorldedit#689]
I am having connectivity issues using FAWE. When I am using FAWE my ms (ping) will go to 40ms, when FAWE is removed it is steady 15ms. Also, on my other servers (not using FAWE) it's also 15ms.

I am using the Latest version of FAWE and have no idea how to replicate it, I've also asked others about their connectivity issues.

**Comment by boy0001** [comment]
Please follow the issue template and include a `/fawe debugpaste`
