### ISSUE TITLE
Anvil commands screw with world saving.

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#691]
After running an anvil command, any change made using WE/by hand/etc don't save properly (or at all). Some chunks save correctly, some do not. This continues for any changes made until the next time the chunks are (re)loaded, which "resets" the world to just before the anvil command. Running a save-all seems to stop this happening (it can happen for hours). The bukkit/spigot auto-save does not stop it.

![inked2017-08-13_20 29 53_li](https://user-images.githubusercontent.com/10080017/29252839-72c4caf6-8066-11e7-8041-0518c86481b8.jpg)

Replicate:
- stone cylinders placed
- /save-all
- diamond cylinders placed
- //anvil replaceall (something in same world)
- gold cylinders placed
- /save-all
- emerald cylinders placed

relogging (reloading chunks) after each step - gold cylinders got screwed with. Nothing else did (when reloading chunks).

**Comment by dordsor21** [comment]
likely related to #676

**Comment by boy0001** [comment]
Seems paper changes how chunks are saved, which is incompatible with my approach. Need to get the raw dirty field.
