### ISSUE TITLE
Error when pasting CR schematics

### ISSUE THREAD

**Issue by guuslieben** [boy0001/FastAsyncWorldedit#693]
# Bug report
**Debug paste link**: 
https://hastebin.com/gabecobomo

**Console error**
(Occurs in the console when executing schematic paste)
https://pastebin.com/EfRbtRKe

**Description of the problem:**
I'm having some trouble when pasting schematics made with CR, it ends up like the picture attached under "How to replicate". We made sure we are using the correct extrablocks.json file, though the same error persists. I do get a load of debug errors in the console ( https://pastebin.com/EfRbtRKe ). Does anyone know any way to fix this? Multiple people are reporting this bug, so I don't think it's just a server/client issue

FAWE version : FastAsyncWorldEdit-forge110-17.08.04-1186ca8-791-14.1.22 (though I have tried other versions as well)
WE version : : worldedit-forge-mc1.10.2-6.1.4-dist

**How to replicate**:
- Make schematic in a Conquest Reforged world (can be both the same or other worlds, hence the schematic function)
- Paste it in a Conquest Reforged World, and it looks like this http://imgur.com/a/y9CsC

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Can you attach the schematic?

**Comment by boy0001** [comment]
Changing `clipboard.use-disk` to false might be a temporary fix.

**Comment by guuslieben** [comment]
[schematic.schematic.txt](https://github.com/boy0001/FastAsyncWorldedit/files/1227120/schematic.schematic.txt)

I have tried using newer versions as well, though that did not fix it. I'll try the `clipboard.use-disk` fix this evening. 

(Rename schematic.schematic.txt to schematic.schematic, changed that so I could upload it straight to GitHub)

**Comment by boy0001** [comment]
The schematic isn't valid. Are you able to save it again?

**Comment by guuslieben** [comment]
Setting `clipboard.use-disk` to false did not fix it unfortunately, here is the schematic again as requested :
https://cdn.discordapp.com/attachments/346559507100598272/346932608862781440/Bank.schemat
Make sure to be using Conquest Reforged when pasting, as it's built within that modpack

**Comment by boy0001** [comment]
If you are still on the outdated version of the plugin, please update before saving the schematic.
