### ISSUE TITLE
Hash for latest version as well as jar

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#698]
Would it be possible to have the hash (if it's not done so already) be accessible similar to http://empcraft.com/fawe/latest.php?bukkit and http://empcraft.com/fawe/latest.php?favs

**Comment by boy0001** [comment]
added: http://empcraft.com/fawe/latesthash.php?bukkit

**Comment by dordsor21** [comment]
could a hash for FAVS be added as well?
