### ISSUE TITLE
/tool commands are not working on server & "Far tools" Left click not working

### ISSUE THREAD

**Issue by wunder-bread** [boy0001/FastAsyncWorldedit#700]
# Bug report

**Debug paste link**:
https://hastebin.com/ekomaguvoj

**Description of the problem:**
/tool commands are not working on server. (no issue in single player). And both single player and server, Left Click on "Far Tools" is not working.

**How to replicate**:
Join server and run /tool command. (or any other tool command, /tool info . /tool repl ...)
And Left click on /tool lrbuild & /tool farwand does nothing. (you have to be within 3 blocks for it to work) Right click works far still.

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Try resetting your `commands.yml` to fix `//tool`. 

Left click on forge was fixed in WorldEdit only recently, so the build is for 1.12. 
The changes would need to be backported to forge 1.10: https://github.com/sk89q/WorldEdit/commit/f2c5b272ade0a1ac7f74beb19aca6faf1d268d4f

**Comment by Nattehine** [comment]
I can confirm that the "far" tools left click are not working in singleplayer 1.12.2.
WorldEdit v.6.1.8
Forge v.14.23.2.2611

Don't know if it's related or not, but I also use WorldEdit CUI Forge Edition v.2.1.2.

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
