### ISSUE TITLE
Schematic Pasting Error java.lang.NoClassDefFoundError: Could not initialize class com.boydti.fawe.sponge.v1_11.SpongeQueue_1_11

### ISSUE THREAD

**Issue by Jaytractive** [boy0001/FastAsyncWorldedit#701]
**Debug paste link**:
https://hastebin.com/ejekezavax

**Description of the problem:**
Error occurs when pasting schematics
18.08 10:05:30 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class com.boydti.fawe.sponge.v1_11.SpongeQueue_1_11

**How to replicate**:
Sponge 1.12 + plugin. paste schematic

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Try the jar for sponge 1.12:
http://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/FastAsyncWorldEdit-sponge-17.08.18-81ffd52-820-15.2.7.jar

**Comment by Jaytractive** [comment]
My bad. I clickeded on sponge 1.12 on this page https://github.com/boy0001/FastAsyncWorldedit/releases. Thanks :)
