### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by CDAGaming** [boy0001/FastAsyncWorldedit#702]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':forge1710:shadowJar'.
> Could not resolve all dependencies for configuration ':forge1710:runtime'.
   > Could not find :forgeBin:1.7.10-10.13.4.1614-1.7.10.
     Searched in the following locations:
         https://repo1.maven.org/maven2//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.pom
         https://repo1.maven.org/maven2//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.jar
         http://repo.dmulloy2.net/content/groups/public//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.pom
         http://repo.dmulloy2.net/content/groups/public//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.jar
         https://repo.destroystokyo.com/repository/maven-public///forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.pom
         https://repo.destroystokyo.com/repository/maven-public///forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.jar
         https://mvnrepository.com/artifact//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.pom
         https://mvnrepository.com/artifact//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.jar
         http://ci.emc.gs/nexus/content/groups/aikar//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.pom
         http://ci.emc.gs/nexus/content/groups/aikar//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.jar
         http://ci.mengcraft.com:8080/plugin/repository/everything//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.pom
         http://ci.mengcraft.com:8080/plugin/repository/everything//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.jar
         http://ci.athion.net/job/PlotSquared/ws/mvn//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.pom
         http://ci.athion.net/job/PlotSquared/ws/mvn//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.jar
         http://empcraft.com/maven2//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.pom
         http://empcraft.com/maven2//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.jar
         https://hub.spigotmc.org/nexus/content/groups/public//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.pom
         https://hub.spigotmc.org/nexus/content/groups/public//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.jar
         http://maven.sk89q.com/repo//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.pom
         http://maven.sk89q.com/repo//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.jar
         http://nexus.hc.to/content/repositories/pub_releases//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.pom
         http://nexus.hc.to/content/repositories/pub_releases//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.jar
         http://repo.maven.apache.org/maven2//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.pom
         http://repo.maven.apache.org/maven2//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.jar
         http://ci.frostcast.net/plugin/repository/everything//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.pom
         http://ci.frostcast.net/plugin/repository/everything//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.jar
         http://maven.sk89q.com/artifactory/repo//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.pom
         http://maven.sk89q.com/artifactory/repo//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.jar
         http://repo.spongepowered.org/maven//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.pom
         http://repo.spongepowered.org/maven//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.jar
         http://files.minecraftforge.net/maven//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.pom
         http://files.minecraftforge.net/maven//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.jar
         https://libraries.minecraft.net//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.pom
         https://libraries.minecraft.net//forgeBin/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.jar
         file:/C:/Users/tonyg/.gradle/caches/minecraft/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forgeBin-1.7.10-10.13.4.1614-1.7.10.jar
         file:/C:/Users/tonyg/.gradle/caches/minecraft/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forgeBin.jar
     Required by:
         project :forge1710

**Comment by boy0001** [comment]
To build the forge modules you must first use 
> `gradle setupDecompWorkspace`

If you only want to build the bukkit jar, use
> `gradle :bukkit:build`

Or remove everything but `core` and `bukkit` from the `settings.gradle`
