### ISSUE TITLE
metrics problem - URL not found

### ISSUE THREAD

**Issue by Zughy** [boy0001/FastAsyncWorldedit#705]
# Bug report
**Debug paste link**:
https://hastebin.com/wugegibela

**Description of the problem:**
Everytime I start the server, this => https://hastebin.com/cuqizefaxu.vbs appears

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
It's a minor issue with metrics. It shouldn't alter the results, but may result in redundant data being sent to the server.
