### ISSUE TITLE
Patern glitch 

### ISSUE THREAD

**Issue by TheCreeperCow** [boy0001/FastAsyncWorldedit#707]
# Bug report
Block patern bugs out on undo large action
**Debug paste link**:
https://hastebin.com/idivohuhat

**Description of the problem:**
A video says more than words https://www.youtube.com/watch?v=-bueCvykALk

**How to replicate**:
make a large action like a stone platform then undo it

**Checklist**:

- [Y] I included a `/fawe debugpaste` link
- [Y] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Y] I made sure I am using an up-to-date version of FAWE
- [Y] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
You're almost using the latest build, but that wouldn't be a problem.

Was that a //set stone on a large area of vanilla terrain?

**Comment by TheCreeperCow** [comment]
Yes

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
