### ISSUE TITLE
Itemframes and Armorstans doesn’t rotate

### ISSUE THREAD

**Issue by TheoRetisch1** [boy0001/FastAsyncWorldedit#710]
It is not possible to rotate Itemframes and Armorstands, they just stay in their old position and fall down while everything else is rotated.

How to reproduce:
1.	Copy a structure with Itemframes
2.	type //rotate [degress]
3.	//paste

Pictures of the mess: http://imgur.com/a/Vh9Ix
Here is the debug paste link of the testsystem: https://hastebin.com/eyeqihuzud

**Comment by boy0001** [comment]
Could you please attach a schematic of your build for testing?

**Comment by TheoRetisch1** [comment]
Of course: https://ufile.io/08k06

**Comment by TheoRetisch1** [comment]
Awesome! 👍
