### ISSUE TITLE
Undo doesnt contain air

### ISSUE THREAD

**Issue by TheoRetisch1** [boy0001/FastAsyncWorldedit#711]
Undo doesnt contain air
If you undo something only blocks of the last action are undoed but not the air around the object. This issue leads to some unpleasant merges. Of course its only relevant in special situations, its for example very nasty if you play monday-painters. 

I uploaded some pictures in order to clarify the issue: http://imgur.com/a/osH20

Here is the debug paste link of the testsystem: https://hastebin.com/kozoyenife

**Comment by boy0001** [comment]
Undo does contain air. What it doesn't contain is blocks you place by hand.  This isn't a bug, the plugin just doesn't record changes done by hand or other plugins. If you think it should, please create a new ticket.

**Comment by TheoRetisch1** [comment]
Thank you for the reply :). I missed a step sorry :/. Of course one need to cut the second object too and type //undo 2 afterwards to see the result. I also made sure that with default WorldEdit everything works fine.
Here is the updated imagine explanation: http://imgur.com/a/NOFCm
