### ISSUE TITLE
Undo doesnt contain air

### ISSUE THREAD

**Issue by TheoRetisch1** [boy0001/FastAsyncWorldedit#714]
_I "reopend" this issue myself because the last attempt didn´t had a correct description._

//undo doesnt contain air. If you undo something only blocks of the last action are undoed but not the air around the object. Just build two objects on the same spot + tap //set 0, one after the other of course. After that tap //undo 2 --> the two building appear merged togehter, because undo doesnt contan air. The issue doenst appear with "default" worldedit. I uploaded some pictures in order to clarify the issue: http://imgur.com/a/NOFCm
FAWE DebugPaste: https://hastebin.com/kozoyenife

**Comment by boy0001** [comment]
I'll add that if you use `//replace 0`, the same thing will happen with default WorldEdit. Only difference is WorldEdit stores redundant changes (air -> air).
