### ISSUE TITLE
Several Worldedit-actions delete Armorstands for no reason /detection issue

### ISSUE THREAD

**Issue by TheoRetisch1** [boy0001/FastAsyncWorldedit#715]
**Description:** There excist a weird detection issue with armorstands: If you for example replace blocks in a certain position relative to a invincible armorstand, the armorstand gets deleted and undo wont bring it back. One can replace every other block around a armorstand but if you touch the one critical block with fawe the armorstand is gone. Of course I tested the issue using "default" worldedit: I found out that "default" Worldedit cant copy armorstands xD, but it wont delete armorstand. So it´s a FAWE-Detection problem? Since working with Armorstands is nowadays a big deal, this bug makes working with FAWE + armorstands very challenging.

**How to replicate:** Since its challenging to find the blocks that would delete the armorstands I made some images and provide a schematic: http://imgur.com/a/l2jip
armorstand_test: https://ufile.io/k1cjk

**FAWE DebugPaste:** https://hastebin.com/cejebeziza

**Comment by boy0001** [comment]
Please enable `combine-stages` to undo armor stands removed that way.

**Comment by TheoRetisch1** [comment]
Thank you, I appreciate it :)
