### ISSUE TITLE
Catenary brush errors

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#716]
![image](https://user-images.githubusercontent.com/10080017/29868190-ec86e060-8d75-11e7-856a-5a2c3ab3d0b1.png)

not sure if it's me doing something wrong there, but I can't tell what I should be doing differently based on the help given.

**Comment by dordsor21** [comment]
Nevermind, problem is with documentation of it.

Should be lengthFactor=#

**Comment by boy0001** [comment]
The `=1.2` is just the default value for an optional parameter. Any other characters which aren't numeric (or `-`) will be ignored. The command is used like this:
`//br catenary stone 1.2 1.5`

**Comment by dordsor21** [comment]
ah, so that's why the length-factor failed. With the way it's displayed, it seems like you can size= without lengthFactor= also, which I guess is also wrong
