### ISSUE TITLE
//Undo not working properly

### ISSUE THREAD

**Issue by Noiknez** [boy0001/FastAsyncWorldedit#720]
**Debug paste link**:
https://hastebin.com/isekahaquh

**Description of the problem:**
Gif link : http://imgur.com/a/gKBwq (I use //undo & //redo in the gif)
When undo a copied object, it undo only an half of it

**How to replicate**:
1. //Copy something
2. //paste it somewhere
3. //undo (and it will not work for the half of the selection)

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Panossa** [comment]
I don't see when and which half got lost in that tiny gif you pasted here, sorry.

**Comment by boy0001** [comment]
Update FAWE
