### ISSUE TITLE
Setting a language in config is really buggy

### ISSUE THREAD

**Issue by Panossa** [boy0001/FastAsyncWorldedit#721]
**Debug paste link**:
https://hastebin.com/xuxemuvira

**Description of the problem:**
I've set the language option in the FAWE config to "de" which should be german. But the language of the messages were still english. It was one month later (today) that I realized that. Today I deleted the german messages file and got a new one from GitHub. Still nothing. After a restart I noticed the de/message.yml was suddenly completely filled with english lines! 
Then I tried to set the language to russian to test whether all languages are broken. Good news: russian works (I've set language:"ru" in the config and used /fawe reload). Bad news: I can't bring it back to english with /fawe reload. Only when I restart the server completely it is in english again.

**How to replicate**:
I really have no idea.

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Panossa** [comment]
Update: If the language in the config is set to "de" it will just override all german lines in `de/message.yml` to english. ._.

**Comment by boy0001** [comment]
It's because the german translations submitted had formatting errors.
