### ISSUE TITLE
Invisible Block when I use the wand!

### ISSUE THREAD

**Issue by zVqlrio** [boy0001/FastAsyncWorldedit#722]
Debug paste link:
FAWE Debug: https://hastebin.com/amulugaxaf

Description of the problem:
When I do something with the wand, it create a invible block, that you can't overstep. But if I restart the server the block invisible block transform into the previous block. 

How to replicate:
1) //wand
2) //replace 18 0 (and all the commands like: //set... ect)

[X] I included a /fawe debugpaste link
[X] I made sure there aren't duplicates of this report (Use Search)
[X] I made sure I am using an up-to-date version of FAWE
[X] I Made sure the bug/error is not caused by any other plugin

Thanks for reading and for helping me!

Sorry for my english.

**Comment by CDAGaming** [comment]
So the checklist shows properly, please remove the space in the first X

**Comment by zVqlrio** [comment]
In what X?

**Comment by CDAGaming** [comment]
@zVqlrio Like this: "[X] TextHere"

**Comment by zVqlrio** [comment]
Ok, I updated. :D

**Comment by CDAGaming** [comment]
@zVqlrio Remove the quotes, should have said that (Only added quotes bc it wouldnt show you the format)

**Comment by zVqlrio** [comment]
Re-updated! ;D

**Comment by Tareok** [comment]
Pudiste arreglar el problema?

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
