### ISSUE TITLE
FAWE Mob Spawner Particle Effects

### ISSUE THREAD

**Issue by CDAGaming** [boy0001/FastAsyncWorldedit#723]
**Debug paste link**:
https://hastebin.com/ekeyuqomix

**Description of the problem:**
When placing a mob spawner and then trying to replace it with something else (EX: //set air,//replace mob_spawner air) it would remove the spawner but not it's partical effect

**How to replicate**:
1) Place any Mob_spawner down
2) Replace it via FAWE with any block (Preferrably you can set a pos1 and pos2 if you wish)

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
