### ISSUE TITLE
Conquest Reforged blocks: Brushes turn blocks into air.

### ISSUE THREAD

**Issue by Brunokuz** [boy0001/FastAsyncWorldedit#725]
# Bug report

**Debug paste link**: 
 https://pastebin.com/erinecumew

**Description of the problem:**
  When i try to use the brushes like /br sphere, etc. with the conquest blocks, the blocks that i want to change dissapear.

**How to replicate**:
 /br sphere conquest:stone_full_6:6,  //mask 4 (for example) the blocks just turn into air.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
