### ISSUE TITLE
Chunks Glitch

### ISSUE THREAD

**Issue by SpaicyGaming** [boy0001/FastAsyncWorldedit#729]
**Debug paste link**:
https://hastebin.com/eyibevodav

**Description of the problem:**
Every time I create something in the air the chunks below glitches (https://imgur.com/a/rI2rn).

**How to replicate**:
Create something in the air.

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by SpaicyGaming** [comment]
Bump

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
