### ISSUE TITLE
FAWE - setBlocks error

### ISSUE THREAD

**Issue by File14** [boy0001/FastAsyncWorldedit#732]
Hello,

I'm the developer of the plugin called ProPractice. I paste arenas for people to fight in on startup via schematics. After usage, I undo the schematic and set blocks to air in a radius since the UNDO feature only removes the arena, not the blocks inside it that players have been placing.

Version: FastAsyncWorldEdit-bukkit-17.07.22-b07d728-756-13.7.14.jar

I use this method to set blocks to air:
```
			public void run()
			{
				try
				{
					editSession.setBlocks(new CuboidRegion(new Vector(generatedLocation.getBlockX() - 250, 0, generatedLocation.getBlockZ() - 250), new Vector(generatedLocation.getBlockX() + 250, 256, generatedLocation.getBlockZ() + 250)), new BaseBlock(0, 0));
				}
				catch (MaxChangedBlocksException e)
				{
				}

				editSession.flushQueue();
				editSession = null;
			}
		}.runTaskAsynchronously(core);
```

However, for some 1.7 servers they get these errors:

> `[20:32:10 WARN]: Exception in thread "Craft Scheduler Thread - 36"
> 
> [20:32:10 WARN]: org.apache.commons.lang.UnhandledException: Plugin ProPractice v5.6 generated an exception while executing task 22484
> 
> at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
> 
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 
> at java.lang.Thread.run(Thread.java:745)
> 
> Caused by: java.lang.ArrayIndexOutOfBoundsException: 256
> 
> at com.boydti.fawe.bukkit.v1_7.BukkitChunk_1_7.setBlock(BukkitChunk_1_7.java:94)
> 
> at com.boydti.fawe.object.FaweChunk.fillCuboid(FaweChunk.java:223)
> 
> at com.boydti.fawe.object.FaweQueue.setBlocks(FaweQueue.java:226)
> 
> at com.sk89q.worldedit.EditSession.setBlocks(EditSession.java:1654)
> 
> at .???????????????????????.................................................................................................................???IiIIIiiIiiiIIiIIIiIiIIiIi??.iiIiIIiiiiIIIIiiIIIIiiIiIIIIiIiiiiiIiIII?.run(Unknown Source)
> 
> at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
> 
> at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
> 
> ... 3 more`

AND

> `[20:29:17 WARN]: java.lang.ClassCastException: org.spigotmc.FlatMap cannot be cast to net.minecraft.server.v1_7_R4.LongHashMap
> 
> [20:29:17 WARN]: at com.boydti.fawe.bukkit.v1_7.BukkitQueue17$2.run(BukkitQueue17.java:499)
> 
> [20:29:17 WARN]: at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:15)
> 
> [20:29:17 WARN]: at com.boydti.fawe.util.TaskManager$4.run(TaskManager.java:392)
> 
> [20:29:17 WARN]: at com.boydti.fawe.util.TaskManager$4.run(TaskManager.java:388)
> 
> [20:29:17 WARN]: at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:15)
> 
> [20:29:17 WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
> 
> [20:29:17 WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
> 
> [20:29:17 WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:714)
> 
> [20:29:17 WARN]: at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:280)
> 
> [20:29:17 WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:654)
> 
> [20:29:17 WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:559)
> 
> [20:29:17 WARN]: at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)`
>

**Comment by boy0001** [comment]
You are trying to change blocks outside the world (below `y=0`, or above `y=255`)
