### ISSUE TITLE
Problem with flowing Lava

### ISSUE THREAD

**Issue by CodeFoxByChojo** [boy0001/FastAsyncWorldedit#733]
# Bug report
**Debug paste link**: https://hastebin.com/edacefazeh

**Description of the problem:**
If you copy or do something with flowing lava (block id 10) fawe or world edit dont notice it.

Look at this picture: https://puu.sh/xvHLS/78af660804.png

If you type //set 10 it sets 11. -> https://puu.sh/xvHMP/771549e808.png

If you //replace 10 1 it finds 0 blocks with id 10, but they must be there. -> https://puu.sh/xvHPd/71b4212dc4.png

also if you copy a structure with id 10 all blocks with id 10 are id 11 after //paste.
before -> https://puu.sh/xvHTN/3b474fe750.png
after -> https://puu.sh/xvHUp/5a53af5e31.png

When you undo something where flowing lava is affected, the flowing lava is normal lava and not flowing anymore.

Tested it on other servers which use fawe. They have the same bug.

I have a problem with replace flowing water. Same as with lava.

**How to replicate**:
just look at the pictures. They are a step by step instruction.

**Comment by boy0001** [comment]
Minecraft uses `id:11` for flowing and non flowing lava. The data is being lost, but the id is not being changed, so your steps to reproduce are incorrect. 

Issue has been fixed, please update.
