### ISSUE TITLE
//br flatten weirdness

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#735]
`//br flatten 30 null 0 1.5`

![2017-09-11_17 21 54](https://user-images.githubusercontent.com/10080017/30285350-bb3c6760-9715-11e7-92da-615b29b4e442.png)

![2017-09-11_17 22 21](https://user-images.githubusercontent.com/10080017/30285369-ccca3688-9715-11e7-9d23-bbd869b211c0.png)
![2017-09-11_17 22 24](https://user-images.githubusercontent.com/10080017/30285368-ccbbd7e6-9715-11e7-8a75-c9d689049df2.png)

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
