### ISSUE TITLE
Server - Sponge 1.12.1 - FAWE not working at all

### ISSUE THREAD

**Issue by Krosta8** [boy0001/FastAsyncWorldedit#739]
Hello guys,
I tried to use forge version and sponge version, both with the same problem. Nothing working and interact with blocks caused error.
Here is an example of error, when I click on block:
https://pastebin.com/Hp1ggbzQ

Here is an example of error, when I wrote //wand:
https://pastebin.com/s50qTrEd

Sponge version: spongeforge-1.12.1-2479-7.0.0-BETA-2624
FAWE version: FastAsyncWorldEdit-sponge-17.09.13-671dc29-893-16.5.11
Forge version: forge-1.12.1-14.22.1.2479

**Comment by DjSpecialK** [comment]
I also get the same issues in console and here's what it tells me in game when i try to //set [any item]
java.lang.NoClassDefFoundError: Could not initialize class com.boydti.fawe.sponge.v1_11,SpongeQueue_1_11

spongeforge-1.12.1-2444-7.0.0-BETA-2623
FastAsyncWorldEdit-sponge111-17.09.19-0b9def2-903-16.6.0
