### ISSUE TITLE
Jenkins Bug - Latest jar compiling without fixes?

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#74]
@boy0001 Is something up with the jenkins dev builds?
http://ci.athion.net/job/FastAsyncWorldEdit/71/

Grabbing ```FastAsyncWorldEdit-bukkit.jar``` and testing the latest commit fixes, none of the fixes seem to be working. 

Grabbing ```FastAsyncWorldEdit-bukkit19.jar```, the fixes seem to be present.

**Comment by boy0001** [comment]
Fixed
