### ISSUE TITLE
Question: difference between permissions ?

### ISSUE THREAD

**Issue by BloodEko** [boy0001/FastAsyncWorldedit#740]
Hello!
I found these 2 permissions:

fawe.worldguard
fawe.worldguard.member

It's not documented, whats the difference between them, and what they actually do. 
Does it anyone know ?

**Comment by boy0001** [comment]
`fawe.worldguard` - You can worldedit if you are an owner of the region
`fawe.worldguard.` - You can worldedit if you are a member of the region
