### ISSUE TITLE
Please add more configurable messages.

### ISSUE THREAD

**Issue by Panossa** [boy0001/FastAsyncWorldedit#742]
**Description:**
Hey, Empire!
I'd like to be able to get rid of all those pink messages pasted in chat by WorldEdit. Would you please add those to the message.yml? I recently edited every line so that it starts with &7, but some messages are still pink. Example: 
![snap_2017 09 17_18h10m21s_001_](https://user-images.githubusercontent.com/23323875/30522640-d6d946e2-9bd3-11e7-8e26-ff15a4df667e.png)

~Panossa

**Comment by boy0001** [comment]
I've added translations to the selection commands. Please let me know about specific messages which still need to be covered.
