### ISSUE TITLE
A large (1000x255x1000) //set 0 did not remove everything

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#744]
![2017-09-18_11 05 46](https://user-images.githubusercontent.com/10080017/30537399-5bf817b2-9c61-11e7-9e23-925573fcc662.png)
![2017-09-18_11 05 50](https://user-images.githubusercontent.com/10080017/30537400-5c10c410-9c61-11e7-84f3-e938ea6a026f.png)

**Comment by dordsor21** [comment]
Perhaps related to IntellectualSites/PlotSquared#1681

**Comment by braceyourself07** [comment]
Did this just start happening?  Also, after talking with Emp on discord, we have it isolated down to a chunk that does not want to load and selecting the area and //regen or server restart fixes it (essentially forcing the chunk to load or reload).  Your problem area seems rather large compared to mine where it was just a few chunks.

**Comment by dordsor21** [comment]
It seems to specifically happen in random chunks that are not contained within own plots that are reloaded at some point I think. Thus errors in the saving of chunks/etc.

**Comment by braceyourself07** [comment]
Do you have `auto-trim: true` in settings.yml?

**Comment by dordsor21** [comment]
Yes, that'll be the buggy it I s'pose then

**Comment by boy0001** [comment]
Did disabling `auto-trim` fix it?

**Comment by dordsor21** [comment]
Yes, PlotSquared issue then.
