### ISSUE TITLE
[Feature Request] FastAsyncRandomLightUpdates

### ISSUE THREAD

**Issue by Miclebrick** [boy0001/FastAsyncWorldedit#746]
It would be very cool if there were something similar to the built in Spigot random lighting updates, except via FAWE and the async thing

**Comment by dordsor21** [comment]
The spigot thing is already automatic, and is already async, though?

**Comment by Miclebrick** [comment]
The spigot thing freezes my server and isn't async ❌

**Comment by Miclebrick** [comment]
The //fixlighting thing but random and constantly doing it would be cool, basically

**Comment by dordsor21** [comment]
the fact it's random means it's almost async, and I'd imagine it's likely that it only executes with a TPS above a certain threshold. If it locks up your server, you either ought to report it as a bug to spigot, or have some seriously under-powered server.

**Comment by Miclebrick** [comment]
I have a very good server in fact thank you very much :P I put it on the spigot forums and got no response though

**Comment by dordsor21** [comment]
There you go, it's a spigot bug then ;)

Rather than reporting to forums it's be much better worth your while to post on their bug tracker btw
