### ISSUE TITLE
Survival World edit

### ISSUE THREAD

**Issue by Plutoren** [boy0001/FastAsyncWorldedit#747]
I want to give world edit to my players
I want to require the blocks be in the player's inventory
Setting FAWE to "survival" mode for inventory mode does not seem to work
When I run a command such as "//set wool" with survival mode enabled it takes all my wool
and does nothing.
This is clearly not desired and I would appreciated a fix.
The same issue occurs on "creative" mode

The config option:
inventory-mode: 2

Example in game (gif):
https://gyazo.com/7ec5d885ed691556368f12e2b62964d4

Relevant plugins installed:
grief prevention, (standing in my claim, having the gp perm) 
world edit 

I am pretty sure I have all permissions setup correctly when testing

Server was version 1.12.1 during my testing, (will be 1.12.2 soon)

Skype: plutoren1
Discord: Plutoren#5971
Server discord invite: https://discord.gg/zyGppCW

I would be happy to test this on a production server if it can be fixed

**Comment by Bakalexis** [comment]
Are you using some Plot systems in your server, if not it might be GriefPrevention which is not correctly configurated. Have you tried to disable fawe for this thing ? I don't think the problem is caused by fawe, so I can't help you

**Comment by Plutoren** [comment]
Yes I know it is fawe because using the permission fawe.bypass I am suddenly able to use everything normally, the only issue with fawe is the survival inventory, regardless of plugins or permissions it appears this feature does not work as intended 

~Sully G.

**Comment by Bakalexis** [comment]
Can you post your config.yml ?

**Comment by Plutoren** [comment]
Sorry for late reply this went to my spam for some reason this is the config I don't think I changed anything besides inventory mode and max changes thanks for looking hastebin 
  
|  
|   |  
hastebin
   |  |

  |

 
 

    On Tuesday, September 19, 2017 9:14 AM, Bakalexis <notifications@github.com> wrote:
 

 Can you post your config.yml ?—
