### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by NycuRO** [boy0001/FastAsyncWorldedit#748]
Hello.

Anyone can explain me please how can i use /schematic remap?

I want port my PC map to MCPE, but when i write /schematic remap, anything.

When i write /schematic remap "name" PC MCPE, say that:

![image](https://user-images.githubusercontent.com/13573011/30781420-501cbd06-a127-11e7-9a33-125aa754d821.png)

Anyone can help me, please? 👍 

I appreciate effort for help.

@boy0001

**Comment by boy0001** [comment]
To remap an entire map, use `//anvil remap <folder>`.
To remap a loaded schematic use `//schematic remap`.

**Comment by NycuRO** [comment]
Yes, but i don't receive any message when i type:

//schematic load NAME
//schematic remap. @boy0001

**Comment by NycuRO** [comment]
@boy0001 So..?

**Comment by boy0001** [comment]
The command still works, it just doesn't send a message.

**Comment by NycuRO** [comment]
Can you add one message, @boy0001 ?

And thanks for help.

**Comment by NycuRO** [comment]
And please update to 1.2.0 blocks :)

And blockface 👍

**Comment by NycuRO** [comment]
![image](https://user-images.githubusercontent.com/13573011/30782106-0a642bca-a134-11e7-8647-49b0aa7651f9.png)


@boy0001 Remap not works correctly. All blocks get "Update Block" when i paste schematic on map (on pc) and enter on mcpe.

**Comment by boy0001** [comment]
Steps:
 - Copy schematic: `//copy` on PC
 - Load schematic on Nukkit
 - Use `//schematic remap`
 - Paste the schematic.

**Comment by NycuRO** [comment]
Ok thanks. <3
