### ISSUE TITLE
Tips are kinda broken in the current version

### ISSUE THREAD

**Issue by Panossa** [boy0001/FastAsyncWorldedit#749]
**Debug paste link**:
https://hastebin.com/dodekokixu

**Description of the problem:**
I think the state of the tips settings are kinda frozen. "/tips" doesn't affect anything.
Here's me pasting 4 times /tips in a row (which should enable/disable the tips): 
![snap_2017 09 24_15h40m19s_001_](https://user-images.githubusercontent.com/23323875/30783213-5532860a-a13f-11e7-9049-7863c4aec766.png)
As you can see, the status doesn't change. For me, tips are OFF the whole time. I use //paste, then /tips, then //paste and no tips are displayed. The whole thing is the other way round for a few (or all) of our team members. They have tips no matter how often they type "/tips" in chat.

**How to replicate**:
Use latest version, type "/tips" a few times. And try //paste-ing a few things.

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin **(**maybe Paper? But it'd be strange**)**

**Comment by FurryKitten** [comment]
Have the same issue.

**Comment by N0tMyFaultOG** [comment]
Update fawe
If this is an issue still, comment below.
