### ISSUE TITLE
Request - Attach build number to version output when compiling on jenkins.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#75]
Similar to many other plugins such as worldedit, mcmmo, logblock, etc. So you can always check that you have the correct 'latest' version with appropriate fixes. 

To take it even further, you can have the jenkins build number and the commit string of the exact last commit it was compiled against. Similar to worldedit and PaperSpigot.

**Comment by boy0001** [comment]
Fixed
