### ISSUE TITLE
AT LEAST //undo isn't logged by CoreProtect+BlocksHub.

### ISSUE THREAD

**Issue by Panossa** [boy0001/FastAsyncWorldedit#752]
**Debug paste link**:
https://hastebin.com/opegecoruv

**Description of the problem:**
I just installed the newest versions of BlocksHub and CoreProtect, did the whole setup and ran into a problem. If I break or place blocks with my hand it gets logged. If I do //set 0 it gets logged, too.  Brushes seem to be logged, too. I think every block placement is. But when I do /u or //undo CoreProtect doesn't notice the change. It's a pretty heavy bug as it makes CoreProtect nearly unusable on big servers.

**How to replicate**:
Install newest FAWE, BlocksHub, CoreProtect, "//set 0" and then "//undo".
Here's an example where I used //copy, //paste, then broke one block and //undid the everything else. As you can see the manual block break got logged. 
![snap_2017 09 29_15h45m08s_004_](https://user-images.githubusercontent.com/23323875/31018708-4cdd5074-a52d-11e7-9aa1-b31561d8529d.png)

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin (Blockshub?)

**Comment by N0tMyFaultOG** [comment]
Update the plugins
If the issue persists still, reply to the ticket
