### ISSUE TITLE
[Reporting Bug] Falling sand causing skipping ids in console

### ISSUE THREAD

**Issue by DJDan21** [boy0001/FastAsyncWorldedit#753]
# Bug report

**Debug paste link**: https://hastebin.com/hewokefosa

**Description of the problem:**

I made a tower block of sand then broke a lower part of the sand. I am using the latest version of the plugin of fawe.  I am sure how to fix this issue https://gyazo.com/76126150e2161c5eb98129e68792c030 

**How to replicate**:

Make a sand that is 200 blocks high, then break a block and watch sand take ages to fall down.

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Update fawe
If this is an issue still, comment below.
