### ISSUE TITLE
FAWE New Brush Suggestion

### ISSUE THREAD

**Issue by teamAngelic** [boy0001/FastAsyncWorldedit#756]
# **NEW BRUSH SUGGESTION**

**Information about the brush:**
This would be a simple arch brush, by selecting position 1 & position 2 to two different coordinates it would create an arc based on the command input.

## HOW WILL THE BRUSH WORK
**Brush Commands & Information:**
The brush will have a simple command, _//brush arch [material] [height]_
Let's say we are picking stone material [ID:1] and a height of 1. It would make this arch:
![image](https://user-images.githubusercontent.com/30430512/31088523-e2519d50-a798-11e7-9603-b87bfb08724b.png)

**Flags:**
And of course we will have flags for this, what I believe would make the brush user-friendly is adding the following.

> [-d] This is the density flag, Player's job is to tell the plugin what would they like the thickness of the brush to be, let's say 2-3 and it would make a thick arch with a density of 2-3 blocks.
> [-r] This is the random flag, this does not make an organized arch, this makes the arch shape randomized if you're making terrain or for your personal needs.

## **NOTES**
**Additional information:**
This plugin will be used for terraforming, possible structural needs or when making organics, whether there are possible ways to do this or not, I believe this would simplify builder needs. Any opinions and suggestions are appreciated, I am willing to update this anytime soon.

**Comment by Panossa** [comment]
You wrote //pos1 and //pos2 as if you're requesting not a brush but a normal command you can type after setting the first and second selection point. Maybe you need to specify that "pos1" and "pos2" are clicks you make with your mouse. OR you really want just a command and not a brush. Cause I don't see a point in this being a brush when the whole purpose of it is to activate a command which operates on two already set points.

**Comment by teamAngelic** [comment]
@Panossa Thank you for your input. But this brush would be similar to catenary brush, it works the same as pos1 and pos2.
