### ISSUE TITLE
Weird Message in Console

### ISSUE THREAD

**Issue by Techno3600** [boy0001/FastAsyncWorldedit#757]
**Description of the problem:**
Some weird error appears in the console whenever I do a command.

Here is the code
`com.boydti.fawe.logging.rollback.RollbackOptimizedHistory@7df63942
02.10 22:31:56 [Server] INFO Changeset com.boydti.fawe.logging.rollback.RollbackOptimizedHistory@a1e8360
02.10 22:32:10 [Server] INFO Changeset com.boydti.fawe.logging.rollback.RollbackOptimizedHistory@248412b5
02.10 22:32:25 [Server] INFO Changeset com.boydti.fawe.logging.rollback.RollbackOptimizedHistory@4880049c
02.10 22:33:48 [Server] INFO Changeset com.boydti.fawe.logging.rollback.RollbackOptimizedHistory@234fc6ba
02.10 22:33:50 [Server] INFO Changeset com.boydti.fawe.logging.rollback.RollbackOptimizedHistory@480ef6d5
02.10 22:33:54 [Server] INFO Changeset com.boydti.fawe.logging.rollback.RollbackOptimizedHistory@6272cc81`

**To replicate do any World Edit Command.**
**Checklist**:

- [] I included a `/fawe debugpaste` link
**https://hastebin.com/agekecaruc**

**Comment by N0tMyFaultOG** [comment]
Update fawe
If this is an issue still, comment below.
