### ISSUE TITLE
Some Piston & Dispenser Issues w/ FAWE Anvil to LevelDB Converter

### ISSUE THREAD

**Issue by TheAntVenom** [boy0001/FastAsyncWorldedit#758]
This is a bug report specific to the FAWE Anvil to LevelDB Editor.

After converting an Anvil map, I observed that all horizontal, unextended pistons face 180 degrees away from where they're supposed to. This issue does not occur for pistons facing up or down. This may occur with horizontal extended pistons, but I'm not sure.

Regular, Extended, upwards facing pistons have the "update" block on top of them after conversion.

After converting a map containing dispensers full of TNT, I could not right click on the dispensers to have their interface open, nor did anything happen when they were activated by redstone. This may not occur with vertical dispensers, but I didn't test that.

Thanks,
AntVenom

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
