### ISSUE TITLE
There is no download for forge(and sponge) build

### ISSUE THREAD

**Issue by Cavesnakes** [boy0001/FastAsyncWorldedit#759]
after build 908 (17.09.24), there is no download for forge(and sponge) build 

maybe this project for forge is discontinued or something?

is it ok to use forge build 908 for my spongeforge 1.10.2 (API 5) server?

**Comment by dordsor21** [comment]
https://github.com/boy0001/FastAsyncWorldedit/commit/f0915b558b8433140e043449318771df052d3e39 - forge modules were stopping the entire project from building. Using build 908 is absolutely fine.

**Comment by Cavesnakes** [comment]
why forge build is excluded? any reason for that?

no offence, i'm just curious :P
