### ISSUE TITLE
Entities do not remove from paste area when typing //undo. They do not re-place when typing //redo.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#76]
FAWE dev 71 (bukkit19 jar version)
WorldEdit 6.1.1 dev 3487
ProtocolLib 4.0 dev 273
PaperSpigot 712.

Copied a glass box that has an armor stand and item frames to a place a little further away. Then typed //undo to remove the paste. The entities did not remove themselves.
![link](http://i.imgur.com/pwdyjvD.png)

Instead, they fell to the ground after a few seconds. (Assuming tick time checked for block hanging, couldn't find any block, then it fell.)

![link2](http://i.imgur.com/ckLAgKw.png)

Then tried to //redo. It did not replace the entities.
![link3](http://i.imgur.com/zpI5dhf.png)

**Comment by mibby** [comment]
Also mob entities do not get removed when typing //undo.

**Comment by boy0001** [comment]
Should be fixed.
