### ISSUE TITLE
Modded IDs issue

### ISSUE THREAD

**Issue by Eufranio** [boy0001/FastAsyncWorldedit#760]
**Debug paste link**:
https://hastebin.com/duxomerixi

**Description of the problem:**
When FAWE sets ANY modded block (let's say I select an area which contains modded blocks and use //set 0), it will set the vanilla blocks correctly, but the modded ones will turn into OTHER modded ones. Like, everything vanilla turns into air, but modded blocks turn into another random modded block.

**How to replicate**:
Start a server with Thermos and 1 or more mod and FAWE-Forge & WorldEdit-Bukkit. Place down modded blocks, select the area that they're in and execute any world interaction (//set, //regen, //replace...). 

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by evernife** [comment]
Can confirm that!

I set my walls of chisel:stones into minecraft:pumpkins

It was a bit sad...

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket

**Comment by evernife** [comment]
Seems to be working good now

![image](https://user-images.githubusercontent.com/11357801/46751422-e38fa900-cc90-11e8-8ca7-43ac27927f14.png)
