### ISSUE TITLE
Stairs reset orientation when replacing.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#761]
FAWE dev 927
WorldEdit dev 3709
Spigot 1.12.2

When you replace stairs with ```/replace``` or ```/replacenear```, the orientation resets to west direction. It doesn't do a simple swap. Such as replacing purpur stairs used in an entire build with nether stairs of various orientations.

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket

**Comment by ashton727** [comment]
Same issue

**Comment by NotMyFault** [comment]
Don't comment on 3 year old issues. Move to https://github.com/IntellectualSites/FastAsyncWorldEdit and raise a new issue. This repository is no longer maintained, like outlined in a variety of spots.
