### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by zedrox464** [boy0001/FastAsyncWorldedit#764]
Hi when I was using your converter It crashed when I do large files. Try to fix it. Nice job BTW.  I will have links to all the world downloads. I hope you can fix it and convert these worlds. Please upload the converted files to mediafire and send the links to zedrox464@gmail.com. Thank you.
https://www.dropbox.com/s/wvhba685mjnezg2/Jansey%27s%20World-40.zip?dl=0
http://hermitcraft.com/maps/HermitCraftVanilla-S4.zip
http://hermitcraft.com/maps/HermitCraftVanilla-S3.zip
http://hermitcraft.com/maps/HermitCraftVanilla-S2.zip
http://hermitcraft.com/maps/HermitCraftVanilla-S1.zip
https://www.youtube.com/redirect?q=https%3A%2F%2Fod.lk%2Fd%2FOTJfMzkwODk2Ml8%2FKingdoms%2520-%2520Ep%2520150.zip&redir_token=W574ANdD9SVWX-6OPOBaiYBRust8MTUwNzY1NjI0MEAxNTA3NTY5ODQw&v=jbqurM0C_dI&event=video_description

**Comment by CDAGaming** [comment]
I can convert these worlds later, i have some spare time to assist (After i see if https://github.com/boy0001/FastAsyncWorldedit/commit/d93f9f05531919072a281285a65d6fa847199125 fixed entities somewhat on my world)

**Comment by N0tMyFaultOG** [comment]
If the issue persists still, reply to the ticket
