### ISSUE TITLE
Same seed but no builds

### ISSUE THREAD

**Issue by DylanSpeiser** [boy0001/FastAsyncWorldedit#766]
Okay so my Main World on Java edition, I was using for around a year and I tried to convert it to Bedrock, and the converted world had the same exact terrain (I'm guessing it was the same seed) but all of my builds did not convert. The converter seems to think everything is fine, but I have no idea how to fix this. Please help, thank you so much.

**Comment by N0tMyFaultOG** [comment]
If the issue persists still, reply to the ticket
