### ISSUE TITLE
Pasting rotated structures produces errors

### ISSUE THREAD

**Issue by Panossa** [boy0001/FastAsyncWorldedit#767]
**Debug paste link**:
https://hastebin.com/mometelani

**Description of the problem:**
One of our builders encountered an error with FAWE where this is pasted in the chat whenever he pastes a rotated structure:
[Here](https://cdn.discordapp.com/attachments/120577453797277696/368352841913597954/javaw_2017-10-13_13-01-37.png)

Error in console:
[Here](https://hastebin.com/icaqohogak.vbs)

**How to replicate**:
I think //copy, //rotate 90, //paste should do the trick. 

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Update fawe
If this is an issue still, comment below.
