### ISSUE TITLE
FAWE not working on the latest version of Sponge

### ISSUE THREAD

**Issue by gaeqs** [boy0001/FastAsyncWorldedit#768]
# Bug report
**Debug paste link**:
(Cannot paste. It gives an error)

**Description of the problem:**
FAWE doesn't work on the latest version of Sponge 1.12.2. It loads witout errors, but them appear when you use any function.

Errors:
http://prntscr.com/gx1912

**How to replicate**:
Just use any command, like //wand

**Checklist**:

- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Update fawe
If this is an issue still, comment below.
