### ISSUE TITLE
Error with ItemFrames and AffineRotations

### ISSUE THREAD

**Issue by Rhonim** [boy0001/FastAsyncWorldedit#769]
# Bug report

**Debug paste link**:

Unable to do this due to a handshake_failure. Using latest FAWE. (https://pastebin.com/ub8wzbz0)
**Description of the problem:**

Item frames aren't being pasted and throw an error when attempting to use 
```
schem.paste(FaweAPI.getWorld(loc.getWorld().getName()),
                BukkitUtil.toVector(loc),
                false,
                false,
                new AffineTransform().rotateY(90);
```
**Produces the following error**:
https://pastebin.com/t5L6W2bd

**How to replicate**:

Create a schematic on with item frames contained in it, then attempt to paste it using the code above
**Checklist**:

- [ ] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
