### ISSUE TITLE
Paintings copied in a region selection are offset on paste.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#77]
FAWE dev 71 (bukkit19 jar version)
WorldEdit 6.1.1 dev 3487
ProtocolLib 4.0 dev 273
PaperSpigot 712.

E.g.

Saved region.
![link](http://i.imgur.com/Qz6ArYr.png)

Pasted.
![link2](http://i.imgur.com/aaXSH1K.png)

**Comment by boy0001** [comment]
Normal WorldEdit bug. May not be easily fixable on my end.
