### ISSUE TITLE
ClassCastException - fixLightning

### ISSUE THREAD

**Issue by Eufranio** [boy0001/FastAsyncWorldedit#773]
**Debug paste link**:
https://hastebin.com/yikupemuxo

**Description of the problem:**
Running //fixlightning throws an error on the console and won't work at all. Stacktrace: https://hastebin.com/libosaxuzo.rb

**How to replicate**:
Just use //fixlightning on a Thermos modded server and FAWE.

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Update fawe & favs
If this is an issue still, comment below.
