### ISSUE TITLE
NotABlockException - The item with the ID 271 is not a block

### ISSUE THREAD

**Issue by Eufranio** [boy0001/FastAsyncWorldedit#774]
**Debug paste link**:
https://hastebin.com/yikupemuxo

**Description of the problem:**
Using //br throws an error in the console (when holding an non-placeable item). Stacktrace: https://hastebin.com/titulevaba.md

**How to replicate**:
Use //br and try to build something on a Thermos modded server.

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Update fawe & favs
If this is an issue still, comment below.
