### ISSUE TITLE
Block placement bug in schematics

### ISSUE THREAD

**Issue by mrsglo** [boy0001/FastAsyncWorldedit#777]
# Bug report

**Debug paste link**:
https://hastebin.com/wejoqeyesi

**Description of the problem:**
Block duplication client side for 1.9+ clients when placing block in pasted schematic.

**How to replicate**:
Create a 1.8.8 server with ViaVersion and use 1.9-1.12 client (not 1.8).
Paste a schematic.
Place a block in the pasted schematic, sometimes the block is duplicated and it creates a cube with the block. (Works best with water, 70% of the time).

Video: https://youtu.be/pfhQHoTRK7A

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Update fawe & favs
If this is an issue still, comment below.
