### ISSUE TITLE
Anvil and LevelDB Converter

### ISSUE THREAD

**Issue by ShapescapeBuildteam** [boy0001/FastAsyncWorldedit#779]
Downloading levedb.jar and mappings (~4MB), please wait...
Starting converter...
Copying level data
Scanning worlds...
 - dimension 0 (region)
 - including portals
Writing converted data...
Collecting threads
java.lang.OutOfMemoryError: Java heap space
	at org.iq80.leveldb.util.Slice.<init>(Slice.java:53)
	at org.iq80.leveldb.util.Slices.allocate(Slices.java:89)
	at org.iq80.leveldb.impl.DbImpl.writeWriteBatch(DbImpl.java:1335)
	at org.iq80.leveldb.impl.DbImpl.writeInternal(DbImpl.java:701)
	at org.iq80.leveldb.impl.DbImpl.put(DbImpl.java:652)
	at org.iq80.leveldb.impl.DbImpl.put(DbImpl.java:645)
	at com.boydti.fawe.nukkit.core.converter.MCAFile2LevelDB$FileCache.close(MCAFile2LevelDB.java:580)
	at com.boydti.fawe.nukkit.core.converter.MCAFile2LevelDB.close(MCAFile2LevelDB.java:327)
	at com.boydti.fawe.nukkit.core.converter.MCAFile2LevelDB.accept(MCAFile2LevelDB.java:294)
	at com.boydti.fawe.nukkit.core.converter.MCAFile2LevelDB.accept(MCAFile2LevelDB.java:70)
	at com.boydti.fawe.nukkit.core.converter.ConverterFrame$7.run(ConverterFrame.java:459)
	at java.lang.Thread.run(Unknown Source)
java.lang.OutOfMemoryError: Java heap space
	at org.iq80.leveldb.util.Slice.<init>(Slice.java:53)
	at org.iq80.leveldb.util.Slices.allocate(Slices.java:89)
	at org.iq80.leveldb.impl.DbImpl.writeWriteBatch(DbImpl.java:1335)
	at org.iq80.leveldb.impl.DbImpl.writeInternal(DbImpl.java:701)
	at org.iq80.leveldb.impl.DbImpl.put(DbImpl.java:652)
	at org.iq80.leveldb.impl.DbImpl.put(DbImpl.java:645)
	at com.boydti.fawe.nukkit.core.converter.MCAFile2LevelDB$FileCache.close(MCAFile2LevelDB.java:580)
	at com.boydti.fawe.nukkit.core.converter.MCAFile2LevelDB.close(MCAFile2LevelDB.java:327)
	at com.boydti.fawe.nukkit.core.converter.MCAFile2LevelDB.accept(MCAFile2LevelDB.java:294)
	at com.boydti.fawe.nukkit.core.converter.MCAFile2LevelDB.accept(MCAFile2LevelDB.java:70)
	at com.boydti.fawe.nukkit.core.converter.ConverterFrame$7.run(ConverterFrame.java:459)
	at java.lang.Thread.run(Unknown Source)
(FAWE) Anvil and LevelDB converter
(FAWE) Conversion complete!
 - The world save is still being compacted, but you can close the program anytime
 - There will be another prompt when this finishes

What is not converted?
 - Inventory is not copied
 - Some block nbt may not copy
 - Any custom generator settings may not work
 - May not match up with new terrain
Starting compaction
(FAWE) Done compacting!
(FAWE) Compaction complete!
(FAWE) --------------------------------------------------------------------------------------------
(FAWE) Thread: pool-3-thread-1 | Id: 33 | Alive: true
(FAWE) sun.misc.Unsafe.park(Native Method)
(FAWE) java.util.concurrent.locks.LockSupport.park(Unknown Source)
(FAWE) java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
(FAWE) java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
(FAWE) java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
(FAWE) java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
(FAWE) java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
(FAWE) java.lang.Thread.run(Unknown Source)
(FAWE) --------------------------------------------------------------------------------------------
(FAWE) Thread: Thread-7 | Id: 29 | Alive: true
(FAWE) --------------------------------------------------------------------------------------------
(FAWE) Thread: AWT-Windows | Id: 10 | Alive: true
(FAWE) sun.awt.windows.WToolkit.eventLoop(Native Method)
(FAWE) sun.awt.windows.WToolkit.run(Unknown Source)
(FAWE) java.lang.Thread.run(Unknown Source)
(FAWE) --------------------------------------------------------------------------------------------
(FAWE) Thread: leveldb-compaction-0 | Id: 44 | Alive: true
(FAWE) sun.misc.Unsafe.park(Native Method)
(FAWE) java.util.concurrent.locks.LockSupport.park(Unknown Source)
(FAWE) java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
(FAWE) java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
(FAWE) java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
(FAWE) java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
(FAWE) java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
(FAWE) java.lang.Thread.run(Unknown Source)
(FAWE) --------------------------------------------------------------------------------------------
(FAWE) Thread: DestroyJavaVM | Id: 18 | Alive: true
(FAWE) --------------------------------------------------------------------------------------------
(FAWE) Thread: D3D Screen Updater | Id: 15 | Alive: true
(FAWE) java.lang.Object.wait(Native Method)
(FAWE) sun.java2d.d3d.D3DScreenUpdateManager.run(Unknown Source)
(FAWE) java.lang.Thread.run(Unknown Source)
(FAWE) --------------------------------------------------------------------------------------------
(FAWE) Thread: TimerQueue | Id: 46 | Alive: true
(FAWE) sun.misc.Unsafe.park(Native Method)
(FAWE) java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
(FAWE) java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
(FAWE) java.util.concurrent.DelayQueue.take(Unknown Source)
(FAWE) javax.swing.TimerQueue.run(Unknown Source)
(FAWE) java.lang.Thread.run(Unknown Source)
(FAWE) --------------------------------------------------------------------------------------------
(FAWE) Thread: AWT-EventQueue-0 | Id: 12 | Alive: true
(FAWE) java.lang.Thread.dumpThreads(Native Method)
(FAWE) java.lang.Thread.getAllStackTraces(Unknown Source)
(FAWE) com.boydti.fawe.nukkit.core.converter.ConverterFrame$6.actionPerformed(ConverterFrame.java:272)
(FAWE) javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
(FAWE) javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
(FAWE) javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
(FAWE) javax.swing.DefaultButtonModel.setPressed(Unknown Source)
(FAWE) javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
(FAWE) java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
(FAWE) java.awt.Component.processMouseEvent(Unknown Source)
(FAWE) javax.swing.JComponent.processMouseEvent(Unknown Source)
(FAWE) java.awt.Component.processEvent(Unknown Source)
(FAWE) java.awt.Container.processEvent(Unknown Source)
(FAWE) java.awt.Component.dispatchEventImpl(Unknown Source)
(FAWE) java.awt.Container.dispatchEventImpl(Unknown Source)
(FAWE) java.awt.Component.dispatchEvent(Unknown Source)
(FAWE) java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
(FAWE) java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
(FAWE) java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
(FAWE) java.awt.Container.dispatchEventImpl(Unknown Source)
(FAWE) java.awt.Window.dispatchEventImpl(Unknown Source)
(FAWE) java.awt.Component.dispatchEvent(Unknown Source)
(FAWE) java.awt.EventQueue.dispatchEventImpl(Unknown Source)
(FAWE) java.awt.EventQueue.access$500(Unknown Source)
(FAWE) java.awt.EventQueue$3.run(Unknown Source)
(FAWE) java.awt.EventQueue$3.run(Unknown Source)
(FAWE) java.security.AccessController.doPrivileged(Native Method)
(FAWE) java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
(FAWE) java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
(FAWE) java.awt.EventQueue$4.run(Unknown Source)
(FAWE) java.awt.EventQueue$4.run(Unknown Source)
(FAWE) java.security.AccessController.doPrivileged(Native Method)
(FAWE) java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
(FAWE) java.awt.EventQueue.dispatchEvent(Unknown Source)
(FAWE) java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
(FAWE) java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
(FAWE) java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
(FAWE) java.awt.EventDispatchThread.pumpEvents(Unknown Source)
(FAWE) java.awt.EventDispatchThread.pumpEvents(Unknown Source)
(FAWE) java.awt.EventDispatchThread.run(Unknown Source)
(FAWE) --------------------------------------------------------------------------------------------
(FAWE) Thread: JavaFX Application Thread | Id: 28 | Alive: true
(FAWE) com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
(FAWE) com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
(FAWE) com.sun.glass.ui.win.WinApplication$$Lambda$63/17082353.run(Unknown Source)
(FAWE) java.lang.Thread.run(Unknown Source)
(FAWE) --------------------------------------------------------------------------------------------
(FAWE) Thread: Attach Listener | Id: 5 | Alive: true
(FAWE) --------------------------------------------------------------------------------------------
(FAWE) Thread: Thread-6 | Id: 27 | Alive: true
(FAWE) sun.misc.Unsafe.park(Native Method)
(FAWE) java.util.concurrent.locks.LockSupport.park(Unknown Source)
(FAWE) java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
(FAWE) java.util.concurrent.LinkedBlockingDeque.takeFirst(Unknown Source)
(FAWE) com.sun.glass.ui.InvokeLaterDispatcher.run(InvokeLaterDispatcher.java:108)
(FAWE) --------------------------------------------------------------------------------------------
(FAWE) Thread: Java2D Disposer | Id: 8 | Alive: true
(FAWE) java.lang.Object.wait(Native Method)
(FAWE) java.lang.ref.ReferenceQueue.remove(Unknown Source)
(FAWE) java.lang.ref.ReferenceQueue.remove(Unknown Source)
(FAWE) sun.java2d.Disposer.run(Unknown Source)
(FAWE) java.lang.Thread.run(Unknown Source)
(FAWE) --------------------------------------------------------------------------------------------
(FAWE) Thread: Reference Handler | Id: 2 | Alive: true
(FAWE) java.lang.Object.wait(Native Method)
(FAWE) java.lang.Object.wait(Unknown Source)
(FAWE) java.lang.ref.Reference.tryHandlePending(Unknown Source)
(FAWE) java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)
(FAWE) --------------------------------------------------------------------------------------------
(FAWE) Thread: AWT-Shutdown | Id: 9 | Alive: true
(FAWE) java.lang.Object.wait(Native Method)
(FAWE) java.lang.Object.wait(Unknown Source)
(FAWE) sun.awt.AWTAutoShutdown.run(Unknown Source)
(FAWE) java.lang.Thread.run(Unknown Source)
(FAWE) --------------------------------------------------------------------------------------------
(FAWE) Thread: Timer-0 | Id: 32 | Alive: true
(FAWE) java.lang.Object.wait(Native Method)
(FAWE) java.lang.Object.wait(Unknown Source)
(FAWE) java.util.TimerThread.mainLoop(Unknown Source)
(FAWE) java.util.TimerThread.run(Unknown Source)
(FAWE) --------------------------------------------------------------------------------------------
(FAWE) Thread: Signal Dispatcher | Id: 4 | Alive: true
(FAWE) --------------------------------------------------------------------------------------------
(FAWE) Thread: Finalizer | Id: 3 | Alive: true
(FAWE) java.lang.Object.wait(Native Method)
(FAWE) java.lang.ref.ReferenceQueue.remove(Unknown Source)
(FAWE) java.lang.ref.ReferenceQueue.remove(Unknown Source)
(FAWE) java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)
(FAWE) --------------------------------------------------------------------------------------------
(FAWE) Thread: QuantumRenderer-0 | Id: 25 | Alive: true
(FAWE) sun.misc.Unsafe.park(Native Method)
(FAWE) java.util.concurrent.locks.LockSupport.park(Unknown Source)
(FAWE) java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
(FAWE) java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
(FAWE) java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
(FAWE) java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
(FAWE) java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
(FAWE) com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
(FAWE) java.lang.Thread.run(Unknown Source)

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
