### ISSUE TITLE
History/Clipboard use-disk bugs.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#78]
FAWE dev 71 (bukkit19 jar version)
WorldEdit 6.1.1 dev 3487
ProtocolLib 4.0 dev 273
PaperSpigot 712.

With both history and clipboard use-disk settings enabled. History compression disabled.

Saved region.
![link](http://i.imgur.com/3YEhnE1.png)

Pasted.
![link2](http://i.imgur.com/ApXNzCT.png)

___

Another example.

Original copy area.
![link3](http://i.imgur.com/gRpoEl9.png)

Set region to stone, then undid.

Then pasted the copy. Then relogged.
![link4](http://i.imgur.com/5psByQD.jpg)

Original area entities/tile entities turned into invisible black banners.
![link5](http://i.imgur.com/vQKYr2p.png)

**Comment by boy0001** [comment]
Should be fixed.
