### ISSUE TITLE
//paste error

### ISSUE THREAD

**Issue by LogGits** [boy0001/FastAsyncWorldedit#782]
A whole mountain was //copy from one world to another. Then //paste produced this error https://pastebin.com/dYRhVf0e.

**Comment by Sitmobedaf** [comment]
I have some problem:
https://pastebin.com/RamPpkCZ

**Comment by Valik888** [comment]
I have same error like @Sitmobedaf when trying paste a scheme in this way:
`com.sk89q.worldedit.world.World world = FaweAPI.getWorld("world");
Schematic schematic = ClipboardFormat.SCHEMATIC.load(file);
System.out.printf("Entities count: %d", schematic.getClipboard().getEntities().size());
if(schematic.getClipboard().getEntities().size()>0) {
//This do nothing, entity's count remain unchanged
schematic.getClipboard().
     getEntities().
        removeAll(schematic.getClipboard().getEntities());
System.out.printf("After delete all entity's - %d",                
schematic.getClipboard().getEntities().size());
}
//Getting exception in next line:
EditSession editSession1 = schematic.paste(world, position, allowUndo, !noAir, (Transform) null);
editSession1.commit();
`

**Comment by boy0001** [comment]
Duplicate #785
