### ISSUE TITLE
Broken download link

### ISSUE THREAD

**Issue by SilentStormm** [boy0001/FastAsyncWorldedit#783]
The 1.12 download for Forge link is broken, and there isn't a WorldEdit for 1.12 download link anywhere
![2017-11-06 1](https://user-images.githubusercontent.com/33431920/32460118-fb4bdd98-c331-11e7-97e3-91389f683db3.png)

**Comment by Dpa1991** [comment]
It's been like this for a while now, I think I saw a post on the sponge forums dating back a month or so with someone asking & no answer.

**Comment by boy0001** [comment]
Links have been fixed:
http://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/
