### ISSUE TITLE
brush vis bugs out banners & signs

### ISSUE THREAD

**Issue by Cynadyde** [boy0001/FastAsyncWorldedit#784]
# Bug report

**Debug paste link**:

https://hastebin.com/wulezutore

**Description of the problem:**

The brush visualization feature does not play nice with banners or signs.
After bringing the visualization zone over...
- a **standing banner**, it turns into a 1m tall invisible post as seen below. 
- a **hanging banner**, it turns into 1m tall invisible slab on the wall.
- a **sign**, its text becomes invisible.

Everything turns back to normal after logging out and logging back in.

Additionally (seen in the very last image), it is possible to scroll onto and off of the brush item in such a way as to not remove the visualization zone.

![fawe-brush-visualization-bug](https://user-images.githubusercontent.com/19740479/32584991-2c9dff28-c4c9-11e7-8b0b-c36655bdeedb.png)

**How to replicate**:

I brought the "highlighted zone" onto the banner /sign and then off of it.

These are the two commands I used:
/br sphere 1 1
/br vis 2

Tricking the brush into not getting rid of the visualization zone is tricky. I only scroll off of the item at the right moment.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
