### ISSUE TITLE
[bug/major] Loading Certain Schematics is Broken

### ISSUE THREAD

**Issue by kangarko** [boy0001/FastAsyncWorldedit#785]
Hello boy0001!

**Debug paste link**:
https://hastebin.com/atohahipok

**Description and replication:**
Some schematics files are broken and won't load correctly, or freeze the server, both using CoreArena or Puncher plugin with [the following WorldEdit integration](https://pastebin.com/fCnDMV9i) (see iteration on line 28, that's causing too long and thus freezing the server or making FAWE throw errors), or simply //schematic commands.

Suspicious schematics: 
https://mega.nz/#F!N3BGSIqD!iXDA4c0yjKWzm197uKvkhA

Following errors appear when loading schematic via //schematic:
https://pastebin.com/AXX9HtDF

Also some really high timings when using FAWE with Puncher on that small schematic:
https://timings.aikar.co/?id=af5cbd2bb94745379052356c1a161589

**IMPORTANT:** After further testing this DOES NOT happen on 1.11.x and older, only since 1.12 and newer both Spigot and PaperSpigot.

**NOTE:** I was running tests with both 12GB and 1GB RAM, no change in results.

Thank you for your time!

**Comment by boy0001** [comment]
Fixed, please update.

**Comment by kangarko** [comment]
Thank you :)
