### ISSUE TITLE
#fullcopy pattern doesn't work with folder

### ISSUE THREAD

**Issue by braceyourself07** [boy0001/FastAsyncWorldedit#789]
# Bug report

**Debug paste link**:
https://hastebin.com/povumewiki

**Description of the problem:**
When trying to use the fullcopy pattern referencing a folder of schematics, get an out of bounds error:
https://hastebin.com/iwiyibunev.md

**How to replicate**:
Using the command /br scatter #fullcopy[folder2][true] 30 5 5 -o
The above error is displayed on console when trying to use.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
