### ISSUE TITLE
Undo bugs preserving original entity/tile entity positioning/items.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#79]
FAWE dev 71 (bukkit19 jar version)
WorldEdit 6.1.1 dev 3487
ProtocolLib 4.0 dev 273
PaperSpigot 712.

History compression, history use-disk and clipboard use-disk disabled.

Selected region.
![link1](http://i.imgur.com/siOpAjt.png)

Set it to stone.
![link2](http://i.imgur.com/aEI8jmu.png)

Typed undo.
![link3](http://i.imgur.com/g9Q0L4c.png)
![link4](http://i.imgur.com/dW18yxC.png)

The banner block turned into an invisible chest.

Breaking the middle chest leaves an invisible double chest graphical issue that you can walk through.

![link5](http://i.imgur.com/G2Qx01X.png)
![link6](http://i.imgur.com/uJAFi5j.png)

Relogging, all the entities turned into chests.
![link8](http://i.imgur.com/0W7h2ln.png)

Meaning it could be related to this issue https://github.com/boy0001/FastAsyncWorldedit/issues/78, except that means it isn't a history/compression issue since they were disabled on this testing scenario.

**Comment by boy0001** [comment]
Should be fixed.
