### ISSUE TITLE
//setbiome Ocean not working

### ISSUE THREAD

**Issue by Erumeldor** [boy0001/FastAsyncWorldedit#795]
# Bug report
With FAWE I'm unable to set the biome to OCEAN. All other testet biomes worked.
It doesn't work with //setbiome and with the methods (I used the api)

**Debug paste link**:
There is no error. But here is the paste: https://hastebin.com/otivorewap

**Description of the problem:**
The biome will not be set to OCEAN, whatever I try. Without FAWE (only WorldEdit) it is possible.
I tried a lot of FAWE versions from 550 to newest.

**How to replicate**:
Try to set any other biome to ocean. (//setbiome ocean)

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Erumeldor** [comment]
It's close to moving to the second page, so here is a push. Does someone has an idea where that could be fixed? :)

**Comment by Erumeldor** [comment]
I'm on the second page, a good reason for another #push.

No one any idea?

**Comment by Erumeldor** [comment]
Push? :(

**Comment by Foorack** [comment]
@Erumeldor This is not a forum. Issues are primarily shown after the date they were created, not last commented. Unfortunately I don't know what is causing this. Will have to wait until one of the developer comments on this. :confused:

**Comment by boy0001** [comment]
There's no option to set the default order issues appear for everyone else. For me it's now sorted by `recently-updated`. Sorry for the late reply. 

I'll fix this at some point, for the time being you can use another biome with the [same color](https://gist.github.com/boy0001/54bd4b27302eb2abced76cd35dc6e2e9#file-block-and-biome-color-codes-L194) e.g. deep ocean.

**Comment by Erumeldor** [comment]
Im creating a BiomeRepair Plugin to reset the biomes from a backup to the specific world, so working with another biome isn't an option ;)
At least thanks for the answer. ;)

Do you maybe know where this comes from? For my purposes I could fix this issue on our server myself (and fork to you if it's working👌)

**Comment by boy0001** [comment]
The plugin has a value of 0 if the biome isn't changed:
https://github.com/boy0001/FastAsyncWorldedit/blob/master/bukkit/src/main/java/com/boydti/fawe/bukkit/v1_12/BukkitChunk_1_12.java#L474

**Comment by Erumeldor** [comment]
So. I just looked into the code, because there was no action on your side ;)

I see, there is a value when the biome isn't changed. But that would be silly to have that on 0, because that is already a biome number.
What I see is: The `biomes` that is checked for 0 is only filled one, that would be here:
https://github.com/boy0001/FastAsyncWorldedit/blob/master/bukkit/src/main/java/com/boydti/fawe/bukkit/v1_12/BukkitChunk_1_12.java#L459

If you check the `nmsChunk.getBiomeIndex()`, it returns the array `g`.
`g` is intialized the same way FAWE does. BUT: `g` is filled with `-1` per default.
I cannot link it (because I don't find it on github). It is in Craftbukkit -> Chunk -> Line 115 (in my decompiled Version).
There it's `Arrays.fill(this.g, (byte)-1);`

So, if you remove the check if `biomes[i] != 0` and replace it with something like `biomes[i] >= 0` it is setting the biome correctly, as you already said.

The reason why I don't push in a merge-request is, that I don't know it this affects something else in your plugin.
I hope it would be possible to give a look into it, and fix this bug :)

Thanks a lot! 👍
