### ISSUE TITLE
FAWE not correctly placing chunks

### ISSUE THREAD

**Issue by Davis2133** [boy0001/FastAsyncWorldedit#796]
https://imgur.com/a/iYS6p
https://imgur.com/a/bRtNi
When I try to edit a long distance, a error in console appears and some chunks just don't get changed
FAWE debugpaste:
 Welcome to this paste
 It is meant to provide us at IntellectualSites with better information about your problem

 We will start with some informational files
links.config_yml: https://hastebin.com/oraqicawow
links.messages_yml: https://hastebin.com/ogiqikerid
links.commands_yml: https://hastebin.com/gupeyepuza
links.latest_log: https://hastebin.com/exabuticoh

 Server Information
server.platform: bukkit
server.plugins: 
 - ColorCodes: 2.0
 - CoreProtect: 2.14.2
 - PluginConstructorAPI: 1.0.11
 - OpenInv: 3.3.0
 - ClearLag: 2.9.7
 - SetSpawn: 2.2.1
 - Administration_Panel: 1.1.0
 - Multiverse-Core: 2.5.0-b727
 - ProtocolLib: 4.2.0
 - NoCheatPlus: 3.15.1-RC-sMD5NET-b1084
 - FastAsyncWorldEdit: 17.11.13-12580b5-945-18.0.2
 - iDisguise: 5.6.4
 - MaxBans: 2.7
 - TrollCommandsPlusPlus: 5.27.52
 - PermissionsEx: 1.23.4
 - EasyWarp: 3.8
 - Multiverse-Portals: 2.5.0-b751
 - Vault: 1.5.6-b49
 - Essentials: 2.0.1-b488
 - FastAsyncVoxelSniper: 17.11.13-12580b5-945-18.0.2
 - HolographicDisplays: 2.2.6
 - Citizens: 2.0.22-SNAPSHOT (build 1487)
 - VoxelSniper: 5.171.0-SNAPSHOT
 - RandomTeleport: 5.0.2
 - SuperVanish: 5.10.1
 - FakePlayersOnline: 0.1.8
 - WorldEdit: 6.1.7;dd00bb1
 - WorldGuard: 6.1.3-SNAPSHOT;c904242
 - Punishmental: 5.0
 - GriefPrevention: 16.7.1
server.version: git-Bukkit-0a81101 (MC: 1.11) / 1.11-R0.1-SNAPSHOT

 YAY! Now, let's see what we can find in your JVM
memory.free: 92953984
memory.max: 1037959168
java.specification.version: '1.8'
java.vendor: 'Oracle Corporation'
java.version: '1.8.0_144'
os.arch: 'x86'
os.name: 'Windows 10'
os.version: '10.0'

 Okay :D Great. You are now ready to create your bug report!
 You can do so at https://github.com/boy0001/FastAsyncWorldedit/issues

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.

**Comment by JakeDaDream** [comment]
> If the issues persist still, reopen the ticket.

I'm going through the same things. Not sure what the issue is. Do you know what the main causes of them are?
