### ISSUE TITLE
Fawe Worldguard __global__ (Please respond as soon as possible)

### ISSUE THREAD

**Issue by Callial** [boy0001/FastAsyncWorldedit#799]
# Bug report

**Debug paste link**: 
https://hastebin.com/epoculolad

**Description of the problem:**
Worldguard can not be denied within a specific worldguard region it can only be allowed.

**How to replicate**:
Create a single worldguard region to not allow fawe within and try to add the player as a member to the __global__ or a template region.
add both the fawe.worldguard.member and the fawe.worldguard perms or just apply one or the other to the member or group.
Then If then if the player or group is added to the __global__ region the player can use FAWE anywhere even in regions they should not be able to.
If added to a template region nothing changes fawe is still denied

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report No worldguard ones open and this one is actually a different problem.
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
The reason for this is that it's costly to check every block through the WorldGuard API and I have yet to find/implement an efficient space-partitioning data structure.

**Comment by DragonHeart98361** [comment]
Ah ok I understand. Well I wish you the best of luck in future development :)
