### ISSUE TITLE
History compression is not outputted when both compress and use-disk settings are enabled.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#80]
FAWE dev 71 (bukkit19 jar version)
WorldEdit 6.1.1 dev 3487
ProtocolLib 4.0 dev 273
PaperSpigot 712.

The history compression output ```[FAWE] History compressed. Saved ~ #b (#x smaller)``` does not occur when both history compress and use-disk are enabled. Disabling use-disk, it outputs. Not sure if intended or if because it doesn't compress when using disk storage.

**Comment by boy0001** [comment]
It always compresses. With compression disabled it just compresses less.

**Comment by mibby** [comment]
Ah, alright. Well it doesn't output the compression information when use-disk is enabled. :)

**Comment by boy0001** [comment]
irc:
http://webchat.esper.net/?nick=&channels=IntellectualCrafters
