### ISSUE TITLE
Paste Schematic Outside allowed Region

### ISSUE THREAD

**Issue by Demonofpower** [boy0001/FastAsyncWorldedit#801]
Hey, 
i try to paste a Schematic in my ownPlugin with the FAWE API.
I disabled Region restrictions but everytime i paste a schematic it denies me.

[18:43:58] [INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[0;37;22m Outside allowed region (bypass with /wea, or disable `region-restrictions` in config.yml) 

Cu

**Comment by Erumeldor** [comment]
Just use the FAWE EditSession and allow regions there:
EditSession editSession = new EditSessionBuilder(world).allowRegions(true).build();

Information can be found there: https://github.com/boy0001/FastAsyncWorldedit/wiki/WorldEdit-EditSession

If "issue" is fixed, please close it.

**Comment by Demonofpower** [comment]
Sorry but i can´t fix my problem.

` World weWorld = new BukkitWorld(Bukkit.getWorlds().get(0));
        
            EditSession editSession = null;
            Schematic schem;
			try {
				
				schem = ClipboardFormat.SCHEMATIC.load(file);
				
				EditSession by = new EditSessionBuilder(new BukkitWorld(Bukkit.getWorlds().get(0))).allowedRegionsEverywhere().build();
				editSession = schem.paste(weWorld, getVector(middle));
				by.flushQueue();
				
			} catch (IOException e) {
			}
            
            editSession.flushQueue();
            
           
            player.sendMessage("Success!");`

Is the code correct? c:

**Comment by mcgrizzz** [comment]
Same issue here. I posted on this duplicate issue #820

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
