### ISSUE TITLE
FAWE does not log some blocks for CoreProtect

### ISSUE THREAD

**Issue by BoomEaro** [boy0001/FastAsyncWorldedit#803]
**Debug paste link**:
https://hastebin.com/orakimacel

**Description of the problem:**
Signs, frames, armor stands, and other similar objects do not log in if they are inserted by a plugin. This is a big vulnerability, someone will be able to set up the sign for construction and not be able to restore the building, because there are no logs!

https://hkar.ru/RQpf (The screenshot shows how I copied the distant objects that are for verification, and inserted here, but most logs are missing)

https://hkar.ru/RQpe (Before copying, just put the blocks by hand)
**How to replicate**:
Simply //set sign or other similar objects and write /co i to check the object for installation.

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin
(Sorry for my english)

**Comment by boy0001** [comment]
This is a limitation of BlocksHub, not FAWE.

FAWE's in built logger (which you have disabled) should handle those correctly.

**Comment by BoomEaro** [comment]
I checked FastAsyncWorldEdit with Blockhub - some blocks do not log
And I checked the usual AsyncWorldEdit with BlockHub - everything works there.
