### ISSUE TITLE
Big delay occassionally before placing blocks

### ISSUE THREAD

**Issue by Miclebrick** [boy0001/FastAsyncWorldedit#806]
Is it normal for there to be a delay when performing pretty much any worldedit operation sometimes, where it just doesn't place any blocks? Or is that a bug?

**Comment by Combustible** [comment]
How big is "big"? Especially when doing large operations, there is often a multi-second delay while FAWE is updating chunks in the background before they get sent to your client to be rendered. Sometimes, for tens or hundreds of millions of blocks, the delay is in the tens of seconds.

**Comment by Miclebrick** [comment]
Usually, it's a few seconds, but often it can go up to a few minutes. It's not only large edits, it happens if you just do /up 1.

**Comment by Miclebrick** [comment]
I don't get this anymore so I'm gonna close it.
