### ISSUE TITLE
Is this plugin dead?

### ISSUE THREAD

**Issue by AnZaNaMa** [boy0001/FastAsyncWorldedit#807]
I'm just wondering if this plugin is dead. It claims to have a 1.12 version but said version doesn't even load when added to Sponge. The last build was 18 days ago but it only fixed one issue and completely ignored the fact that the plugin doesn't work at all on Sponge API 7. The last official release was in May of 2016...

Is anyone still actively developing this plugin?

**Comment by KourisBP** [comment]
Plugin is still active yes, Works perfectly find for 1.12.2 on my server but I'm using paperclip not sponge.

**Comment by Combustible** [comment]
Works quite well with Spigot as well for 1.12.2.

**Comment by AnZaNaMa** [comment]
Well, I'd post an issue if there was any sort of report I could give. But there's not any message or anything. The plugin shows as loaded but none of the commands do anything
