### ISSUE TITLE
v3.5.0 for Bukkit/Spigot 1.8.8 not loading

### ISSUE THREAD

**Issue by User3794739** [boy0001/FastAsyncWorldedit#808]
Because of the use of structure blocks, the //pos1 and //pos2 commands of the newest version don't work with Minecraft 1.8.
Which version is the latest 1.8-compatible one?

**Comment by User3794739** [comment]
Okay, just had to scroll down on the dowload-site.
Now I've downloaded the "v3.5.0" "Bukkit/Spigot 1.8.8" version (https://goo.gl/pGJJDz), which isn't loading on my 1.8.8 spigot server. Is PaperSpigot required for this version?

**Comment by boy0001** [comment]
Disable the experimental settings.

**Comment by User3794739** [comment]
I did so. Now the server is shutting down, after all plugins are loaded. 
#816

**Comment by boy0001** [comment]
Oh, you're using 3.5.0, that's a really old version which won't support the current WorldEdit. 

Please use the latest version of FAWE:
https://github.com/boy0001/FastAsyncWorldedit/wiki/Download-Instructions:-Bukkit-Spigot

**Comment by User3794739** [comment]
Thanks. ^^
Got he version from https://github.com/boy0001/FastAsyncWorldedit/releases, where it is listed as the newest version.
