### ISSUE TITLE
Falling Blocks Disappear

### ISSUE THREAD

**Issue by kangarko** [boy0001/FastAsyncWorldedit#809]
Hello,

an user have reported that my plugin has an incompatibility with FAWE:

`Block physics don't work with fawe. When they do get launched it is invisible and the users don't see it but when they walk over a block that was displaced invisibly they start glitching into the block. It doesn't show the block was moved on the clients screen.`

My plugin does not use WorldEdit at all in procedural damage. WorldEdit is only used when starting or finishing an arena to restore the arena map. 

The damage that the user is complaining about spawns a FallingBlock normally using Bukkit API, so I am referencing here for a possible bug in FAWE.

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
