### ISSUE TITLE
StackOverflowError when calling EditSession#replaceBlocks(Region, Set<BaseBlock>, BaseBlock)

### ISSUE THREAD

**Issue by Phoenix616** [boy0001/FastAsyncWorldedit#810]
# Bug report
**Debug paste link**: https://hastebin.com/juricudofe

**Description of the problem:**
StackOverflowError when calling `EditSession#replaceBlocks(Region, Set<BaseBlock>, BaseBlock)`. [The code](https://github.com/boy0001/FastAsyncWorldedit/blob/master/core/src/main/java/com/sk89q/worldedit/EditSession.java#L1732) seems to be calling itself? Before d7d897d1 it was `new BlockPattern(replacement)`.

**How to replicate**:
Call `EditSession#replaceBlocks(Region, Set<BaseBlock>, BaseBlock)`

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Erumeldor** [comment]
I can confirm this issue.
I just used directly the method with blockpattern because the other one is calling itself.
