### ISSUE TITLE
Copied Chisel&Bits blocks doesn't paste

### ISSUE THREAD

**Issue by IHazFury** [boy0001/FastAsyncWorldedit#814]
Whenever chiseled blocks from C&B are pasted, they paste as empty blocks that dissapear on block update.

**Comment by CreativeMD** [comment]
It looks like FAWE doesn't copy any modded tileentities in 1.12.2.

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket

**Comment by blakedj** [comment]
The problem is still there. You cannot copy things created with Little Tiles.
