### ISSUE TITLE
v.3.5.0 for Spigot 1.8.8 causes crash [added server log]

### ISSUE THREAD

**Issue by User3794739** [boy0001/FastAsyncWorldedit#816]
**Debug paste link**:
Plugin isn't loading, so no paste link for you
I can just give you some errors from the log:
https://hastebin.com/diyekadisu

**Description of the problem:**
When I put v.3.5.0 in my plugins folder, the sever is stopping immediately after starting.

**How to replicate**:
Put https://github.com/boy0001/FastAsyncWorldedit/releases/tag/v3.5.0 for Bukkit/Spigot 1.8.8 in the plugins folder of a Spigot server with the following Spigot version installed: git-Spigot21fe707-e1ebe52

**Checklist**:
- [ ] I included a `/fawe debugpaste` link - I can't.
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Still not using the latest FAWE. Folow the instructions (click the download link) on this page linked in the last issue: https://github.com/boy0001/FastAsyncWorldedit/wiki/Download-Instructions:-Bukkit-Spigot
or download the latest build from http://ci.athion.net/job/FastAsyncWorldEdit/ if it's easier.

**Comment by User3794739** [comment]
boy001 awnswered my other issue.
The only problem was an is, that many links are redirecting to https://github.com/boy0001/FastAsyncWorldedit/releases where you can't find the latest version.
examples:
- "Installation" in https://github.com/boy0001/FastAsyncWorldedit/wiki
- "FastAsyncWorldEdit/VoxelSniper" in https://github.com/IntellectualSites/PlotSquared/releases/tag/dev
