### ISSUE TITLE
it says i have no more memory but yet my storage is empty

### ISSUE THREAD

**Issue by corychampion31** [boy0001/FastAsyncWorldedit#819]
# Bug report

**Debug paste link**:

**Description of the problem:**

**How to replicate**:

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of FAWE
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Memory is RAM, not hard disk storage.
