### ISSUE TITLE
Pasting schematics not allowed outside region

### ISSUE THREAD

**Issue by heyoomimi** [boy0001/FastAsyncWorldedit#820]
**Debug paste link**: 
https://hastebin.com/uziwivufus
**Description of the problem:**
I tried pasting a schematic but it says it's outside the allowed region, even after running /wea and disabling region-restrictions in the config.
https://cdn.discordapp.com/attachments/268444645527126017/388920733562044418/unknown.png
It works fine when I do commands like setting but not with pasting schematics. 
**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Tiippex** [comment]
I have the same problem!

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
