### ISSUE TITLE
(API) Entites become invisible after world.commit();

### ISSUE THREAD

**Issue by MClausz** [boy0001/FastAsyncWorldedit#822]
I'm using FAWE to make a smoke grenade, this is my class:
https://pastebin.com/wQAkWLVf
But there is a problem, armor stands that are inside the smoke (crops) will become invisible, I don't know whether this is a packet problem, the armor stands still exist or are actually gone.

**Comment by Miclebrick** [comment]
can confirm this issue is a thing, happens when I use normal worldedit

**Comment by N0tMyFaultOG** [comment]
If the issue persists still, reply to the ticket
