### ISSUE TITLE
MCPE / Nukkit

### ISSUE THREAD

**Issue by NycuRO** [boy0001/FastAsyncWorldedit#824]
Hello.

Can you implement one command who start one "task" who replaced all PC blocks to PE blocks?

Or by region, etc etc? :D 

Not only with schematic. Will be greatfull!

@boy0001

**Comment by dordsor21** [comment]
Download and run the Nukkit FAWE jar. You will be able to do this with a selected world.

**Comment by NycuRO** [comment]
@dordsor21 How?

**Comment by NycuRO** [comment]
And please re-open, commands not work on nukkit. Get errors any time.

**Comment by dordsor21** [comment]
Open a different issue. Download the latest Nukkit FAWE build and literally double-click it, like you would to run another program
