### ISSUE TITLE
Issues with Thermos 1.7.10

### ISSUE THREAD

**Issue by Crimento** [boy0001/FastAsyncWorldedit#825]
# Bug report

**Debug paste link**:
https://pastebin.com/YMP2AeVq (Server crash with latest 1.7.10 Forge FAWE + Latest **Bukkit** Worldedit (6.1.7.3))
https://hastebin.com/ofivumekep (Latest 1.7.10 Forge FAWE + 1.7.10 Forge Worldedit 6.1.1 (link to 6.1.2 isn't working anymore))

**Description of the problem:**
Can't start server with latest bukkit worldedit and latest forge FAWE.
If I use both forge FAWE and WorldEdit then even basic commands like //set doesn't work.

**How to replicate**:
Install latest 1.7.10 bukkit worldedit & forge FAWE
Get server crash.
Install latest 1.7.10 forge worldedit & FAWE
Commands not working.

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Hastebins are empty, if this is an issue still, post the logs below.
