### ISSUE TITLE
Massive FPS drop when performing actions over the void

### ISSUE THREAD

**Issue by BrainStone** [boy0001/FastAsyncWorldedit#826]
# Bug report

**Debug paste link**: https://hastebin.com/esurofekuj

**Description of the problem:**
When performing actions in a void world with nothing below the FPS drops extremely. Like from 1000+ to game almost crashing.  
While I can't rule out that is happening with just WorldEdit I think this is an issue that should be addressed.

**How to replicate**:
Run `//cyl 1 100` in a void world

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Gabik21MC** [comment]
This is totally client related and also occurs with just using worldedit.

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket and we will look for a new solution
