### ISSUE TITLE
server crash on plot auto

### ISSUE THREAD

**Issue by PhanaticD** [boy0001/FastAsyncWorldedit#827]
using plotsquared build 536, FAWE 944, paperspigot build 1283

not sure if this is a plotsquared or FAWE issue so im putting issues for both

this has happened twice now: https://pastebin.com/fn4pAq4N

**Comment by boy0001** [comment]
The error looks like from a bugged block with NBT (usually a sign). The server is unable to serialize the chunk it's in. It could have been corrupted (somehow?), or placed maliciously by a player.

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
