### ISSUE TITLE
FastAsyncWorldEdit problem with Chunk Loading

### ISSUE THREAD

**Issue by Faciliamo** [boy0001/FastAsyncWorldedit#828]
**Debug paste link**:
https://hastebin.com/ukalivanoz

**Description of the problem:**
I have Paper Spigot 1.7.10, Fawe latest build and WorldEdit lates build, when i build something with FAWE the chunks where i build disappear, https://youtu.be/LdwHO2Lcj8Q, i tried to downgrade version of WorldEdit/FAWE, but when i downgrade the plugin doesn't work anymore, we tryed to unload all plugins, but the problem is still remaining

**How to replicate**:
When you create a build with worldedit in air, the chunk under this "Build" disappear.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)]
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Gabik21MC** [comment]
I fixed this my own version of fawe, but I edited too many things to make it a proper pull request.

**Comment by boy0001** [comment]
@Gabik21MC 
If you make your fork public, I can take a look at what you changed and copy what's necessary to master.

**Comment by Gabik21MC** [comment]
I won't be at home until new year, so it will take some time

**Comment by Faciliamo** [comment]
If you can release your version i'll appreciate

**Comment by SpaicyGaming** [comment]
@boy0001 I have the same issue. I've already reported it 4 months ago. https://github.com/boy0001/FastAsyncWorldedit/issues/729

**Comment by Gabik21MC** [comment]
https://github.com/Gabik21MC/FastAsyncWorldedit
Here is the fork with the fix. I deleted some classes because some imports in them could not be resolved and they were not necessary for me.

**Comment by Gabik21MC** [comment]
@boy0001

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
