### ISSUE TITLE
Download websites down

### ISSUE THREAD

**Issue by KennyTV** [boy0001/FastAsyncWorldedit#829]
Neither the ci (http://ci.athion.net/job/FastAsyncWorldEdit/) nor the download links (http://empcraft.com/fawe/latest.php?bukkit) are online / reachable

**Comment by boy0001** [comment]
@dordsor21 
It'll probably be online soon. Empcraft is just a redirect. 

For now, here are instructions on how to build the jar yourself: https://github.com/boy0001/FastAsyncWorldedit#building

Or the current jar:
[fawe.zip](https://github.com/boy0001/FastAsyncWorldedit/files/1587388/fawe.zip)

**Comment by JohnPines** [comment]
When will it be back up.

**Comment by JohnPines** [comment]
Failed to connect to ci.athion.net port 443: Connection timed out
Not found, redirecting to: https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/

**Comment by boy0001** [comment]
I've added `ci.codemc.org` as a fallback now, so this will be less likely to occur in the future.
