### ISSUE TITLE
Feature Request - Overhaul /fawe command output.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#83]
Personal opinion for how commands should work.

* '/fawe' no longer reloads the plugin. Instead, outputs all the commands implemented from FAWE.
* Implement '/fawe reload' to reload the config settings.
* Allows for future support of help pages in case you ever wanted to add '/fawe help' - or just have a description of what each command does in the command list of '/fawe'.
* Add '/fawe version'. Outputs version (and build number if using a jenkins build). As well as plugin author.

**Comment by boy0001** [comment]
The other commands FAWE adds are mostly WorldEdit commands, so listing only them doesn't make a whole lot of sense. I can create a new ticket if you think the help page for WorldEdit could be improved. 

Anywho, `/fawe version` and `/fawe reload` have been added.
