### ISSUE TITLE
There was an error handling a FAWE command : class not found ChunkLoadCallback

### ISSUE THREAD

**Issue by OtherQuoeia** [boy0001/FastAsyncWorldedit#830]
# Bug report

**Debug paste link**:

https://hastebin.com/aletenofin

**Description of the problem:**
see under link
https://gyazo.com/9a9953b4061fede50123a16428dd1df7
i tested under issues "Or the current jar: fawe.zip" jar.
https://github.com/boy0001/FastAsyncWorldedit/issues/829

**How to replicate**:

I only rebooted the server and pc

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by monkey8113** [comment]
Suddenly without any notice, i had this problem also after daily server restart.
https://hastebin.com/zuqonatevu

**Comment by DevJul1an** [comment]
You need to build the jar yourself or use PaperSpigot until the jenkins is back up.

**Comment by JohnPines** [comment]
this is happening to me also

**Comment by JohnPines** [comment]
I uninstalled FAWE and WorldEdit isnt working either...
ERROR:
java.lang.NoSuchMethodError: com.google.common.base.Objects.firstNonNull(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

**Comment by boy0001** [comment]
@JohnPines 
That error without FAWE is because you are on an old version of WorldEdit and need to update. It wasn't an issue before because FAWE has the updated classes.

**Comment by boy0001** [comment]
Has been fixed. See:
https://github.com/boy0001/FastAsyncWorldedit/issues/829#issuecomment-353969198
