### ISSUE TITLE
Worldedit // FAWE Error

### ISSUE THREAD

**Issue by Cypherverse** [boy0001/FastAsyncWorldedit#831]
# Bug report

**Debug paste link**:
https://hastebin.com/adejafegud - Worldedit Debugpaste
https://hastebin.com/haxekavene - FAWE Debugpaste

**Description of the problem:**
Worldedit commands worn work https://gyazo.com/7d82acce2cdb7942f4f4a563fb377454

**How to replicate**:

**Checklist**:

- [!] I included a `/fawe debugpaste` link
- [I Looked but couldnt find an answer] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [!] I made sure I am using an up-to-date version of FAWE
- [Not Sure.] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Duplicate #830
