### ISSUE TITLE
Not able to use W.E anywhere

### ISSUE THREAD

**Issue by iiCarelessness** [boy0001/FastAsyncWorldedit#832]
# Bug report

**Debug paste link**: https://pastebin.com/AXBxJJpk
https://my.mixtape.moe/zgqfbq.yml

**Description of the problem:**
Builders have basic perms, flatworld has no region flags, so should be able to build there, can't.
![image](https://user-images.githubusercontent.com/21291440/34367709-eced7bee-eaa5-11e7-9f24-02af672e9ee9.png)

**How to replicate**:
Have normal config, don't add fawe.bypass to a group, deop yourself, try worldedit in any region.

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Add the perms `fawe.worldguard` and `fawe.worldguard.member`.

**Comment by iiCarelessness** [comment]
That didn't help anything.

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
