### ISSUE TITLE
Ligthning / Religthning didnt work, while Placeholder API is running.

### ISSUE THREAD

**Issue by Fandrael** [boy0001/FastAsyncWorldedit#833]
# Bug report
**Debug paste link**:
https://pastebin.com/pPZLmcb9

**Description of the problem:**
Since I start working with PlaceholderAPI 2.8.2 an error accurs, when i do operations like: Setlight, Relight, Removelightning. From the point on, I activate Placeholders API, the NMS isnt working anymore.

**How to replicate**:
I am not really sure, if it is the API... Did you have this situation anytime before?
I could not fix it. **Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Fandrael** [comment]
Somebody of you have any Plan? I think... I had updated an reinstalled every of the acting plugins. I see, that the Placeholders API Plugin has delivered NMS in their dependencies on github.

**Comment by dordsor21** [comment]
Use the latest build, and it's also safer to use 1.12.2
