### ISSUE TITLE
FAWE breaks worldedit

### ISSUE THREAD

**Issue by RavaPollo** [boy0001/FastAsyncWorldedit#835]
# Bug report

**Debug paste link**:

**Description of the problem:**
 Basically, when i download the FastAsyncWorldEdit.jar , i put it into plugins, restart server and when it's all restarted, none of the worldedit commands work.. I have tried reinstalling it multiple times, still crashed. https://pastebin.com/F7tCGbK8 is my console log, a few errors are present relating to FAWE. or the files are attached into zip

**How to replicate**:

Not possible, all you do is load the FastAsyncWorldEdit.jar (From bukkit page) and it causes prob
**Checklist**:
Doing the command /fawe does nothing, so i can't paste the debug thing.

**Comment by boy0001** [comment]
Use the updated version on spigot, or here's a direct link to the latest jar:
http://empcraft.com/fawe/latest.php?bukkit
