### ISSUE TITLE
 region-restrictions: false not working correctly

### ISSUE THREAD

**Issue by joblo2213** [boy0001/FastAsyncWorldedit#836]
# Bug report
**Debug paste link**:
https://hastebin.com/awoxiqohop

**Description of the problem:**
Although no regions are defined and regionrestrictions are set to `false` in the config I sometimes get the following message while using brushes:

![grafik](https://user-images.githubusercontent.com/17405009/34385520-ad92e438-eb23-11e7-9598-314172f97a33.png)

What `/rg info` gives me:
![grafik](https://user-images.githubusercontent.com/17405009/34385675-a1d0c592-eb24-11e7-96bf-1e052d0c6c6d.png)

**How to replicate**:
Here my configuration. The error often occurs if I use Brushes with a large radius. (Like `/br s stone 100`)
My config.yml: [config.yml.zip](https://github.com/boy0001/FastAsyncWorldedit/files/1589323/config.zip)
My permissions.yml: [permissions.yml.zip](https://github.com/boy0001/FastAsyncWorldedit/files/1589325/permissions.yml.zip)

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by DarkObscurity** [comment]
I also am experiencing this issue... it randomly started appearing today on our server, I tried everything, disabling all restrictions, taking away and resetting the permissions, ut non of this helps, also I can't togle /wea it keeps on saying your actions are now restricted... the server has been running for moths without issues
