### ISSUE TITLE
[Bug/error] There was an error handling a FAWE command

### ISSUE THREAD

**Issue by Wynnevir** [boy0001/FastAsyncWorldedit#839]
# Bug report

**Debug paste link**:
https://hastebin.com/noyezecuju

**Description of the problem:**
It seems some key commands like //copy and //paste are unable to be used, they result in this error:
https://hastebin.com/ikizumigug.apache
A picture of the error in game too:
http://puu.sh/yOQkz/a17ac5823b.png
I have found other closed posts that have an error similar to this, but they don't have any steps I can take on my end. Most of them just say "fixed".
My Current spigot version is as up to date as I can get it:
This server is running CraftBukkit version git-Spigot-549c1fa-45c8386 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
(It says I am 1 behind but I don't have anything over 1.12.2 buildtools 70 available to me in panel so I don't know what it's on about)
It was working 100% fine yesterday, and had stopped working **before** I ran this update. I tried to update it as an attempt to fix it, and it is still not working.
Worldedit without FAWE works fine.

**How to replicate**:
1) Use some commands like //copy or //paste
2) Receive error 

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by WindUnwaken** [comment]
If you also found, plugin auto update?
and now author close all download site.. hope it fix soon

**Comment by Wynnevir** [comment]
I don't want to use auto update just for the sake of not waking up one morning to find everything broke, but the latest buildtools should also be the most up to date available without need of auto update.
that aside, this issue is very likely not related to the auto update setting.

**Comment by dordsor21** [comment]
Should be fixed in latest build.

**Comment by jas777** [comment]
Same error https://hastebin.com/izemiditec

**Comment by dordsor21** [comment]
Use latest build http://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/
