### ISSUE TITLE
FAWE Broke

### ISSUE THREAD

**Issue by Techno3600** [boy0001/FastAsyncWorldedit#841]
# Bug report
**Debug paste link**:
****
https://hastebin.com/zulufodone
****Description of the problem:**
**
Here is the console error:
https://pastebin.com/GjRj8eQb
**How to replicate**:
****
Do anything.

**Comment by EvilOlaf** [comment]
Confirmed with Spigot 1.8.8 and WorldEdit 6.1.5;4651611

**Comment by evanmcclan** [comment]
@Techno3600 I'm having this exact same issue. nothing with the world edit commands work.
**Bump**

**Comment by EvilOlaf** [comment]
This has been fixed already I think. Are you on the latest build?

**Comment by Wynnevir** [comment]
im having this issue with a lot of commands on the latest build. it spontaneously happened this morning.

**Comment by dordsor21** [comment]
The very latest build. It should be fixed.
