### ISSUE TITLE
//cfi errors.

### ISSUE THREAD

**Issue by Tobberz** [boy0001/FastAsyncWorldedit#843]
**Debug paste link**:
https://hastebin.com/ganunemera

**Description of the problem:**
//cfi gives multiple errors.
Here's a link to them:
https://pastebin.com/Q5mxGjY1

**How to replicate**:
Simply type //cfi.

**Comment by boy0001** [comment]
You need to setup textures:

Put any jars with textures you want (e.g. your .minecraft/versions/<version>/<version>.jar) in FastAsyncWorldEdit/textures
