### ISSUE TITLE
FAWE Removing chunks with brushes & Outside allowed region confirmation.

### ISSUE THREAD

**Issue by fyrmftw** [boy0001/FastAsyncWorldedit#845]
# Bug report
- FAWE Removing chunks with brushes & Outside allowed region confirmation.

**Debug paste link**:
https://hastebin.com/opubewejir

**Description of the problem:**
Last few latest updated jar version, is causing fawe to remove chunks during brushes & it spamming outside allowed region and it cannot paste the blocks

**Screenshot of issue:**
https://i.imgur.com/tmh6Bkq.jpg

**How to replicate:**
Use latest jar version of FAWE, grab a sword, type /br smooth, then /br size 5, and start right clicking on areas, and it will say "Outside allowed region" and start removing blocks and causing deep chunk removals, as seen in screenshot above.

**Fixing issue:**
I downgraded versions and FAWE was working properly again.

**Checklist:**
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
Yes. On my server too.

**Comment by RedstoneFuture** [comment]
![2018-01-14_20 09 11](https://user-images.githubusercontent.com/4140635/34919599-f0bc9b90-f966-11e7-9462-121d831611ce.png)

**Comment by acm321** [comment]
@fyrmftw What version did you downgrade to to make it work again? I'm having similar issues with other brushes, see #884 as referenced above.

**Comment by RedstoneFuture** [comment]
Still a issue ... and I find a big problem. I can't build with this bug. ^^

**Comment by RedstoneFuture** [comment]
@fyrmftw @acm321 

https://github.com/boy0001/FastAsyncWorldedit/issues/923 was fixed and I can now use //brush without this problem. Try the last version of FAWE (and PlotSquared).
