### ISSUE TITLE
Blockstate syntax

### ISSUE THREAD

**Issue by BrainStone** [boy0001/FastAsyncWorldedit#846]
According to the `extrablocks.json` there is support for named block variants/blockstates.

From my testing things like `stone:andesite` work just fine. But how would I specify multiple states like leaves have. Everything I tried didn't work.

**Comment by boy0001** [comment]
You can use the numbers 0-16

**Comment by BrainStone** [comment]
I’m very well aware of that. Though I’m trying to avoid number memorization.
