### ISSUE TITLE
Favs/Fawe bug, not able to undo favs

### ISSUE THREAD

**Issue by N0tMyFaultOG** [boy0001/FastAsyncWorldedit#849]
**Debug paste link**:
https://hastebin.com/ulovovuyoy

**Description of the problem:**
I use fawe and favs, but if you brush something with Voxel, /u or //undo just undo's the Fawe actions. It doesn't undo any VoxelSniper stuff.
An abstract from the console goes below:

[17:53:48 INFO]: NotMyFault issued server command: /u
[17:53:48 INFO]: [VoxelSniper] Player "NotMyFault" used /u

**How to replicate**:
Run fawe and favs, set up a brush and try to //undo it.

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Sprungente** [comment]
same here

**Comment by BrainStone** [comment]
We experience this issue as well!

**Comment by boy0001** [comment]
Was fixed
