### ISSUE TITLE
Outside allowed region problems (Disabled region-restrictions: false not work)

### ISSUE THREAD

**Issue by NilssMiner99** [boy0001/FastAsyncWorldedit#852]
# Bug report

**Debug paste link**: https://hastebin.com/iloraxokug

**Description of the problem:**

It says "(FAWE) Outside allowed region...".
I have disabled it and it says that, and when you have used the command /wea its work not on every block.

**How to replicate**:

Use it in a other world or other GS (PlotSquared) with bypass and you will see its not working every time.

And when you use //brush smooth -> https://i.imgur.com/nIQNTD2.jpg (This is only when the message come when its not says "Outside allowed..." its work)

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Sprungente** [comment]
same here 
Spigot 1.12.2 Without Plotsquared but with Worldguard
Happens with smooth

Please fix it as fast is possible. Thanks

**Comment by joblo2213** [comment]
I also had this issue and reported it.
So this is a duplicate of #836

**Comment by DarkObscurity** [comment]
Just updated to the newest version, issue is still there...

**Comment by Sprungente** [comment]
Same here

Von meinem iPhone gesendet

Am 03.01.2018 um 23:17 schrieb DarkObscurity <notifications@github.com<mailto:notifications@github.com>>:


Just updated to the newest version, issue is still there...

**Comment by Sprungente** [comment]
Next time it is friendly to say why a issue will close

**Comment by NilssMiner99** [comment]
Sry, false button

**Comment by LogGits** [comment]
@boy0001 Any news on this. It appears to be effecting brush smooth aswell.

**Comment by Sprungente** [comment]
it looks like the plugin-team aren't motivated to get support

**Comment by dordsor21** [comment]
It's a free plugin, You're not entitled to devs working on this in their free time to cater to everything straight away.

**Comment by Wattyooo** [comment]
Or anything it would appear.

**Comment by Sprungente** [comment]
I don't say about free time or something. I'm entitled to expect that the devs working to fix bugs, improve the plugin and that the plugin works, what it says.

**Comment by dordsor21** [comment]
Then pay for it...

**Comment by Sprungente** [comment]
okay so people they don't pay don't entitled a plugin that works. It's nice to know .

**Comment by dordsor21** [comment]
Nevermind. The point and your head are entirely perpendicular

**Comment by Gabik21MC** [comment]
@Sprungente do a pull request yourself instead of bashing at people doing a free plugin. Also you should know that making an async block place implementation that supports more features than plain worldedit for all versions requires a lot of knowledge about the obfuscated code, which is very time consuming. The dev of this plugin is also a human and is probably also working on other projects.

**Comment by Sprungente** [comment]
I'm finish here @Gabik21MC . I misunderstand me. I wanna say that user from plugin have the permission to explain what the plugin says. I never said that the dev are bad, not working or something. With no motivated maybe it has more important things to do as a major Bug in a plugin (for example reallife, family etc.). I'm thanksfull for that, what the devteam will do.

It isn't ok that i'm standing here like a bad guy  only  i told what i have thought. I'm supporting many free pluginprojects and spigot with many donate. Also i donate money for helping poor people in crisis country.

I'm sure the bug will fixed but i hope it has (in the buglist) a higher priority. 

Thanks for the discussion even if it on the wrong place. Sorry for the rest, who get emails from this discussion

**Comment by DarkObscurity** [comment]
Just tested the newest release, still not working

**Comment by boy0001** [comment]
You still may see the message appear when region-restrictions are disabled if you try edit something below or above the world.

**Comment by Sprungente** [comment]
Please Reopen this because it isn't fixed: 

https://hastebin.com/axaxoyiwon

What is happen when its smooth: https://picload.org/view/ddlagdwa/fuerdev.jpg.html

Normally Log say no errors or warning. Maybe something with worldedit?

I hope it's ok. when I don't open a new issue.

**Comment by Sprungente** [comment]
It fixes the message but the bug with the holes are still exist. 
It's an unfriendly bug :/

**Comment by boy0001** [comment]
Using [this version?](http://ci.athion.net/job/FastAsyncWorldEdit/958/artifact/target/FastAsyncWorldEdit-bukkit-18.01.10-0a77607-959-18.1.0.jar)

**Comment by Sprungente** [comment]
oh updater has only updated to 958.

You have sended 959 and it works fine . Oh my gosh! my life is saved :)

Thanks you and have fun with my 2 donations :)

**Comment by boy0001** [comment]
Thanks <3

**Comment by joblo2213** [comment]
Huge thanks from me and also the whole building team of our server for resolving this bug! :relaxed:

**Comment by joblo2213** [comment]
Huge thanks from me and also the whole building team of our server for resolving this bug! :relaxed:

**Comment by sirgenex** [comment]
same problem, the link dont work.
