### ISSUE TITLE
Unable to affect chunks with chests.

### ISSUE THREAD

**Issue by guuslieben** [boy0001/FastAsyncWorldedit#854]
# Bug report
**Platform**
SpongeAPI 5.2.0

**Debug paste link**:
https://hastebin.com/uqugiyelav

**Description of the problem:**
Removing a chunk with any type of chest in it, will output this log and leave the chunks unaffected.
Doesn't seem to affect all chests. This bug has been occuring for quite some time already, posted it to the Discord channel but received no fix there.
https://hastebin.com/ogureqipip.sql

**How to replicate**:
Place chests within a chunk.
Execute //set 0, //cut, or anything alike

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
