### ISSUE TITLE
FAWE not working at all

### ISSUE THREAD

**Issue by Mike5357** [boy0001/FastAsyncWorldedit#856]
# Bug report

**Debug paste link**:

Cant generate: 
[11:16:07] [Server thread/INFO] [nucleus]: Mike5357 ran the command: /fawe debugpaste
[11:16:07] [pool-3-thread-6/INFO] [STDERR]: [com.boydti.fawe.object.FawePlayer$2:run:244]: java.lang.NullPointerException

**Description of the problem:**

FAWE not working at all. Cant seem to find anything in the log except for this in the fml log: https://pastebin.com/DGYup0kj
and if I type "fawe" in console:
https://pastebin.com/3cRKw2ei

FAWE version: FastAsyncWorldEdit-sponge111-17.12.30-5583994-953-18.0.10
Sponge version: spongeforge-1.12.2-2555-7.0.0-BETA-2799

Logs with no mods installed except Sponge and FAWE:
latest.log: https://pastebin.com/zQXARnc5
fml-server-latest.log: https://pastebin.com/AeZ4ZnkD

**Checklist**:

- [X] [SEE ERROR ABOVE] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by braunly** [comment]
*bump*
Latest FAWE-sponge not working with latest SpongeForge 1.12
`//set` error
![set](https://user-images.githubusercontent.com/8600722/37764208-bf43b00c-2dc9-11e8-865a-9e0263009880.png)
`//stack`, `//sphere` and `//hsphere` commands error
![stack1](https://user-images.githubusercontent.com/8600722/37764157-8fe4feba-2dc9-11e8-90de-57158428bc97.png)
`//replace`, `//paste`, `//cyl`, `//naturalize` not working too

Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-06016f2
SpongeForge: 1.12.2-2611-7.1.0-BETA-2970
Minecraft Forge: 14.23.2.2627

**Comment by twiztidloc** [comment]
haveing same issue
