### ISSUE TITLE
this site is not work http://builds.enginehub.org/job/worldedit?branch=master 

### ISSUE THREAD

**Issue by mat41997** [boy0001/FastAsyncWorldedit#86]
you can add alternative link to download requet wolrdedit 6.1.1?

**Comment by boy0001** [comment]
Works for me?
http://builds.enginehub.org/job/worldedit/8896/download/worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar

**Comment by mat41997** [comment]
not work for me.

**Comment by mat41997** [comment]
i not can open this site
i not can download this file

ERR_CONNECTION_TIMED_OUT

**Comment by RoboMWM** [comment]
Works for me, and not boy0001's issue anyways. Sounds like an issue on your end.

**Comment by mat41997** [comment]
you can add alternative link? to download worldedit 6.1.1

**Comment by EvilOlaf** [comment]
Also working perfectly for me.

**Comment by mat41997** [comment]
lol...
