### ISSUE TITLE
Smooth brush doesn't work properly

### ISSUE THREAD

**Issue by TrademarkTM** [boy0001/FastAsyncWorldedit#861]
# Bug report
**Debug paste link**: I'm posting it as soon as hastebin starts to work. (https://pastebin.com/UBizBajR)

**Description of the problem:** The smooth brush is making holes in the terrain instead of smoothing it properly: https://i.imgur.com/OPe50EL.png. It also spams `Outside allowed region`, even with `region-restrictions` disabled.

The only protection plugin I'm using is WorldGuard.

**How to replicate**:
.//brush smooth 5, then use it in any terrain

```
[19:35:41 INFO]: FastAsyncWorldEdit version 17.12.30-5583994-953-18.0.10
[19:35:41 INFO]: Fast Async WorldEdit plugin
[19:35:41 INFO]: Author: Empire92
```

**Comment by Sprungente** [comment]
#852

**Comment by BBoyJD10** [comment]
same issue here

**Comment by Danni122112** [comment]
Same on my server, it worked fine a few weeks ago, I have done no edits to either Worldedit or FAWE config files, and yesterday several of my staff were complaining about this issue. Been trying to figure it out ever since, but no luck so far.

**Comment by Pawned** [comment]
Same issue, for some reason smoothing seems to be ignoring the fact that region-restrictions is disabled. Have given my admins fawe.bypass permission node as a temporary workaround.

**Comment by Sprungente** [comment]
fixed
see on the Doublepost:

 #852

**Comment by BBoyJD10** [comment]
NMot fixed
