### ISSUE TITLE
FAWE Structure block placement console error spam

### ISSUE THREAD

**Issue by NocturneCZ** [boy0001/FastAsyncWorldedit#863]
# Bug report
**Debug paste link**:
Error from console:
https://pastebin.com/xgBXAFNB

Debug paste:
https://hastebin.com/pamomevahi

**Description of the problem:**
Whenever I place the vanilla structure block, FAWE spams the console with an error pasted above

**How to replicate**:
Place down a structure block, thats all

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by TufanMeric** [comment]
Same error occurs for me on join, last automatic update was broken, i guess.
