### ISSUE TITLE
NPE errror is spamming my console...

### ISSUE THREAD

**Issue by Rocologo** [boy0001/FastAsyncWorldedit#864]
# Bug report
 This NPE bug is spamming my console
https://pastebin.com/ZuGx0xGT

**Description of the problem:**
It started after I deleted a world (deleting the directory) and restarted my server. After restoring  the deleted I still get this bug in the console....

**How to replicate**:

**Checklist**:

- [X] I included a `/fawe debugpaste` link

07.01 13:47:16 [Server] INFO (FAWE) https://hastebin.com/ugoxacuwop 
07.01 13:47:13 [Server] INFO WorldEdit: #CONSOLE (in "world"): debugpaste

- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Try this jar:
http://ci.athion.net/job/FastAsyncWorldEdit/955/artifact/target/FastAsyncWorldEdit-bukkit-18.01.07-bb7b1cb-956-18.0.13.jar

**Comment by Rocologo** [comment]
This solved the problem. Thank you.
