### ISSUE TITLE
Chunk errors - Renders the plugin unusable.

### ISSUE THREAD

**Issue by R34LP3NGWIN** [boy0001/FastAsyncWorldedit#865]
**Debug paste link**:
https://hastebin.com/xodaceyuwe
**Description of the problem:**
I have the same issue with WorldEdit and VoxelSniper. When I do certain commands it misses chunks or doesn't do specific chunks of the operation. For example if I do //sphere stone 25, it will only do part of the sphere, missing chunks (https://imgur.com/a/vYmU2). This also happens if I do the same with VoxelSniper. I have also found the same issue happens where it skips chunks when doing //set air.

This more than likely isn't a bug and I'm just being stupid but if you could help it would be greatly appreciated :)

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Use Spigot or Paper, not Craftbukkit.
