### ISSUE TITLE
Cannot load plugin [InvalidDescriptionException: Invalid plugin.yml]

### ISSUE THREAD

**Issue by blackphreak** [boy0001/FastAsyncWorldedit#866]
# Bug report
**Debug paste link**:
-- none --

**Description of the problem:**
console output:
https://pastebin.com/RnrH92DR

It shows that the plugin is unable to load.
OS: Centos7
Java: jre1.8.0_151
Spigot Version: git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
Plugin Version: FastAsyncWorldEdit-bukkit-18.01.07-bb7b1cb-956-18.0.13 [The Latest Release]

**How to replicate**:
By starting the spigot server...

**Checklist**:
- [] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Try downloading the plugin again. Looks like the jar you have isn't valid.
