### ISSUE TITLE
Strange issues with hoppers and furnaces. 

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#87]
I have no idea how this could be related to FAWE but on the other side I did not change anything besides this plugin. 

Anyway. Since I migrated to FAWE 3.4.x I get weird issue reports about hoppers not proceeding items anymore or furnaces freezing while processing a block. This is usually the case when a chunk gets unload.  But in fact a player was each and every time close to the affected blocks when this happened. 

 
The issues started when I regenerated about 60 regions spread around the whole world one by one. 

Destroying the affected blocks and set them again fixes this. Well, for a while at least. Short time later I restarted regenerating various regions and the same furnaces froze again. 

This is so weird. Especially as the regenerated regions were (probably) not even close to the affected blocks... 

Edit: It seems like Redstone is affected as well. In some situations it does not work as expected anymore.

**Comment by EvilOlaf** [comment]
Confirmed. This is caused by FAWE for unknown reason. 
Could reproduce a situation where redstone did not properly disable itself after the power source (redstone torch) has been removed. After removing the plugin and restarting the server, everything went back to normal.
I'll do a short video clip.

**Comment by boy0001** [comment]
Increase the `tick-limiter.physics` to 50000.

**Comment by EvilOlaf** [comment]
The latest dev build was an unsuccessful build.
