### ISSUE TITLE
FastAsyncWorldEdit crash by rejoin.

### ISSUE THREAD

**Issue by JoelDeadMach** [boy0001/FastAsyncWorldedit#873]
# Bug report
The plugin crash everythime by restart when i paste a build it past not the whole chunks.
**Debug paste link**:
https://hastebin.com/focoxigepe

**Description of the problem:**
The plugin crash everythime by restart when i paste a build it past not the whole chunks.
When i do //set <id> it past only some chunks not the whole select region.
When i do //paste it paste not the whole build one some chunks.
It gives a error in console about history i disabled history and no error anymore

**Comment by boy0001** [comment]
Can you attach the crash log?

**Comment by FakeGamer** [comment]
https://pastebin.com/n6b0ymDJ

This is all what i have the console have more but i cant paste that its spamming as fack xD

**Comment by boy0001** [comment]
The crash log would be in the `crash-reports` folder. As for that error, updating FAWE should fix it.

**Comment by FakeGamer** [comment]
There is no crash-reports folder i already checked that.

**Comment by FakeGamer** [comment]
https://pastebin.com/pWmGJDCs

This is the error what i mean when i do //copy

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
