### ISSUE TITLE
Best way to relight an area?

### ISSUE THREAD

**Issue by Miclebrick** [boy0001/FastAsyncWorldedit#874]
What's the most efficient way to relight an area? (Completely, including fixing block lighting). ATM I just FaweAPI.fixLighting() with NONE and then OPTIMAL to completely relight all chunks in a selection. Is there a better way, specifically for when doing it over and over for ships?

**Comment by boy0001** [comment]
The easiest would be to let the queue handle lighting automatically. 

I could possibly do further optimizations to lighting depending on what you are doing. (Though it won't be done soon)
 - If it's a large area, I can make the relighting multi-threaded
 - If you are moving the ship to an overlapping region, some lighting could be skipped

**Comment by Miclebrick** [comment]
The areas can be quite large for big ships like cruisers, but usually people fly smaller ships. They can be up to 100x50ish sometimes, usually more like 20x10ish though.

I tried letting the queue handle the lighting itself but IIRC that ended up leaving lights with no source behind.
