### ISSUE TITLE
Region restrictions bypass permission.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#876]
FAWE dev 966

@boy0001 Would it be possible to implement a region restriction bypass permission to allow keeping the ```region-restrictions``` feature enabled while also allowing a specific group to bypass the check to worldedit anywhere all the time?

For example, I would like to keep this enabled so I can give players worldedit in a plots world while allowing them to _only_ be able to worldedit within their plot.
```
# Set true to enable WorldEdit restrictions per region (e.g. PlotSquared or WorldGuard).
# To be allowed to WorldEdit in a region, users need the appropriate
# fawe.<plugin>  permission. See the Permissions page for supported region plugins.
region-restrictions: true
```

However I also have some groups / users who are given worldedit outright and are allowed to use it anywhere globally. With region-restrictions enabled, they can't worldedit anywhere anymore as it outputs ```Your WorldEdit action was cancelled: No allowed region```.

I do not feel comfortable giving them the ```fawe.admin``` permission because they aren't an admin and they'd be required to type ```/wea``` every time they would like to worldedit anywhere. The ```fawe.bypass``` permission seems to be for bypassing set worldedit restrictions like sizes, which I also do not want to provide.

Thus would it be possible to implement a permission like ```fawe.bypass.region-restrictions``` so they can _always_ bypass the check to worldedit anywhere without having to type anything?

**Comment by boy0001** [comment]
I could break `fawe.bypass` into multiple permissions.

**Comment by mibby** [comment]
I'd appreciate it a lot!

**Comment by mibby** [comment]
It also seems you can no longer ```/butcher``` outside regions with ```region-restrictions: true``` set. So players who were given the permission to butcher normal mobs in a radius no longer can do that.

If a permission to bypass the region restriction for butchering could be added too, that would be great!

**Comment by mibby** [comment]
@boy0001 Do you have any time-frame when you expect you'll be able to break down the bypass permissions?

**Comment by boy0001** [comment]
`fawe.bypass`:
 - `fawe.limit.*`
 - `fawe.bypass.regions`.
