### ISSUE TITLE
Asset Pack download

### ISSUE THREAD

**Issue by Untuned** [boy0001/FastAsyncWorldedit#878]
Is there a place I can download the assetpack web folder?  I do not see it anywhere.

**Comment by RedstoneFuture** [comment]
The webinterface for the schematic- up & download?

**Comment by Untuned** [comment]
I meant this: http://empcraft.com/assetpack/

**Comment by RedstoneFuture** [comment]
https://github.com/boy0001/plotupload

**Comment by Untuned** [comment]
That is the same as the web interface, I was looking for the assetpack download.

**Comment by boy0001** [comment]
I've added a link to the source on the assetpack page. 

http://empcraft.com/assetpack/source.zip
