### ISSUE TITLE
Global cooldown for WE commands

### ISSUE THREAD

**Issue by Slaand** [boy0001/FastAsyncWorldedit#879]
Hello, can you add global cooldown for WE commands?
For example all commands will be in the same cooldown after one WE command.

**Comment by boy0001** [comment]
Why do you need a cooldown? Is some command being abused?

**Comment by Slaand** [comment]
Yes, it's can be used on creative servers.

**Comment by boy0001** [comment]
What command is causing issues for you?

**Comment by Slaand** [comment]
I think fast use of /snow and /thaw is the problem. It causes memory leaks & maybe its not an issue of this plugin. That's why I have asked for this cooldown.

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
