### ISSUE TITLE
Can't copy entities

### ISSUE THREAD

**Issue by Tiippex** [boy0001/FastAsyncWorldedit#886]
#794 is similar but not the same. I don't use the API...

# Bug report
**Debug paste link**:
https://hastebin.com/iqusemeqoc

**Description of the problem:**
I simply can't copy/paste armorstands (entities).

**How to replicate**:
1. Mark a region with an armorstand in it:
![Region](http://tiippex.de/pics/i/sq0d9.png)
2. //copy
3. //paste
![Result](http://tiippex.de/pics/i/jjdys.png)

**Comment by Ghost295** [comment]
Same problem on a 1.8.8 server using the last fawe version

**Comment by boy0001** [comment]
@Tiippex 
This was fixed in ea63c77d7e0797978f3ca3b5df9587c55f745d4e
please update.
