### ISSUE TITLE
PlotSquared  undo / redo restrictions

### ISSUE THREAD

**Issue by Arkobat** [boy0001/FastAsyncWorldedit#887]
**Debug paste link**:
https://hastebin.com/gosetilibo

**Description of the problem:**
If you use FAWE on PlotSquared, you are limited to use WorldEdit on plots where you are a member.
This, unfortunately, isn't the case with /undo and /redo
This means if a user(griefer) is member of a plot, and places a lot of shit (grief), and the owner removes the griefer, even though he isn't a member anymore, he can still use /undo & /redo, to keep griefing the plot, after the owner has repaired the damage.

**How to replicate**:
Add a player to a plot.
Let the player do a worldedit action
Remove the player again
The player can now still /undo and /redo, on the plot.

**Comment by L4BORG** [comment]
I can confirm this, it will work even if player was denied from plot and after the player would rejoin.

**Comment by Sanyasp** [comment]
The problem will be solved? This is very important and urgent. Serious vulnerability. :(
