### ISSUE TITLE
non-cuboid selections unsupported

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#89]
I noticed that other selection models than cuboids are unsupported by FAWE. I tried to `//copy` and `//paste` something and it also tells me the time how long it took to complete the action, but basically nothing happened.
Tested with a poly and a cylinder selection.

FAWE 3.4.2

**Comment by Darlelet** [comment]
Confirmed issue using poly selection with latest FAWE version: selecting the region is fine, but trying to replace blocks inside the selection (ex: `//set x`) gives you the following output:
```
[WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.ClassCastException: com.sk89q.worldedit.regions.Polygonal2DRegion cannot be cast to com.sk89q.worldedit.regions.CuboidRegion
[...]
```

**Comment by boy0001** [comment]
@Darlelet 
I cannot replicate the issue since it was fixed. Please create a new ticket with the required information
