### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by TheoRetisch1** [boy0001/FastAsyncWorldedit#890]
I experienced a server crash and cant find the reason. The server ran out of memory. It was all done during A FastAsyncWorldEdit operation, so it is likely the source of the issue. 
I aprreciate any help you can provide :).

Edit: The command /b tree [type] of FastAsynchronVoxelsniper is causing one of those erros everytime you right click: https://pastebin.com/xiqeVizY
The command still works fine.

FAWE: 18.01.21 - 68bda0d-988-18.4.3
FAV: 17.08.27 - ee0a09e-843-15.7.2
server-version: git-Paper-1300 (MC: 1.12.2) / 1.12.2-R0.1-SNAPSHOT
error: https://pastebin.com/KQ63xksD

**Comment by boy0001** [comment]
Update FAVS and FAWE to fix the right click error. 

If you include a `/fawe debugpaste` I can take a look at the out of memory issue.

**Comment by TheoRetisch1** [comment]
Sorry for bothering I updated FAVS and the erros are gone. I dont have a fawe deugpaste including the server crash and I suppose that the server ran out of memory because of those errors. So we can close this issue and I will open a new one if it happens again. Thank you for you help :)
