### ISSUE TITLE
Error: Size exceeds Integer.MAX_VALUE

### ISSUE THREAD

**Issue by Tiippex** [boy0001/FastAsyncWorldedit#896]
I tried to copy an huge area. I had to confirm the copy command.

![Error](http://tiippex.de/pics/i//vka9x.png)

**How to replicate**:
Mark a huge area
//copy
//confirm
--> Error

The region was two billion blocks big but it was possible a few versions ago.
@boy0001 sorry for mention you here. I really need a solution soon. Have to manage big projects from my builders....

**Comment by boy0001** [comment]
It was larger than `2,147,483,647` blocks, and Java doesn't support mapping a file larger than that. (You have clipboard on disk enabled). 

I recommend trying `//anvil copy` and `//anvil paste` for large selections.

**Comment by Tiippex** [comment]
Saidly that crashed my server:
Crash report: https://hastebin.com/atefigabeg.sql

Log: https://hastebin.com/acuzeyoleb.md

and there you can see the #561 problem too.
