### ISSUE TITLE
Worldedit takes years by copying an block!

### ISSUE THREAD

**Issue by JoelDeadMach** [boy0001/FastAsyncWorldedit#897]
# Bug report
WorldEdit takes years before it copy's a build!
**Debug paste link**:
https://hastebin.com/qeqitibuke

**Description of the problem:**
Hello, I since 2 weeks ago my worldedit is really slow! When i copy a build it takes seriously like 10 minutes before it says "<ammount> Blocks were copied."

**How to replicate**:
Before i do //copy i use /wea then i select the reagion than i do //copy (i takes like 10/15 minutes before its complates) Its not the memory i updated the memory also to like 10 GB and 5GB still the same bug!

How can i fix this? Please help me!

**Comment by boy0001** [comment]
Can you try updating WorldEdit. The version you have doesn't support 1.12.2.
