### ISSUE TITLE
Nukkit superpickaxe does not drop items.

### ISSUE THREAD

**Issue by jacklollz2** [boy0001/FastAsyncWorldedit#898]
**Debug paste link**:
https://hastebin.com/ayirobuwax
Nukkit version is #3​7 Jan 24, 2018 4:35 PM https://ci.potestas.xyz/job/NukkitX/job/master/

**Description of the problem:**
When using the superpickaxe in Nukkit, it doesn't drop items.

**How to replicate**:
Select pickaxe
Type /superpickaxe single
Mine a block
Item does not drop

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Set `many-drop-items` if you want the area pickaxe to drop items.

**Comment by Twister1one** [comment]
I update, because d'ont working with version 263
