### ISSUE TITLE
fastasyncworldedit bug

### ISSUE THREAD

**Issue by popcorn9499** [boy0001/FastAsyncWorldedit#9]
worldedit will not work when i load up fast async worldedit

it basically places fake blocks i cant see when i use it. the only thing that works is seting blocks to air.
the commands were //set and //replace
The blocks didnt disappear till server restart

worldedit 6.1
fastasyncworldedit 3.3.0
spigot: R0.1-Snapshot

**Comment by RoboMWM** [comment]
> spigot: R0.1-Snapshot

Try getting the version again.

**Comment by popcorn9499** [comment]
It seems to be working better now. Still have desyncs at times. But that seems to just happen as players seem to disappear from view at times.

**Comment by RoboMWM** [comment]
We have no clue what you're talking about, considering the little information you've provided...

**Comment by popcorn9499** [comment]
ok what i mean is the clients are desyncing. like players disappearing as if they did /v but they didnt. Things like that.  I think thats spigot though. 

Basically player hops in and out of boats or something and they may disapear. and depending on such they will disapear with the boat or not. and u can right click the boat and see them again and u will be pushed by them.

**Comment by RoboMWM** [comment]
Oh, I think I might've had that issue on 1.8.8, though I haven't had much time to get and watch others play around with the plugin. But from the sounds of it, it could be a spigot bug since you mentioned that issue with boats.

**Comment by popcorn9499** [comment]
Ya i have seen this issue happen with forge so id assume it can happen anywhere cuz it only makes sense. And since spigot is a entire rewrite of the server they may be pulling out bugs still. the issue does happen with worldedit too but thats probly again spigot.

**Comment by RoboMWM** [comment]
Ehm... well, I know this messes around with entities - perhaps see if they can do the worldedit while being outside of the respective chunks it edits?

**Comment by popcorn9499** [comment]
maybe. it happened before i installed this plugin too so its not your problem i dont think. If u like ill tell u if it gets better or worse
