### ISSUE TITLE
Bypass plots using /tree

### ISSUE THREAD

**Issue by ItzAntony** [boy0001/FastAsyncWorldedit#900]
**Debug paste link**:
https://hastebin.com/nukigebefa

**Description of the problem:**
Users can bypass the plot protection by using /tree on other users plots.

**How to replicate**:
Type /tree and right click on any plot

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Has been fixed
