### ISSUE TITLE
ForwardExtent.setRemovingEntities = false seems to be ignored

### ISSUE THREAD

**Issue by Joeywp** [boy0001/FastAsyncWorldedit#902]
Related to a previous issue I posted: https://github.com/boy0001/FastAsyncWorldedit/issues/708

I'm trying to move from vanilla-WE to FAWE, but I'm encountering a small problem that prevents me from making this move. I'm trying to paste a schematic with a given offset (x,y,z) without removing existing items. For some reason though, when using `setRemovingEntities(false)` on a ForwardExtentCopy seems to be partly ignored, as the entities are still removed. Usually only happens to those that are contained in blocks, but sometimes also when entities are on slabs and other half blocks.

As I know what I'm doing (the entities that are removed are managed by my plugin, mostly gravityless armorstands, but they are mounted by players) I was wondering if it's possible to force FAWE to keep entities even while they are currently (partly) in a block? Or would this require making a fork with a "fix" or NMS "hacks" for this?

The code I'm using:

```java
File schematicFile = ....
double offsetX, offsetY, offsetZ = ....
boolean entities = false;
boolean noAir = false;

World world = new BukkitWorld(Bukkit.getWorld("world"));
WorldData worldData = world.getWorldData();
Clipboard clipboard = ClipboardFormat.SCHEMATIC.getReader(new FileInputStream(schematicFile)).read(worldData);
Extent extent = WorldEdit.getInstance().getEditSessionFactory().getEditSession(world, -1);


Vector to = clipboard.getOrigin().add(offsetX, offsetY, offsetZ);
ForwardExtentCopy copy = new ForwardExtentCopy(
        extent,
        clipboard.getRegion(),
        clipboard.getOrigin(),
        extent,
        clipboard.getOrigin().add(offsetX, offsetY, offsetZ)
);

copy.setCopyEntities(entities);
copy.setRemovingEntities(false);

if (noAir) {
    copy.setSourceMask(new ExistingBlockMask(clipboard));
}
Operations.complete(copy);
```

**Comment by boy0001** [comment]
Entities are removed if you are placing a block there. The `setRemovingEntities` is used for e.g. `//cut` to remove the original entity when you paste.

**Comment by joeywp** [comment]
Ah I see now. So that does mean that to do what I want (force entities in blocks to not be removed) I have to implement it myself in a fork?

**Comment by Miclebrick** [comment]
What I do for stuff like this is TP the entities to Y 500 with no gravity until it's done placing blocks, then TP them back
