### ISSUE TITLE
Unknown Command But FAWE and WorldEdit are loaded

### ISSUE THREAD

**Issue by Nik2143** [boy0001/FastAsyncWorldedit#906]
With the worldedit without FAWE everything works correctly but when I insert FAWE all the commands associated with worldedit stop working.
/Fawe debugpaste don't work and I have the error "Unknow command. Type /help for help".
With /pl FAWE and Worldedit are loaded
In console I have this error https://hastebin.com/sojukokave.vbs

**Comment by boy0001** [comment]
Can you attach your full startup log?

**Comment by Nik2143** [comment]
https://pastebin.com/Zq2n1KEy

**Comment by boy0001** [comment]
You have two versions of WorldEdit installed. Delete the older one.

**Comment by Nik2143** [comment]
I deleted the worldedit files and FAWE downloaded it but still does not start and give the same problem 
Start log:https://pastebin.com/rpYxpn9A

**Comment by Nik2143** [comment]
Fixed deleting PlotSquared
