### ISSUE TITLE
Masks with different checks on the same block type don't work

### ISSUE THREAD

**Issue by blindcat97** [boy0001/FastAsyncWorldedit#908]
# Bug report

https://hastebin.com/ilicugulem

**Description of the problem:**

When using brush masks, I can't seem to use a mask that uses two different checks on the same type of block. For instance, `/mask [159]&>[159]` doesn't work. It doesn't affect any blocks at all. However, if I check `/mask [159]&<[0]` the appropriate blocks are changed. 

I've attempted this with other blocks, as well as other brushes, and other masks as well. Nothing works, and just leaves the blocks completely unaffected. The console produces no visible errors.

The images below show the masks used for that attempt in the chat. The brush was just a sphere brush with material set to grass blocks.
![image](https://user-images.githubusercontent.com/13594367/35748057-a4df0bf0-081a-11e8-9d8c-ade215530813.png)
![image](https://user-images.githubusercontent.com/13594367/35748097-d14dc4ba-081a-11e8-9f2c-6a176099f86d.png)

**How to replicate**:

Essentially, try to use a mask with two different checks for the same block type.

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin (I removed all other plugins to test before submitting this, although the debug was taken beforehand and does still include those other plugins.)

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
