### ISSUE TITLE
Regen Generating Outside Selected Region

### ISSUE THREAD

**Issue by Elxafil** [boy0001/FastAsyncWorldedit#909]
**Description of the problem:**
When trying to generate biomes within PlotSquared plots the regen command is cancelled except for when you use /wea it runs but then it generates a biome outside the constraints of the Plot so I am asking for this to be fixed.

**How to replicate**:
Using //regen Forest on a plotsquared plot

**Checklist**:
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I included a `/fawe debugpaste` link
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Elxafil** [comment]
@boy0001 are you just going to ignore all your issues with your plugin???

**Comment by N0tMyFaultOG** [comment]
Update the plugins
If the issue persists still, reply to the ticket
