### ISSUE TITLE
//flip not properly flipping extrablocks.json

### ISSUE THREAD

**Issue by guuslieben** [boy0001/FastAsyncWorldedit#911]
# Bug report
**Debug paste link**:
https://hastebin.com/puqifuyodu

**Description of the problem:**
Using the Conquest Reforged mod `//flip` is not working properly on certain items (we have a working `extrablocks.json` file for `//rotate` and all that good stuff). Even though `//rotate` works, `//flip` remains an issue. Here for example is our `extrablocks.json` file (which does affect `//rotate`, as mentioned earlier).

![image](https://user-images.githubusercontent.com/10957963/35820179-2afe13fc-0aa5-11e8-96d3-7303231afea7.png)

`FastAsyncWorldEdit-forge110-18.01.25-7136fb4-992-18.4.7`

```
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-c675e80
    SpongeForge: 1.10.2-2477-5.2.0-BETA-2731
    Minecraft Forge: 12.18.3.2511
```

**How to replicate**:
Using the Conquest Reforged mod (with the appropriate `extrablocks.json` file) use //flip on a selection with e.g. vertical slabs/corner blocks.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
