### ISSUE TITLE
Wand doesn't work in SpongeVanilla

### ISSUE THREAD

**Issue by redbluescreen** [boy0001/FastAsyncWorldedit#915]
# Bug report

**Debug paste link**: https://hastebin.com/vehugiwoju

**Description of the problem:** When using wand in SpongeVanilla, the command works but wand doesn't appear in hand. SpongeVanilla version: 1.12.2-7.1.0-BETA-16

**How to replicate**:
1. Use SpongeVanilla 1.12.2-7.1.0-BETA-16
2. Use latest FastAsyncWorldedit
3. Try wand command

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Use SpongeForge

**Comment by redbluescreen** [comment]
pos1/pos2 and set worked

**Comment by redbluescreen** [comment]
I discovered that wands were put in my backpack not in my hand
