### ISSUE TITLE
FAWE and FAVS installed correctly?

### ISSUE THREAD

**Issue by BENBUHmann** [boy0001/FastAsyncWorldedit#916]
Commands like // rollback USER 10 10m directly in front of the testhole only leaves
"Total: 0 changes" answer.
================================================================
# Welcome to this paste
# It is meant to provide us at IntellectualSites with better information about your problem

# We will start with some informational files
links.config_yml: https://hastebin.com/adavudopan
links.messages_yml: https://hastebin.com/iserahuqik
links.commands_yml: https://hastebin.com/giborevega
links.latest_log: https://hastebin.com/adimirujey

# Server Information
server.platform: bukkit
server.plugins: 
 - FastAsyncWorldEdit: 18.02.11-e1c3404-1007-19.1.2
 - Essentials: 2.0.1-b488
 - FastAsyncVoxelSniper: 18.02.11-e1c3404-1007-19.1.2
 - ProtocolLib: 4.3.0
 - WorldEdit: 6.1.7;dd00bb1
 - VoxelSniper: 5.172.0-SNAPSHOT
server.version: git-Spigot-3d850ec-809c399 (MC: 1.12.2) / 1.12.2-R0.1-SNAPSHOT

# YAY! Now, let's see what we can find in your JVM
memory.free: 364975248
memory.max: 954728448
java.specification.version: '1.8'
java.vendor: 'Oracle Corporation'
java.version: '1.8.0_101'
os.arch: 'amd64'
os.name: 'Windows 7'
os.version: '6.1'

# Okay :D Great. You are now ready to create your bug report!
# You can do so at https://github.com/boy0001/FastAsyncWorldedit/issues

**Comment by BENBUHmann** [comment]
Complement:
Only Worldedit executed commands are processed with // rollback
no voxelsniper

**Comment by N0tMyFaultOG** [comment]
Try updating your fawe and favs
