### ISSUE TITLE
//setbiome doesn't work!

### ISSUE THREAD

**Issue by what-name** [boy0001/FastAsyncWorldedit#920]
# Bug report

**Debug paste link**:
There's no error. https://hastebin.com/bubizenehu

**Description of the problem:**
//setbiome doesn't work. I used `//setbiome Forest`, then I rejoined the server but nothing happened.

**How to replicate**:
`//setbiome <biome>`

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Try updating your fawe
