### ISSUE TITLE
FAWE Anvil to LevelDB Converter Problem

### ISSUE THREAD

**Issue by AdamUPNow** [boy0001/FastAsyncWorldedit#922]
**Description of the problem:**
Hi, I used the converter to convert my world and anything beyond a certain coordinate is gone.

Here is a link to how it looks [https://drive.google.com/open?id=1xsLakPNg6XnY3vL5aQACM02XszdcHI67](url)

I used FastAsyncWorldEdit-nukkit-18.02.09-e09c0c2-1006-19.1.1 version

My java world is around 1GB in size. The nether is also not quite correct.

I don't know if this helps.  Thanks for making the software!

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
