### ISSUE TITLE
Anvil DeleteAllUnvisited Crashes & Issues

### ISSUE THREAD

**Issue by delbertina** [boy0001/FastAsyncWorldedit#925]
# Bug report

**Debug paste link**:

**Description of the problem:**

[https://hastebin.com/isihijerey](https://hastebin.com/isihijerey)

**How to replicate**:

Long story short, I'm experiencing crashes when using the anvil deleteallunvisited command. Here is a paste of a server log from one of the crashes. [https://pastebin.com/hH3BYExw](https://pastebin.com/hH3BYExw) 

I'm using this command to test trimming down a large ~50gb overworld. It does not crash every time I do the command, but more after time. Like I'll start with an input value of 20, then 40, then 60 etc and it'll crash right about that point depending. The depending is because I get different results after I run the same argument value thru twice in a row. 

Not to add weird little details to this already weird issue report, but I've noticed that when running the command at higher argument values (100+) the server memory slowly climbs above the max allocated ram for the server. For instance, I just default was running this test server with 2gigs. Over the course of maybe 5-10m the ram usage of the server had climbed up to 8+ gigs. Doing a /save-all quickly fixed the issue, but did not keep it from starting again.

I couldn't easily find any documentation on anyone else having this issue so not sure if I've done something obviously wrong or this is genuinely the first time this has happened to someone. Is there any config values I should be changing or a different way to go about incrementally sweeping up a map with that command?

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
