### ISSUE TITLE
Suggestion: Include logging of normal block placement

### ISSUE THREAD

**Issue by IceString3** [boy0001/FastAsyncWorldedit#926]
Back in 1.8 we had several alternatives for block loggers, including CoreProtect, Prism, LogBlock...
Now for 1.12 we only have CoreProtect, which does its job, but I think it would be better if FAWE included logging of normal block placement, so people have another option.
Having plugins that prevent griefing is important, but sometimes you have to deal with a grief, no matter how hard you try to prevent it. If FAWE had the feature of logging blocks placed normally, it would definitely be a better plugin. (FAWE is already an excellent plugin, though) I think it would be very hard to implement such feature, but in my opinion it would be worth it.

**Comment by SirYwell** [comment]
I think it isn't the task of this plugin to log like CoreProtect and LogBlock. I would rather recommend to develop another plugin with this function.

**Comment by boy0001** [comment]
So the main reason why FAWE has logging and rollback of edits is that it can just use the existing history files for undo/redo. A complete logging solution would require writing a full logging plugin, since it's not compatible with the current approach.

If enough people are interested, I will consider it.

**Comment by SirYwell** [comment]
It's probably a little bit too much but I'm thinking about something similar for a while.
But the main enhancement compared to other logging plugins would be a function for running servers where you don't want to have downtime.
To give an example:

There are two similar worlds, one on a server where builders do their work and one on a server where the users can play.
Both worlds use the same database to log changes. With a command, you can apply the changes which are made on world 1 to the other world (probably using FAWE's API). So it would be a little bit like a version control system for Minecraft :D

What do you think about it?

**Comment by gardenGnostic** [comment]
I really like the idea of this feature IceString posted. Block logging would be cool, and could be considered for several reasons, mainly because CoreProtect logging WE creates a ton of memory usage.

**Comment by Nik2143** [comment]
I think is a good idea

**Comment by Tiippex** [comment]
Would be very nice but it's a lot of work :o

**Comment by iGPLTV** [comment]
You absolutely should. 100%
