### ISSUE TITLE
File unable to open. 

### ISSUE THREAD

**Issue by twizzletwanger** [boy0001/FastAsyncWorldedit#932]
File is just a properties.jar document. Don't seem to have an app to open. Running Windows 10. Please help.

**Comment by twizzletwanger** [comment]
Opened the file. 
ERROR. Conversion failed. You will have to do it manually. (Nukkit server + anvil2leveldb command)

**Comment by N0tMyFaultOG** [comment]
Update them
If the issue persists still, reply to the ticket
