### ISSUE TITLE
ClipboardFormat.SCHEMATIC.load(file)

### ISSUE THREAD

**Issue by tomocrafter** [boy0001/FastAsyncWorldedit#933]
ClipboardFormat.SCHEMATIC.load(file) is not availlable. how can i call it?

**Comment by boy0001** [comment]
You need to have FAWE as a dependency, if it is, make sure it's a higher priority than WorldEdit (determined by the order you have it in)

**Comment by tomocrafter** [comment]
![image](https://user-images.githubusercontent.com/10905364/37480922-cb882f10-28c3-11e8-86a3-4153eb954087.png)
![image](https://user-images.githubusercontent.com/10905364/37480932-d1749e4a-28c3-11e8-8270-6918f733abc9.png)
I already added as dependency. but still there is no ClipboardFormat.SCHMATIC.load method.

**Comment by tomocrafter** [comment]
Yes, Already did it and successfully.

`new Schematic(ClipboardFormat.SCHEMATIC.getReader(new FileInputStream(file)).read(null)).paste(weWorld, to, false, true, null);`
But this will work properly.
