### ISSUE TITLE
TileEntities (ShulkerBox) disapearing in game, but minecraft still tries to load them on start

### ISSUE THREAD

**Issue by JustDJplease** [boy0001/FastAsyncWorldedit#934]
# Bug report

**Debug paste link**: https://hastebin.com/ukakuqulum

**Description of the problem:**

I was using fawe to paste some schematics into my world, and all was working fine until I restarted my server. One of the schematics contained a large number of shulkerboxes (about 100). Pasting these was no problem at all, but the schematic I pasted wasn't looking too good, so I removed it again with //undo.
After I restarted my server, as it loaded the world, it started to display a huge number of warnings. These warning all looked like this: https://hastebin.com/inezekixel.md

The server was still trying to load the shulkerboxes as tile entities, but since the paste was undone, it couldn't associate them with any blocks, and thus spammed by console.

**How to replicate**:

- Save a schematic including shulker boxes.
- Paste it somewhere.
- Undo your paste.
- Restart the server.

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Tiippex** [comment]
I'm think I already reported it in a similar way here: #910

**Comment by boy0001** [comment]
Duplicate #910
