### ISSUE TITLE
Admins becoming invisible on world change

### ISSUE THREAD

**Issue by Pugabyte** [boy0001/FastAsyncWorldedit#935]
# Bug report

**Debug paste link**: https://hastebin.com/owiyofoceq

**Description of the problem:**
I'm experiencing a bug where admins are becoming permanently vanished when switching worlds, until they do /vanish twice. I'm not sure what is causing it, but its only appeared recently, so I'm going through the plugins that were last updated and asking if its at all possible that the plugin is causing it.

**How to replicate**:
I have not tested this, but I am using VanishNoPacket for vanishing. Install it and FAWE on a 1.12 server, use /op or give yourself `*` perm and switch worlds. You should be invisible to all other non-opped players

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report 
- [x] I made sure I am using an up-to-date version of FAWE [/ver fastasync](https://i.imgur.com/SyTIhHP.png)
- [ ] ~~I made sure the bug/error is not caused by any other plugin~~
    - Cannot confirm whether or not it is FAWE, that is the purpose of this issue.

**Comment by boy0001** [comment]
Remove FAWE, if the problem persists, then it's not related.
