### ISSUE TITLE
An error occurred in the console when you enter //wand when the inventory is full

### ISSUE THREAD

**Issue by BoomEaro** [boy0001/FastAsyncWorldedit#936]
# Bug report
**Debug paste link**:
https://hastebin.com/labijexedo

**Description of the problem:**
https://pastebin.com/dR80EPCC

**How to replicate**:
After the previous removal of the "fix" in the hand of things, if the inventory is filled with objects, (//wand) an error appears in the console, but the item is still deleted. 

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
thanks
