### ISSUE TITLE
[1.8] Biome not changing immediatly anymore

### ISSUE THREAD

**Issue by User3794739** [boy0001/FastAsyncWorldedit#937]
# Bug report

**Debug paste link**:

https://hastebin.com/silodexawi

**Description of the problem:**

In older versions of FAWE, the biome changed immediatly when using //setbiome or the biome pattern. In the latest version, you need to rejoin the server to see the changes.

**How to replicate**:

- Server version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) / 1.8.8-R0.1-SNAPSHOT
- Use //setbiome

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

I forgot to put the server online before creating the debug paste, but with online mode true the issue is still the same.

**Comment by N0tMyFaultOG** [comment]
Try updating fawe
