### ISSUE TITLE
Schematics loading does not work properly

### ISSUE THREAD

**Issue by mikroskeem** [boy0001/FastAsyncWorldedit#938]
# Bug report

**Debug paste link**: https://hastebin.com/uvufakifit

**Description of the problem:**

![](https://0x0.st/smHw.png)

**How to replicate**:

- Put schematic to `plugins/WorldEdit/schematics`
- Do `//schem list global`
- Try to click on schematic to load it

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by mikroskeem** [comment]
This gets urgent fast as Hastebin does not store pastes for a long time :)

**Comment by SirYwell** [comment]
I can't reproduce this error even with the same file name. Could it be a problem with permissions?
Other ideas:
- Did you tried other filenames?
- Did you tried it with a player's schematic?

**Comment by mikroskeem** [comment]
> Did you tried other filenames?
Yes, result was the same

> Did you tried it with a player's schematic?
No. Player schematics seem to work fine, but global ones do not.

**Comment by boy0001** [comment]
I can't replicate, so I've added some more info to the message which may help

**Comment by mikroskeem** [comment]
I can try to reproduce this again later

**Comment by N0tMyFaultOG** [comment]
If that's an issue still, feel free to re-open it
