### ISSUE TITLE
Async issues when used in CommandSigns

### ISSUE THREAD

**Issue by xeyownt** [boy0001/FastAsyncWorldedit#940]
**Description of the problem:**
I'm using [CommandSigns](https://github.com/Nokorbis/ar-command-signs) to create some custom WorldEdit script (this is basically to create / repair a 60x60 platform in the air, maybe there is a better plugin for that). The script I use is:

    //pos1 1,200,1
    //pos2 61,200,61
    //set cobblestone
    //shift 1 up
    //gmask 0
    //walls "cobblestone_wall"
    //gmask

The problem is that the various commands seem to act asynchronously. Even the 3rd command (`//set cobblestone`) sometimes occurs before the `pos2` command, with very bad effect. Things I noticed:

* `//set` occurs before `//pos1` or  `//pos2`. I don't understand how this is possible? At least, the `pos1`
* All `//gmask` commands were always executed before the `//set` command.

I see no way to make the thing behave consistently.

**How to replicate**:
Install CommandSigns and create a sign with script above. Before triggering the script change the pos1 and pos2 to different values.

**Checklist**:
* Well I did `/fawe debugpaste` but it does not give any result.
* I'm using the latest FAWE (`FastAsyncWorldEdit-bukkit-18.03.01-b430f47-1020-19.1.15.jar`).
* I'm using Spigot 1.12.2.

**Comment by xeyownt** [comment]
Just noticed that I still had the usual "WorldEdit" plugin loaded. I'm restarting without the plugin, and test again... Sorry for that.

**Comment by xeyownt** [comment]
Ok I still get the same results. Clicking several times on the sign, I get really "fancy" results...

**Comment by xeyownt** [comment]
... just noticed that WorldEdit plugin gets added automatically. I guess this is FAWS doing so?

**Comment by User3794739** [comment]
The order CommandSigns executes commands is not really FAWE related, I guess.

**Comment by xeyownt** [comment]
Ok. I understand from your comment that CommandSigns would in fact fire all commands in parallel, and not run them sequentially as I was expecting first. There is no much information on CommandSigns, so I found this way of doing really natural. Especially because I know no way to serialize FAWE commands on the same line.

So indeed that's not FAWE problem.
