### ISSUE TITLE
Voxel don't want to work anymore (with an error)

### ISSUE THREAD

**Issue by Noiknez** [boy0001/FastAsyncWorldedit#942]
# Bug report

**Debug paste link**:
Error Console : https://pastebin.com/yPdpTWpK
Fawe DebugPaste : https://hastebin.com/xusukekide
**Description of the problem:**
When a player do "/b e lift" it does nothing but an error in the console
**How to replicate**:
Do /b e lift and wait
**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Update FAVS
