### ISSUE TITLE
//sel bypasses max-radius

### ISSUE THREAD

**Issue by N0tMyFaultOG** [boy0001/FastAsyncWorldedit#951]
**Debug paste link**:
https://hastebin.com/udibehuvuv

**Description of the problem:**
With //sel it is possible to create spheres larger than the max size given in WorldEdit.

**How to replicate**:
//sel ellipsoid 
Order of commands to make the ellipsoid:
1. //sel ellipsoid. 
2. //pos1 (this creates the center block)
3. Fly far up, and a distance to the side, and do //pos2
4. Now do //set [block]

It works with any mode on the //sel list

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
This is the intended behavior. Use the limits in `FastAsyncWorldEdit/config.yml`.
