### ISSUE TITLE
Items dupe with //set in chest

### ISSUE THREAD

**Issue by NORTBE** [boy0001/FastAsyncWorldedit#952]
# Bug report

**Debug paste link**:
https://hastebin.com/bomelovoya

**Description of the problem:**
I own server where //set is allowed for some donator ranks in their regions
And i found some items dupe bug
VIDEO:
https://youtu.be/nxBddrynJSI

**How to replicate**:
Do nothing with chest "skip chest editon", or just fix this bug somehow

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Yeah, you basically need to disable the use of `//undo` if you want to prevent duping right now.
