### ISSUE TITLE
java.lang.NoClassDefFoundError: com/boydti/fawe/wrappers/FakePlayer

### ISSUE THREAD

**Issue by BlackBeltPanda** [boy0001/FastAsyncWorldedit#953]
# Bug report

**Debug paste link**:
 https://hastebin.com/ohewiwanaf

**Description of the problem:**
WorldEdit stops functioning and the console/log is spammed with thousands of these errors: https://pastebin.com/raw/7iJiKrjL

**How to replicate**:
Not sure, it seems to happen randomly.

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Did you use `/reload` ?

**Comment by BlackBeltPanda** [comment]
No, I never use "/reload", it breaks too many things. XD

**Comment by Miclebrick** [comment]
have you tried reinstalling FAWE?

**Comment by BlackBeltPanda** [comment]
Yes, I just updated to a newer version prior to opening this bug report hoping it would help but it did not.

**Comment by Miclebrick** [comment]
it looks like your fawe jar is messed up or something

**Comment by BlackBeltPanda** [comment]
I've re-downloaded the .jar several times. It's still occurring.

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
