### ISSUE TITLE
Degrees in //gmask don't work anymore

### ISSUE THREAD

**Issue by MrMaleficus** [boy0001/FastAsyncWorldedit#955]
Hello,

I tried to setup a global mask with the degrees argument with all possibles syntax, it don't work anymore.

Here the debugpaste : https://hastebin.com/uzejowapuv

Here some pictures: 

![2018-03-18_01 29 19](https://user-images.githubusercontent.com/5609863/37561326-419db722-2a4c-11e8-8fc3-f2b49a266ad1.png)
![2018-03-18_01 29 31](https://user-images.githubusercontent.com/5609863/37561327-41b4949c-2a4c-11e8-8268-82d9cfa96e8d.png)
![2018-03-18_01 29 57](https://user-images.githubusercontent.com/5609863/37561328-41cd9f14-2a4c-11e8-8ee1-82c143866244.png)

**Comment by MrMaleficus** [comment]
Any news ?

**Comment by boy0001** [comment]
it should have been fixed
