### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by WindUnwaken** [boy0001/FastAsyncWorldedit#956]
# Bug report

**Debug paste link**:
https://hastebin.com/gukapepajo

**Description of the problem:**
server logs error: 
https://hastebin.com/yiwosipife.vbs

crash reports:
https://hastebin.com/kahegewepo.rb

Server crash after running a while but no reason

**Checklist**:
- [Y] I included a `/fawe debugpaste` link
- [Y] I made sure there aren't duplicates of this report [(Use Search)]
- [Y] I made sure I am using an up-to-date version of FAWE
- [Y] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Do you know if any specific commands/operations seem to cause it?

**Comment by N0tMyFaultOG** [comment]
Hastebin is empty, attach the log below if this is an issue still.
