### ISSUE TITLE
//regen - again

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#96]
![2016-05-05_13 28 52](https://cloud.githubusercontent.com/assets/3305006/15042596/aa5a50d6-12c5-11e6-8c00-ba136a7e1360.png)

On `y = 67 and 68` the blocks have not been removed properly. The `regen` was over `expand vert`.

FAWE 3.4.3, don't know which dev build, the latest you suggested to use from another issue.
I recommend adding `-SNAPSHOT` as well as the build number to the file names for dev build in future :).

**Comment by EvilOlaf** [comment]
![2016-05-07_09 13 23](https://cloud.githubusercontent.com/assets/3305006/15090775/003b7b0a-1434-11e6-9f15-4d411a84c405.png)
It seems like FAWE tries to regen but then restores the old behavior after.

**Comment by EvilOlaf** [comment]
![2016-05-08_18 58 18](https://cloud.githubusercontent.com/assets/3305006/15099181/ee5d8236-154e-11e6-8f98-05823f2ad792.png)
Basically everything that is floating on the screen, the dirt and quartz should have been removed with the regen, but is still there. 
When I use `//chunk` and regen it works except from no removed stairs, grass and flowers.

If there are any further information I can provide to enhance the regen with FAWE please let me know.

**Comment by boy0001** [comment]
Fixed
