### ISSUE TITLE
Server crash with water/lava

### ISSUE THREAD

**Issue by xion87** [boy0001/FastAsyncWorldedit#960]
# Bug report

**Debug paste link**:
https://hastebin.com/vibotikizu

**Description of the problem:**
Making a plot of lava/water it generate obsidiand and things make the server crash on chunk load
**How to replicate**:

create a big plot with lava and water
Screen of the crashing plot (was 6x6)
![image](https://user-images.githubusercontent.com/3611852/37961903-d6587158-31b9-11e8-9ae5-85e467ac7e83.png)

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Do you have the crash report?

**Comment by xion87** [comment]
Ops, i forgot to included it. I attached the file since is pretty and pretty long. Btw the crash happened multiple times when "loading" the chunk with that build
[2018-03-27-3.log](https://github.com/boy0001/FastAsyncWorldedit/files/1854826/2018-03-27-3.log)

**Comment by xion87** [comment]
Tried to create a plot with lava/water, it also crash any client near it.
Client crash: https://hastebin.com/vuvojelufi.hs

**Comment by xion87** [comment]
Got another crash today, dunno if is related https://hastebin.com/ecehasamam.md

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
