### ISSUE TITLE
Blocks remain invisible until relogging back into 1.8.8 spigot server

### ISSUE THREAD

**Issue by YoDevison** [boy0001/FastAsyncWorldedit#961]
# Bug report
https://hastebin.com/ridixulito
**Description of the problem:**
Any changes I make end up invisible. For Example: //paste changes don't appear on client.

**How to replicate**:
Every time a cmd that changes blocks is done the blocks remain invisible.

Selection.
![bug1](https://user-images.githubusercontent.com/29128256/38074727-91e5cf44-32e4-11e8-993f-cfefc0653e26.PNG)

//copy
![bug2](https://user-images.githubusercontent.com/29128256/38074757-b284e33e-32e4-11e8-9c32-af08d0097c5b.PNG)

//paste
![bug3](https://user-images.githubusercontent.com/29128256/38074766-be57ca78-32e4-11e8-8d2a-500ec7e9e30a.PNG)

Before and after relog:
https://gyazo.com/04f7483298d76f9971b462601de45501

EDIT: This problem occurs in other worlds than the default range of worlds generated. I.E. More End Generated worlds. However not inside the default generated worlds. Possible World corruption with chunk updates? and/or plugin does not support more worlds without MV?

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by LoXR** [comment]
Having this problem aswell on paperspigot 1.12.2, I worldedit something in, it does say all that, also moves me when its pasted in. But doesnt show until either out of chunk and re-entered or re-logged.

**Comment by blindcat97** [comment]
Same issue on Spigot 1.12.2, not in the overworld but in both the End and the Nether. I tested it on a blank server with only WE and FAWE. and the default world name (since it's custom on my main server), and had the exact same issue. Only logging out and back in makes it appear correctly, and only for me. Friends have to log back in themselves to see the update. It's pretty hard to do anything like that.

**Comment by fabien91** [comment]
Same issue with Spigot 1.11.2, to fix the problem i use an old version of FAWE (FastAsyncWorldEdit-bukkit-18.02.11)

**Comment by Kit-Pan** [comment]
Am having an identical issue. Am using Spigot 1.12.2 and most up-to-date FAWE.
https://hastebin.com/qoteguqihi

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
