### ISSUE TITLE
Dont use the #color[color] in my server

### ISSUE THREAD

**Issue by ThaiOtran** [boy0001/FastAsyncWorldedit#963]
# Bug report
I dont use the #color[color]
In /fawe debugpaste:
https://hastebin.com/upiredeqip 

**Description of the problem:**
Picture:
![image](https://user-images.githubusercontent.com/38041084/38251675-555e5aa4-377c-11e8-814c-e51166c64152.png)
More
![image](https://user-images.githubusercontent.com/38041084/38251703-66b219bc-377c-11e8-8b06-a5de1e9e7f74.png)

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of FAWE
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Hastebin is empty, attach the log below if this is an issue still.
