### ISSUE TITLE
Deleting double chest = com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_12_R1.TileEntityChest@5e6a6b34) at -110,150,312 (AIR) where there was no entity tile! error

### ISSUE THREAD

**Issue by Miclebrick** [boy0001/FastAsyncWorldedit#966]
When double chests are removed, the tile entity of one of the chests is not removed properly.

Error: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_12_R1.TileEntityChest@5e6a6b34) at -110,150,312 (AIR) where there was no entity tile!

To reproduce, simply  //set air on a double chest, leave, wait for chunks to unload, return

**Comment by xion87** [comment]
I confirm the issue, is happening also with shulker chest
