### ISSUE TITLE
ProtcolLib depend Warn/Error

### ISSUE THREAD

**Issue by Tiippex** [boy0001/FastAsyncWorldedit#969]
**Debug paste link**:
https://hastebin.com/udesogeyem

**Description of the problem:**
Everything works fine, but I got this NullPointerException:
https://hastebin.com/ropujayole.md

**How to replicate**:
simply use the /schematic show command

I guess that ProtocolLib should be dependency....

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Tiippex** [comment]
It was a guess, I don't know the solution, but the error exists.

**Comment by boy0001** [comment]
error fixed in 049aff4d74806e683225a0e47a92823dbc8dc040
