### ISSUE TITLE
Feature Request - Add physicsFreez

### ISSUE THREAD

**Issue by Blue-Guy** [boy0001/FastAsyncWorldedit#97]
Just like in AsyncWorldEdit!

**Comment by Blue-Guy** [comment]
Maybe this can be accomplished with `tick-limiter` in the config?

**Comment by RoboMWM** [comment]
Afaik FAWE freezes physics by default, and furthermore via `tick-limiter`

**Comment by Janmm14** [comment]
tick-limiter might not be the thing to rely on, where can be some difficulties if the code behind uses things like tick%10==0 or similar. so i suggest to not rely on that for fawe foo.

**Comment by boy0001** [comment]
*freeze, and it is already default behavior. You can further limit physics by configuring the tick limiter. 

@Janmm14
Not sure what you mean by that since the tick limiter in fawe is a per tick thing; it resets every tick, not every 10 ticks.

**Comment by Janmm14** [comment]
I'm sorry I thought you were talking about spigot's tick limit

**Comment by RoboMWM** [comment]
Yea, totally different thing (thankfully).
