### ISSUE TITLE
This is less of a bug, more of a request.

### ISSUE THREAD

**Issue by Shaliquinn** [boy0001/FastAsyncWorldedit#972]
So I have recommended this plugin countless times, and I encourage most of the other professional builders/teams I work with to use it on their servers.
However, I don't use FAWE and I wish I could on my own server.
Here is why I don't use it.

When I set a brush in my hand such as:
//b s grass 10
//mask stone

It works fine till I have to alter the brush in any way such as:
//b s grass 8

or
//b s sponge 10

When I change my brush size/type I have to readdress my mask EVERY time, 
especially on a complex bush set such as it gets difficult:
//b s 10%air,10%18,10%18:1 10
//mask stone,air,sponge,!log

This doesn't seem like a big deal, but it can be infinitely frustrating if all you do is build (This is my job.)

Your imports and everything else with this plugin, however, is truly amazing. So please don't think of this as a criticism. But I will pretty pretty please ask that you find a way for our brush masks to not reset every time I alter my brush. <3 TYSM for taking the time to read/consider this request.

**Comment by dordsor21** [comment]
https://github.com/boy0001/FastAsyncWorldedit/wiki/Commands#brush-options-commands-edittop

**Comment by boy0001** [comment]
As indicated by dord, you could already change the material and other basic settings for existing brushes.

I never really thought about it until now, but the brush specific settings (e.g. heightmap yscale) can't be changed. dunno if that's even an issue for anyone, but I've made some tweaks anyway. Settings should now persist so long as it's the same brush type. Use `//none` to clear the brush.

**Comment by Shaliquinn** [comment]
tysm!
