### ISSUE TITLE
mass edit world

### ISSUE THREAD

**Issue by Wqrld** [boy0001/FastAsyncWorldedit#978]
How do you edit all blocks in the whole world?(eg replace) Anvil looks like what i need but it always freezes my server and crashes it. Is there any other way?

**Comment by boy0001** [comment]
It's recommended to unload the world before running the anvil command.

**Comment by Wqrld** [comment]
i will try doing that thanks

**Comment by Wqrld** [comment]
it worked instantly but it now returns a lot of [11:01:33 ERROR]: Chunk file at -25,16 is in the wrong location; relocating. (Expected -25, 16, got -24, 7) when loading the world

**Comment by Wqrld** [comment]
and now my servers crashes when i try to log in in the corrupted wqrld

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
