### ISSUE TITLE
NukkitWorld class isn't within API on Maven

### ISSUE THREAD

**Issue by uselesswaifu** [boy0001/FastAsyncWorldedit#979]
I have a simple question relating towards Maven. I need the class titled `NukkitWorld`, but NukkitWorld isn't anywhere within the API. So there isn't a simple way for me to get this class; to add it to Maven.

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.

**Comment by uselesswaifu** [comment]
This is still an issue. I think you could maybe include FAWE-Nukkit within the maven repo.
