### ISSUE TITLE
Too many schematics in folder causes crash

### ISSUE THREAD

**Issue by ShawnPR1** [boy0001/FastAsyncWorldedit#980]
**[Debug paste link](https://hastebin.com/yefokeyata)**

**Description of the problem:**
When adding too many schematics (12 or more) to one's personal schematics folder and typing `//schem list mine` to show them, the client gets kicked from the server with the following error:
`Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 1)`

I assume that the plugin is trying to display all the schematics in one message, but can't do that and therefore causes this error. I did see that there is a page number displayed for multiple schematic pages, but it does seem that this is not implemented yet.

**How to replicate**:
Simply add/create 12 or more schematics so they are in your personal schematics folder then type `//schem list mine` and you should receive this exact error. Me and 2 friends could replicate it every single time with small schematic files as well (only 1 block saved as a schematic). We even renamed the file to only be `s.schematic` thinking the names were too long, but it simply seems it can't show all schematics in one message.

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Duplicate #976
Please update
