### ISSUE TITLE
NPE on wrong id

### ISSUE THREAD

**Issue by xion87** [boy0001/FastAsyncWorldedit#982]
Debugpaste: https://hastebin.com/oduroyakij

Errror: https://hastebin.com/kufilogumu.md

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Hastebin is empty, attach the log below if this is an issue still.
