### ISSUE TITLE
Can't get FAWE to convert anything

### ISSUE THREAD

**Issue by EchoSigma** [boy0001/FastAsyncWorldedit#986]
I've tried converting an older world from before 1.2 and even a random test world in the latest version. Both would not convert and gave me the error that it manually needed to be converted with nukkit + anvil2db command.
http://www.mediafire.com/file/92vdlunrlmmgtt4/Servival.rar

Thanks a ton.

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.

**Comment by TheShibaLover** [comment]
Hi, I have the same problem. I'm a bit late, but did you ever figure this out?
