### ISSUE TITLE
//image

### ISSUE THREAD

**Issue by RainOfPain125** [boy0001/FastAsyncWorldedit#987]
# Bug report

**Debug paste link**:

https://hastebin.com/fimefixiqa
**Description of the problem:**

https://pastebin.com/kYAz41gu
**How to replicate**:

Not sure
**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Please create a `FastAsyncWorldEdit/textures` folder with `.minecraft/versions` jar or mods in it.If the file exists, please make sure the server has read access to the directory
