### ISSUE TITLE
Error when trying to use plugin schematics

### ISSUE THREAD

**Issue by AMinecraftDev** [boy0001/FastAsyncWorldedit#989]
hey, I'm getting this weird error when trying to use schematics that are imported from my plugin into FastAsyncWorldEdit. Here is the error: https://hastebin.com/obuhaqinus.md here is my code where it's trying to paste the schematic: https://hastebin.com/agubetojit.cpp the weird thing is when I use the plugin#saveResource method to save a schematic from my plugin into a proper file it doesn't work, but if I go create a schematic ingame with //schem save and then put that schematic in my plugin folder it works, any ideas on what my issue is? I think it could be something to do with compression or something like that when the file is transfered from the jar to a proper file.

**Comment by boy0001** [comment]
Can you attach the following:
 - The resource in your jar file
 - The file created when calling `plugin#saveResource`

**Comment by AMinecraftDev** [comment]
[CellTier1 (from jar).zip](https://github.com/boy0001/FastAsyncWorldedit/files/1960285/CellTier1.from.jar.zip)
[CellTier1 (from plugin#saveResource).zip](https://github.com/boy0001/FastAsyncWorldedit/files/1960288/CellTier1.from.plugin.saveResource.zip)

**Comment by AMinecraftDev** [comment]
Also when calling the ClipboardFormat.SCHEMATIC.isFormat(file) it states false for the schematics pasted in via. the plugin, but true for the ones that were created from commands ingame and dumped into the directory.

**Comment by boy0001** [comment]
Both those schematics are invalid.

**Comment by AMinecraftDev** [comment]
Invalid how? I use //schem save on the server I got them from which is using WorldEdit and FAWE?

**Comment by AMinecraftDev** [comment]
Nvm I got it, I just used //download instead and it seems to be working. Thanks! 😄
