### ISSUE TITLE
/wrg causes issues with WorldEditRegions

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#99]
with FAWE installed, /wrg defaults to the FAWE's region selection command, rather than WorldEditRegion's main command

**Comment by RoboMWM** [comment]
If you're using FAWE, you don't need WorldEditRegions, as FAWE already implements such restrictions.

**Comment by dordsor21** [comment]
The server I'm from uses WERegions for its region creation.

**Comment by chamunks** [comment]
@RoboMWM [this](https://www.spigotmc.org/resources/worldeditregions.448/) is what @dordsor21 is talking about. FAWE shouldn't contain any functionality which covers this.

**Comment by RoboMWM** [comment]
Yes I'm aware what the plugin is, hence my prior comment. I also recall (iirc) seeing this plugin listed as "not compatible with" earlier in FAWE's project page.

**Comment by chamunks** [comment]
@RoboMWM I've had this plugin installed long before there was a Spigot page I got it straight from @boy0001 when we came up with the idea.  I was unaware of the incompatibility I'll see if he can chime in on this.

**Comment by chamunks** [comment]
@RoboMWM It seems the latest build fixes this issue.  Just waiting on @dordsor21's confirmation to close the ticket.  Ty for your timely responses.

**Comment by dordsor21** [comment]
This is indeed fixed
