### ISSUE TITLE
Little residence issue

### ISSUE THREAD

**Issue by WarrioR151** [boy0001/FastAsyncWorldedit#992]
Debug paste link: https://hastebin.com/tesamafara

Description of the problem: If I mark two points in the residence and write //set 1 so I have to stay inside the residence to execute the order when I go outside the residence and type //​​Set 1 so it write that I'm out of residence (yes, i am but can it be done so to set it up with //set 1 even if I do not stay in the residence I have it selected?)

(I am not good in english, soo i recorded video of my problem, here is link)

https://youtu.be/DMZjkzhVlFQ

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
