### ISSUE TITLE
//gui throws errors

### ISSUE THREAD

**Issue by HYPExMon5ter** [boy0001/FastAsyncWorldedit#993]
**Debug paste link**:
https://hastebin.com/anetocutob

**Description of the problem:**
`//gui` throws errors
Errors: https://hastebin.com/zihehopimu.vbs

**How to replicate**:
Run `//gui`

**Comment by N0tMyFaultOG** [comment]
`//gui` is only supported on Pocket Edition, running it on a normal server does no longer throw an error.
