### ISSUE TITLE
//image bug

### ISSUE THREAD

**Issue by kikelkik** [boy0001/FastAsyncWorldedit#994]
# Bug report

**Debug paste link**:
https://hastebin.com/esuculubef

**Description of the problem:**
Using //image with large images causes Null pointer exceptions and crashes the image.

**How to replicate**:
I used //image https://i.imgur.com/TYdjpJI.png
As you can see, the picture is 419x458px and most parts have transparency (maybe this is the problem?). 

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Please attach the full exception.

**Comment by kikelkik** [comment]
This is the exception:
https://hastebin.com/ebucojiyib.md

**Comment by boy0001** [comment]
You are correct, it should now be working correctly.

Note: If the alpha value doesn't match that of a block, no block will be placed there. 

Alpha values for transparent blocks:
```Java
// Not in any particular order
Block{ID:161, Data: 0} has alpha 154
Block{ID:18, Data: 0} has alpha 165
Block{ID:18, Data: 1} has alpha 165
Block{ID:18, Data: 2} has alpha 154
Block{ID:18, Data: 3} has alpha 201
Block{ID:20, Data: 0} has alpha 70
Block{ID:212, Data: 0} has alpha 159
Block{ID:212, Data: 1} has alpha 158
Block{ID:212, Data: 2} has alpha 158
Block{ID:212, Data: 3} has alpha 158
Block{ID:5, Data: 3} has alpha 201
Block{ID:5, Data: 4} has alpha 183
Block{ID:79, Data: 0} has alpha 159
Block{ID:95, Data: 0} has alpha 123
Block{ID:95, Data: 10} has alpha 123
Block{ID:95, Data: 11} has alpha 123
Block{ID:95, Data: 12} has alpha 123
Block{ID:95, Data: 13} has alpha 123
Block{ID:95, Data: 14} has alpha 123
Block{ID:95, Data: 15} has alpha 123
Block{ID:95, Data: 1} has alpha 123
Block{ID:95, Data: 2} has alpha 123
Block{ID:95, Data: 3} has alpha 123
Block{ID:95, Data: 4} has alpha 123
Block{ID:95, Data: 5} has alpha 123
Block{ID:95, Data: 6} has alpha 123
Block{ID:95, Data: 7} has alpha 123
Block{ID:95, Data: 8} has alpha 123
Block{ID:95, Data: 9} has alpha 123
```
