### ISSUE TITLE
FAVS Filldown Brush only works on water

### ISSUE THREAD

**Issue by Tiippex** [boy0001/FastAsyncWorldedit#996]
# Bug report
FAVS Version: 18.03.26-48992d2-1054-19.4.17
FAWE Version: 18.04.27-2ec9a92-1089-19.5.23
git-Paper-1404 (MC: 1.12.2)

**Description of the problem:**
The filldown brush works on water only. This problem exists quite long.

**How to replicate**:
[Video](https://concon.world/pics/i/c6moywa2az.mp4)

**Comment by N0tMyFaultOG** [comment]
Update fawe & favs
If the issue persists still, reply to the ticket

**Comment by Tiippex** [comment]
@N0tMyFaultOG
Tested it a few moments ago. Still doesn’t work D:
